### ISSUE TITLE
my play command don't work

### ISSUE THREAD

**Issue by HiiZun** [Androz2091/discord-player#1]
hello in my bot i have added a command "play"

```
let queue = await client.player.getQueue(message.guild.id).lenght;
if(!message.member.voiceChannel) return message.channel.send("❌ | Error: You're not in a voice channel !")
if(!args[0]) return message.channel.send("❌ | Error: please add a music name !")
if(queue > 30) return message.channel.send("🛑 | Error: you can't add more than 30 music, please subscribe to the premium to increase this limit")
if(client.player.isPlaying(message.guild.id)){

    let song = await client.player.addToQueue(message.guild.id, args[0]);

 const embedok = new Discord.RichEmbed()
.setDescription(`__**✅ Added to queue 🎶**__\n  » ${song.name}`)
.setAuthor(`requested by ${message.author.tag}`, message.author.avatarURL)
.setTimestamp()
message.channel.send(embedok)
} else {
    let song = await client.player.play(message.member.voiceChannel, args[0])
    const embedok1 = new Discord.RichEmbed()
    .setDescription(`__**✅ Now playing 🎶**__\n  » ${song.name}`)
    .setTimestamp()
    message.channel.send(embedok1)
}
```

but this don't work

**Comment by hydraindia** [comment]
`.lenght;`, spelling is wrong. It should be `.length;`

**Comment by Androz2091** [comment]
Also, you have to wait for getting the queue before using .length. And to get the queue size, you have to use the `queue.songs` property. 
```js
let queue = await client.player.getQueue(message.guild.id);
let songCount = queue.songs.length;
// restf o your code 
```

**Comment by HiiZun** [comment]
okay thanks you !

**Comment by HiiZun** [comment]
but i have another error

```
    let queue = await client.player.getQueue(message.guild.id);
                ^^^^^

SyntaxError: await is only valid in async function
```

**Comment by hydraindia** [comment]
use `async` in your command handler

**Comment by HiiZun** [comment]
already 
![image](https://user-images.githubusercontent.com/44111470/74609948-05076d00-50ef-11ea-9e06-4c7c0a9f8b3e.png)

**Comment by Androz2091** [comment]
@HiiZun please send your full `play.js` file

**Comment by HiiZun** [comment]
`const Discord = require('discord.js')
const opusscript = require("opusscript")
const config = require("../config.json")

exports.run = (client, message, args) => {

    let queue = client.player.getQueue(message.guild.id);
    let songCount = await queue.songs.length;
    if(songCount >= 30) return message.channel.send("🛑 | Error: you can't add more than 30 music, please subscribe to the premium to increase this limit")

    if(!message.member.voiceChannel) return message.channel.send("❌ | Error: You're not in a voice channel !")
    if(!args[0]) return message.channel.send("❌ | Error: please add a music name !")
    if(client.player.isPlaying(message.guild.id)){

    let song = client.player.addToQueue(message.guild.id, args[0]);

 var embedok = new Discord.MessageEmbed()
.setDescription(`__**✅ Added to queue 🎶**__\n  » ${song.name}`)
.addBlankField()
.setAuthor(`requested by ${message.author.tag}`, message.author.avatarURL)
.setTimestamp()
message.channel.send(embedok)
} else {
    let song = client.player.play(message.member.voiceChannel, args[0])
    var embedok1 = new Discord.MessageEmbed()
    .setDescription(`__**✅ Now playing 🎶**__\n  » ${song.name}`)
    .addBlankField()
    .setTimestamp()
    message.channel.send(embedok1)
}

}

module.exports.help = {
    name: "play",
    group: "Music",
    botperm: [],
    usrperm: [],
    owneronly: false,
    usage: "play (my music)",
    aliases: ["playmusic", "p", "jouer"],
    description: "listen music from youtube"
    }`

**Comment by hydraindia** [comment]
`const Discord = require('discord.js')
const opusscript = require("opusscript")
const config = require("../config.json")

exports.run = async (client, message, args) => {

    let queue = client.player.getQueue(message.guild.id);
    let songCount = await queue.songs.length;
    if(songCount >= 30) return message.channel.send("🛑 | Error: you can't add more than 30 music, please subscribe to the premium to increase this limit")

    if(!message.member.voiceChannel) return message.channel.send("❌ | Error: You're not in a voice channel !")
    if(!args[0]) return message.channel.send("❌ | Error: please add a music name !")
    if(client.player.isPlaying(message.guild.id)){

    let song = client.player.addToQueue(message.guild.id, args[0]);

 var embedok = new Discord.MessageEmbed()
.setDescription(`__**✅ Added to queue 🎶**__\n  » ${song.name}`)
.addBlankField()
.setAuthor(`requested by ${message.author.tag}`, message.author.avatarURL)
.setTimestamp()
message.channel.send(embedok)
} else {
    let song = client.player.play(message.member.voiceChannel, args[0])
    var embedok1 = new Discord.MessageEmbed()
    .setDescription(`__**✅ Now playing 🎶**__\n  » ${song.name}`)
    .addBlankField()
    .setTimestamp()
    message.channel.send(embedok1)
}

}

module.exports.help = {
    name: "play",
    group: "Music",
    botperm: [],
    usrperm: [],
    owneronly: false,
    usage: "play (my music)",
    aliases: ["playmusic", "p", "jouer"],
    description: "listen music from youtube"
    }`

**Comment by hydraindia** [comment]
`const Discord = require('discord.js')
const opusscript = require("opusscript")
const config = require("../config.json")

exports.run = (client, message, args) => {

    let queue = client.player.getQueue(message.guild.id);
    let songCount = await queue.songs.length;
    if(songCount >= 30) return message.channel.send("🛑 | Error: you can't add more than 30 music, please subscribe to the premium to increase this limit")

    if(!message.member.voiceChannel) return message.channel.send("❌ | Error: You're not in a voice channel !")
    if(!args[0]) return message.channel.send("❌ | Error: please add a music name !")
    if(client.player.isPlaying(message.guild.id)){

    let song = client.player.addToQueue(message.guild.id, args[0]);

 var embedok = new Discord.MessageEmbed()
.setDescription(`__**✅ Added to queue 🎶**__\n  » ${song.name}`)
.addBlankField()
.setAuthor(`requested by ${message.author.tag}`, message.author.avatarURL)
.setTimestamp()
message.channel.send(embedok)
} else {
    let song = client.player.play(message.member.voiceChannel, args[0])
    var embedok1 = new Discord.MessageEmbed()
    .setDescription(`__**✅ Now playing 🎶**__\n  » ${song.name}`)
    .addBlankField()
    .setTimestamp()
    message.channel.send(embedok1)
}

}

module.exports.help = {
    name: "play",
    group: "Music",
    botperm: [],
    usrperm: [],
    owneronly: false,
    usage: "play (my music)",
    aliases: ["playmusic", "p", "jouer"],
    description: "listen music from youtube"
    }`

**Comment by hydraindia** [comment]
Replace this `exports.run = (client, message, args) => {` with `exports.run = async (client, message, args) => {`

**Comment by HiiZun** [comment]
that's normal ? (i'm on discord.js 12)
![image](https://user-images.githubusercontent.com/44111470/74832635-0cf62580-5318-11ea-87df-7d9865158469.png)

**Comment by SoulHarsh007** [comment]
@HiiZun yes this happens when user uses the play command and they are not in a voice chat

**Comment by SoulHarsh007** [comment]
You can add this:  
`if(!message.member.voice.channel) return message.channel.send('you are not in a vc!');`

**Comment by HiiZun** [comment]
already added
![image](https://user-images.githubusercontent.com/44111470/74856174-fd8bd200-5341-11ea-9d0c-a385b761e5de.png)
but i have this error

**Comment by SoulHarsh007** [comment]
> already added
> ![image](https://user-images.githubusercontent.com/44111470/74856174-fd8bd200-5341-11ea-9d0c-a385b761e5de.png)
> but i have this error

Are you sure it is at the top i.e., before the add to queue or `let song;`

**Comment by HiiZun** [comment]
> > already added
> > ![image](https://user-images.githubusercontent.com/44111470/74856174-fd8bd200-5341-11ea-9d0c-a385b761e5de.png)
> > but i have this error
> 
> Are you sure it is at the top i.e., before the add to queue or `let song;`

![image](https://user-images.githubusercontent.com/44111470/74880299-39875d00-536b-11ea-93c6-6f10e5be5696.png)
