### ISSUE TITLE
Could not find a declaration file for module 'discord-player'

### ISSUE THREAD

**Issue by ysfchn** [Androz2091/discord-player#10]
I have this line in my code to add PlayerOptions:
```js
const { Player, PlayerOptions } = require("discord-player");
```

And I initialize the bot like this:

```js
const player = new Player(client, process.env.YOUTUBE_KEY, PlayerOptions.leaveOnEmpty);
```

But it doesn't recognise the PlayerOptions object, so it throws an error while executing the code:

```
TypeError: Cannot read property 'leaveOnEmpty' of undefined
    at Object.<anonymous> (c:\Users\ycdem\Documents\GitHub\Lyre\bot.js:14:74)
    at Module._compile (internal/modules/cjs/loader.js:1155:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

However the `client` object itself can run without any problems, I mean I get no errors when I delete the `PlayerOptions`.

Also my IDE (Visual Studio Code) shows this error while hovering the mouse on the `discord-player`.

![image](https://user-images.githubusercontent.com/54748183/79045931-80c8f600-7c16-11ea-94cd-83fa08f4fab8.png)

I tried `npm install @types/discord-player`, but it doesn't exists in registry. I also searched on the StackOverflow, but looks like it has something to do with package's owner. Also, note that it works perfectly on a cloud application platform like Heroku, but it doesn't execute the same code in local.

The versions of packages:

```
"dependencies": {
    "@discordjs/opus": "^0.1.0",
    "discord-player": "^1.3.8",
    "discord.js": "^12.0.2",
    "dotenv": "^8.2.0"
  },
```

**Comment by Androz2091** [comment]
Hello @ysfchn,
What would you like to do exactly?
If you want to set `leaveOnEmpty` to `true`, just do this:
```js
const player = new Player(client, process.env.YOUTUBE_KEY, {
     leaveOnEmpty: true
});
```

**Comment by ysfchn** [comment]
Oh, thanks, it is working now but I don't know why I can't use `PlayerOptions.leaveOnEmpty` directly like in the example. Sorry for that 😅
