### ISSUE TITLE
Custom Stream Engine Issues

### ISSUE THREAD

**Issue by killer069** [Androz2091/discord-player#1008]
**Describe the bug**

Mentioned [steps](https://github.com/Androz2091/discord-player#custom-stream-engine) to create a resource for **play-dl** is wrong. 
It creates issues when play-dl changes its in-built structure. Either remove the steps or add a way to provide stream type of created resource.

**To Reproduce**
1. Download latest play-dl version.
2. Use code as mentioned in url.
3. Music will never play

**Expected behavior**
Music should be able to play

**Suggestions**
Modification of custom stream Engine.
```ts
import play from 'play-dl'

const queue = player.createQueue(..., {
    ...,
    async onBeforeCreateStream(track, source, _queue) {
        // only trap youtube source
        if (source === "youtube") {
            const playdl_stream = await playdl.stream(track.url)
            return { stream : playdl_stream.stream, type: playdl_stream.type }; // Now just use this object to get type and stream.
        }
    }
});
```

**Please complete the following information:**
 - Node Version: 17.4.0
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.5.0

**Additional context**

**Comment by killer069** [comment]
Play-dl latest version converts Webm to Opus by itself.

FFmpeg never converts raw Opus packets to raw PCM. So your custom engine method will no longer work.

**Comment by DevAndromeda** [comment]
It would not be a perfect solution for us, we need pcm for volumes, and audio filters. Either let users pick what format to retrieve from play-dl or users will need to pipe the stream to opus decoder and then send it back to discord-player. Custom stream engine is not only built for `play-dl` but anything in general.

**Comment by killer069** [comment]
Ok Thanks for the info.

I will see what I can do.
