### ISSUE TITLE
Soundcloud links don't work

### ISSUE THREAD

**Issue by xgoje** [Androz2091/discord-player#102]
why does soundcloud-scraper not work with discord-player or do I gotta do something to make it workkkk

**Comment by Snowflake107** [comment]
@xgoje Uh what do you mean by **doesn't work**? Can you explain??

**Comment by xgoje** [comment]
like if i put a link to play a specific track, it doesn't work

**Comment by Snowflake107** [comment]
your `discord-player` version?

**Comment by xgoje** [comment]
> your `discord-player` version?

latest

**Comment by Androz2091** [comment]
Can you test using v3.0.0-beta.3 please?

**Comment by xgoje** [comment]
Sorry for being inactive, sure

**Comment by Androz2091** [comment]
is it working now?

**Comment by sabyr-cpu** [comment]
I have this problem too 

UnhandledPromiseRejectionWarning: TypeError: soundcloud.getSongInfo is not a function
node_modules\discord-player\src\Player.js:158:57

I use discord-player 3.0.3

**Comment by sabyr-cpu** [comment]
Oh it worked when I updated all packages!
