### ISSUE TITLE
smoothVolume not working

### ISSUE THREAD

**Issue by D3ord3NidAm** [Androz2091/discord-player#1021]
**Describe the bug**
Cannot use smoothvolume

**To Reproduce**
1. Go to 'index.js/ts'
1. paste `require("discord-player/smoothVolume");` to top of index
2. start bot.
3. See error --> MODULE_NOT_FOUND
4. Change module to `require("discord-player/dist/smoothVolume");`
5. start bot.
6. See error --> [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/smoothVolume' is not defined by "exports" 

**Please complete the following information:**
 - Node Version: v16.13.2.
 - Discord Player Version: v5.2.1
 - Discord.js Version: 13.6.0

**Additional context**

**Comment by DevAndromeda** [comment]
Try force upgrading your modules. Example: `yarn upgrade`

**Comment by D3ord3NidAm** [comment]
The file is found in order to use the file but it says its not exported. All files are up to date.

**Comment by DevAndromeda** [comment]
On the latest version, discord player will attempt to auto inject the modified volume transformer. If you don't feel smooth volume changes by default, follow the `require("discord-player/smoothVolume");` method. I have extended the export paths to:

`discord-player/dist/*`
`discord-player/src/*`

**Comment by DevAndromeda** [comment]
stale
