### ISSUE TITLE
Player stops after a second on some videos

### ISSUE THREAD

**Issue by R0dn3yS** [Androz2091/discord-player#1031]
The player just randomly stops playing after a second on some videos, other videos work perfectly.

**Comment by R0dn3yS** [comment]
#1029 closes this

**Comment by retrouser955** [comment]
use play-dl

**Comment by retrouser955** [comment]
https://discord-player.js.org/docs/main/master/typedef/PlayerOptions scroll all the way down and check using a custom extractor in welcome section of the docs
