### ISSUE TITLE
Connection being undefined

### ISSUE THREAD

**Issue by Kici33** [Androz2091/discord-player#1071]
**Describe the bug**
Library tries to handleVoiceState while multi-instancing (from other bot) causing the whole application to collapse.
`queue.connection` is undefined, if there's bot running along discord-player ones
**To Reproduce**
So we use discord-player in our project as follows:
- There is main bot that handles various types of things (including music bots). We call it master
- Then there are music objects (bots), where all of them create their own player/queue when initiated.
- I don't know what's the exact moment _handleVoiceState is executed, but It'll always throw 
`TypeError: Cannot read properties of undefined (reading 'channel')`, if there's no bot on voice channel
- I am more happy to share my code with you but I can't do it here for the public, so for more details you can contact me (Kici33#0001)

**Screenshots**
![image](https://user-images.githubusercontent.com/31071107/156622169-bafd1c75-6aa5-41a2-94f0-44d1828d7e4b.png)

**Please complete the following information:**
 - Node Version: `v16.11.0`
 - Discord Player Version: `v5.2.2`
 - Discord.js Version: `v13.6.0`

**Additional context**

So I added additional check which prevents any further actions if `queue.connection` is undefined, 
![image](https://user-images.githubusercontent.com/31071107/156622601-63495dcc-f880-42fb-9210-d92a4357bf8c.png)
and it seems to do the job.

The exact code is in Player.js (line between 80-83)

**Comment by DevAndromeda** [comment]
try v5.3.x, re-open if this still persists
