### ISSUE TITLE
"leaveOnEmpty" & "channelEmpty" bugs

### ISSUE THREAD

**Issue by StarJules** [Androz2091/discord-player#1074]
This bug has been around for 6 months and they still haven't fixed it... Instead of fixing this bug, they are adding smoothvolume and other shi** things that no one asked for. Other users have even shown ways to solve this, but you don't even care. If you want to fix that, use 5.0.2 version of discord-player.

**Comment by Olebeh** [comment]
That really worked! I don't know what would i do withput you. Thank you very much!

**Comment by Olebeh** [comment]
> That didn't work for me, did you just switch to 5.0.2? Is there any other available fix?

Yeah, that's all what did I do. Have you uninstalled it before installing 5.0.2? Try `npm uninstall discord-player` and then type `npm i discord-player@5.0.2`

**Comment by StarJules** [comment]
> That didn't work for me, did you just switch to 5.0.2? Is there any other available fix?

Strange, because here it works normally. I just uninstalled and installed again using `npm i discord-player@5.0.2`. If you're using `ffmpeg-static` package, use the 4.4.1 version.

**Comment by nizeic** [comment]
> They haven't fixed the bug because they don't know what is causing it or how to fix it.

isn't this already fixed in the `develop` branch?
https://github.com/Androz2091/discord-player/commit/977b12fb3a9fba46ce52663e0ec6c38a844a9501

it hasn't been published to the npm registry yet though

**Comment by n-xsi** [comment]
> > That didn't work for me, did you just switch to 5.0.2? Is there any other available fix?
> 
> 
> 
> Strange, because here it works normally. I just uninstalled and installed again using `npm i discord-player@5.0.2`. If you're using `ffmpeg-static` package, use the 4.4.1 version. If you want to take a look at my package:
> 
> `"@discord-player/extractor": "^3.0.2",
> 
> "@discordjs/builders": "^0.12.0",
> 
> "@discordjs/opus": "^0.7.0",
> 
> "discord-player": "^5.0.2",
> 
> "discord-ytdl-core": "^5.0.4",
> 
> "ffmpeg-static": "^4.4.1",
> 
> "libsodium-wrappers": "^0.7.9",
> 
> "soundcloud-scraper": "^5.0.2",
> 
> "spotify-url-info": "^2.2.5",
> 
> "tiny-typed-emitter": "^2.1.0",
> 
> "youtube-sr": "^4.1.13",
> 
> "ytdl-core": "^4.10.0"
> 
> `

Thanks a lot!
This worked perfectly
