### ISSUE TITLE
The spotify playlist size is limited

### ISSUE THREAD

**Issue by LordPrinz** [Androz2091/discord-player#1078]
The bug appears when i try to play a spotify playlist which has more than 100 tracks. Bot plays only first 100 tracks of the playlist.

**Comment by DevAndromeda** [comment]
This is due to the way we parse spotify playlists. Only 100 items max are available while parsing from widget. This is a limit from spotify itself.

**Comment by pauldb09** [comment]
> This is due to the way we parse spotify playlists. Only 100 items max are available while parsing from widget. This is a limit from spotify itself.

We can use the ofilicial api with a module like play-dl or official api
