### ISSUE TITLE
Player not emit trackStart event

### ISSUE THREAD

**Issue by ACGaming1508** [Androz2091/discord-player#1079]
**Describe the bug**
`trackStart` event won't be emitted when the player starts playing a track

**Please complete the following information:**
 - Node Version: `16.13.0`
 - Discord Player Version: `5.2.2`
 - Discord.js Version: `13.6.0`

**Additional context**
I put `console.log(track.name);` in the listener to check when the player starts playing a track but it didn't log as expected(nothing logged)

**Comment by pauldb09** [comment]
What's the outpout of your nowplaying command ( If you don't have one, can you just console.log queue#current) ?

**Comment by ACGaming1508** [comment]
> What's the outpout of your nowplaying command ( If you don't have one, can you just console.log queue#current) ?

Put `console.log()` in `trackStart` event listener? No, it won't log anything because the event won't be emitted. I evaluated the `<Queue>.current` and it shows the actual playing track.

**Comment by ACGaming1508** [comment]
The only problem is the player event

**Comment by pauldb09** [comment]
> > What's the outpout of your nowplaying command ( If you don't have one, can you just console.log queue#current) ?
> 
> Put `console.log()` in `trackStart` event listener? No, it won't log anything because the event won't be emitted. I evaluated the `<Queue>.current` and it shows the actual playing track.

Nah i'm not talking about this. Just eval queue#current with an eval command or sth else

**Comment by pauldb09** [comment]
Try downgrading to 5.1

**Comment by ACGaming1508** [comment]
Thanks it now works. But this version still has some bugs, how can I handle it?
