### ISSUE TITLE
TypeError: Cannot read property 'createMessageCollector' of undefined

### ISSUE THREAD

**Issue by MrPerfectShot** [Androz2091/discord-player#108]
Hello when i try to play a music i get this error,
(node:17736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
    at \node_modules\discord-player\src\Player.js:179:47

**Comment by ElectroluxV2** [comment]
Me too
(node:10656) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
    at F:\DDBOT\node_modules\discord-player\src\Player.js:179:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:10656) TypeError: Cannot read property 'createMessageCollector' of undefined
    at F:\DDBOT\node_modules\discord-player\src\Player.js:179:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by Hyuuh** [comment]
> Me too
> 
> ```
> (node:10656) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
>     at F:\DDBOT\node_modules\discord-player\src\Player.js:179:47
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
>     at processPromiseRejections (internal/process/promises.js:247:11)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> (node:10656) TypeError: Cannot read property 'createMessageCollector' of undefined
>     at F:\DDBOT\node_modules\discord-player\src\Player.js:179:47
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (node:10656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>     at emitDeprecationWarning (internal/process/promises.js:180:11)
>     at processPromiseRejections (internal/process/promises.js:249:13)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> ```

@MrPerfectShot @ElectroluxV2
How would they be using the code to give me a reference?
Remember that the parameters that [`Play`](https://discord-player.js.org/Player.html#play) has to receive must be the [`Message`](https://discord.js.org/#/docs/main/stable/class/Message) class, not the [`VoiceChannel`](https://discord.js.org/#/docs/main/stable/class/VoiceChannel) class;

```diff
- <Player>.play(message.member.voice.channel, args[0])
+ <Player>.play(message, args[0])
```

**Comment by MrPerfectShot** [comment]
I was using <Player> .play (message.member.voice.channel, args [0]) thanks is that I had seen here https://discord-player.js.org/Player.html#play with the message.member.voice.channel

**Comment by ElectroluxV2** [comment]
It's not obvious that library is defualt installed as beta release (npm i discord-player) and documentation is default for older version.

> > Me too
> > ```
> > (node:10656) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
> >     at F:\DDBOT\node_modules\discord-player\src\Player.js:179:47
> >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> >     at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
> >     at processPromiseRejections (internal/process/promises.js:247:11)
> >     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> > (node:10656) TypeError: Cannot read property 'createMessageCollector' of undefined
> >     at F:\DDBOT\node_modules\discord-player\src\Player.js:179:47
> >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > (node:10656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> >     at emitDeprecationWarning (internal/process/promises.js:180:11)
> >     at processPromiseRejections (internal/process/promises.js:249:13)
> >     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> > ```
> 
> @MrPerfectShot @ElectroluxV2
> How would they be using the code to give me a reference?
> Remember that the parameters that [`Play`](https://discord-player.js.org/Player.html#play) has to receive must be the [`Message`](https://discord.js.org/#/docs/main/stable/class/Message) class, not the [`VoiceChannel`](https://discord.js.org/#/docs/main/stable/class/VoiceChannel) class;
> 
> ```diff
> - <Player>.play(message.member.voice.channel, args[0])
> + <Player>.play(message, args[0])
> ```
