### ISSUE TITLE
TypeError: this.client.on is not a function

### ISSUE THREAD

**Issue by FunkiCraft** [Androz2091/discord-player#1081]
**Describe the bug**
I just want to start the Bot and it trow the error:         

```
\node_modules\discord-player\dist\Player.js:55
this.client.on("voiceStateUpdate", this._handleVoiceState.bind(this));
```

**To Reproduce**
Just start the Bot with discord-player v5.2.2

**Please complete the following information:**
 - Node Version: v16.14.0
 - Discord Player Version: v5.2.2
 - Discord.js Version: v13.6.0

**Comment by pauldb09** [comment]
Seems that you didn't provided your client when creating the player
