### ISSUE TITLE
After the bot disconnects a vc, it won't reconnect a second time

### ISSUE THREAD

**Issue by idleCyrex** [Androz2091/discord-player#1108]
When i disconnect the bot (rclick disconnect) it shows that the track has entered the queue instead of joining the voice again
![image](https://user-images.githubusercontent.com/92122091/161055642-cce5f6ff-e595-47d7-bdd6-95b2035f6118.png)
That s the error in console log
![image](https://user-images.githubusercontent.com/92122091/161055527-b91966b8-d9b0-49ff-b7f2-5d96cd6f480f.png)

**Comment by DevAndromeda** [comment]
can you try v5.3.x and let me know if this still persists?
