### ISSUE TITLE
URL gives bot a not found error.

### ISSUE THREAD

**Issue by BlitzDBS** [Androz2091/discord-player#1110]
**Describe the bug**
When I try to add a playlist or a song by URL it says not found. Only search works.

**To Reproduce**
Try inputting a song or playlist URL.

**Expected behavior**
The bot to play the song/playlist.

**Screenshots**
![image](https://user-images.githubusercontent.com/72931850/161178257-72966234-fdb7-4d42-8ad3-8b4e44923314.png)

**Please complete the following information:**
 - Node Version: 17.2.0
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.6.0

**Comment by Nguyenwasd72** [comment]
Mine is working (i use Niconiconii code):
![image](https://user-images.githubusercontent.com/97346078/161425272-8469743b-a9b0-4738-9d0c-e26df161581a.png)

**Comment by BlitzDBS** [comment]
Thanks for the input, but I already overhauled my bot to use DisTube.
