### ISSUE TITLE
No stream source provided

### ISSUE THREAD

**Issue by oscarbrehier** [Androz2091/discord-player#1146]
**Describe the bug**
Error: No stream source provided

I am trying to play a playlist I saved on my database but this error occurs each time I run the command.

`const songs = [];
        const queue = client.player.createQueue(interaction.guild, { metadata: interaction.channel });

        const db = await Playlist.findOne({ createur: interaction.member.id });
        if(!db) return interaction.reply({ content: 'Vous ne possédez pas de playlist' });

        console.log(client.player);

        db.chansons.forEach(async song => {

            songs.push(new Track(client.player, song));

        });

        try { if(!queue.connection) await queue.connect(interaction.member.voice.channel); } 
        catch(e) { 

            await client.player.deleteQueue(interaction.guild.id);
            return interaction.error({
                content: "Je n'ai pas pu rejoindre le salon vocal",
                ephemeral: true
            });

        }

        joinVoiceChannel({ 
            channelId: interaction.member.voice.channel.id,
            guildId: interaction.guild.id,
            adapterCreator: interaction.guild.voiceAdapterCreator,
            selfDeaf: true
        });

        queue.addTracks(songs);
        if (!queue.playing) await queue.play();

        interaction.reply({ content: 'done' });`

**Comment by pauldb09** [comment]
the package can't find a valid steam for your track, so you should store urls and search them, but not a big deal.

i've already faced this error and i haven't found yet a way to fix ( if it can be fixed )

**Comment by DevAndromeda** [comment]
re-open if this still persists
