### ISSUE TITLE
Track duration is undefined

### ISSUE THREAD

**Issue by imLinguin** [Androz2091/discord-player#115]
When track is added with youtube URL. It's duration is undefined as well as many other things. This brakes `createProgressBar()` function.
![image](https://user-images.githubusercontent.com/62100117/95662083-b05caa80-0b34-11eb-9ee6-7cf1beb37dea.png)

**Comment by Androz2091** [comment]
Can you test using v3.0.0-beta.3 please?

**Comment by martin640** [comment]
Bug is still present in v3.0.0
![image](https://user-images.githubusercontent.com/34661724/98028777-dbbe7680-1e0e-11eb-98ec-4ab4c6db770b.png)

**Comment by Androz2091** [comment]
Did you try using v3.0.1?

**Comment by martin640** [comment]
> Did you try using v3.0.1?

yes, same result
![image](https://user-images.githubusercontent.com/34661724/98035850-686e3200-1e19-11eb-8302-aa39e7b3277b.png)

**Comment by imLinguin** [comment]
I'll do some research and testing. I'll let you guys know what's going.

**Comment by imLinguin** [comment]
Looks like it works with playlists only.
![obraz](https://user-images.githubusercontent.com/62100117/98085480-ae5ce180-1e7d-11eb-8ee6-3f66085367a0.png)
URLs to one video still broken

**Comment by imLinguin** [comment]
Made pr #141 that should fix all problems with durations and undefined author.

**Comment by Androz2091** [comment]
Fixed.
