### ISSUE TITLE
Add nextTrack() function to queue

### ISSUE THREAD

**Issue by drjayy** [Androz2091/discord-player#1154]
**Describe the feature you would like**

```
I imagine a function inside the queue, where you can easily grab the next Track object for simplicity purposes. 
Use case -> Previewing the next playing track when skipping a track (see screenshot below)
```

**Expected behavior**

```
Get the next Track in the queue.
```

**Screenshots**

![image](https://user-images.githubusercontent.com/77808206/166233868-55043872-6afa-46e9-a041-913104d30d0c.png)

**Additional context**

**Current Grabbing Method:**

```
queue.tracks.values().next().value
```

**Comment by Olebeh** [comment]
isn't `queue.tracks[0]` even more simplier then this function?

**Comment by jayyythewaffle** [comment]
> isn't `queue.tracks[0]` even more simplier then this function?

queue.tracks[0] wasn't working for me, it always printed undefined

**Comment by Olebeh** [comment]
> 

Well, actually, it just can't work, the reason why it didn't work for you is because you maybe hadn't any tracks in your queue? Also, try logging `queue.tracks.length`, if it's more than one, then `queue.track[0]` should be logged as a Track object

**Comment by jayyythewaffle** [comment]
> > 
> 
> Well, actually, it just can't work, the reason why it didn't work for you is because you maybe hadn't any tracks in your queue? Also, try logging `queue.tracks.length`, if it's more than one, then `queue.track[0]` should be logged as a Track object

I don't know what happend that `queue.tracks[0]` didn't work for me but the method above definitely works too, But thanks you for the advice.

**Comment by drjayy** [comment]
Closed due to missing activity and participation
