### ISSUE TITLE
Yesterday worked fine today NOT, it doesnt work anymore...

### ISSUE THREAD

**Issue by Tomato6966** [Androz2091/discord-player#117]
Finding songs is not possible ... sadly

**Comment by Cyanitem** [comment]
Agreed

**Comment by TisRyno** [comment]
Two libraries required by discord-player were removed, see -
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

**Comment by Snowflake107** [comment]
@TisRyno nope, DMCA took down **youtube-dl** which is a python lib and **discord-player** is a JavaScript lib. This package isnt finding songs because that's what happens when u r using a scraper and website updates it's structure.

**Comment by Snowflake107** [comment]
For more info, see **[ytsr issue #71](https://github.com/TimeForANinja/node-ytsr/issues/71)**

**Comment by Tomato6966** [comment]
For now this package may not work, but maybe it will get updated soon, you can still use the source code to code it yourselfe with discord-ytld-core and youtube-sr or so.
