### ISSUE TITLE
[NOT A BUG WITH THIS, BUT WITH THE WEBSITE] Wrong information

### ISSUE THREAD

**Issue by CraftingShadowDE** [Androz2091/discord-player#1180]
**Describe the bug**
On this [website](https://discord-player.js.org/docs/main/master/typedef/PlayerOptions), there is a problem. It tells you that the option volumeSmoothness is a boolean, but it isn't. This confused me and I think I'm not the only one, so please correct it.

**To Reproduce**
1. Click on the link ( https://discord-player.js.org/docs/main/master/typedef/PlayerOptions )
2. Scroll down to volumeSmoothness
3. See error --> It tells you that it's a boolean

**Expected behavior**
It tells you that it's not a boolean

**Screenshots**
![grafik](https://user-images.githubusercontent.com/82935664/169882070-55baf632-c063-4215-91ad-3af3f85522c3.png)

**Please complete the following information:**
 - Node Version: -/-
 - Discord Player Version: -/-
 - Discord.js Version: -/-

**Additional context**
-/-

**Comment by pauldb09** [comment]
Seems that docs are not updated because it's a number in the types files, weird
