### ISSUE TITLE
New Feature Requests

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#12]
I've been using this package as my daily music driver for my bot for a the past day now, and I've got some features which could be very useful.

`client.player.remove(songId)` - The songId would be what it is listed as in the queue so you would have to implement `Song.SongId`
Playlist support? - I don't know if this is already a thing
Add the requester to who queued the song `Song.requestedBy`
`client.player.search(query, maxResults)` - Searches for music on YouTube and returns about the results.
`client.player.seek(time)` - Seeks to a certain part in the song

**Comment by thomasthebro1** [comment]
I will keep adding things which could be added here:
Another thing I recommend adding is more options to `client.player.isPlaying`, instead of making it return a boolean value, return and object with the following data:
```
{
    Playing: boolean,
    Paused: boolean
}

**Comment by thomasthebro1** [comment]
Support for other services such as SoundCloud and Spotify would be a nice addition! 👍

**Comment by thomasthebro1** [comment]
I've managed to create 2 commands (remove - removes a specific song from the queue, shuffle - shuffles the queue) which I've incorporated without the module framework and they work great 😄

**Comment by Androz2091** [comment]
All right, nice! If you know how to implement it in the package, you can do it.

**Comment by thomasthebro1** [comment]
Hey I was just wondering if you would be nice enough to put my bot on the README for the package. The bot isn't open source but it would be nice if it could be listed under "Public Bots" which rely on the package for music :).

The bot is called Radon Bot and can be invited using this link: https://discordapp.com/api/oauth2/authorize?client_id=579766576383918115&permissions=8&scope=bot

**Comment by Androz2091** [comment]
The `examples of bots` section is useful for users because **they can read the code to make their own bots**. If your bot's code is not public, it won't really have an interest. But we could imagine `Made with` section, dedicated to the bots like you, yes.
And as you can see, the v1.4.0 introduced some requested features above!

**Comment by thomasthebro1** [comment]
Yes I noticed the changes, I am currently in the middle of updating my code to patch these changes.

**Comment by thomasthebro1** [comment]
Features added in Version 2 (except seek)
