### ISSUE TITLE
returning the "Not found" error for all inputs

### ISSUE THREAD

**Issue by Naxey** [Androz2091/discord-player#120]
The module stopped returning _result_ and is now returning the "Not found" error for any input
the code snipped containing _result_

> const result = await client.player.play(message.member.voice.channel, args.join(" "), message.author).catch((err) => {console.log(err)});
> if(!result) return message.channel.send(`Your songs weren't found...`);

the err log:

> 0|bot-clea | Error: Not found
> 0|bot-clea |     at /root/node_modules/discord-player/src/Player.js:285:35
> 0|bot-clea |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by iiFed** [comment]
the package is broken 😐  your code looks fine

**Comment by TheGamer456YT** [comment]
yeah, i've been getting the same thing these few days, looks like the package is broken sadly...

**Comment by Androz2091** [comment]
Duplicated of #122
