### ISSUE TITLE
<rejected> TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by AgileGhost** [Androz2091/discord-player#1201]
**Describe the bug**
I have no idea what is causing this bug, nor do I know what it does. I just saw it pop up in my logs a few times. Nothing has changed in terms of code for the bot for this to happen, so there is no obvious link to what could be causing it, as this is my first time seeing it. (I am using play-dl with it btw.)

```js
Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading '0')
      at /data/Bots/Crystalline/node_modules/discord-player/dist/Player.js:388:68
      at Array.map (<anonymous>)
      at Player.<anonymous> (/data/Bots/Crystalline/node_modules/discord-player/dist/Player.js:383:72)
      at Generator.next (<anonymous>)
      at fulfilled (/data/Bots/Crystalline/node_modules/tslib/tslib.js:115:62)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
} undefined
```
Ver: 5.2.2

**Comment by YuriXbr** [comment]
temp fix
go to the <discord-player/dist/Player.js file on line 388, comment the code already written and put any text in its place, you will not have the information of the author of the song, but there will be no crashes


`author: (_d = 'temp disabled'),  //(_d = (_c = m.track.artists[0]) === null || _c === void 0 ? void 0 : _c.name) !== null && _d !== void 0 ? _d : "Unknown Artist",`

**Comment by DevAndromeda** [comment]
try v5.3.x, re-open if this still persists
