### ISSUE TITLE
Feature to show since when the bot is playing

### ISSUE THREAD

**Issue by CraftingShadowDE** [Androz2091/discord-player#1203]
**Describe the feature you would like**
I would love to have a way to get a timestamp of the current queue being created so you can show the user since when it's playing.

**Expected behavior**
```js
const queue = client.player.getQueue(interaction.guild.id);
console.log(queue.playingSince);
```
The output should be a unix timestamp which you can then convert to a discord timestamp
```js
interaction.channel.send({ content: `The bot is playing since <t:`+queue.playingSince+`:F>` });
```
Then, you could see since when the bot has been playing (example is shown in the screenshot)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/82935664/173433281-162c9a90-3366-4bb6-afcc-5148842d1199.png)

**Additional things**
If this is already possible, please tell me how because I couldn't find anything.

**Comment by nizeic** [comment]
store the timestamp when the queue gets created with `Date.now()`?

e.g
```js
// somewhere in your play command, when queue.connect() gets called
queue.playingSince = Math.floor(Date.now() / 1000);

console.log(queue.playingSince);
```

then send it to discord with
```js
.channel.send({ content: `The bot has been playing since <t:${queue.playingSince}:F>` });
```

**Comment by DevAndromeda** [comment]
Are we talking about the timestamp that starts from the queue creation? If so, we can use the queue's id to do the trick. Since the id of a queue is `Snowflake`, we can use the snowflake deconstructor to get the timestamp back:

```js
import { SnowflakeUtil } from "discord.js"

const playingSince = SnowflakeUtil.deconstruct(queue.id).timestamp;
```

**Comment by CraftingShadowDE** [comment]
> Are we talking about the timestamp that starts from the queue creation? If so, we can use the queue's id to do the trick. Since the id of a queue is `Snowflake`, we can use the snowflake deconstructor to get the timestamp back:
> 
> ```js
> import { SnowflakeUtil } from "discord.js"
> 
> const playingSince = SnowflakeUtil.deconstruct(queue.id).timestamp;
> 
> // or
> const timestamp = `<t:${Date.parse(SnowflakeUtil.deconstruct(queue.id).date) / 1000}:F>`;
> ```

This is what I have done now, I guess the other one would work too but this seems better to me. Thank you!
