### ISSUE TITLE
Some events not working & not adding songs to queue

### ISSUE THREAD

**Issue by iiBlackwolf** [Androz2091/discord-player#1225]
Some of the package events are not working like
```js
    player.on("trackAdd", async (queue, track) => {
...
    });

    player.on("trackStart", (queue, track) => {
...
    });
```

and i am adding the music to queue then play it if it wasn't playing by
```js
if (!queue.playing) await queue.play();
```
If the `trackStart` didn't work `queue.playing` return false so it doesn't add the music to queue it plays the music even if it was already playing another one before

**Please complete the following information:**
 - Node Version: 16.7.0
 - Discord Player Version: ^5.2.3-dev
 - Discord.js Version: ^13.6.0

**Comment by Olebeh** [comment]
yeah, that's a known bug, but no one cares about it starting from november 2021. there's already a not stable fix on dev branch, but i still recommend to download 5.0.2 version for events to fully work
