### ISSUE TITLE
SOUNDCLOUD_SEARCH Unhandled Exception

### ISSUE THREAD

**Issue by colinkehoe** [Androz2091/discord-player#1247]
**Describe the bug**
Server user tries to search SoundCloud for "pon de floor". 

**To Reproduce**
Use QueryType.SOUNDCLOUD_SEARCH for the Query, using a string argument.
Use "pon de floor" as the search terms.

**Expected behavior**
Play "Pon de Floor" by Major Lazer.

**Screenshots**
![Screen Shot 2022-07-12 at 10 26 52 PM](https://user-images.githubusercontent.com/66656222/178644633-2bad9cf4-8403-44ec-b48a-2616c21ebe24.png)
![Screen Shot 2022-07-12 at 10 18 13 PM](https://user-images.githubusercontent.com/66656222/178645004-97662d2e-c0e8-4064-800d-947c7a9040ee.png)**Please complete the following information:**
 - Node Version: 16.15.1
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.8.0

**Additional context**
I attempted putting the code in a try{}catch{} block, but it still outright crashes the bot instead of just throwing the error. Not sure why.

**Comment by pauldb09** [comment]
Coul you please add a listenner to the unhandledException event using this:
just put it on top of your main file

```js
process.on("unhandledException",console.log)
```

**Comment by colinkehoe** [comment]
![Screen Shot 2022-07-18 at 12 07 04 PM](https://user-images.githubusercontent.com/66656222/179565062-829ee43f-f79b-4652-b9ef-71732dde588c.png)
The command is inside of a try...catch block so I'm not entirely sure where it's going wrong.

**Comment by DevAndromeda** [comment]
please transfer to https://github.com/DevAndromeda/soundcloud-scraper
