### ISSUE TITLE
Add an isPaused property to the Queue class

### ISSUE THREAD

**Issue by ASPNyan** [Androz2091/discord-player#1251]
**Describe the feature you would like**
I would like there to be a feature that gets whether the selected queue is currently paused.

**Expected behavior**
`queue.isPaused` would return `true` or `false` depending on whether it is paused or not. I would use it both as a way to show for example, if someone used the `/queue` command I have (which shows the queue) then in the footer of the embed the code would be `.setFooter({content: `Paused: ${queue.isPaused}`})` as well as other things. It could also be used to check if someone is trying to pause the queue when it is already paused, or vice versa. i.e.
```
const state = interaction.options.getBoolean('state')
if ((queue.isPaused && state) === true) {
    return interaction.reply({
        content: `The Queue is Already Paused!`,
        ephemeral: true
    })
}
```

**Screenshots** & **Additional context**
n/a

**Comment by pauldb09** [comment]
`queue.connection.paused` already exists

**Comment by ASPNyan** [comment]
Well..
Imma be honest I thought I checked everything
Seems like a kinda roundabout way to do it but sure, ty
