### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'setVolume')

### ISSUE THREAD

**Issue by ASPNyan** [Androz2091/discord-player#1256]
**Describe the bug**
When using `queue.setVolume()`, an error stating `TypeError: Cannot read properties of undefined (reading 'setVolume')` occurs

**To Reproduce**
1. Use `queue.setVolume()`
2. Error

**Expected behavior**
Change the queue volume and continue normally

**Screenshots**
n/a

**Please complete the following information:**
 - Node Version: v16.15.0
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.9.0

**Additional context**
This happens with both a set number (`queue.setVolume(10);`) and using a const (`const volume = 10; queue.setVolume(volume);`)

Code (this is inside of a slash command callback using WOKCommands):
```
callback: async({ interaction, guild }) => {
        const volume = interaction.options.getInteger(`volume`)!
        const queue = player.getQueue(guild!) as Queue

        queue.setVolume(volume)

        const embed = new MessageEmbed()
        .setDescription(`**Volume Set to ${volume}!**`)

        return await interaction.reply({
            embeds: [embed]
        })
}
```

**Comment by DevAndromeda** [comment]
Queue doesn't exist
