### ISSUE TITLE
Plz try to understand 

### ISSUE THREAD

**Issue by parasop** [Androz2091/discord-player#126]
Plz update discord-player we need your support

**Comment by Snowflake107** [comment]
Please wait because we are also humans and we have a lot of work, not only `discord-player` but we will try to update it asap 😄

**Comment by parasop** [comment]
Plz first update discord-player

**Comment by Androz2091** [comment]
Hello, if you need more help please use the discord server: **https://discord.gg/hw87VUQ**.
