### ISSUE TITLE
queue.tracks returning an empty array

### ISSUE THREAD

**Issue by MDxWARRIORxOP** [Androz2091/discord-player#1275]
```js
queue.tracks //=> empty array
```

queue.tracks is returning an empty array even tho music is being played.

 - Node Version: 18.6.0
 - Discord Player Version: 5.3.0-dev.3
 - Discord.js Version: 14.0.3

**Comment by DevAndromeda** [comment]
Are you testing this with o ly one track or have you tried afding multiple tracks?

**Comment by MDxWARRIORxOP** [comment]
okay well that worked, thanks :D
