### ISSUE TITLE
add leaveOnEnd delay

### ISSUE THREAD

**Issue by eyerrock** [Androz2091/discord-player#1299]
**Describe the feature you would like**
Add a delay for the leaveOnEnd option.
It would be nice if there was something similiar to leaveOnEmptyCooldown but for the leaveOnEnd option.

**Expected behavior**
The bot would stay for the specified amount of time and disconnect afterwards.
When new tracks are addedto the queue the cooldown would get reset.

**Comment by xWass** [comment]
yes good idea i approve

**Comment by Olebeh** [comment]
upvote, wanted this feature for very long time, but didn't publish for some reason
