### ISSUE TITLE
The Player isn't picking YouTube Playlist Thumbnails

### ISSUE THREAD

**Issue by GPBR815** [Androz2091/discord-player#1302]
When i try to load a youtube playlist into my bot, it gives me the following error: "given: Thumbnail { id: null, width: 0, height: 0, url: null }", while when i use other commands like load a single YouTube song, or even Spotify playlists, the thumbnails works fine, is there a way to fix it? Thanks in advance

**Comment by DevAndromeda** [comment]
Could you open this issue at https://github.com/devandromeda/youtube-sr/issues

**Comment by GPBR815** [comment]
> Could you open this issue at https://github.com/devandromeda/youtube-sr/issues
Done!
