### ISSUE TITLE
skipTo with repeatMode

### ISSUE THREAD

**Issue by TapsHTS** [Androz2091/discord-player#1308]
**Describe the bug**
If the repeatMode is set to Queue, the skipTo function removes the music that is before the requested one.

**To Reproduce**
1. Playing multiple songs
2. Set a repeatMode (Queue for example)
3. and use skipTo

**Please complete the following information:**
 - Node Version: 16.16.0
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.6.0

**Additional context**
If you want to test it with my bot in the Support Server use @Neotux

**Comment by TapsHTS** [comment]
@DevAndromeda ?

**Comment by DevAndromeda** [comment]
> @DevAndromeda ?

There's no repeat mode checks inside `skipTo` so this is a bit odd behavior. Is it working normally?

**Comment by TapsHTS** [comment]
I think we should add one to avoid losing the music.
