### ISSUE TITLE
The bot can't play music

### ISSUE THREAD

**Issue by CodeName393** [Androz2091/discord-player#1309]
**Describe the bug**
The bot, which was used well until the last minute, will not play from today.

**To Reproduce**
Play music as usual

**Expected behavior**
Music Played

**Screenshots**
![image](https://user-images.githubusercontent.com/62503817/185385240-ba2a27e7-6066-47be-bc10-89acabe57089.png)
![image](https://user-images.githubusercontent.com/62503817/185385342-c0b43daa-48f9-461b-af96-19f8f071c91c.png)

**Please complete the following information:**
 - Node Version: 16.15.1
 - Discord Player Version: 5.3.1
 - Discord.js Version: 13.10.2

**Additional context**

**Comment by CanineData62816** [comment]
I believe this is an issue with ytdl-core, [see here](https://github.com/fent/node-ytdl-core/issues/1110)

**Comment by tonyG433** [comment]
Yeah, it is indeed a ytdl-core issue. We are currently waiting for a fix

**Comment by xWass** [comment]
Can confirm, ytdl skill issued. Still appears to be an issue. I read downgrading to version 4.10.0 doesn't fix the issue with this specific lib. causes disconnect after playing starts.

**Comment by xWass** [comment]
Noticed some people still facing issues. Thanks to Umut for this solution.
You can swap from dev 3 to 5.3-dev.2 and set ytdl-core to 4.10.0. It seems the newest version of ytdl-core breaks the bot.

**Comment by DevAndromeda** [comment]
Closed in favor of #1295, please move further discussions there
