### ISSUE TITLE
addToQueue does not exist on class 'Player'.

### ISSUE THREAD

**Issue by CuriosBasant** [Androz2091/discord-player#132]
I think there is no method called addToQueue on class Player. But it is mentioned in the docs though. Why is that?

**Comment by Androz2091** [comment]
Indeed this method has been removed in v3.0.0. Where do you see it in the docs?

**Comment by CuriosBasant** [comment]
Yes here it is. 
![Uploading image.png…]()

**Comment by Androz2091** [comment]
Can you refresh the page? (clear your cache)

**Comment by CuriosBasant** [comment]
Yes, it is done now.
