### ISSUE TITLE
Add a feature to go to the previous song

### ISSUE THREAD

**Issue by CuriosBasant** [Androz2091/discord-player#133]
Instead of deleting the track from the queue after it is ended/switched. Let it be in the queue, and let the user to go back and listen to previous song again.

**Comment by Androz2091** [comment]
Interesting idea. Do you have an idea for the name of the method to go back to the previous song?

**Comment by CuriosBasant** [comment]
just use `back` or `prev` or `previous`

**Comment by CuriosBasant** [comment]
And I suggest to change the method `skip` to `next`. Then calling `back` will be good.
