### ISSUE TITLE
Player won't play Spotify music

### ISSUE THREAD

**Issue by ddemile** [Androz2091/discord-player#1341]
**Describe the bug**
The player find anything when i put a spotify link

**Expected behavior**
Listen to a good spotify music...

**Please complete the following information:**
 - Node Version: v16.15.1
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.6.0

**Comment by retrouser955** [comment]
Send code

**Comment by ddemile** [comment]
```js
const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require("discord.js");
const client = require('../../Utility/client')
const { QueryType } = require("discord-player");

module.exports = {
    data: new SlashCommandBuilder()
        .setName('play')
        .setDescription("Permet de jouer des vidéos ou des sons")
        .addStringOption(option => option
            .setName('searchterms')
            .setDescription("Mots clés")
            .setRequired(true)),
    async execute(interaction) {
        let embed = new MessageEmbed()

        let errorEmbed = new MessageEmbed()
            .setColor("RED")

        if (!interaction.member.voice.channel) {
            errorEmbed.setDescription(':x: Vous devez être dans un salon vocal pour executer cette commande')
            return interaction.reply({ embeds: [errorEmbed] })
        }

        if (!interaction.member.voice.channel.permissionsFor(client.user).toArray().includes("CONNECT" && "SPEAK")) {
            errorEmbed.setDescription(`:x: Je n'ai pas les permissions nécessaires sur <#${interaction.member.voice.channel.id}>`)
            return interaction.reply({ embeds: [errorEmbed] })
        }

        await interaction.deferReply();

        try {
            const queue = await client.player.createQueue(interaction.guild)
            if (!queue.connection) await queue.connect(interaction.member.voice.channel)
            if (!queue.allTracks) queue.allTracks = []
    
            let url = interaction.options.getString("searchterms")
            try {
                var result = await client.player.search(url, {
                    requestedBy: interaction.user,
                    searchEngine: QueryType.YOUTUBE_PLAYLIST
                })
    
                if (result.tracks.length === 0) {
                    result = await client.player.search(url, {
                        requestedBy: interaction.user,
                        searchEngine: QueryType.SPOTIFY_PLAYLIST
                    })
                }
    
                const playlist = result.playlist
                console.log(playlist)
                await queue.addTracks(result.tracks)
                embed.setDescription(`**${result.tracks.length} sons de [${playlist.title}](${playlist.url})** ont été ajouté à la queue`).setThumbnail(playlist.thumbnail)
                result.tracks.forEach(song => {
                    queue.allTracks.push(song)
                })
            } catch (err) {
                const result = await client.player.search(url, {
                    requestedBy: interaction.user,
                    searchEngine: QueryType.AUTO
                })
    
                if (result.tracks.length === 0) {
                    errorEmbed.setDescription(':x: Aucun resultat')
                    return await interaction.editReply({ embeds: [errorEmbed] })
                }
    
                const song = result.tracks[0]
                await queue.addTrack(song)
                embed.setDescription(`**[${song.title}](${song.url})** a été ajouté à la queue`).setThumbnail(song.thumbnail).setFooter({ text: `Duration: ${song.duration}` })
                queue.allTracks.push(song)
            }
    
            if (!queue.playing) await queue.play()
            await interaction.editReply({ embeds: [embed] })
        } catch (err) {
            console.error(err)
            errorEmbed.setDescription(':x: Une erreur est survenue')
            return interaction.editReply({ embeds: [errorEmbed] })
        }
    },
};

```

**Comment by retrouser955** [comment]
Try console logging `results`

**Comment by ddemile** [comment]
![image](https://user-images.githubusercontent.com/104416229/188258347-25c5d25f-288e-4090-ac88-b5771d09e5a9.png)

**Comment by ddemile** [comment]
And it's perfectly working with youtube

**Comment by retrouser955** [comment]
This is **not a bug**. you have used `queue.allTracks.push` but you have to use `queue.addTracks` to add multiple tracks to the queue

**Comment by retrouser955** [comment]
Check out the following links
https://github.com/Whirl21/Musico/blob/musico/commands/slash/music/play.js#L78

https://discord-player.js.org/docs/main/master/class/Queue?scrollTo=addTracks

**Comment by ddemile** [comment]
The problem is the `client.player.search` function don't return any tracks when i put a spotify link

**Comment by DevAndromeda** [comment]
> ```js
> const { SlashCommandBuilder } = require('@discordjs/builders');
> const { MessageEmbed } = require("discord.js");
> const client = require('../../Utility/client')
> const { QueryType } = require("discord-player");
> 
> module.exports = {
>     data: new SlashCommandBuilder()
>         .setName('play')
>         .setDescription("Permet de jouer des vidéos ou des sons")
>         .addStringOption(option => option
>             .setName('searchterms')
>             .setDescription("Mots clés")
>             .setRequired(true)),
>     async execute(interaction) {
>         let embed = new MessageEmbed()
> 
>         let errorEmbed = new MessageEmbed()
>             .setColor("RED")
> 
>         if (!interaction.member.voice.channel) {
>             errorEmbed.setDescription(':x: Vous devez être dans un salon vocal pour executer cette commande')
>             return interaction.reply({ embeds: [errorEmbed] })
>         }
> 
>         if (!interaction.member.voice.channel.permissionsFor(client.user).toArray().includes("CONNECT" && "SPEAK")) {
>             errorEmbed.setDescription(`:x: Je n'ai pas les permissions nécessaires sur <#${interaction.member.voice.channel.id}>`)
>             return interaction.reply({ embeds: [errorEmbed] })
>         }
> 
>         await interaction.deferReply();
> 
>         try {
>             const queue = await client.player.createQueue(interaction.guild)
>             if (!queue.connection) await queue.connect(interaction.member.voice.channel)
>             if (!queue.allTracks) queue.allTracks = []
>     
>             let url = interaction.options.getString("searchterms")
>             try {
>                 var result = await client.player.search(url, {
>                     requestedBy: interaction.user,
>                     searchEngine: QueryType.YOUTUBE_PLAYLIST
>                 })
>     
>                 if (result.tracks.length === 0) {
>                     result = await client.player.search(url, {
>                         requestedBy: interaction.user,
>                         searchEngine: QueryType.SPOTIFY_PLAYLIST
>                     })
>                 }
>     
>                 const playlist = result.playlist
>                 console.log(playlist)
>                 await queue.addTracks(result.tracks)
>                 embed.setDescription(`**${result.tracks.length} sons de [${playlist.title}](${playlist.url})** ont été ajouté à la queue`).setThumbnail(playlist.thumbnail)
>                 result.tracks.forEach(song => {
>                     queue.allTracks.push(song)
>                 })
>             } catch (err) {
>                 const result = await client.player.search(url, {
>                     requestedBy: interaction.user,
>                     searchEngine: QueryType.AUTO
>                 })
>     
>                 if (result.tracks.length === 0) {
>                     errorEmbed.setDescription(':x: Aucun resultat')
>                     return await interaction.editReply({ embeds: [errorEmbed] })
>                 }
>     
>                 const song = result.tracks[0]
>                 await queue.addTrack(song)
>                 embed.setDescription(`**[${song.title}](${song.url})** a été ajouté à la queue`).setThumbnail(song.thumbnail).setFooter({ text: `Duration: ${song.duration}` })
>                 queue.allTracks.push(song)
>             }
>     
>             if (!queue.playing) await queue.play()
>             await interaction.editReply({ embeds: [embed] })
>         } catch (err) {
>             console.error(err)
>             errorEmbed.setDescription(':x: Une erreur est survenue')
>             return interaction.editReply({ embeds: [errorEmbed] })
>         }
>     },
> };
> ```

This could be happening because of your query type. Remove multiple search handlers and use a single one with `QueryType.AUTO` which auto resolves your query. This lib cannot search spotify playlists, you have to explicitly provide a url

**Comment by ddemile** [comment]
![image](https://user-images.githubusercontent.com/104416229/188259054-5ee6ae7c-e005-4f89-9c23-09ac446f660c.png)

That's not working

**Comment by ddemile** [comment]
Oh it's working in new version of discord-player

**Comment by Lacyway** [comment]
Having the same issue on 5.3.1. Searching for a spotify does not work, I've logged the 'searchResult' and it finds nothing. Any ideas what could be wrong?

```js
const searchResult = await player.search(query, {
            requestedBy: interaction.user,
            searchEngine: QueryType.AUTO
});
```

**Comment by retrouser955** [comment]
as @ddemile mentioned, upgrade discord-player

**Comment by Lacyway** [comment]
I'm running 5.3.1, isn't that the latest?

**Comment by retrouser955** [comment]
> I'm running 5.3.1, isn't that the latest?

Can you send code?

**Comment by Lacyway** [comment]
It's as in my reply above. It's been working fine for months and then suddenly stopped working. Updated to 5.3.1, update Node JS and Discord JS and still won't find any Spotify links. Playlists works.

```js
const searchResult = await player.search(query, {
            requestedBy: interaction.user,
            searchEngine: QueryType.AUTO
});
```

**Comment by KenjieDec** [comment]
I think it's because `spotify-url-info` returning _**undefined`**_

**Comment by retrouser955** [comment]
> I think it's because `spotify-url-info` returning _**undefined**_

Yes this might be it

**Comment by Bibyyy** [comment]
> Oh ça marche dans la nouvelle version de discord-player

tu es sous quel version ?

**Comment by BeratBilgic** [comment]
I was getting the same error. I uninstalled and reinstalled discord-player. It works with spotify link now for me.
