### ISSUE TITLE
Spotify tracks duration and thumbnail

### ISSUE THREAD

**Issue by Bibyyy** [Androz2091/discord-player#1342]
**Describe the bug**
the duration of a spotify sound or its image is not available. It works with youtube song.

**To Reproduce**
1. put this overrides to update spotify-url-info (picture 1)

2. Try to play spotify song with url. and if when it playing you create an embed with "result.tracks[0].duration" you see that (picture 2):

3. Same for the picture of song "result.tracks[0].thumbnail" return basic spotify picture like picture 3 

**Expected behavior**
But I would like it to be like before and like youtube sounds so image and duration like this:
![image](https://user-images.githubusercontent.com/109045167/188316059-3bc35d34-0e3a-46cc-9f85-86bd17c2c168.png)

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/109045167/188315878-fd25c2f6-bab6-40a5-9ab4-a368ff0230d3.png)
2. ![image](https://user-images.githubusercontent.com/109045167/188315989-a1e8fc74-3a63-4c7b-a716-168b644eca8c.png)
3. ![image](https://user-images.githubusercontent.com/109045167/188316128-a4d67e79-e1fc-41a7-a6af-8c2a7630e6c5.png)

**Please complete the following information:**
 - Node Version: 18.7.0
 - Discord Player Version: 5.3.1
 - Discord.js Version: 14.3.0
 - spotify-url-info: 3.1.7

**Additional context**
i don't know what else to say, this only works with spotify, probably due to spotify-url-info in discord-player

**Comment by retrouser955** [comment]
Can you send your code?

**Comment by Bibyyy** [comment]
> Can you send your code?

`if(!interaction.member.voice.channel)
            return interaction.followUp("Veuillez d'abord rejoindre un channel vocal.");
        
        const audio = interaction.options.getString("audio");
        
        const queue = await player.createQueue(interaction.guild);

        if(!queue.connection) await queue.connect(interaction.member.voice.channel)
        let embed = new EmbedBuilder()
        const result = await player.search(audio, {
            requestedBy: interaction.user,
            searchEngine: QueryType.AUTO,
        });
        console.log(result);
        if(result.tracks.length === 0)
            return interaction.followUp("Aucun résultats");
        
        await interaction.followUp({ content: `⏱ | Chargement de votre ${result.playlist ? 'playlist' : 'son'}...` });
        if (result.playlist) {
            queue.addTrack(result.tracks[0]);
            queue.addTracks(result.tracks);
        }
        else 
            queue.addTrack(result.tracks[0]);
        
        if (!queue.playing) await queue.play();
        result.playlist ? embed
            .setColor("#6f5ef7")
            .setTitle("__Commande /play :__")
            .setAuthor({name: "Lobot", iconURL: "https://cdn.discordapp.com/attachments/995460031115956255/995735324833615952/emblem_128.png"})
            .setDescription(`**${result.tracks.length} sons depuis [${result.playlist.title}](${result.playlist.url})** à été ajouté à la Queue`)
            .setThumbnail(result.tracks[0].thumbnail)
            .setFooter({text: `Durée: ${result.tracks[0].duration}`})
            .setTimestamp()
        :
        embed
            .setColor("#6f5ef7")
            .setTitle("__Commande /play :__")
            .setAuthor({name: "Lobot", iconURL: "https://cdn.discordapp.com/attachments/995460031115956255/995735324833615952/emblem_128.png"})
            .setDescription(`**[${result.tracks[0].title}](${result.tracks[0].url})** à été ajouté à la Queue`)
            .setThumbnail(result.tracks[0].thumbnail)
            .setFooter({text: `Durée: ${result.tracks[0].duration}`})
            .setTimestamp();
        
        if (!queue.playing) await queue.play()
        await interaction.editReply({
            content: "",
            embeds: [embed]
        });`

**Comment by Bibyyy** [comment]
![image](https://user-images.githubusercontent.com/109045167/188316519-f456379c-24ca-4682-b248-30976290833c.png)
I feel like everything is default, 0 views, no duration, default thumbnail

**Comment by retrouser955** [comment]
Probably caused by [this line](https://github.com/Androz2091/discord-player/blob/master/src/Player.ts#L411) or [this line](https://github.com/Androz2091/discord-player/blob/master/src/Player.ts#L422)

**Comment by Bibyyy** [comment]
> Probably caused by [this line](https://github.com/Androz2091/discord-player/blob/master/src/Player.ts#L411) or [this line](https://github.com/Androz2091/discord-player/blob/master/src/Player.ts#L422)
> 
> [This line](https://github.com/Androz2091/discord-player/blob/8d7b841d9aa2f21c484d75a99ebfe816bc0988c1/src/utils/Util.ts#L26) might be trying to divide a string

yep, the both of this line return not the good things : 
```ts
thumbnail: m.track.album?.images?.[0]?.url ?? "https://www.scdn.co/i/_global/twitter_card-default.jpg",
duration: Util.buildTimeCode(Util.parseMS(m.track.duration_ms)),
```
