### ISSUE TITLE
Bot randomly stops playing music

### ISSUE THREAD

**Issue by Olebeh** [Androz2091/discord-player#1348]
I don't really know what's causing it, but here is how it looks:

we have a few songs in the queue. When one song ends, it actually doesn't end. We check now playing - this song is playing 3:20/3:20. The player is not paused at this time. It doesn't happen with a specific song, it can happen randomly. Only destroying the queue helps. Skip and other things doesn't help. What's can be the problem?

**Comment by DevAndromeda** [comment]
@Olebeh can you add `debug` event listener and check the player status for this particular case?
