### ISSUE TITLE
Volume Resets when playing new song

### ISSUE THREAD

**Issue by EBits00** [Androz2091/discord-player#1355]
**Describe the bug**
When song ends and plays a new song, volume resets to 100%

**To Reproduce**
Just play a song, set the volume to like 15%, then when the next song plays it resets to 100%

**Expected behavior**
Should stay at the wanted %

**Please complete the following information:**
 - Node Version: 16.15.1
 - Discord Player Version: 5.3.1
 - Discord.js Version: 14.3.0

**Comment by archaeopteryx1** [comment]
@EBits00 the fix is currently available on `discord-player@dev` if you need it asap. This change will soon be released on stable channel after finishing some other tasks.

**Comment by KingKophuhn** [comment]
@EBits00 in /discord-player/dist/Structures/Queue.js line: 681 is missing this line of code:
this.setVolume(this.options.initial Volume);
Add this line just before this:
setTimeout(() => {
            this.connection.playStream(resource);
        }, this.#getBufferingTimeout()).unref();
for me everything is working now.
