### ISSUE TITLE
TypeError: discord_js_1.IntentsBitField is not a constructor

### ISSUE THREAD

**Issue by Elpistolero131** [Androz2091/discord-player#1366]
Hi, I install discord-player and I have this error:
`TypeError: discord_js_1.IntentsBitField is not a constructor` and I don't know why, I'm in the good version, etc...

Here is all of the error:
```
/home/container/node_modules/discord-player/dist/Player.js:46
        if (this.client?.options?.intents && !new discord_js_1.IntentsBitField(this.client?.options?.intents).has(discord_js_1.IntentsBitField.Flags.GuildVoiceStates)) {
                                              ^
TypeError: discord_js_1.IntentsBitField is not a constructor
    at new Player (/home/container/node_modules/discord-player/dist/Player.js:46:47)
    at /home/container/index.js:41:21
    at Object.<anonymous> (/home/container/index.js:172:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by archaeopteryx1** [comment]
> Hi, I install discord-player and I have this error: `TypeError: discord_js_1.IntentsBitField is not a constructor` and I don't know why, I'm in the good version, etc...
> 
> Here is all of the error:
> 
> ```
> /home/container/node_modules/discord-player/dist/Player.js:46
>         if (this.client?.options?.intents && !new discord_js_1.IntentsBitField(this.client?.options?.intents).has(discord_js_1.IntentsBitField.Flags.GuildVoiceStates)) {
>                                               ^
> TypeError: discord_js_1.IntentsBitField is not a constructor
>     at new Player (/home/container/node_modules/discord-player/dist/Player.js:46:47)
>     at /home/container/index.js:41:21
>     at Object.<anonymous> (/home/container/index.js:172:3)
>     at Module._compile (node:internal/modules/cjs/loader:1126:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
>     at Module.load (node:internal/modules/cjs/loader:1004:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:17:47
> ```

you're not in the good version. You are getting this error because you are trying to run this in discord.js v13. Upgrade to discord.js v14 and this error will go away.

**Comment by Elpistolero131** [comment]
ok but if I want to do the code with v13 I can't?

**Comment by archaeopteryx1** [comment]
> ok but if I want to do the code with v13 I can't?

use versions below v5.3 for v13

**Comment by Elpistolero131** [comment]
But I'm in v5.2.0 and it dosen't work

**Comment by archaeopteryx1** [comment]
> But I'm in v5.2.0 and it dosen't work

That's not helpful at all for me to provide support. I'm no god to know ehat exactly is `it doesnt work` supposed to mean when you havent listed the actual problem of 5.2.0. I am confident enough to say that the main topic of this issue shouldn't occur in this particular version because we've had tested that code for a long time with v13.

Please consider providing the following: real error/issue, reproduction steps, dependency metadata, etc. and not just "it doesnt work" so that we can actually help you 😄
