### ISSUE TITLE
 Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by x07ex** [Androz2091/discord-player#1367]
**BUG:**
```ts
(ERROR) | TypeError: Cannot read properties of undefined (reading 'source')
    at Queue.play (C:\Users\0xwar\Desktop\PhilosopherPLBot\node_modules\discord-player\dist\Structures\Queue.js:628:55)
    at Ready.<anonymous> (C:\Users\0xwar\Desktop\PhilosopherPLBot\src\events\guilds\Ready.ts:49:17)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\0xwar\Desktop\PhilosopherPLBot\src\events\guilds\Ready.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
**Code:**
```ts
   const Lofi = [
      // Array YT links
   ]

    const queue: any = await this.client.player
      .createQueue(
        this.client.channels.cache.get(configuration.voiceChannelID) as any,
        {
          metadata: {
            channel: this.client.channels.cache.get(
              configuration.voiceChannelID
            ) as any,
          },
        }
      )
      .connect(
        this.client.channels.cache.get(configuration.voiceChannelID) as any
      );

    const track = Lofi[Math.floor(Math.random() * Lofi.length)];
    await queue.play(track);
   ```

**Screnshot:**
[ Link](https://prnt.sc/ZIpGqDWWzXsw)

**Extra info:**
 - Node Version: v16.17.0
 - Discord Player Version: 5.3.1
 - Discord.js Version: 14.3.0

**Comment by archaeopteryx1** [comment]
> **BUG:**
> 
> ```ts
> (ERROR) | TypeError: Cannot read properties of undefined (reading 'source')
>     at Queue.play (C:\Users\0xwar\Desktop\PhilosopherPLBot\node_modules\discord-player\dist\Structures\Queue.js:628:55)
>     at Ready.<anonymous> (C:\Users\0xwar\Desktop\PhilosopherPLBot\src\events\guilds\Ready.ts:49:17)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\0xwar\Desktop\PhilosopherPLBot\src\events\guilds\Ready.ts:5:58)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> **Code:**
> 
> ```ts
>    const Lofi = [
>       // Array YT links
>    ]
> 
>     const queue: any = await this.client.player
>       .createQueue(
>         this.client.channels.cache.get(configuration.voiceChannelID) as any,
>         {
>           metadata: {
>             channel: this.client.channels.cache.get(
>               configuration.voiceChannelID
>             ) as any,
>           },
>         }
>       )
>       .connect(
>         this.client.channels.cache.get(configuration.voiceChannelID) as any
>       );
> 
>     const track = Lofi[Math.floor(Math.random() * Lofi.length)];
>     await queue.play(track);
> ```
> 
> **Screnshot:** [ Link](https://prnt.sc/ZIpGqDWWzXsw)
> 
> **Extra info:**
> 
> * Node Version: v16.17.0
> * Discord Player Version: 5.3.1
> * Discord.js Version: 14.3.0

looks like you are trying to play a url instead of track. You have to load a track first. Discord Player cannot play urls directly. You have to construct a `Track` object first. This can be done via `<Player>.search()`
