### ISSUE TITLE
Supports playback in buffers and audio URLs

### ISSUE THREAD

**Issue by KohnoseLami** [Androz2091/discord-player#1370]
**Describe the feature you would like**
Enables playback of Buffer, local and network files.

**Expected behavior**
Allow non-Track objects for Queue.play() function
For example, a Buffer, a local path, or a URL

**Additional context**
I'm implementing TTS for music playback and text chat on YouTube.
Music works fine, but if you generate TTS with an API, there's no way to play it.

**Comment by archaeopteryx1** [comment]
> **Describe the feature you would like** Enables playback of Buffer, local and network files.
> 
> **Expected behavior** Allow non-Track objects for Queue.play() function For example, a Buffer, a local path, or a URL
> 
> **Additional context** I'm implementing TTS for music playback and text chat on YouTube. Music works fine, but if you generate TTS with an API, there's no way to play it.

Adding support for custom sources have to be done via extractors or `onBeforeCreateStream`. Discord Player itself doesn't play anything.

Roughly, it works like this:

Step 1:
`query` => `player.search()` => `external/internal extractors` => `track objects`

Step 2:
`queue.play()` => `stream source lookup` => `fire onBeforeCreateStream if it exists else use default streaming service` => `audio stream` => `ffmpeg` => `@discordjs/voice`

You must create a `Track` object, discord-player needs a track. Even if you are playing a raw url or file path or something like that, you must initialize a track object. For example, you may initialize a local file track object and then construct stream via `onBeforeCreateStream`.

You can create an extractor to handle this: [Example of raw HTTP url extractor](https://github.com/archaeopteryx1/extractor/blob/256801d97acaa8db71395605fc6e1a4e6694cc0f/src/Attachment.ts).

If you are just trying to play raw http url, you can just install `@discord-player/extractor` and pass your query to `player.search()`
