### ISSUE TITLE
(node:2130) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!

### ISSUE THREAD

**Issue by BadBanOfficial** [Androz2091/discord-player#1371]
**Describe the bug**
Some songs doesnt play and give me this error (node:2130) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!

**Please complete the following information:**
 - Node Version: dont remember
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.10.1

**Comment by archaeopteryx1** [comment]
Listen to `connectionError` and `error` events. Example:

```js
player.on("error", () {/* do something */});
player.on("connectionError", () => {/* do something */});
```
