### ISSUE TITLE
Can discord-player play music from a live video from youtube?

### ISSUE THREAD

**Issue by chaos3326** [Androz2091/discord-player#1372]
I am new to `discord-player` and just successfully implement playing a song from URL, title name, or playing a playlist. But the bot cannot play a live song from Youtube. I just want to ask: did I do it wrong, or because discord-player does not support live video URL?

**Comment by archaeopteryx1** [comment]
Yes it can as long as youtube extractors support this. Discord Player uses ytdl-core by default but you can add your own implementation via `onBeforeCreateStream`

**Comment by chaos3326** [comment]
Thank you. Also I notice my bots usually crash because I tried to add long songs (3 hours). Is it because my bot RAM cannot handle such a long file?
