### ISSUE TITLE
Spotify links not giving duration

### ISSUE THREAD

**Issue by jmiln** [Androz2091/discord-player#1375]
**Describe the bug**
When playing music from spotify links, we're often (but not consistently) getting `'NaN:NaN:NaN:NaN'` as the duration.

**To Reproduce**
I've updated a copy of https://github.com/Whirl21/Musico to discord.js v14 (With a PR there with my current code)
- This is one of the URLs that has issues: https://open.spotify.com/track/5VHLyvcMd0g5xdcyMSddds?si=2e7283556b04452e

And this is the resulting track info we get from it:
```
Track {
  id: '1023475597692637205',
  title: 'Hush',
  author: 'HELLYEAH',
  url: 'https://open.spotify.com/track/0CLtAB24zCxWFJ9eq1ywh0',
  thumbnail: 'https://www.scdn.co/i/_global/twitter_card-default.jpg',
  duration: 'NaN:NaN:NaN:NaN',
  views: 0,
  requestedBy: User {
    id: '355948745017524225',
    bot: false,
    system: false,
    flags: UserFlagsBitField { bitfield: 0 },
    username: 'Screech',
    discriminator: '9179',
    avatar: '7a5a661114ad2cff09b8b89989fba850',
    banner: undefined,
    accentColor: undefined
  },
  playlist: undefined
}
```

**Expected behavior**
The duration to come through consistently for all songs, instead of just some

**Please complete the following information:**
 - Node Version: v16.17.0
 - Discord Player Version: 5.3.1
 - Discord.js Version: 14.3.0

**Additional context**

**Comment by retrouser955** [comment]
Hey @jmiln, Thanks for reaching out! A fix for this has been implemented on discord-player@dev. Install it using `npm i discord-player@dev`

**Comment by jmiln** [comment]
Looks like that did it, at least for me. 
Thanks for the quick response!
