### ISSUE TITLE
TypeError: queue.metadata.send is not a function

### ISSUE THREAD

**Issue by ArtichautLearnCode** [Androz2091/discord-player#1388]
TypeError: queue.metadata.send is not a function

my code : 

player.on('trackAdd', (queue, track) => {
   
    queue.metadata.send(`Track ${track.title} added in the queue ✅`);
});

**Comment by archaeopteryx1** [comment]
You should specify metadata value while creating queue:

```js
const queue = player.createQueue(interaction.guild, {
    metadata: {
        channel: interaction.channel
    }
});
```

Now you can access that channel via metadata object inside events:

```js
player.on("trackAdd", (queue, track) => {
    queue.metadata.channel.send(`Track ${track.title} added to the queue`);
});
```
