### ISSUE TITLE
Use Discord Structures

### ISSUE THREAD

**Issue by CuriosBasant** [Androz2091/discord-player#139]
I see your code, that you're not using discord structure to instantiate the `Player` for each guild. Rather you're having a collection of players that is saved to the client. I think that's not appropriate, to use efficiently. Because it requires to pass the `<Guild>.id` to each method we want to access, to access the player of that particular guild.

One more thing, why every method of the class `Player` requires us to pass a `message` object. That's really inappropriate and redundant.

**Comment by thomasthebro1** [comment]
Hey! I just thought that I would leave my feedback related to the recent V4 update here.
I love all of the new features including the ability to seek the current track, move to a different channel, go back/forward a song etc. But I think that this is a crucial suggestion to think upon; for developers it's very annoying to continuously specify the `Message` object in each different function for the player, maybe there a different way to get around this? I think that this might be the next big important change to discord-player.

**Comment by Snowflake107** [comment]
I don't see a point of using `Discord Structures` in this library (users will do it if they need). However, we can improve  the `Player` where you do not need to pass `message` to every methods 🤔

**Comment by thomasthebro1** [comment]
Yes that's what I am talking about. Passing the `Message` parameter to all of the methods every single time can quickly make the code look pretty messy

**Comment by Majoramari** [comment]
> I don't see a point of using `Discord Structures` in this library (users will do it if they need). However, we can improve the `Player` where you do not need to pass `message` to every methods 🤔

using a message prevent you from using slash commands so this need to change

**Comment by Dragonizedpizza** [comment]
using this package with a slash command essentially breaks the package.

you're going to need to pass the interaction object, and if you do, your events wouldn't work, since discord.js's slash commands have different methods, etc.

I feel like a good solution would be to provide another parameter which is a boolean in the event,
```js
player.on('trackStart', (message, track, isSlash) => {
if (isSlash) // ...
else // ...
});
```

**Comment by Snowflake107** [comment]
Discord.js Slash Commands are available from Discord.js v13 and current Discord Player version targets Discord.js v12.
We will have a clean rewrite targeting Discord.js v13 with many breaking changes. It's not a good idea to use this lib (which currently is for v12) with discord.js master (v13) anyways

**Comment by Snowflake107** [comment]
> using a message prevent you from using slash commands so this need to change

are you guys ok if Discord Player stops emitting events with the `message` object? You would need to handle the event yourself somehow to get the job done. You'd get `Guild` object though..

**Comment by Majoramari** [comment]
> > using a message prevent you from using slash commands so this need to change
> 
> are you guys ok if Discord Player stops emitting events with the `message` object? You would need to handle the event yourself somehow to get the job done. You'd get `Guild` object though..

If i got the member and channel back why would i need a message? I'm just wondering what would break.

**Comment by Snowflake107** [comment]
You won't get text channel either..

**Comment by Dragonizedpizza** [comment]
couldn't you send an interaction instead of message, and then pass a boolean, like I said?

**Comment by Snowflake107** [comment]
Queue objects will be designed to hold your metadata (anything you wanna attach to the queue object, passed by you while creating your queue) and that data will always be available to you whenever this lib returns you the queue object.

For example, if you pass a message object as queue metadata, you would always get that message object in your specific queue. Is that good?

> couldn't you send an interaction instead of message, and then pass a boolean, like I said?

are we talking about including `message` parameter in every methods again?

**Comment by Snowflake107** [comment]
Let me know about this https://github.com/Androz2091/discord-player/blob/v5/example/index.ts

**Comment by Snowflake107** [comment]
> Everyone would need to rewrite their code if they're doing what you're thinking of, so why not just pass a third parameter in the end, which would return whether the message is a Discord.Message or an interaction?

You'd definitely need to rewrite. And it's complicated to handle slash commands in current library structure. That's why we are rewriting v5 completely with new discord.js features as well as `@discordjs/voice`.

**Comment by Dragonizedpizza** [comment]
@Snowflake107 what if I want to pass 2 things in the metadata? 
Perhaps you could make the metadata an object or array.
```js
client.player.createQueue(message.guild, {
metadata: {
message: message,
someOtherStuff: "ok"
}});
```
or 
```js
client.player.createQueue(message.guild, {
metadata: [ ["KEY", "VALUE"] ]
}});
```

**Comment by Dragonizedpizza** [comment]
I just realized you could already do the first one, but what about the second one?

**Comment by zyrouge** [comment]
> I just realized you could already do the first one, but what about the second one?

You should probably handle it.

**Comment by Snowflake107** [comment]
> what if I want to pass 2 things in the metadata?
`metadata` can be anything :)

**Comment by Snowflake107** [comment]
@CuriosBasant Discord.js **[removed `Structure` completely](https://github.com/discordjs/discord.js/pull/6027)** so I'm gonna close this issue.
