### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by TrixiS** [Androz2091/discord-player#1395]
Discord player just does not free any memory. 

1. Check the memory your process allocated
1. Play a track from YouTube URL
2. Check the memory again
3. Destroy the queue
4. Check the memory once again and see that it is not changed from the previous time

**Comment by archaeopteryx1** [comment]
> Discord player just does not free any memory

JavaScript is a garbage collected language thus we do not have the control over memory management. Wait for the garbage collector to do the job or run the node process with `--expose_gc` flag to expose the `gc` global which you can invoke to run the garbage collector manually.

**Comment by TrixiS** [comment]
The problem is that memory allocates every time I play a single track. All options are default. So memory is not reused at all I guess (and gc does not free anything while running a bot with some tracks already played tho)

**Comment by AquamonSE** [comment]
Hi! Memory overload is a real issue. The RAM memory keeps stacking after each new track/url loaded into the player. For example after playing two 10-12 hours videos (24/7 lofi playlist) it leaves ram at 2GB. If I then requeue the same track which already should be stored in RAM it adds it another time and this issue keeps growing the RAM to very high numbers. This is only on a single server, I've tried added it on another server and it keeps stacking them.

A fix that flushes the ram of previous song played and/ a fix that lets it use the same url that's already stored in RAM to work on a different server when it plays the same song/url would be appreciated. 👍
