### ISSUE TITLE
Track does not play immediately when added to the queue.

### ISSUE THREAD

**Issue by babahgee** [Androz2091/discord-player#1405]
**Describe the bug**
When requesting a song, the requested song is not added to an existing queue. It also doesn't play any sound at all. I have tried using different music streaming services like SoundCloud, Spotify and Deezer but none of them work. After calling the same command a few times, it will eventually start playing the song. The queue remains still empty. 

I have no idea how to fix this issue. I am also not sure whether it's me or it's a bug that has to be fixed.

**Expected behavior**
I wrote the code from a few months ago when it used to work. It seems that ``queue.addTracks()`` and ``queue.addTrack()`` are not working. 

**Screenshots**
I made a logging system that logs every event. You can see an user attempting to play a song several times. 

After two or three attempts, it finally started playing the song. This can been seen in the last three lines.
![image](https://user-images.githubusercontent.com/61418505/196057295-f5d248be-6754-4297-b42e-381f26c4771a.png)

**Please complete the following information:**
 - Node Version: 18.8.0
 - Discord Player Version: 5.3.2
 - Discord.js Version: 14.6.0
 - ffmpeg-static version: 5.1.0

**Additional context**

**Comment by archaeopteryx1** [comment]
You need to invoke `queue.play()` in order to actually start playing

**Comment by babahgee** [comment]
> You need to invoke `queue.play()` in order to actually start playing

Forgot to mention, the ``queue.play()`` method has been called at the end of the script, when adding requested tracks to a queue.

![image](https://user-images.githubusercontent.com/61418505/196122427-5f4103d5-9508-4ed9-8a8c-d97af8237b3e.png)

**Comment by archaeopteryx1** [comment]
> > You need to invoke `queue.play()` in order to actually start playing
> 
> Forgot to mention, the `queue.play()` method has been called at the end of the script, when adding requested tracks to a queue.
> 
> ![image](https://user-images.githubusercontent.com/61418505/196122427-5f4103d5-9508-4ed9-8a8c-d97af8237b3e.png)

If you want to play a track without adding it to the queue, use `queue.play(track, { immediate: true })`, do not use `queue.addTrack` or anything here.

**Comment by archaeopteryx1** [comment]
addTrack adds the track to the queue, it does not play the track.

**Comment by babahgee** [comment]
> addTrack adds the track to the queue, it does not play the track.

Yes, I figured that out by reading the name of the function. What I am trying to say is that my queue won't play for some reason, whether I play tracks immediately or add them to a queue.

Thanks for helping me out by the way, I really appreciate that!

**Comment by babahgee** [comment]
I still haven't figure it out how to solve the problem. Since Discord released the 'activity' feature, I don't think the bot should be useful anymore. 

In case anyone wants to contact me about this, hit me up on Discord BΛBΛΉ GΣΣ#7100.

Thank you.
