### ISSUE TITLE
queue.playing not updating when setPaused is used

### ISSUE THREAD

**Issue by jarrodback** [Androz2091/discord-player#1413]
### Discussed in https://github.com/Androz2091/discord-player/discussions/1159

<div type='discussions-op-text'>

<sup>Originally posted by **AlohaSteam** May  7, 2022</sup>
No idea if this is me or what but the queue.playing function is not working. It just seems as it completely disregards it, now I'm learning js so idk if its just me doing something wrong or if its the actual package itself.

`
        const queue = player.createQueue(message.guild, {
            metadata: VoiceChannel
        })

        if(!queue.playing) {
            queue.play(song);
            message.channel.send(`${song.title} is now playing.`)
        } else if(queue.playing) {
            queue.addTrack(song);
            message.channel.send(`${song.title} is queud up to play.`)
        }
`

from the documentation and the source code from the bots that use discord-player this should work right?</div>

**Comment by YoYo-178** [comment]
yeah same, i had to manually override `queue.playing` values to make my code work

**Comment by febkosq8** [comment]
For those wondering, check `queue.connection.paused` to see if the player is paused.
`queue.playing` always stays true.

**Comment by royalty37** [comment]
> For those wondering, check `queue.connection.paused` to see if the player is paused. `queue.playing` always stays true.

I'm having a similar issue... 

I wrote my bot in Typescript and my commands don't behave how I want... Queue.connection.paused is true even when music is playing. 

And queue.playing is always false, even when music is playing. 

Causes unwanted behaviour when running a generic play or pause function.
