### ISSUE TITLE
UnhandledPromiseRejection Warning

### ISSUE THREAD

**Issue by SpreeHertz** [Androz2091/discord-player#142]
Code: 
`const Discord = require('discord.js')`
`const bot = new Discord.Client();`

`const { Player } = require("discord-player");`
`const player = new Player(bot);`
`bot.player = player;`

`bot.on("ready", ready => {
    console.log("I am online.")
    bot.user.setActivity("I am back! | V1.1.1");
})`

`bot.on("message", async message => {
    let prefix = '+';`

    const args = message.content.slice(prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();

    if (command === 'play') {
        let track = await bot.player.play(message.member.voice.channel, args[0], message.member.user.tag);
        message.channel.send(`Currently playing **${track.name}, Requested by ${track.requestedBy}`);
    
    }

    if (command === 'stop') {
        let track = await bot.player.stop(message.guild.id);
        message.channel.send(`The song(s) has been stopped.`)
        
    }
    

})

bot.login('mytoken')

Error:

![image](https://user-images.githubusercontent.com/48062454/98268551-ab174200-1fb2-11eb-8b7a-121f368ece34.png)

**Comment by Androz2091** [comment]
You should upgrade your code to v3. For more information join the support server https://discord.gg/hw87VUQ
