### ISSUE TITLE
TypeError: Cannot read property 'createMessageCollector' of undefined

### ISSUE THREAD

**Issue by WhiteSkyAngel** [Androz2091/discord-player#144]
Hey !
While I want to play a music it say this :

```
(node:3463) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
    at /home/Bot Discord/node_modules/discord-player/src/Player.js:178:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Androz2091** [comment]
Hello, can you send me the code please?

**Comment by Conn3rrrr** [comment]
`const Discord = require('discord.js');
const request = require('request');

const { prefix, token} = require('./config.json');
const client = new Discord.Client();


const { Player } = require("discord-player");
// Create a new Player (you don't need any API Key)
const player = new Player(client);
// To easily access the player
client.player = player;
// add the trackStart event so when a song will be played this message will be sent
client.player.on('trackStart', (message, track) => message.channel.send(`Now playing ${track.title}...`))

client.on("ready", () => {
    console.log("I'm ready !");
});

client.on("message", async (message) => {

    const args = message.content.slice(prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();

    // !play Despacito
    // will play "Despacito" in the member voice channel

    if (command === "play") {
        client.player.play(message.member.voice.channel, args[0], message.member.user);
        // as we registered the event above, no need to send a success message here
    }

});

client.login(token);`

not op but here is my code, getting the same error

**Comment by DashCruft** [comment]
For everyone's information, discord-player is still in the beta phase and most people have this problem. For now, please install discord-player v2.3.1 by doing `npm i discord-player@2.3.1` to avoid any possible errors associated with the discord-player npm package. Thanks!

**Comment by DeathMario** [comment]
@DashCruft The version 2.3.1 for me doesn't works too.

**Comment by Androz2091** [comment]
The code is actually wrong for v3:

```js
if (command === "play") {
        client.player.play(message.member.voice.channel, args[0], message.member.user);
        // as we registered the event above, no need to send a success message here
    }
```

should be 

```js
if (command === "play") {
        client.player.play(message, args[0]);
        // as we registered the event above, no need to send a success message here
    }
```

Hope this helps!

**Comment by BrianWasTkn** [comment]
I tried doing your method @Androz2091, It didn't worked either.

**Comment by WhiteSkyAngel** [comment]
I used ZerioDev music bot @Androz2091 !

**Comment by Androz2091** [comment]
Please upgrade to v3.1.0, and if the problem still occurs open a new issue.
