### ISSUE TITLE
Player stuck on buffering when a playlist is queued

### ISSUE THREAD

**Issue by febkosq8** [Androz2091/discord-player#1443]
**Describe the bug**

Randomly the player gets stuck on buffering when a playlist is queued. 
To get it to fix, I have to add a new song to the playlist so that the song that it was stuck on starts playing. 
It's not fixed on song basis and I can't figure out what is causing this buffering to happen. I have debug enabled and this is what it says when it stops playing.

```
state change:
{"status":"playing","missedFrames":0,"playbackDuration":223860,"resource":true,"stepTimeout":false}
to {"status":"idle","resource":false,"stepTimeout":false}
state change:
from {"status":"idle","resource":false,"stepTimeout":false}
to {"status":"buffering","resource":true,"stepTimeout":false}
```

**To Reproduce**

1. Queue a playlist and wait for the player to get stuck on buffering

**Expected behavior**
It should finish buffering and start playing the song.

**Screenshots**
N/A

**Please complete the following information:**
 - Node Version: v18.12.1
 - Discord Player Version: 5.3.2
 - Discord.js Version: 14.6.0

**Comment by skdhg** [comment]
🤔 how do we solve buffering issue? Would it be a good idea to wait for specified amount of time and if it is still buffering then terminate the song?

**Comment by febkosq8** [comment]
For what I saw, sometimes the state is not changing once buffering is over ! 
Back when this used to happen and if i add a new song to the queue, then the song that was supposed to play will start playing as if nothing happened.

**Comment by skdhg** [comment]
> For what I saw, sometimes the state is not changing once buffering is over ! Back when this used to happen and if i add a new song to the queue, then the song that was supposed to play will start playing as if nothing happened.

The state is handled by `@discordjs/voice`, we do not have control over it. We rely on the events that `@discordjs/voice` emits to indicate if the audioPlayer has been playing the track or not

**Comment by febkosq8** [comment]
Then a timeout would work I guess.

**Comment by hmes98318** [comment]
I have the same problem.
I increase the `highWaterMark` to `1 << 27` will alleviate this problem
hardly ever get stuck again.
