### ISSUE TITLE
bot does not join the voice channel

### ISSUE THREAD

**Issue by KatowProject** [Androz2091/discord-player#145]
i'm using the latest version (3.0.2)

i'm trying the command, but....
<img src="https://cdn.discordapp.com/attachments/496983030993518592/774770043908784168/unknown.png">

bot doesn't joining the voice
<img src="https://cdn.discordapp.com/attachments/496983030993518592/774772042901618718/unknown.png">

**Comment by DashCruft** [comment]
Uh your running it as an eval.... you need to put that with a requirement and use it in a command file or just a command and test it

**Comment by KatowProject** [comment]
before using the "eval" method, I created the command file, but there was no response from the bot.

in previous versions, I always used eval first before creating a command to check if it worked, but this time there was no response from the bot. 😥

the command is running
![image](https://user-images.githubusercontent.com/52640561/98458100-d28f2a00-21bf-11eb-9e7d-64ab4835efc0.png)

but.... bot doesn't joining the voice
![image](https://user-images.githubusercontent.com/52640561/98458129-f8b4ca00-21bf-11eb-822d-8acbe4b791c9.png)

**Comment by DashCruft** [comment]
but your showing a picture with the bot joined the voice channel...

**Comment by KatowProject** [comment]
Where do I show the picture that the bot is joined the voice channel?
in my picture, the bot not joined the voice channel😥
the command is running without error code, but the bot not joined the voice channel.....

is my explanation incomprehensible?

**Comment by BrianWasTkn** [comment]
try using async/await on your eval for example:
```
(async () => {
  await client.player.play(message, query)
})
```

**Comment by Androz2091** [comment]
This is weird. You can try debugging the package using a debug tool or some `console.log`, without more information I can't really help...

**Comment by EvEloBE** [comment]
same problem. Code is: `try {
      await message.client.player
        .play(message, args.join(' ') || 'Ashes Stellar', message.author)
        .then(() => console.log('test'));

      console.log('test');
      // await message.client.player.setVolume(message, 90);
    } catch (e) {
      console.log(e);
    }` I tested making the bot join manually. He joined but nothing played so i tried console.logging something and nothing did log so i think there is some loading error or something like that going on internally because It doesnt log anything after the `await`. I Didnt find anything else that could help.

**Comment by KatowProject** [comment]
this time I tried to use an example from this repository (discord-player)
```js
const Discord = require("discord.js"),
client = new Discord.Client(),
settings = {
    prefix: "!",
    token: "insert token"
};

const { Player } = require("discord-player");
// Create a new Player (you don't need any API Key)
const player = new Player(client);
// To easily access the player
client.player = player;
// add the trackStart event so when a song will be played this message will be sent
client.player.on('trackStart', (message, track) => message.channel.send(`Now playing ${track.title}...`))

client.on("ready", () => {
    console.log("I'm ready !");
});

client.on("message", async (message) => {

    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();
  
   if(command === "play"){
        client.player.play(message, args.join(' '))
        console.log(`${message.author.tag} ran play`)
     // as we registered the event above, no need to send a success message here
   }
    // !play Despacito
    // will play "Despacito" in the member voice channel
});

client.login(settings.token);
```

results
![image](https://user-images.githubusercontent.com/52640561/98490618-995cc580-2264-11eb-8ecc-e7f46450b230.png)


but.....
![image](https://user-images.githubusercontent.com/52640561/98490640-abd6ff00-2264-11eb-9b88-07932b7fecb7.png)
bot doesn't join the voice channel

**Comment by Pronicio** [comment]
Youtube links work, try...

**Comment by Androz2091** [comment]
Closed due to inactivity. If the problem still occurs, please open a new issue.

**Comment by BlazeDexX** [comment]
I have the same issue
