### ISSUE TITLE
How do you add a song to the queue?

### ISSUE THREAD

**Issue by BrianWasTkn** [Androz2091/discord-player#146]
Okay so, I've recently saw a rewritten version of this package somewhere on npmjs.com and it has a addToQueue function? And I wanna know how you add a song to the queue? Is it the same as .play?

**Comment by Androz2091** [comment]
Hello @BrianWasTkn, yes you should use the `.play()` function and listen for the right event to send the success message

**Comment by BrianWasTkn** [comment]
oh wow, you're active, so it automatically emits the specific player events in the documentation site? Is that it?

thank you so much!

**Comment by Androz2091** [comment]
Yes, you will have to listen for the [trackAdd](https://discord-player.js.org/Player.html#event:trackAdd) event.

**Comment by BrianWasTkn** [comment]
alright, thanks for your help! Much appreciated and I love all of it.
