### ISSUE TITLE
option to restrict sources

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-player#1495]
**Describe the feature you would like**

An option to restrict sources, wherein you could make discord-player ONLY use spotify, etc.

**Expected behavior**

```js
const player = new Player(client, { source: 'spotify' });
```

**Screenshots**

**Additional context**

**Comment by skdhg** [comment]
> **Describe the feature you would like**
> 
> An option to restrict sources, wherein you could make discord-player ONLY use spotify, etc.
> 
> **Expected behavior**
> 
> ```js
> const player = new Player(client, { source: 'spotify' });
> ```
> 
> **Screenshots**
> 
> **Additional context**

on dev version, you are able to force a specific extractor to be used via `ext:` query type.

Example:

```js
const res = await player.search(query, { searchEngine: `ext:com.discord-player.soundcloudextractor` });
```

which would force discord-player to only use soundcloud extractor even if it doesnt support that search query. While `searchEngine` still accepts `QueryType`, the value `ext:` is special as it denotes a specific extractor. While in query type, discord-player will query all extractors until it can find the one which is able to handle that query.

This is however yet to be implemented for streaming. And queries such as `youtube*`, `appleMusic*` or `spotify*` all go through the same extractor, `youtube`. While they do fetch metadata from respective sources, streaming happens from only one source so we do need a way of controlling that. It can also be forced to stream some other things via `onBeforeCreateStream` as usual.

**Comment by skdhg** [comment]
You can find the list of currently implemented extractors here https://github.com/Androz2091/discord-player/tree/develop/packages/extractor/src/extractors

**Comment by Dragonizedpizza** [comment]
thank you! are there any plans to restrict streaming sources?

**Comment by skdhg** [comment]
> thank you! are there any plans to restrict streaming sources?

It should be possible with `onBeforeCreateStream`. You can use one of the extractors to stream or create your own method.

```js
onBeforeCreateStream(track, source) {
    if (source === 'youtube') {
        const ext = player.extractors.get('com.discord-player.soundcloudextractor');
        // now use this extractor to resolve stream
    }
}
```

**Comment by skdhg** [comment]
Implemented

```js
import { Player } from 'discord-player';
import { YouTubeExtractor } from '@discord-player/extractor';
 
const player = new Player(client, {
    blockStreamFrom: [
        // now your bot will no longer be able to use
        // youtube extractor to play audio even if the track was
        // extracted from youtube
        YouTubeExtractor.identifier
    ],
    blockExtractors: [
        // this will block the listed extractors from being
        // able to query metadata (aka search results parsing)
        // This example disables youtube search, spotify bridge
        // and apple music bridge
        YouTubeExtractor.identifier
    ]
});
```

**Comment by Dragonizedpizza** [comment]
thank you very much
