### ISSUE TITLE
setRepeatMode Bug

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#15]
Hi there, I've just recently implemented the use of the repeat song function into my bot, however, I found a bug.
When the queue has 2 or more song (the currently playing song and another) the repeat function will work correctly as expected to. But if there is only the 1 song (currently playing) the repeat function will not work and will just disconnect from the voice channel as if its not enabled.

**Comment by Androz2091** [comment]
I will look into this problem as soon as possible!

**Comment by thomasthebro1** [comment]
Thank you!
