### ISSUE TITLE
The module never found the song

### ISSUE THREAD

**Issue by VyrekXD** [Androz2091/discord-player#150]
I use this code await bot.player.play(message.member.voice.channel, 'Lizzo - Juice', message.member.user.tag) and when i put it it gaves me the same error: Error: Not found

**Comment by Androz2091** [comment]
Hello @VyrekXD, you should use:
```js
await bot.player.play(message, 'Lizzo - Juice');
```
please read the new documentation for v3 (https://discord-player.js.org)

**Comment by Pronicio** [comment]
The main page has not been updated. (https://discord-player.js.org)

**Comment by VyrekXD** [comment]
Hi, thank u
