### ISSUE TITLE
option to loop entire queue

### ISSUE THREAD

**Issue by Naxey** [Androz2091/discord-player#151]
title

**Comment by Androz2091** [comment]
This can currently be done by listening the events (when the `queueEnd` event is triggered, you can fill the queue again). But something like that would be nice indeed, I think:
```js
client.player.setLoopMode(true);
```

**Comment by TheSpoiledSnail** [comment]
> This can currently be done by listening the events (when the `queueEnd` event is triggered, you can fill the queue again). But something like that would be nice indeed, I think:
> 
> ```js
> client.player.setLoopMode(true);
> ```

How do I fill in the queue again? I'm new to coding

**Comment by Androz2091** [comment]
You can use `queue.tracks.push()``
