### ISSUE TITLE
Executing .play after music is playing force it to skip to the next song

### ISSUE THREAD

**Issue by danitseitlin** [Androz2091/discord-player#1511]
**Describe the bug**
When a song is playing, and you add a song to the queue it forces the current song to stop and start playing the next song.

**To Reproduce**
1. Run any /play bot command to run the song that used to play before 5.4.0
2. Run it again

**Expected behavior**
Song is added to queue

**Comment by skdhg** [comment]
Hello @danitseitlin, I am unable to reproduce this issue with your steps. Could you please provide more info on this? A code snippet of your play command would be helpful.

**Comment by Danrejk** [comment]
It happens to me as well.
What I do to reproduce it is add the song twice in rapid succession 

here's a snippet of my play command:

`execute: async ({ client, interaction }) => {
		if (!interaction.member.voice.channel){
            return interaction.reply("Musisz być na kanale głosowym, żebym coś ci zagrał.");
        }

		const queue = await client.player.createQueue(interaction.guild);
		if (!queue.connection){
            await queue.connect(interaction.member.voice.channel)
            queue.setVolume(config.volume)
        }

		let embed = new EmbedBuilder()
        let url = interaction.options.getString("url")
        
        const result = await client.player.search(url, {
            requestedBy: interaction.user,
            searchEngine: QueryType.YOUTUBE_VIDEO
        })
        if (result.tracks.length === 0)
            return interaction.reply("Bredzisz.")

        const song = result.tracks[0]
        await queue.addTrack(song)

        if (!queue.playing) await queue.play()`

**Comment by TheJerryFox** [comment]
Same thing here, worked perfectly fine before

**Comment by royalty37** [comment]
Same issue, since late December on recent versions of Discord Player.

**Comment by skdhg** [comment]
I am still unable to reproduce this issue. Could you try using `npm i discord-player@dev` and see if this issue occurs in that version?

**Comment by Danrejk** [comment]
found 0 vulnerabilities

**Comment by lapetitehanae** [comment]
same problem on discord-player@dev

**Comment by lapetitehanae** [comment]
to reproduce this problem : start a music AND start another one before the first one starts

it's boring.. fix this please

**Comment by skdhg** [comment]
somebody suggested me that this code could potentially fix this issue:

Replace

```js
// play command part
if(!queue.connection) {
    await queue.connect(message.member.voice.channel);
    await queue.play(track);
}
```

with

```js
// play command part
if(!queue.connection) {
    await queue.connect(message.member.voice.channel);
    await queue.play(track);
} else {
    queue.addTrack(track);
}

// event handler part
player.on('trackEnd', async () => {
    if(!queue.connection) await queue.play(track);
});
```

**Comment by skdhg** [comment]
> to reproduce this problem : start a music AND start another one before the first one starts

The problem seems to be the asynchronous nature of the player. You queue track 1, execute play() and as no other tracks are being played, discord player proceeds to the stage where it starts streaming process where track 1 is removed from the tracks list because it is passed to the audio player and since track 2 was also added immediately when discord player still hasnt started streaming, the queue manager thinks it is playing for the first time as it cant find the other track in the queue so it instead starts playing track 2 which skips the track 1.

**Comment by Danrejk** [comment]
I'm not sure if this is related to all of this, but:
`queue.playing` sometimes remains false even when the music is playing

**Comment by lapetitehanae** [comment]
> somebody suggested me that this code could potentially fix this issue:
> 
> Replace
> 
> ```js
> // play command part
> if(!queue.connection) {
>     await queue.connect(message.member.voice.channel);
>     await queue.play(track);
> }
> ```
> 
> with
> 
> ```js
> // play command part
> if(!queue.connection) {
>     await queue.connect(message.member.voice.channel);
>     await queue.play(track);
> } else {
>     queue.addTrack(track);
> }
> 
> // event handler part
> player.on('trackEnd', async () => {
>     if(!queue.connection) await queue.play(track);
> });
> ```

helllo, i tried this and when i add more than 7 music in queue i have this message in console : (node:36) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 trackEnd listeners added to [Player]. Use emitter.setMaxListeners() to increase limit

it's a serious problem or I can ignore it

**Comment by dan1xk** [comment]
same problem here :/
