### ISSUE TITLE
Issue pulling up documentation.

### ISSUE THREAD

**Issue by ChadForbes** [Androz2091/discord-player#1519]
I am not sure if this is the right place to put this but when I go to https://discord-player.js.org/docs the page doesn't finish loading. A couple of errors come up in the console.

![Screenshot 2023-01-16 213903](https://user-images.githubusercontent.com/5529602/212804847-c5bbe265-c2b3-4bbf-a5bb-0dfa126bc880.png)

**Comment by skdhg** [comment]
> I am not sure if this is the right place to put this but when I go to https://discord-player.js.org/docs the page doesn't finish loading. A couple of errors come up in the console.
> 
> ![Screenshot 2023-01-16 213903](https://user-images.githubusercontent.com/5529602/212804847-c5bbe265-c2b3-4bbf-a5bb-0dfa126bc880.png)

Yes the documentation website is outdated. I will start working on the website soon.
