### ISSUE TITLE
When the player done, it's skip 1 song and goes to 2nd song in queue

### ISSUE THREAD

**Issue by ABX-PenDZ** [Androz2091/discord-player#1523]
![bug1](https://user-images.githubusercontent.com/123088660/213462520-8e980d13-e9a4-4859-8edd-b28cbeb4670d.png)
![bug2](https://user-images.githubusercontent.com/123088660/213462555-1a5b0678-f597-4d8d-9112-57f5ee28b193.png)
So, i played 3 song and 1st song is playing. After 1st song done it goes to 3rd song and skip the 2nd song

NOTE! : Sorry, if the screenshots is not clear

**Comment by skdhg** [comment]
Possible relation with #1511 #1512

**Comment by gyeongent** [comment]
have same problem on 5.2.2
: skipping 2nd songs

**Comment by CaptainKirk7** [comment]
I'm getting this on 5.4.0 as well

**Comment by olliedean** [comment]
Happens to me too, tried using discord-player@dev instead, and it says
`SyntaxError: The requested module 'prism-media' does not provide an export named 'FFmpeg'`

and also 
```
➤ YN0002: │ discord-player@npm:5.4.1-dev.0 [c6934] doesn't provide play-dl (pcd687), requested by @discord-player/extractor
➤ YN0002: │ discord-player@npm:5.4.1-dev.0 [c6934] doesn't provide ytdl-core (paa479), requested by @discord-player/extractor
```

**Comment by ItsAuric** [comment]
@olliedean these are usually just `peer dependency` warnings and are safe to ignore unless it tells you that it is required in your `workspace`

**Comment by olliedean** [comment]
> @olliedean these are usually just `peer dependency` warnings and are safe to ignore unless it tells you that it is required in your `workspace` then it would be best to install the packages requested 

already tried installing them, oh well. still not sure about the prism error though.
