### ISSUE TITLE
Player / ffmpeg error after playing about 1 hour worth of playlist

### ISSUE THREAD

**Issue by febkosq8** [Androz2091/discord-player#1536]
**Describe the bug**
Constantly getting a error (see below) while playing a playlist. Usually after 1 hour of playback this error starts popping up until I restart the server.
This started after I changed discord-player from 5.3.2 to 5.4.0. This also broke skip (Issue #1512) and also broke player.on("trackStart",...) (Issue #1538)
Bot running on heroku. Using [ffmpeg buildpack](https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git)

**To Reproduce**

1. Add a youtube playlist (with many number of songs) into queue
2. Let the bot start playing.
3. After about 1 hour, node js will crash with 
```
Error: spawn ffmpeg EAGAIN
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
errno: -11,
code: 'EAGAIN',
syscall: 'spawn ffmpeg',
path: 'ffmpeg',
spawnargs: [
'-i',               '-',
'-ss',              '0',
'-analyzeduration', '0',
'-loglevel',        '0',
'-f',               's16le',
'-ar',              '48000',
'-ac',              '2',
'pipe:1'
]
}
```
Since I had been handling "uncaughtException" in my bot code, my bot didn't crash straight away.
One of the next error that got emitted from my player.on("error",...) was 
```
ERROR : Player error emitted from the queue: write EPIPE
Error: write EPIPE
at afterWriteDispatched (node:internal/stream_base_commons:160:15)
at writeGeneric (node:internal/stream_base_commons:151:3)
at Socket._writeGeneric (node:net:923:11)
at Socket._write (node:net:935:8)
at writeOrBuffer (node:internal/streams/writable:392:12)
at _write (node:internal/streams/writable:333:10)
at Writable.write (node:internal/streams/writable:337:10)
at PassThrough.ondata (node:internal/streams/readable:766:22)
at PassThrough.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12) {
errno: -32,
code: 'EPIPE',
syscall: 'write'
}
```

**Expected behavior**
1. The error's shouldn't have happened in the first place stopping the playlist playback.

**Screenshots**

<img width="603" alt="1st error" src="https://user-images.githubusercontent.com/33223665/214937049-34490733-4c46-4ad3-ab63-885331233540.png">

<img width="547" alt="2nd error" src="https://user-images.githubusercontent.com/33223665/214937110-683dbac1-045f-4a06-9e3f-8e1bd58c43dc.png">

<img width="505" alt="player.on('error')" src="https://user-images.githubusercontent.com/33223665/214937225-cff2d1ce-8695-4bc1-bbc4-a17e4f41fe06.png">

<img width="209" alt="dependencies" src="https://user-images.githubusercontent.com/33223665/214937304-5b1f10a1-a682-4b2a-8128-d581b5be6818.png">

**Please complete the following information:**
 - Node Version: v18.13.0
 - Discord Player Version: v5.4.0
 - Discord.js Version: v14.7.1

**Additional context**
Had another issue since sometime but dont think its related to this (Issue #1443)

**Comment by skdhg** [comment]
Could you try this in `discord-player@dev`? Remove `ytdl-core` and add `play-dl` for `EPIPE` issues

**Comment by febkosq8** [comment]
Swtiching to `discord-player@dev`. Will update soon.

**Comment by febkosq8** [comment]
After switching to `discord-player@dev` and `play-dl`, every time I try to play a spotify playlist I get a new uncaughtException.

```
TypeError: Cannot read properties of null (reading 'body')
at /app/node_modules/node-fetch/lib/index.js:1519:27
at IncomingMessage.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1749:6)
at Object.onceWrapper (node:events:627:28)
at IncomingMessage.emit (node:events:513:28)
at emitCloseNT (node:internal/streams/destroy:132:10)
at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```
Can confirm Issue #1512 & #1538 has been fixed in dev.
Will update if the original issue come back.

**Comment by skdhg** [comment]
See https://github.com/Androz2091/discord-player/issues/1526#issuecomment-1400645159 for node-fetch patch

**Comment by febkosq8** [comment]
Adding node-fetch@2.6.7 to my package json helped that issue.

Can confirm that the original issue no exists 👍 , played for like 3 hours and didn't face any issues.

Since this is dev branch, are there any major bugs that I should know of ? 

Do I close my issues or keep them open as its still not merged into stable ?

**Comment by skdhg** [comment]
> Adding node-fetch@2.6.7 to my package json helped that issue.
> 
> Can confirm that the original issue no exists 👍 , played for like 3 hours and didn't face any issues.
> 
> Since this is dev branch, are there any major bugs that I should know of ?
> 
> Do I close my issues or keep them open as its still not merged into stable ?

No major bugs at the moment, as @dev isnt up to date with develop branch as of right now (develop branch has a lot of new changes unpublished currently). Let's keep this open as a reference if anyone else is having this issue until there is another stable release

**Comment by febkosq8** [comment]
I keep getting this Error every 30 mins into a new queue.

It gets emitted from `player.on("error",...)`

```
Discord Player error emitted from the queue: No stream extractors are available for this track
at Queue.play (/app/node_modules/discord-player/dist/index.js:1388:41)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by skdhg** [comment]
> I keep getting this Error every 30 mins into a new queue.
> 
> It gets emitted from `player.on("error",...)`
> 
> ```
> Discord Player error emitted from the queue: No stream extractors are available for this track
> at Queue.play (/app/node_modules/discord-player/dist/index.js:1388:41)
> at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

It means it couldn't find extractors which supported that track
