### ISSUE TITLE
Stop plays music when muted/unmuted

### ISSUE THREAD

**Issue by lapetitehanae** [Androz2091/discord-player#1537]
**Describe the bug**
Bot stop plays music when muted/unmuted

**To Reproduce**
1. Launch a music
2. Right click on bot and press "Mute on server"
3. Right click on bot and uncheck "Mute on server"
4. And now the bot doesn't play any music (it's supposed to have one in progress)

**Expected behavior**
Bot continuing to play the music even after muted/unmuted him

**Please complete the following information:**
 - Node Version: 18.12.1
 - Discord Player Version: 5.3.2
 - Discord.js Version: 14.7.1

**Comment by febkosq8** [comment]
It seems to be working for my bot running 5.4.0.

**Comment by lapetitehanae** [comment]
> It seems to be working for my bot running 5.4.0.

i'm using 5.3.2 because of this : https://github.com/Androz2091/discord-player/issues/1511

**Comment by skdhg** [comment]
> > It seems to be working for my bot running 5.4.0.
> 
> i'm using 5.3.2 because of this : #1512

Using older versions is not recommended as a lot of other stuff can be outdated just like this one.
