### ISSUE TITLE
player.on('trackStart') doesn't get trigger since 5.4.0

### ISSUE THREAD

**Issue by febkosq8** [Androz2091/discord-player#1538]
**Describe the bug**
The event "trackStart" doesn't get triggered consistently ever since 5.4.0.

**To Reproduce**
1. Queue a new song or playlist
2. The event "trackStart" doesn't get triggered
3. But If I stop the existing queue immediately and then requeue something new then the event is triggered.

**Expected behavior**
Everytime a track is queued or started, it should trigger "trackStart"

**Screenshots**
<img width="487" alt="image" src="https://user-images.githubusercontent.com/33223665/214940429-b1b89ff5-6f76-4d55-b7c9-ca017d8f56f5.png">

**Please complete the following information:**
 - Node Version: v18.13.0
 - Discord Player Version: v5.4.0
 - Discord.js Version: v14.7.1

**Additional context**
Another issue that started with 5.4.0 is (Issue #1536 & Issue #1512)

**Comment by skdhg** [comment]
Seems to be #1487

**Comment by skdhg** [comment]
This should've been fixed in discord-player@dev as it seems to be related to #1487 

No ETA for stable release as of right now as a lot of stuff need to be tested properly

**Comment by febkosq8** [comment]
Swtiching to `discord-player@dev`. Will update soon.

**Comment by febkosq8** [comment]
Can confirm that the original issue no exists in dev branch👍
