### ISSUE TITLE
I have 3.0.2 and i have errors

### ISSUE THREAD

**Issue by VyrekXD** [Androz2091/discord-player#154]
I use this code in my eval "await bot.player.play(message, 'Lizzo - Juice')" and it doesnt make anything.

**Comment by VyrekXD** [comment]
If i use node15 has to do?

**Comment by Androz2091** [comment]
What do you mean, "it doesn't make anything"? You have nothing in the terminal?

**Comment by VyrekXD** [comment]
the bot doesnt make anything

**Comment by Victorthemachine** [comment]
Can you just paste the whole class please? No clue what is wrong with just that one line

**Comment by ezywebca** [comment]
@VyrekXD can you please better explain the following
current node version:
current discordjs version:

your code showing the error and or your main bots code so we can figure out the error in maybe your code 

have you tried install ffmpeg and all the needed npm's

**Comment by Androz2091** [comment]
Closed due to inactivity
