### ISSUE TITLE
Play BUG

### ISSUE THREAD

**Issue by PixelMadness** [Androz2091/discord-player#157]
/*****************************************************************************************************
 * validateURL will be renamed to validateID to match with getPlaylistID in the next release of ytpl *
 *                   set `ytpl.do_warn_deprecate = false` to disable this message                    *
 *****************************************************************************************************/

**Comment by TasoOneAsia** [comment]
This has been changed on the master branch already.

See this:
https://github.com/Androz2091/discord-player/blob/771ca7cebc8531e4bab7e60fb96f3f05a86a461f/src/Util.js#L26

**Comment by PixelMadness** [comment]
> This has been changed on the master branch already.
> 
> See this:
> https://github.com/Androz2091/discord-player/blob/771ca7cebc8531e4bab7e60fb96f3f05a86a461f/src/Util.js#L26

Yea but if i try latest package i get error if i go to 2.3.1 i get error

**Comment by TasoOneAsia** [comment]
What version are you running specifically, your message is a little confusing on that aspect. Are you running 3.02? Or are you running a past release?

**Comment by PixelMadness** [comment]
> What version are you running specifically, your message is a little confusing on that aspect. Are you running 3.02? Or are you running a past release?

i changed to 3.0.2 and get 
Uncaught Promise Error: TypeError: Cannot read property 'createMessageCollector' of undefined
at /home/container/node_modules/discord-player/src/Player.js:178:47
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by TasoOneAsia** [comment]
Ok, see my response in #158
