### ISSUE TITLE
queue.playing isn't true while playing a song

### ISSUE THREAD

**Issue by 0xffruktoz** [Androz2091/discord-player#1577]
I'm trying to stop the playing song by checking `queue.playing` but it is not true while playing a song. 
**However, the problem does not always occur.** Sometimes its true but sometimes its not. I don't know how to fix it.

**Comment by skdhg** [comment]
> I'm trying to stop the playing song by checking `queue.playing` but it is not true while playing a song. **However, the problem does not always occur.** Sometimes its true but sometimes its not. I don't know how to fix it.

Which version are you on?

**Comment by 0xffruktoz** [comment]
version 5.4.0

**Comment by 0xffruktoz** [comment]
> > I'm trying to stop the playing song by checking `queue.playing` but it is not true while playing a song. **However, the problem does not always occur.** Sometimes its true but sometimes its not. I don't know how to fix it.
> 
> Which version are you on?

I'm using version 5.4.0

**Comment by ultra-farao** [comment]
I have the same problem on 5.4.0.
