### ISSUE TITLE
Uncaught Promise Error:  TypeError: Cannot read property 'createMessageCollector' of undefined

### ISSUE THREAD

**Issue by PixelMadness** [Androz2091/discord-player#158]
Uncaught Promise Error:  TypeError: Cannot read property 'createMessageCollector' of undefined
    at /home/container/node_modules/discord-player/src/Player.js:178:47
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Code: 

if(!message.member.voice.channel) return message.channel.send(`You're not in a voice channel ${emotes.error}`);
    if (!args[0]) return message.channel.send(`Please specify a song to play ${emotes.error}`);

    const aTrackIsAlreadyPlaying = bot.player.isPlaying(message.guild.id);
        if(aTrackIsAlreadyPlaying){
            const result = await bot.player.addToQueue(message.guild.id, args.join(" ")).catch(() => {});
            if(!result) {
                message.member.voice.channel.leave()
                return message.channel.send(`This song provider is not supported.`)
            };

            if(result.type === 'playlist'){
                message.channel.send(`${result.tracks.length} songs added to the queue ${emotes.music}`);
            } else {
                message.channel.send(`${result.name} added to the queue ${emotes.music}`);
            }

        } else {
            const result = await bot.player.play(message.member.voice.channel, args.join(" ")).catch(() => {});
            if(!result) {
                message.member.voice.channel.leave()
                return message.channel.send(`This song provider is not supported.`)
            };

            if(result.type === 'playlist'){
                message.channel.send(`${result.tracks.length} songs added to the queue ${emotes.music}\nCurrently playing ${result.tracks[0].name}`);
            } else {
                message.channel.send(`Currently playing ${result.name} ${emotes.music}`);
            }

            const queue = bot.player.getQueue(message.guild.id)
            .on('end', () => {
                message.channel.send(`There is no more music in the queue ${emotes.error}`);
            })
            .on('trackChanged', (oldTrack, newTrack) => {
                message.channel.send(`Now playing ${newTrack.name} ... ${emotes.music}`);
            })
            .on('channelEmpty', () => {
                message.channel.send(`Music stopped, there are no more members in the voice channel ${emotes.error}`);
            });
        }

**Comment by TasoOneAsia** [comment]
Probably because you are sending the player the wrong type multiple different times in this code. It accepts a message object not these arguments:


```
const result = await bot.player.addToQueue(message.guild.id, args.join(" ")).catch(() => {});

const result = await bot.player.play(message.member.voice.channel, args.join(" ")).catch(() => {});

```

Are not going to resolve properly leading to the error.

**Comment by 3scava1i3r** [comment]
can you please explain this a little better

**Comment by TasoOneAsia** [comment]
Sure, in V3 the player methods have been changed to accept a `Discord.Message` instance as the first argument rather than other types as previously. So, for example. This is how you would use the `play()` method in v3:

```javascript
// msg: Discord.Message instance
// query: Search String/URL or Track instance
client.player.play(msg, query)
```

This error can occur if the `msg` parameter is of incorrect type (not a Discord.Message). This happens because the player expects a message to correctly create a Collection, when it does not receive this correct type, it will throw this undefined message.

Hope that clears it up for you 😄
