### ISSUE TITLE
TypeError: import_equalizer.FiltersChain Randomly happening

### ISSUE THREAD

**Issue by XCOYoshi** [Androz2091/discord-player#1588]
**Describe the bug**
Discord Player now throws this bug wenn trying to run  `queue.connect(interaction.member.voice.channel)`

```
TypeError: import_equalizer.FiltersChain is not a constructor
    at new StreamDispatcher (I:\GIT\Plan-Bot\node_modules\discord-player\dist\index.js:1300:16)
    at VoiceUtils.connect (I:\GIT\Plan-Bot\node_modules\discord-player\dist\index.js:1505:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Queue.connect (I:\GIT\Plan-Bot\node_modules\discord-player\dist\index.js:754:24)
    at async Object.execute (I:\GIT\Plan-Bot\commands\play.js:60:6)
    at async Client.<anonymous> (I:\GIT\Plan-Bot\index.js:91:90)
```

**To Reproduce**
```
const queue = await client.player.nodes.create(guild, {
	leaveOnEnd: true,
	leaveOnStop: true,
	leaveOnEmpty: true,
	leaveOnEmptyCooldown: 300000,
	disableEqualizer: true,
	ytdlOptions: {
		filter: "audioonly",
		opusEncoded: true,
		quality: "highestaudio",
		highWaterMark: 1 << 30,
	},
	metadata: channel,
	
});				
try {
	await queue.connect(interaction.member.voice.channel);
} catch(error) {
	console.log(error)
	void client.player.nodes.delete(guild.id);
	return void interaction.reply({ embeds: [voiceEmbed] });
}
```

**Expected behavior**
the bot conectes and play the musik

**Please complete the following information:**
 - Node Version: 18.12.1
 - Discord Player Version: 6.0.0-dev.2
 - Discord.js Version: 14.7.1

**Additional context**
the problem just startet after runing npm install and starting the thing

**Comment by XCOYoshi** [comment]
Testet  with <Player.createQueue> <Player.deleteQueue> aswell same issu

**Comment by skdhg** [comment]
Try

```sh
npm i @discord-player/equalizer@dev
```

**Comment by XCOYoshi** [comment]
now getting this error
```
{"level":"error","message":"Error while performing play."}
TypeError: queue.play is not a function
    at Object.execute (I:\GIT\Plan-Bot\commands\play.js:76:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (I:\GIT\Plan-Bot\index.js:91:90)
```

**Comment by XCOYoshi** [comment]
did somthing change there aswell ?

**Comment by skdhg** [comment]
Looks like you are using your old code with new queue system, which is incompatible unfortunately.

Please take a look at example bot here https://github.com/Androz2091/discord-player/tree/develop/examples/karasu

Docs are available at https://discord-player.netlify app

**Comment by XCOYoshi** [comment]
ok i wait until proper documentation on how to upgrade is available thx fore the quick help i am going back to the old system fore now
