### ISSUE TITLE
trackAdd and tracksAdd Events

### ISSUE THREAD

**Issue by Zsl8** [Androz2091/discord-player#1609]
This two events is not working in the dev version when you use the <Player>.play() function it only works when you use the <Queue>.addTrack() Or <Queue>.addTracks() functions

**Comment by hmes98318** [comment]
`v5.4.0` has the same problem.

**Comment by hmes98318** [comment]
Events `trackStart` `trackStart` doesn't work when i call `.play()` in v5.4.0 , but v5.3.2 normal.

**Comment by skdhg** [comment]
> This two events is not working in the dev version when you use the .play() function it only works when you use the .addTrack() Or .addTracks() functions

Those events do not exist in dev version. https://discord-player.netlify.app/docs/types/discord-player/GuildQueueEvents

**Comment by skdhg** [comment]
This event won't be emitted when a track is not queued (because it is possible to play without adding the track to the queue when using `playerNode.play` method)

**Comment by febkosq8** [comment]
`Version : 6.0.0-dev.4`
When i queue a playlist, both audioTrackAdd & audioTracksAdd get emitted.
I would expect audioTrackAdd to emit only when a single track is getting added.

**Comment by skdhg** [comment]
I've decided to make it work in this way:

* When multiple tracks are queued, it will only emit `audioTracksAdd` with array of all tracks. Use `tracks[0]` to get the track which would be emitted by `audioTrackAdd`.
* When single track is queued, it will only emit `audioTrackAdd` with that particular track.
* When single track is removed, it will emit `audioTrackRemove`
* When multiple tracks are removed, it will emit `audioTracksRemove` with array of tracks.
