### ISSUE TITLE
i always get a not found error for any query that i make 

### ISSUE THREAD

**Issue by 3scava1i3r** [Androz2091/discord-player#161]
![Screenshot from 2020-11-16 18-57-55](https://user-images.githubusercontent.com/52003051/99257850-b170ae00-283d-11eb-8d06-16112f742d21.png)

**Comment by DashCruft** [comment]
Same

**Comment by 3scava1i3r** [comment]
@DashCruft great content on YouTube by the way

**Comment by RoytjexD** [comment]
Same thing, please let me know if you guys have found a fix

**Comment by Androz2091** [comment]
Please use #167
