### ISSUE TITLE
Track stops playing after 30-60 seconds

### ISSUE THREAD

**Issue by Nico-Mayer** [Androz2091/discord-player#1630]
**Describe the bug**
After the bot joins the VC it starts playing the selected song, but after 30-60 the track stops.
Bot stays in VC for quite some time after that.
No logs are present in Node console.
Same bug is mentioned here [Issue](https://github.com/discordjs/discord.js/issues/9185)

**To Reproduce**
1. Play a song via slash command
2. Wait until song stops playing.

**Expected behavior**
Bot should play the whole song and then leve the VC.

**Screenshots**
-

**Please complete the following information:**
 - Node Version: 19.7.0 & 18.14.2
 - Discord Player Version: 5.4.0
 - Discord.js Version: 14.7.1

**Additional context**
-

**Comment by Crocross** [comment]
@Nico-Mayer , the issue is with a change from discord and discordjs/voice. It's not really a discord-player issue. There are two temporary fixes right now that you can use in the meantime that are in the discord thanks to @skdhg : 

```js
import { VoiceConnectionStatus } from '@discordjs/voice';
// or const { VoiceConnectionStatus } = require('@discordjs/voice');

// v6
player.events.on('connection', (queue) => {
    queue.dispatcher.voiceConnection.on('stateChange', (oldState, newState) => {
        if (oldState.status === VoiceConnectionStatus.Ready && newState.status === VoiceConnectionStatus.Connecting) {
            queue.dispatcher.voiceConnection.configureNetworking();
        }
    });
});

// v5
player.on('connectionCreate', (queue) => {
    queue.connection.voiceConnection.on('stateChange', (oldState, newState) => {
        if (oldState.status === VoiceConnectionStatus.Ready && newState.status === VoiceConnectionStatus.Connecting) {
            queue.connection.voiceConnection.configureNetworking();
        }
    })
});
```

**Comment by skdhg** [comment]
This is the new solution as per https://github.com/discordjs/discord.js/issues/9185#issuecomment-1452510633

```js
// v6
player.events.on('connection', (queue) => {
  queue.dispatcher.voiceConnection.on('stateChange', (oldState, newState) => {
    const oldNetworking = Reflect.get(oldState, 'networking');
    const newNetworking = Reflect.get(newState, 'networking');

    const networkStateChangeHandler = (oldNetworkState, newNetworkState) => {
      const newUdp = Reflect.get(newNetworkState, 'udp');
      clearInterval(newUdp?.keepAliveInterval);
    }

    oldNetworking?.off('stateChange', networkStateChangeHandler);
    newNetworking?.on('stateChange', networkStateChangeHandler);
  });
});

// v5
player.on('connectionCreate', (queue) => {
    queue.connection.voiceConnection.on('stateChange', (oldState, newState) => {
      const oldNetworking = Reflect.get(oldState, 'networking');
      const newNetworking = Reflect.get(newState, 'networking');

      const networkStateChangeHandler = (oldNetworkState, newNetworkState) => {
        const newUdp = Reflect.get(newNetworkState, 'udp');
        clearInterval(newUdp?.keepAliveInterval);
      }

      oldNetworking?.off('stateChange', networkStateChangeHandler);
      newNetworking?.on('stateChange', networkStateChangeHandler);
    });
});
```

**Comment by zoltan-lima** [comment]
Is anyone else after implementing this fix running into the issue that the player only plays tracks for 2m 30s and then stops and queues the next track? Is there a fix similair to above for it?

**Comment by skdhg** [comment]
# Note to newcomers

If you just installed discord-player, there's a chance that you have v6.0.0 installed. If yes, you can ignore this issue as discord-player v6.0.0 comes with this patch. v6.0.0 users can disable default patch by setting `DP_NO_KEEPALIVE_PATCH=true`, although this patch only gets applied if `@discordjs/voice` version is less than or equal to `0.14.0`
