### ISSUE TITLE
Who is using Discord Player?

### ISSUE THREAD

**Issue by skdhg** [Androz2091/discord-player#1638]
Please share your awesome projects using discord-player here if you have one. Use this or similar format:

# Project Name

We are using discord-player to .... (optional description)

Link: repo url (required)

**Example:**

# AtlantaBot

We are using discord-player to manage all of our music commands.

Link: https://github.com/Androz2091/AtlantaBot

**Comment by Mittelblut9** [comment]
# Mittelbot
I am using discord-player to let people play their favourite music in their discord servers (No yt ofc ;) )

Link: https://github.com/Mittelbots/Mittelbot

**Comment by Lutra-Fs** [comment]
# Flowease

I am using discord-player to play songs from NetEase.

Link: https://github.com/Lutra-Fs/Flowease

**Comment by JazzyArmando1234** [comment]
### Music Bot

Only music bot which use discord-player.

Link: https://github.com/JazzyArmando1234/music-bot/tree/master

**Comment by yeci226** [comment]
### Yeci

I am using discord-player to play music with shards :)

Link: https://github.com/yeci226/yeci-bot

**Comment by Greensky-gs** [comment]
I made a Lofi music bot with discord-player v5.3.2 (updating to v6 soon) 

Here is the link [to Lofi Girl bot by Greensky](https://github.com/Greensky-gs/Lofi-girl)

**Comment by itsauric** [comment]
# karasu-music-bot

This is a music bot created by using the sapphire framework & discord-player with this project being written in TypeScript

https://github.com/itsauric/karasu-music-bot

**Comment by febkosq8** [comment]
# Jappan

A simple discord bot made to make someone's life easier

Currently features Music Playback, Fun Commands, Leveling System & Moderation Tools

Built using Discord.js, Node.js and hosted on Heroku.

GitHub Repo : [LINK](https://github.com/febkosq8/Jappan)

**Comment by Mylloon** [comment]
# Botanique
A bot I made with my girlfriend, we're using discord-player for the music and for lyrics
Link: https://git.mylloon.fr/ConfrerieDuKassoulait/Botanique

**Comment by akanora** [comment]
## Bhop Music Bot

There were not many bots made with discord-player 6.0.0 and discord.js 14.7.1, I was bored and made a simple one. We are using discord-player to listen music while bhopping. 🐇

GitHub Repository: https://github.com/akanora/bhop-music-bot

**Comment by hmes98318** [comment]
# Music Disc

I am using discord-player v6 to play music on Discord with friends.  
It's easy to set up and run yourself.  

Link: https://github.com/hmes98318/Music-Disc

**Comment by ervin-sungkono** [comment]
# Discord Music Bot
I am using discord player to make a discord music bot, it can play music, see lyrics, and most features a music bot does.

Link: https://github.com/ervin-sungkono/Discord-Music-Bot

**Comment by skdhg** [comment]
Please make a pull request modifying https://github.com/Androz2091/discord-player/blob/master/docs/community/community_resources.md if you want to add your project (music bot or extractor). Your projects are displayed at https://discord-player.js.org/docs/guides/community-resources
