### ISSUE TITLE
GuildQueue.node.seek() is not working

### ISSUE THREAD

**Issue by matthijs-vr** [Androz2091/discord-player#1640]
**Describe the bug**
When trying to seek to a specific timestamp in a song, it adds the song to the end of the queue again and just keeps playing without changing the progress.

**To Reproduce**
1. Have a song playing
2. Use GuildQueue.node.seek(60000)

**Expected behavior**
The player changes the progress in the current song to the specified timestamp

**Please complete the following information:**
 - Node Version: 19.2.0
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1

**Comment by skdhg** [comment]
Hello, the issue has been identified and will be fixed in the next release. As a workaround, you can use `await queue.filters.triggerReplay(seekTime);` to perform seek.
