### ISSUE TITLE
Playlists are not working

### ISSUE THREAD

**Issue by ddemile** [Androz2091/discord-player#1642]
**Describe the bug**
Playlists from every platforms are not working, when I try to play a playlist I have the following error:
`Could not extract stream for this track`

**To Reproduce**
1. Put a playlist link

**Expected behavior**
Not having an error

**Screenshots**
![image](https://user-images.githubusercontent.com/104416229/222944089-2be30237-ac8f-467a-9bc1-aad916f9df87.png)

**Please complete the following information:**
 - Node Version: v18.12.1
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1

**Comment by febkosq8** [comment]
Try the following as it is working for me (YT and Spotify playlists):

Deleting node_modules and package-lock files.
Then run `npm i`
and try again
