### ISSUE TITLE
Playing albums/playlists from all major streaming platforms does not work

### ISSUE THREAD

**Issue by yazninja** [Androz2091/discord-player#1643]
**Describe the bug**
Discord-player will happily play tracks/ singles, bhowever when there are multiple tracks being returned as a searchResult, it errors out.

**To Reproduce**
play any of these links;
1. https://open.spotify.com/album/1ONjVRtxAqiTivu0EiEBm5?si=7Wp_NnggT7i-AcWvy-RbGg
2. https://music.apple.com/ph/playlist/2000s-alternative-essentials/pl.7f3a307b0f2e49b1b521b4d4d5c21c7c
3. https://www.youtube.com/watch?v=572QgKc6xT8&list=RDCLAK5uy_k27uu-EtQ_b5U2r26DNDZOmNqGdccUIGQ

**Expected behavior**
to play the playlist and add it to queue if there are multiple tracks

**Screenshots**
![image](https://user-images.githubusercontent.com/71800112/222944210-72ba14bb-9f17-41d0-96a1-26e6105cb022.png)
![image](https://user-images.githubusercontent.com/71800112/222944227-5af989a8-dbeb-4524-b3dd-0b7850535043.png)

**Please complete the following information:**
 - Node Version: 18.14.2
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1

**Comment by ddemile** [comment]
Hey, something like that should work :
```js
let query = interaction.options.getString("search_terms")

const queue = client.player.nodes.create(interaction.guild, {
    metadata: {
        channel: interaction.channel,
        client: interaction.guild.members.me,
        requestedBy: interaction.user,
    },
    selfDeaf: true,
    volume: 80,
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 300000,
    leaveOnEnd: true,
    leaveOnEndCooldown: 300000,
});
if (!queue.connection) await queue.connect(interaction.member.voice?.channelId)
const search = await client.player.search(query, { searchEngine: QueryType.AUTO, requestedBy: interaction.member })
queue.addTrack(search.tracks)
await queue.node.play()
```

**Comment by febkosq8** [comment]
Try the following as it is working for me (YT and Spotify playlists):

Deleting node_modules and package-lock files.
Then run npm i
and try again

**Comment by sulsalloom** [comment]
> Hey, something like that should work :
> 
> ```js
> let query = interaction.options.getString("search_terms")
> 
> const queue = client.player.nodes.create(interaction.guild, {
>     metadata: {
>         channel: interaction.channel,
>         client: interaction.guild.members.me,
>         requestedBy: interaction.user,
>     },
>     selfDeaf: true,
>     volume: 80,
>     leaveOnEmpty: true,
>     leaveOnEmptyCooldown: 300000,
>     leaveOnEnd: true,
>     leaveOnEndCooldown: 300000,
> });
> if (!queue.connection) await queue.connect(interaction.member.voice?.channelId)
> const search = await client.player.search(query, { searchEngine: QueryType.AUTO })
> queue.addTrack(search.tracks)
> await queue.node.play()
> ```

this will break on single tracks adding this line should fix it  

```
const tracks = searchResult.playlist
      ? searchResult.tracks
      : searchResult.tracks[0];
    queue.addTrack(tracks);
```

**Comment by sulsalloom** [comment]
experiencing the same issue  right now tried deleting node modules and package-lock files  still not working

**Comment by febkosq8** [comment]
@sulsalloom 
I tried your code.
Only thing I had to change was one line , `metadata: interaction` to `metadata: interaction.channel`.

After that everything worked as expected. Can you try that change to see if it fixes it.
![image](https://user-images.githubusercontent.com/33223665/223225593-934f060e-333f-466a-b7ae-2a3eb69cb1d9.png)

**Comment by febkosq8** [comment]
@yazninja 

The yt link that you gave (https://www.youtube.com/watch?v=572QgKc6xT8&list=RDCLAK5uy_k27uu-EtQ_b5U2r26DNDZOmNqGdccUIGQ) isn't a playlist, it's probably a yt music mix or something similar. (IDK much about those)

Playlist will have `youtube.com/playlist?` in it. Player as far as I tested only supports such links.

**Comment by sawdex** [comment]
![image](https://user-images.githubusercontent.com/127150323/223227793-b7223e9b-b859-44c1-b7bf-01226d18f6c4.png)

**Comment by febkosq8** [comment]
> ![image](https://user-images.githubusercontent.com/127150323/223227793-b7223e9b-b859-44c1-b7bf-01226d18f6c4.png)

The new event for same is `playerStart` not `trackStart`

**Comment by sulsalloom** [comment]
> @sulsalloom I tried your code. Only thing I had to change was one line , `metadata: interaction` to `metadata: interaction.channel`.
> 
> After that everything worked as expected. Can you try that change to see if it fixes it. ![image](https://user-images.githubusercontent.com/33223665/223225593-934f060e-333f-466a-b7ae-2a3eb69cb1d9.png)

still the same using this playlist [https://www.youtube.com/playlist?list=PLOHoVaTp8R7dfrJW5pumS0iD_dhlXKv17](url)
also tested @yazninja other 2 lists both of them don't work

**Comment by sawdex** [comment]
i tried trackStart and still @febkosq8

**Comment by febkosq8** [comment]
> still the same using this playlist https://www.youtube.com/playlist?list=PLOHoVaTp8R7dfrJW5pumS0iD_dhlXKv17
also tested @yazninja other 2 lists both of them don't work

Just now tried that link works for me. Do you have your bot code on git ?

**Comment by febkosq8** [comment]
> i tried trackStart and still @febkosq8

Do you have your bot code on git ?

**Comment by sawdex** [comment]
'use strict';

const fs = require('fs');

const dotenv = require('dotenv');
const { Client, GatewayIntentBits, Partials, Collection } = require('discord.js');
const { Player } = require('discord-player');
const express = require('express');
require('console-stamp')(console, { format: ':date(yyyy/mm/dd HH:MM:ss)' });

const embed = require('/home/container/src/embeds/embeds');


dotenv.config();
const ENV = process.env;
const color = {
    white: '\x1B[0m',
    grey: '\x1B[2m',
    green: '\x1B[32m'
};




let client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMembers,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildVoiceStates,
    ],
    partials: [Partials.Channel],
    disableMentions: 'everyone',
});
client.config = {
    name: 'Bass',
    prefix: '+',
    playing: '+help | music',
    defaultVolume: 50,
    maxVolume: 100,
    autoLeave: true,
    autoLeaveCooldown: 5000,
    displayVoiceState: true,
    port: 33333
};





client.config.ytdlOptions = {
    filter: 'audioonly',
    quality: 'highestaudio',
    highWaterMark: 1 << 27
}


client.commands = new Collection();
client.player = new Player(client, {
    ytdlOptions: client.config.ytdlOptions
});
const player = client.player;




const setEnvironment = () => {
    return new Promise((resolve, reject) => {
        client.config.name = typeof (ENV.BOT_NAME) === 'undefined' ?
            client.config.name :
            ENV.BOT_NAME;

        client.config.prefix = typeof (ENV.PREFIX) === 'undefined' ?
            client.config.prefix :
            ENV.PREFIX;

        client.config.playing = typeof (ENV.PLAYING) === 'undefined' ?
            client.config.playing :
            ENV.PLAYING;

        client.config.defaultVolume = typeof (ENV.DEFAULT_VOLUME) === 'undefined' ?
            client.config.defaultVolume :
            Number(ENV.DEFAULT_VOLUME);

        client.config.maxVolume = typeof (ENV.MAX_VOLUME) === 'undefined' ?
            client.config.maxVolume :
            Number(ENV.MAX_VOLUME);

        client.config.autoLeave = typeof (ENV.AUTO_LEAVE) === 'undefined' ?
            client.config.autoLeave :
            (String(ENV.AUTO_LEAVE) === 'true' ? true : false);

        client.config.autoLeaveCooldown = typeof (ENV.AUTO_LEAVE_COOLDOWN) === 'undefined' ?
            client.config.autoLeaveCooldown :
            Number(ENV.AUTO_LEAVE_COOLDOWN);

        client.config.displayVoiceState = typeof (ENV.DISPLAY_VOICE_STATE) === 'undefined' ?
            client.config.displayVoiceState :
            (String(ENV.DISPLAY_VOICE_STATE) === 'true' ? true : false);

        client.config.port = typeof (ENV.PORT) === 'undefined' ?
            client.config.port :
            Number(ENV.PORT);

        //console.log('setEnvironment: ', client.config);
        resolve();
    })
}


const loadEvents = () => {
    console.log(`-> loading Events ......`);
    return new Promise((resolve, reject) => {
        const files = fs.readdirSync(`${__dirname}/src/events/`).filter(file => file.endsWith('.js'));

        console.log(`+--------------------------------+`);
        for (const file of files) {
            try {
                const event = require(`${__dirname}/src/events/${file}`);
                console.log(`| Loaded event ${file.split('.')[0].padEnd(17, ' ')} |`);

                client.on(file.split('.')[0], event.bind(null, client));
                delete require.cache[require.resolve(`${__dirname}/src/events/${file}`)];
            } catch (error) {
                reject(error);
            }
        };
        console.log(`+--------------------------------+`);
        console.log(`${color.grey}-- loading Events finished --${color.white}`);

        resolve();
    })
}


const loadFramework = () => {
    console.log(`-> loading Web Framework ......`);
    return new Promise((resolve, reject) => {
        const app = express();
        const port = client.config.port || 33333;

        app.get('/', function (req, res) {
            res.send('200 ok.')
        });

        app.listen(port, function () {
            console.log(`Server start listening port on ${port}`);
            resolve();
        });
    })
}


const loadCommands = () => {
    console.log(`-> loading Commands ......`);
    return new Promise((resolve, reject) => {
        const files = fs.readdirSync(`${__dirname}/src/commands/`).filter(file => file.endsWith('.js'));

        console.log(`+---------------------------+`);
        for (const file of files) {
            try {
                const command = require(`${__dirname}/src/commands/${file}`);

                console.log(`| Loaded Command ${command.name.toLowerCase().padEnd(10, ' ')} |`);

                client.commands.set(command.name.toLowerCase(), command);
                delete require.cache[require.resolve(`${__dirname}/src/commands/${file}`)];
            } catch (error) {
                reject(error);
            }
        };
        console.log(`+---------------------------+`);
        console.log(`${color.grey}-- loading Commands finished --${color.white}`);

        resolve();
    })
}


Promise.resolve()
    .then(() => setEnvironment())
    .then(() => loadFramework())
    .then(() => loadEvents())
    .then(() => loadCommands())
    .then(() => {
        console.log(`${color.green}*** All loaded successfully ***${color.white}`);
        client.login(ENV.TOKEN);
    });




const settings = (queue, song) =>
    `**Volume**: \`${queue.volume}%\` | **Loop**: \`${queue.repeatMode ? (queue.repeatMode === 2 ? 'All' : 'ONE') : 'Off'}\``;


player.events.on('error', (queue, error) => {
    console.log(`There was a problem with the song queue => ${error.message}`);
});

player.events.on('connectionError', (queue, error) => {
    console.log(`I'm having trouble connecting => ${error.message}`);
});

player.events.on('playerStart', (queue, track) => {
    if (queue.repeatMode !== 0) return;
    queue.metadata.channel?.send({ embeds: [embed.Embed_play("Playing", track.title, track.url, track.duration, track.thumbnail, settings(queue))] });
});

player.events.on('trackAdd', (queue, track) => {
    if (queue.previousTracks.length > 0)
        queue.metadata.send({ embeds: [embed.Embed_play("Added", track.title, track.url, track.duration, track.thumbnail, settings(queue))] });
});

player.events.on('channelEmpty', (queue) => {
    if (!client.config.autoLeave)
        queue.stop();
});

**Comment by febkosq8** [comment]
@sawdex 

Please create a git repo to show your code next time.

Can you update your event code to this and try again to see if its broadcasting the event ?
```
player.events.on('playerStart', (queue, track) => {
console.log("PlayerStart HIT");
if (queue.repeatMode !== 0) return;
queue.metadata.channel?.send({ embeds: [embed.Embed_play("Playing", track.title, track.url, track.duration, track.thumbnail, settings(queue))] });
});
```

**Comment by sawdex** [comment]
@febkosq8 
![image](https://user-images.githubusercontent.com/127150323/223231586-84113557-c833-4b6c-909a-c2e713b6196f.png)
no embed i think the error from play command

**Comment by febkosq8** [comment]
> image
no embed i think the error from play command

So the event is working as intended. If you are fine with a simple update to the user, try what I have.
```
queue.metadata.send(`▶ | Started playing: **${track.title}**`);
```

**Comment by sawdex** [comment]
@febkosq8 
now working thank you, now I know that the problem is from embed.

**Comment by febkosq8** [comment]
@sulsalloom 

You only have discord-player@6.0.0 in your package.
You will need @discord-player/extractor, @discord-player/equalizer & @discord-player/utils for everything to properly work.

Run the following in terminal
```
npm i discord-player@latest @discord-player/extractor@latest @discord-player/equalizer@latest @discord-player/utils@latest
```
Then delete `node_modules` & `package-lock.json`.
Then run the following and try again
```
npm cache clean --force
npm i
```

**Comment by sulsalloom** [comment]
> @sulsalloom
> 
> You only have discord-player@6.0.0 in your package. You will need @discord-player/extractor, @discord-player/equalizer & @discord-player/utils for everything to properly work.
> 
> Run the following in terminal
> 
> ```
> npm i discord-player@latest @discord-player/extractor@latest @discord-player/equalizer@latest @discord-player/utils@latest
> ```
> 
> Then delete `node_modules` & `package-lock.json`. Then run the following and try again
> 
> ```
> npm cache clean --force
> npm i
> ```

still same issue i pushed to the rep if you wanna have a look

**Comment by skdhg** [comment]
> @yazninja
> 
> The yt link that you gave (https://www.youtube.com/watch?v=572QgKc6xT8&list=RDCLAK5uy_k27uu-EtQ_b5U2r26DNDZOmNqGdccUIGQ) isn't a playlist, it's probably a yt music mix or something similar. (IDK much about those)
> 
> Playlist will have `youtube.com/playlist?` in it. Player as far as I tested only supports such links.
> 
> The other two links worked perfectly fine for me.

Mixes are not supported, see skdhg/youtube-sr#31

**Comment by febkosq8** [comment]
@sulsalloom 

I tried your code on my local machine, and it didn't work for me. 
I tried changing stuff but nothing worked out. Any single tracks would work. But no playlist would work. 
From debug logs, I found out that the searchResults are being fetched as expected but player.play doesn't seem to work. 
I also checked player debug event and every standard extractors were being loaded as expected.

Don't know what is going wrong over here. My best guess is the way your bot is structured. I will try to dig around more in free time.

Error Stack

```
Error: Play request received but track was not provided
    at GuildQueuePlayerNode.play (<dir>/discord-bot/node_modules/discord-player/dist/index.mjs:863:13)
    at GuildQueuePlayerNode.play (<dir>/discord-bot/node_modules/discord-player/dist/index.mjs:888:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Player.play (<dir>/discord-bot/node_modules/discord-player/dist/index.mjs:2581:7)
    at async play_handler (<dir>/discord-bot/commands/play.js:28:5)
```

**Comment by febkosq8** [comment]
> changed my code to cjs and now it works thats weird

Yea, that should not be a thing.
