### ISSUE TITLE
Cannot read property "createMessageCollector((m)

### ISSUE THREAD

**Issue by HyperZoneX** [Androz2091/discord-player#166]
![image](https://user-images.githubusercontent.com/74700373/99739838-4cae9100-2a93-11eb-8a34-73bdb991e0ef.png)

I've been trying to fix this for a while now.

**Comment by Snowflake107** [comment]
instead of passing `args`, pass message object received from the `discord.js` because `discord-player` is trying to create a prompt message

**Comment by Androz2091** [comment]
Yes, please read the README file
