### ISSUE TITLE
No results found..

### ISSUE THREAD

**Issue by erafn** [Androz2091/discord-player#167]
Whenever I search for a song using the bot, I always get the same error, no results are found.
Is this just me or is this affecting other people? I couldn't find anything about it.

**Comment by MetalOoze05** [comment]
same

**Comment by RoytjexD** [comment]
I have the same thing, let me know if you guys find out the issue

**Comment by udit2303** [comment]
Seems like you guys are only having it. Can you tell the version for `discord-player`?

**Comment by erafn** [comment]
issue resolved with uninstalling and re-installing discord-player with the latest updates.
