### ISSUE TITLE
moveTrack suggestion

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1670]
**Describe the feature you would like**
I think adding a feature that allows us to move a track's position in the queue would be nice. I have done something similar in my code through removing / inserting tracks but a built in functionality would be useful as well.

**Expected behavior**
Lets say I added a song to the end of queue and I want to move it to play after 3 songs. I'd want to be able to call something like
`moveTrack(songNum, position);` ex. `moveTrack(24, 3);` This assumes there are 25 songs in the queue.

**Comment by febkosq8** [comment]
I know this isn't what was requested, but wanted to drop anyway.
I use `queue.insertTrack(searchResult.tracks[0], 0)` to insert tracks at the start of the queue, might be able to use this to add to the required position?
