### ISSUE TITLE
`error` event not working properly

### ISSUE THREAD

**Issue by TeraBaito** [Androz2091/discord-player#168]
Basically, I followed the "Event messages" section and copied the code as-is (will later change some things with formatting and such, but for now it's just how it is there). However, when testing if the errors logged as they should according to the code provided. However, it came to my surprise that they didn't, and they just logged to the console like if I had never attached the error. I tried using `bot.player.on()` for each event instead of chaining them, migrating them to a file and requiring, among others, but I can't seem to make it work. Why is this, if the `error` event is listed in the package PlayerEvents interface? Thanks in advance.

Code (as I said, it's as-is, but it will further prove the former point) (skipped all the other events to shorten):
```js
const player = new Player(bot);
bot.player = player;

bot.player.on('error', (error, message) => {
        switch(error.name){
        case 'NotPlaying':
            message.channel.send('There is no music being played on this server!');
            break;
        case 'NotConnected':
            message.channel.send('You are not connected in any voice channel!');
            break;
        case 'UnableToJoin':
            message.channel.send('I am not able to join your voice channel, please check my permissions!');
            break;
        default:
            message.channel.send(`Something went wrong... Error: ${error}`);
        }
    });
```

**Comment by Androz2091** [comment]
Hello @TeraBaito, what errors did you try? (for example, you tried to send a command when nothing was playing?)

**Comment by TeraBaito** [comment]
Hello, I just tried the NotConnected one by toggling a play command when the user isn't in a voice channel. Somehow I'm now receiving an UnableToJoin error, but that's probably my fault or from the bot connection. Anyhow, it simply logs the errors, yet other events work as they should somehow...

**Comment by JChoptiany** [comment]
Hello, I have similar problem to yours. Sometimes it catches NotPlaying error, but other types aren't handled at all.

**Comment by Androz2091** [comment]
You are right, some events are not working. They will in the next release (it's already fixed in the develop branch)
