### ISSUE TITLE
Spotify dosen't play!!

### ISSUE THREAD

**Issue by tawashi123** [Androz2091/discord-player#1687]
When i put to play a Spotify song it always says no results!\

 - Node Version: 19.8.1
 - Discord Player Version: 5.2.2
 - Discord.js Version: 13.7.0

**Comment by itsauric** [comment]
The best solution is to update `discord-player` to the latest, this would also mean that you'll have to update `discord.js` for both to work. If you want Spotify to work then take that solution, v5 isn't maintained so you're gonna have to update at this point.

**Comment by hmes98318** [comment]
You can use the following method as a temporary solution for `v5.3.2`, but it is not recommended.  
https://github.com/hmes98318/Music-Disc/issues/11#issuecomment-1361781295
