### ISSUE TITLE
Disconnect Event - Add Reason (Enum maybe)

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1688]
**Describe the feature you would like**
It would be nice if in the disconnect event there was a reason for the disconnection. Some examples could be:

1. Channel was empty and `leaveOnEmptyCooldown` time reached
2. Queue finished and `leaveOnEndCooldown` time reached
3. Kicked from vc
4. Unknown reason

**Expected behavior**
Ability to change message sent based on the reason for the disconnect

**Comment by Crocross** [comment]
Just as an additional note, this original stemmed from the fact that a disconnect command which does `queue.delete();` will also then trigger the event for `emptyQueue` which makes sense for how the delete process works but is also odd to have the bot say that the queue is empty after you have disconnected the bot.

**Comment by skdhg** [comment]
Current handler does not know why or where disconnect occurred, it only knows the bot has been disconnected.

**Comment by Crocross** [comment]
If it is not realistic this can be closed otherwise I'd say maybe leave it as a long term thing but you can decide :)
