### ISSUE TITLE
Remove ffmpeg

### ISSUE THREAD

**Issue by twlite** [Androz2091/discord-player#1693]
Proposal to completely remove ffmpeg and all of its components from this framework.

**Comment by samusaran** [comment]
I was writing you about this in #1639 , the issue is that ffmpeg-static is referenced by discordjs/voice > prism-media. How can you solve it?

**Comment by skdhg** [comment]
> I was writing you about this in #1639 , the issue is that ffmpeg-static is referenced by discordjs/voice > prism-media. How can you solve it?

Based on the source code of prism-media https://github.com/amishshah/prism-media/blob/4ef1d6f9f53042c085c1f68627e889003e248d77/src/core/FFmpeg.js#L125-L128 `ffmpeg-static` will be loaded first. The only way to get around this problem is to not install `ffmpeg-static` at all.

**Comment by febkosq8** [comment]
> The only way to get around this problem is to not install `ffmpeg-static` at all.

FYI, I had the [bug](https://discord.com/channels/558328638911545423/1081647662383775834) where songs would end early if `ffmpeg-static` wasn't installed.

**Comment by skdhg** [comment]
> > The only way to get around this problem is to not install `ffmpeg-static` at all.
> 
> FYI, I had the [bug](https://discord.com/channels/558328638911545423/1081647662383775834) where songs would end early if `ffmpeg-static` wasn't installed.

That could be due to the ffmpeg build available on your system not working properly?

**Comment by febkosq8** [comment]
> That could be due to the ffmpeg build available on your system not working properly?

Probably, it was only happening on Heroku 20 stack

**Comment by samusaran** [comment]
I have ffmpeg 5.1.2 installed on my system (outside npm) and i have the issue where songs ends early

**Comment by skdhg** [comment]
> > That could be due to the ffmpeg build available on your system not working properly?
> 
> Probably, it was only happening on Heroku 20 stack

Heroku buildpack is also pulling it from the same place as ffmpeg-static does.

What you can try is download the appropriate build for your platform from https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest and place the ffmpeg executable at the root of your project and rename it to `ffmpeg` (prism-media will spawn that executable with `./ffmpeg`)

**Comment by samusaran** [comment]
> > I was writing you about this in #1639 , the issue is that ffmpeg-static is referenced by discordjs/voice > prism-media. How can you solve it?
> 
> Based on the source code of prism-media https://github.com/amishshah/prism-media/blob/4ef1d6f9f53042c085c1f68627e889003e248d77/src/core/FFmpeg.js#L125-L128 `ffmpeg-static` will be loaded first. The only way to get around this problem is to not install `ffmpeg-static` at all.

How can I achive that? ffmpeg-static is listed as a dependency of prism-media

```
discord-music-bot@1.0.0 /home/mordack/discord-music-bot
└─┬ @discordjs/voice@0.14.0
  └─┬ prism-media@1.3.5
    └── ffmpeg-static@4.4.1
```

**Comment by skdhg** [comment]
It is listed as a peer dependency (optional) so you should be fine

**Comment by skdhg** [comment]
Note: use https://github.com/androzdev/mediaplex as an alternative to ffmpeg when it is ready
