### ISSUE TITLE
Timestamp doesn't match song length

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1698]
**Describe the bug**
When I search and queue the song "Can't Hold Us (feat. Ray Dalton)" it plays with the link: https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn which is 4:18 in length.

However, I believe [this](https://www.youtube.com/watch?v=2zNSgSzhBfM) is what is actually played which has a timestamp of 7:04

So when I look at the duration from the bot it shows 4:18 but the song continues to play past that (and when creating a progress bar in a `/nowplaying` command it will go like 07:00 | --- | 04:18

**To Reproduce**
1. Run the command `/play search: https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn` or an equivalent command
2. Run any command / look at any message that shows song duration

**Expected behavior**
The duration should be pulled from what is actually playing and show a timestamp of 07:04

**Screenshots**
![image](https://user-images.githubusercontent.com/10664890/227780111-40e7423c-2f37-4c80-a0e5-e0880f31ffca.png)

**Please complete the following information:**
 - Node Version: v19.6.0
 - Discord Player Version: v6.1.1
 - Discord.js Version: v14.8.0

**Additional context**
This issue might be related to https://github.com/Androz2091/discord-player/issues/1699

**Comment by skdhg** [comment]
This is due to cross bridge between metadata & stream source. Can't really do anything about this.

Let me know if it should use the duration of the bridged source rather than original source.

**Comment by Crocross** [comment]
I think it should use bridged source cause it is more of a what you see you get and it'd make more sense for progress bar and such? Though I don't know if others would prefer the source.

**Comment by skdhg** [comment]
utilize `track.metadata`
