### ISSUE TITLE
Playing song twice, bot DCs on second play through

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1699]
**Describe the bug**
Playing the song https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn twice seems to have the bot DC at some point in the middle of the second play through.

**To Reproduce**
1. Run the command `/play search: https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn` or an equivalent command
2. Wait until the song plays through entirely
3. Run the command again
4. Wait and see if the bot DCs randomly (usually around the 4-5 minute mark)

**Expected behavior**
The bot would play both songs through normally.

**Please complete the following information:**
 - Node Version: v19.6.0
- Discord Player Version: v6.1.1
- Discord.js Version: v14.8.0

**Additional context**
The bot is set to not leave on end. Edit: Changing `leaveOnEnd` to false did not help.
This issue might be related to: https://github.com/Androz2091/discord-player/issues/1698

**Comment by Crocross** [comment]
I believe this issue was resolved with the leaveOnEnd fix in version 6.3.0 so I'll close this issue now.

**Comment by zachrussell12** [comment]
This is actually still in issue in 6.3.0. Even when other songs are waiting in the queue, the first song added will play twice even though it says that there is not an additional copy of the first song in the queue.
