### ISSUE TITLE
SOLVED: Play function stopped working

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#17]
I keep getting unhandled rejection warnings. I don't know why this may be - it was originally working this morning and I noticed one of my server members using it earlier and it stopped working all of a sudden.
![image](https://user-images.githubusercontent.com/43547293/80290021-aa1b7300-873a-11ea-9ed5-fc88bbb44e32.png)

I also tried to eval the code using the eval command (`client.player.play(msg.member.voice.channel, 'test')`) and it still thrown a unhandled rejection warning in the console (I did this to test the possibility of it being a command fault instead I've realised that its not my problem)

Edit: Was also working this after noon, probably stopped working this evening (9:22 PM BST), I've also done debugging such as restarting the bot and reloading commands/modules.
Edit 2: I've tried to update to Node 14 as well as trying to downgrade to Node 12 and there is no hope yet.

**Comment by Androz2091** [comment]
@thomasthebro1 maybe Youtube is blocking you, because you send many requests. You will have to debug the play method (actually, this problem is not handled by discord-player, but this is planned).

**Comment by thomasthebro1** [comment]
Yeah I think that might of been the issue, unsure why that was happening however because I have the play method wrapped in a try {} to catch any errors that might happen. How often do you think that I should limit the command to? (e.g. 5 usages per 10 seconds)

**Comment by thomasthebro1** [comment]
Also, I tried to use `song.requestedBy` is this still a work in progress?

**Comment by Androz2091** [comment]
Yes, it's updated in the documentation here: https://discord-player.js.org but not on the README. You can make a PR if you know how.

**Comment by thomasthebro1** [comment]
Yea I've opened a pull request. Also I seem to not be able to access that site
![image](https://user-images.githubusercontent.com/43547293/80309386-a3d5d700-87cc-11ea-9654-49b11467b487.png)

**Comment by thomasthebro1** [comment]
Enhanced with Version 2 - scraping is now used instead of API key.
