### ISSUE TITLE
"Could not extract stream for this track"

### ISSUE THREAD

**Issue by ZeroRaven23** [Androz2091/discord-player#1707]
Yesterday I tested some things from my bot, and today it just isn't working anymore the music part of it. Today I tried to go back to his version, and nothing works or stops giving the error.

Error:
const error = new Error("Could not extract stream for this track");
                      ^

Error: Could not extract stream for this track
    at GuildQueuePlayerNode.play (\Wolf-Project-New\node_modules\discord-player\dist\index.js:949:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.execute (\Wolf-Project-New\src\commands\play.js:87:29)

Version:
Discord-player:  v"6.0.0"
Node.js:  v17.0.1 
npm: v8.1.0

**Comment by TrixiS** [comment]
Same thing. Using just string search query

```
const searchResult = await this.player.search(trackQuery, {
  searchEngine: QueryType.AUTO,
  requestedBy: interaction.user,
});
```

**Comment by ZeroRaven23** [comment]
`const { QueryType } = require("discord-player");

module.exports = {
  name: "play",
  aliases: ["p"],
  description: "Enter your song link or song name to play",
  usage: "play <URL/song name>",
  voiceChannel: true,
  options: [
    {
      name: "search",
      description: "The song link or song name",
      type: 3,
      required: true,
    },
  ],

  async execute(client, message, args) {
    if (!args[0])
      return message.reply({
        content: `❌ | Saudades do nome da musica ne amigo.`,
        allowedMentions: { repliedUser: false },
      });

    const results = await client.player
      .search(args.join(" "))
      .catch((error) => {
        console.log(error);
        return message.reply({
          content: `❌ | Mestre deve ta envolvido certeza.`,
          allowedMentions: { repliedUser: false },
        });
      });

    if (!results || !results.hasTracks())
      return message.reply({
        content: `❌ | Num achei nada não.`,
        allowedMentions: { repliedUser: false },
      });

    const queue = await client.player.nodes.create(message.guild, {
      metadata: {
        channel: message.channel,
        client: message.guild.members.me,
        requestedBy: message.user,
      },
      selfDeaf: true,
      leaveOnEmpty: client.config.autoLeave,
      leaveOnEnd: client.config.autoLeave,
      leaveOnEmptyCooldown: client.config.autoLeaveCooldown,
      leaveOnEndCooldown: client.config.autoLeaveCooldown,
      volume: client.config.defaultVolume,
    });

    try {
      if (!queue.connection) await queue.connect(message.member.voice.channel);
    } catch (error) {
      console.log(error);
      if (!queue?.deleted) queue?.delete();
      return message.reply({
        content: `❌ | Num da pra entrar ai não.`,
        allowedMentions: { repliedUser: false },
      });
    }

    results.playlist
      ? queue.addTrack(results.tracks)
      : queue.addTrack(results.tracks[0]);

    if (!queue.isPlaying()) await queue.node.play();

    return message.react("👍");
  },

  async slashExecute(client, interaction) {
    const results = await client.player
      .search(interaction.options.getString("search"))
      .catch((error) => {
        console.log(error);
        return interaction.reply({
          content: `❌ | Mestre deve ta envolvido certeza`,
          allowedMentions: { repliedUser: false },
        });
      });

    if (!results || !results.tracks.length)
      return interaction.reply({
        content: `❌ | Procurei, porem, não achei nada.`,
        allowedMentions: { repliedUser: false },
      });

    const queue = await client.player.nodes.create(interaction.guild, {
      metadata: {
        channel: interaction.channel,
        client: interaction.guild.members.me,
        requestedBy: interaction.user,
      },
      selfDeaf: true,
      leaveOnEmpty: client.config.autoLeave,
      leaveOnEnd: client.config.autoLeave,
      leaveOnEmptyCooldown: client.config.autoLeaveCooldown,
      leaveOnEndCooldown: client.config.autoLeaveCooldown,
      volume: client.config.defaultVolume,
    });

    try {
      if (!queue.connection)
        await queue.connect(interaction.member.voice.channel);
    } catch (error) {
      console.log(error);
      if (!queue?.deleted) queue?.delete();
      return interaction.reply({
        content: `❌ | Não consigo entrar no chat de audio não.`,
        allowedMentions: { repliedUser: false },
      });
    }

    results.playlist
      ? queue.addTracks(results.tracks)
      : queue.addTrack(results.tracks[0]);

    if (!queue.isPlaying()) await queue.node.play();

    return interaction.reply("✅ | **MUSICA COLOCADA**.");
  },
};
`
I forgot to post the code

**Comment by fpsone** [comment]
Duplicated https://github.com/Androz2091/discord-player/issues/1705#issuecomment-1499141602

**Comment by skdhg** [comment]
Please properly check for existing threads #1705
