### ISSUE TITLE
import_equalizer2 doesn't have a FiltersChain() constructor.

### ISSUE THREAD

**Issue by mattpsvreis** [Androz2091/discord-player#1708]
Whenever the `new Player()` object's function play() is called, it spurts out this error `TypeError: import_equalizer2.FiltersChain is not a constructor
    at new StreamDispatcher (C:\Users\Dark\Documents\Pessoal\Programação\Repos\DarkDJ\node_modules\discord-player\dist\index.js:2144:16)`

1. Instantiate a `new Player()`
2. Try to play some music.

 - Node Version: 16.17.0
 - Discord Player Version: 6.1.1
 - Discord.js Version: 14.9.0

**Comment by mattpsvreis** [comment]
Current workaround is importing the development branch of equalizer.

`npm i @discord-player/equalizer@dev`

**Comment by skdhg** [comment]
This is caused by npm cache causing malformed installation. You need to clean install all of your packages or use package managers like yarn
