### ISSUE TITLE
Feedback for Documentation - Playing Local File

### ISSUE THREAD

**Issue by MadisonHurler** [Androz2091/discord-player#1719]
any chance you could direct me to an example for the complete code for a bot that plays a local file.  I see a snippet that was placed here:

https://discord-player.js.org/docs/guides/playing-local-file

**Comment by skdhg** [comment]
> any chance you could direct me to an example for the complete code for a bot that plays a local file. I see a snippet that was placed here:
> 
> https://discord-player.js.org/docs/guides/playing-local-file

It should work with any regular source code, just add the search engine value
