### ISSUE TITLE
Some tracks just won't play

### ISSUE THREAD

**Issue by Sans3108** [Androz2091/discord-player#1735]
**Describe the bug**

When given certain URL's the spotify and youtube extractors just hang, infinitely loading. I've narrowed the problem down to the stream method for each of the extractors but that's about all I know

**To Reproduce**
1. Make sure you're using the stock spotify and youtube extractors
2. Add either [this](https://open.spotify.com/track/52fDe3n6AzSV7C4DEvTRe5) spotify track or [this](https://www.youtube.com/watch?v=F9mpWD7RL2g) youtube track
3. Take your popcorn and enjoy the silence while nothing happens

**Expected behavior**

The tracks should play

**Please complete the following information:**
 - Node Version: 18.16.0
 - Discord Player Version: 6.3.0
 - Discord.js Version: 14.11.0

**Additional context**

It's not just those tracks that are broken, those are just the ones I found
Ily Arch <3

**Comment by skdhg** [comment]
Looks like only `@distube/ytdl-core` was affected with this issue (ytdl-core has different type of issue going on) and `play-dl` seems to be unaffected.
