### ISSUE TITLE
Spotify 100 track limit

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1743]
**Describe the bug**
Spotify seems to be having a 100 track limit again after upgrading to the latest version.

**To Reproduce**
1. Play a playlist with over 100 songs
2. Check the queue size

**Expected behavior**
All the songs in a playlist being added (unless queue max size is set but that is only in testing phase)

**Screenshots**
CroBot is not upgraded, where as CroBot Testing is
![image](https://github.com/Androz2091/discord-player/assets/10664890/98e7302f-c0be-4f3b-a61b-332ceaf54f28)

**Please complete the following information:**
 - Node Version: v19.6.0
 - Discord Player Version: 6.4.0 (extractor version is 4.3.0)
 - Discord.js Version: 14.11.0

**Comment by retrouser955** [comment]
Having the same issue.

**Comment by skdhg** [comment]
should be fixed in https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.5.0
