### ISSUE TITLE
Spotify playlist thumbnail error

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1744]
**Describe the bug**
When playing a spotify playlist and displaying the currentTrack's thumbnail it always seems to return the default spotify thumbnail in the newest update whereas in the old it returned the proper one.

**To Reproduce**
1. Play a playlist
2. Run a command to show the current track's thumbnail

**Expected behavior**
It shows the proper thumbnail

**Screenshots**
CroBot is not upgraded, where as CroBot Testing is
![image](https://github.com/Androz2091/discord-player/assets/10664890/bbb1e6aa-e709-4967-a5e3-f6433dc70ab5)

**Please complete the following information:**
 - Node Version: v19.6.0
 - Discord Player Version: 6.4.0 (extractor version is 4.3.0)
 - Discord.js Version: 14.11.0

**Comment by skdhg** [comment]
should be fixed in https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.5.0
