### ISSUE TITLE
Feature: event - channelPopulated

### ISSUE THREAD

**Issue by Mirasaki** [Androz2091/discord-player#1746]
**Describe the feature you would like**
Loving the `channelEmpty` event. Can we get a `channelPopulated` event as well? (I'm the worst at naming variables so don't listen to me lmao)

The use case is being able to pause when empty, and resume when populated again - so we can save bandwidth in 24/7 autoplay setups

**Expected behavior**
 ```js
  player.events.on('emptyChannel', (queue) => {
    // player#pause
  });

  player.events.on('channelPopulated', (queue) => {
    // player#resume
  });
 ```

**Screenshots**

**Additional context**

**Comment by Crocross** [comment]
Just putting this out there but maybe this could also be a nodeOptions similar to `leaveOnEmpty` or `leaveOnEnd` called `pauseOnEmpty` ?
That being said, the event may have additional uses so this is just an alternative

**Comment by skdhg** [comment]
This feature is now available in `discord-player@dev`, please report any issues

**Comment by skdhg** [comment]
released
