### ISSUE TITLE
Inconsistent decimal precision when changing volume

### ISSUE THREAD

**Issue by Olebeh** [Androz2091/discord-player#1747]
**Describe the bug**
When you change the volume of the player (in my case increase by 10), the volume installed volume is a float number, though it shouldn't be. In my case, I had 100 as an initial volume, increased it by 10, and it became 110.000000001 instead of just 110

**To Reproduce**
1. Change the volume of the player using `queue.node.setVolume(queue.node.volume + 10)`
2. Log the new volume
3. Become shocked

**Expected behavior**
Volume should be 110 instead of 110.000000001

**Please complete the following information:**
 - Node Version: 18.16.0
 - Discord Player Version: 6.5.0
 - Discord.js Version: 14.11.0

**Additional context**
None

**Comment by skdhg** [comment]
This feature is now available in `discord-player@dev`, please report any issues

**Comment by skdhg** [comment]
released
