### ISSUE TITLE
Custom ffmpeg parameters

### ISSUE THREAD

**Issue by ThatGuyJacobee** [Androz2091/discord-player#1750]
**Describe the feature you would like**
It would be fantastic if there was support for custom ffmpeg parameters, because I would like to set a specific amount of threads from the CPU to use on the music functions alongside some other parameters that are typically available.

**Expected behavior**
Firstly, allow custom parameters to be set somewhere or passed through to the player instance. Next, when a song begins playing and ffmpeg is invoked, run the custom parameters that have been set.

**Screenshots**
Not applicable.

**Additional context**
In my specific case, I would like to use the `-threads [Amount]` ffmpeg parameter to limit the amount of CPU threads that ffmpeg can use during processing of the audio stream.

Many thanks for reading this and continually working on this project, much appreciated ❤️

**Comment by skdhg** [comment]
I've included the following method to supply input args for ffmpeg. This will be available in the next version.

```js
queue.filters.ffmpeg.setInputArgs(['-threads', '[Amount]']);
```

**Comment by ThatGuyJacobee** [comment]
That is fantastic, thank you very much! ❤️

**Comment by skdhg** [comment]
released
