### ISSUE TITLE
Redesign the website

### ISSUE THREAD

**Issue by twlite** [Androz2091/discord-player#1751]
Redesign the Documentation website and include more features in it.

**Comment by L0SER8228** [comment]
Please do it, discordjs style would be good. Where you can click on a item and it'll show all the property of that item. 
Like if I search <GuildQueue> it's showing all the property and method. When I scroll down to queue.currentTrack it's showing the return type as Track, but I can't see what's the structure of a track is. I've to search for <Track> class again in the website.

**Comment by skdhg** [comment]
> Please do it, discordjs style would be good. Where you can click on a item and it'll show all the property of that item. Like if I search it's showing all the property and method. When I scroll down to queue.currentTrack it's showing the return type as Track, but I can't see what's the structure of a track is. I've to search for class again in the website.

My current plan is to include `API Reference` and `Documentation` section

`Documentation` will be written as a guide, meaning each and every process is explained manually.
`API Reference` on the other hand, uses auto generated docs content from typedoc to reflect api docs.

If you have any suggestions for the website, feel free to leave it here.
