### ISSUE TITLE
remove(track)

### ISSUE THREAD

**Issue by chimnayajith** [Androz2091/discord-player#1758]
**Describe the bug**
remove(track) removes all occurrences of the track , because its filtering according to the track.id.

https://github.com/Androz2091/discord-player/blob/2d8d90174405be51432dfd89ddda61a939dda161/packages/discord-player/src/manager/GuildQueuePlayerNode.ts#L282

**Expected behavior**
It should be removing only the position specified. if i'm right.

**Please complete the following information:**
 - Node Version: 16.14.0
 - Discord Player Version: 6.6.0
 - Discord.js Version: 14.11.0

**Comment by skdhg** [comment]
fixed in https://github.com/Androz2091/discord-player/commit/4db51b9275dea7eaae2f4d6e9baabc28e95056a2, currently unreleased.

**Comment by skdhg** [comment]
released
