### ISSUE TITLE
[ Bug (possibly) ] YouTube video links work, but anything else doesn't

### ISSUE THREAD

**Issue by ThaddeusKKR** [Androz2091/discord-player#176]
YouTube video links work, but queries, YouTube playlist links, and Spotify links do not work.

Play:
```
client.player.play(message, args.join(' '))
```
I have all the events set up correctly (i think - and there weren't any errors from that)

No error message was shown in the console.

`discord-player` version:
```json
"discord-player": "^3.0.3"
```

**Comment by ThaddeusKKR** [comment]
I think it's possible that the promise is never resolved for some reason

**Comment by ThaddeusKKR** [comment]
Nevermind, I've figured out the issue.

**Comment by Androz2091** [comment]
@ThaddeusKKR what was the problem?
