### ISSUE TITLE
Add nodeOption pauseOnEmpty

### ISSUE THREAD

**Issue by Crocross** [Androz2091/discord-player#1767]
**Describe the feature you would like**
The idea would be a nodeOption called `pauseOnEmpty` similar to `leaveOnEmpty` and `leaveOnEnd` which would pause the audio playback if the channel becomes empty (aside from the bot).

**Expected behavior**
If the channel empties while someone is listening to the bot (maybe a slight dc or has to quickly hop channels) then the bot pauses itself. If someone rejoins the channel it'll resume playback. 

I'd also want this option to still respect `leaveOnEmpty` so that if the channel is empty for the length of the `leaveOnEmptyCooldown` the bot would still DC.

**Comment by skdhg** [comment]
https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.6.2
