### ISSUE TITLE
Player events not firing

### ISSUE THREAD

**Issue by Pdani001** [Androz2091/discord-player#1781]
**Describe the bug**
Since version 6.6.0 the 'disconnect' and 'emptyQueue' (and probably more, I only checked these two) events do not get fired.

**To Reproduce**
1. Set the discord-player version to 6.6.0 or later
2. Try listening to the 'disconnect' or 'emptyQueue' event

**Expected behavior**
The events firing

**Please complete the following information:**
 - Node Version: 19.9.0
 - Discord Player Version: 6.6.x
 - Discord.js Version: 14.11.0

**Comment by skdhg** [comment]
This issue has been fixed but is not released yet #1775

**Comment by skdhg** [comment]
https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.6.2
