### ISSUE TITLE
Bot joining voice channel then leaving instantly (Hosting on Heroku)

### ISSUE THREAD

**Issue by Loadren** [Androz2091/discord-player#1782]
**Describe the bug**
When I try to use my /play command, the bot connects, say the Track has been added to the queue, triggers "playerStart" then "emptyQueue" instantaneously before leaving the channel. There are no error logs, and I even have a try/catch around player.play, but nothing gets caught. It only happens when I push the bot to a platform, locally, everything works just fine.

**To Reproduce**
Host the bot on Heroku.
Use /play on any streamable music.

**Expected behavior**
It should not skip every song.

**Screenshots**
Every message happens in a 3 seconds time frame.
![DiscordPTB_TJtlCiz4hx](https://github.com/Androz2091/discord-player/assets/23261689/cc8c268b-1e67-4bd5-bdc8-d2eb78659928)

**Please complete the following information:**
 - Node Version: 16.13.1
 - Discord Player Version: 6.6.1
 - Discord.js Version: 14.11.0

**Additional context**

**Comment by skdhg** [comment]
Hello, could you check https://github.com/Androz2091/discord-player/issues/1639
