### ISSUE TITLE
Expose autoplay selection api

### ISSUE THREAD

**Issue by skdhg** [Androz2091/discord-player#1783]
Currently discord-player self picks random track from the related tracks list using private method which may not be ideal for most of the users. 

https://github.com/Androz2091/discord-player/blob/c5b52c36f3b216e42a9665b0a74bf8a014305286/packages/discord-player/src/manager/GuildQueue.ts#L988

It would be nice to expose autoplay api and allow users to handle tracks selection. This could be done with similar approach to `willPlayTrack` event:

1. Retrive related tracks list
2. Emit `willAutoPlay` event, allowing the developer to manipulate the config
3. Once done, the developer shall invoke `done()` function passed to that event (unless it is invoked, discord-player shall pause the execution)
4. The step `3` shall be skipped and discord-player shall switch to default behavior if there is no event listener registered for `willAutoPlay` event

#### Example usage

```js
player.events.on('willAutoPlay', async (queue, tracks, done) => {
    // do something here
    const selectedTrack = ...

    return done(selectedTrack || null); // select a track
})
```

**Comment by l3ktu** [comment]
**+1**

**Comment by skdhg** [comment]
https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.6.2
