### ISSUE TITLE
Copying spotify links from spotify not working

### ISSUE THREAD

**Issue by ddemile** [Androz2091/discord-player#1785]
**Describe the bug**
When I copy the link of a Spotfy sound using the desktop app or in the web browser, discord-player is unable to find the sound,
i found that when i remove `intl-fr` from the track url it's working perfectly fine, i imagine it's because my app is in french

**Screenshots**
![image](https://github.com/Androz2091/discord-player/assets/104416229/5b2c2257-cc4f-4408-bbbf-2d83addc3a9d)

**Please complete the following information:**
 - Node Version: v18.12.1
 - Discord Player Version: 6.6.1
 - Discord.js Version: 14.9.0

**Comment by L0SER8228** [comment]
I think, updating the RegEx will fix this

**Comment by joaokristani** [comment]
i just did it
```
       const song23 = inter.options.getString('musica');
        const song = song23.replace(/\/intl-fr/, "");
```

**Comment by skdhg** [comment]
https://github.com/Androz2091/discord-player/releases/tag/discord-player%406.6.2
