### ISSUE TITLE
YT Lists are considered as only one video

### ISSUE THREAD

**Issue by Loadren** [Androz2091/discord-player#1787]
**Describe the bug**
When linking a YT List, the bot isn't picking up the list at all and just adding to queue the first track. When forcing the searchEngine to `QueryType.YOUTUBE_PLAYLIST`, the search result object returns this kind of data :
```js
{
  _data: {
    query: 'https://www.youtube.com/watch?v=i1qjKo6Ts60&list=PL1ij2T_0HM3TnXecXuyqMgYUB5sHyY1ri',
    queryType: 'youtubePlaylist',
    playlist: null,
    tracks: [ [Track] ],
    extractor: YoutubeExtractor {
      context: [ExtractorExecutionContext],
      options: {},
      createBridgeQuery: [Function: createBridgeQuery],
      _stream: [AsyncFunction: _stream],
      _ytLibName: 'play-dl'
    },
    requestedBy: User {
      ...
    }
  }
}
```

**To Reproduce**
Try to use `player.search` or `player.play` with a list like this one : https://www.youtube.com/watch?v=i1qjKo6Ts60&list=PL1ij2T_0HM3TnXecXuyqMgYUB5sHyY1ri
It plays only the first song.

**Expected behavior**
It should consider lists as Playlists, and add all the songs to the queue instead of only the first one.

**Please complete the following information:**
 - Node Version: 18.14.2
 - Discord Player Version: 6.6.2
 - Discord.js Version: 14.11.0

**Comment by skdhg** [comment]
@Loadren are you able to load it by modifying the query? Here's a code to transform the query to youtube playlist query.

```js
const updatedQuery=query.includes('youtube.com')&&query.includes('&list=')?(()=>{let a;a=query.split('&list=')[1]?.split('&')?.[0];if(!a)return query;return `https://www.youtube.com/playlist?list=${a}`;})():query;
```

**Comment by Loadren** [comment]
It works like a charm now. All the songs in playlist are added into the queue. Thanks a lot!

**Comment by skdhg** [comment]
Please keep this open as this is a bug in discord-player query validator
