### ISSUE TITLE
Make youtube bridge work only when YoutubeExtractor is registered

### ISSUE THREAD

**Issue by twlite** [Androz2091/discord-player#1789]
SoundCloud bridge only works when SoundCloudExtractor is registered but it is not the case for YouTube bridge.

YouTube bridge should only work when there is youtube extractor available. If there is no youtube extractor, an extractor may fall back to loading soundcloud if it is available. If both of them are not available, it should throw an error.

This should not be considered as a breaking change, and it would encourage people to use what they prefer.

For compatibility reasons, it should first load youtube bridge and then fall back to soundcloud unless explicitly specified.

I do not expect any code changes after this update on the users side.

This would also make it easier to not include youtube playback on one's bot if needed, which is already possible though. https://discord-player.js.org/guide/faq/disable-youtube

**Comment by L0SER8228** [comment]
Can we add a 3rd extract if YouTube and SoundCloud both failed? Or specify which extractor to use first ?

**Comment by retrouser955** [comment]
> Can we add a 3rd extract if YouTube and SoundCloud both failed? Or specify which extractor to use first ?

Currently, the only stream providers we know of are YouTube and SoundCloud. Feel free to list the one you know.

**Comment by LakhindarPal** [comment]
I made a hungama-music downloader. [Check it](https://github.com/LakhindarPal/hungama-music). Though there's some bug, but the APIs are working. You can make a hungama-music extractor.

Jiosaavn also support stream. There's not any npm package, but there's some api scrapers. Hope you will make a extractor for JioSaavn too.

**Comment by skdhg** [comment]
> I made a hungama-music downloader. [Check it](https://github.com/LakhindarPal/hungama-music). Though there's some bug, but the APIs are working. You can make a hungama-music extractor.
> 
> Jiosaavn also support stream. There's not any npm package, but there's some api scrapers. Hope you will make a extractor for JioSaavn too.

We dont have plans on introducing yet another extractor to our maintenance list at the moment. You can release your own extractor package. See https://discord-player.js.org/guide/extractors/creating-extractor for more info.
