### ISSUE TITLE
queue.tracks.size starts at 1 and counts the second track at 1 too

### ISSUE THREAD

**Issue by ImDouzix** [Androz2091/discord-player#1791]
so basically i was trying to make an if statement that checks if the que tracks size is 1, and if it is it doesnt send an embed, it works for the first track, but it also works for the SECOND track, and this is in the addTrack event, so its not when i skip, whenever i add 2 tracks, both of them count as 1 in the queue tracks size, but if there is no songs in queue, it counts the current one as 1 too, so we can differenciate between current song at next song.

**Comment by ImDouzix** [comment]
this was the code when i was checking:
player.events.on("audioTrackAdd", (queue, track) => {
    console.log(queue.tracks.size)

        const embed = new EmbedBuilder()
        .setDescription(`${emojis.check} [${track.title}](${track.url}) has been queued!`)
        .addFields(
            { name: "Duration:", value: track.duration.toString() },
            { name: "Requested By:", value: `${track.requestedBy?.tag}` },
        )
        .setThumbnail(track.thumbnail || unavailable)
        .setColor(colors.success)

        return queue.metadata.channel.send({ embeds: [embed] })

})
and i ran this:
!play [song]
!play [song]
!play [song]

and console outputed this:
1
1
2

**Comment by skdhg** [comment]
Like I explained earlier, currently playing track does not live inside the queue. This behavior is normal.
