### ISSUE TITLE
Rewrite default voice state handler

### ISSUE THREAD

**Issue by twlite** [Androz2091/discord-player#1818]
This code has not been touched for years at this point. We can do better than this. Feel free to make a pr if you are interested.

https://github.com/Androz2091/discord-player/blob/72f79921fd7c607c5514d668454381f0bfbc5584/packages/discord-player/src/DefaultVoiceStateHandler.ts#L1-L111

**Comment by nayangoyal** [comment]
Hi, @twlite can you assign this issue to me? I want to work on this issue.

**Comment by twlite** [comment]
@nayangoyal sure

**Comment by twlite** [comment]
@nayangoyal are you still on this? Otherwise I will have to do it myself.

**Comment by nayangoyal** [comment]
Yes I am still working on this issue. Due to my academic paper I stopped working on it.now my paper has been over. So, I started working on it again.
