### ISSUE TITLE
Spotify phone link and youtube playlist search box link

### ISSUE THREAD

**Issue by SlmixX** [Androz2091/discord-player#1820]
support spotify phone links like this `https://open.spotify.com/track/2SL6oP2YAEQbqsrkOzRGO4` and support youtube playlist search box links like this `https://www.youtube.com/playlist?list=PLhVQfRIFpqb0bsHButNuF3P_LLXHoqWqS`

**Comment by twlite** [comment]
# Originally reported by @mariusbegby (7marre)
> ## spotify.link urls not working
> 
> E.g. https://spotify.link/QCGEhSsnuDb which is equivalent to https://open.spotify.com/track/12GEpg2XOPyqk03JZEZnJs results in "no results found".
>
> This is because the short `spotify.link` url is a redirect, and discord-player does not follow the link.
>
> ![image](https://github.com/Androz2091/discord-player/assets/46562212/8e3af3ac-d8c4-47de-a3b4-f909a3926c77)

**Comment by twlite** [comment]
> support spotify phone links like this `https://open.spotify.com/track/2SL6oP2YAEQbqsrkOzRGO4` and support youtube playlist search box links like this `https://www.youtube.com/playlist?list=PLhVQfRIFpqb0bsHButNuF3P_LLXHoqWqS`

YouTube playlist link you provided works
![image](https://github.com/Androz2091/discord-player/assets/46562212/029dcff0-5c28-409f-82a3-1b02630bf3d1)

**Comment by SlmixX** [comment]
> > support spotify phone links like this `https://open.spotify.com/track/2SL6oP2YAEQbqsrkOzRGO4` and support youtube playlist search box links like this `https://www.youtube.com/playlist?list=PLhVQfRIFpqb0bsHButNuF3P_LLXHoqWqS`
> 
> YouTube playlist link you provided works ![image](https://user-images.githubusercontent.com/46562212/271698874-029dcff0-5c28-409f-82a3-1b02630bf3d1.png)

i'm sorry i messed up i meant the built in copy link from youtube like this `https://youtube.com/playlist?list=PLhVQfRIFpqb0bsHButNuF3P_LLXHoqWqS&si=JmfTJ5zcjV4hT2gj` 
![image](https://github.com/Androz2091/discord-player/assets/97211142/c7dc8f01-06b0-47c6-b70b-6cc06ff0d037)

**Comment by twlite** [comment]
> i'm sorry i messed up i meant the built in copy link from youtube like this `https://youtube.com/playlist?list=PLhVQfRIFpqb0bsHButNuF3P_LLXHoqWqS&si=JmfTJ5zcjV4hT2gj`

This works
![image](https://github.com/Androz2091/discord-player/assets/46562212/1882bfc4-9966-4fa0-bba3-e1fceaaab062)

I am currently working on `spotify.link` query support.
