### ISSUE TITLE
Optimize playlists loading

### ISSUE THREAD

**Issue by twlite** [Androz2091/discord-player#1821]
Consider a scenario in which a playlist encompasses a multitude of songs. Loading the entire playlist into a queue might not be a prudent choice for several compelling reasons:

1. **Potential Memory Leak**: Loading an extensive playlist could lead to a memory leak due to the sheer volume of data involved.
2. **Excessive API Calls**: Fetching all songs at once might result in an excessive number of API calls, causing performance issues and potential rate limiting by the API provider.
3. **Bulky Queue**: It can result in an unwieldy and overly large queue, which may not be manageable or efficient for the implementor.

To address these concerns and provide more control over the loading process, I propose the implementation of a feature that allows limiting the number of items loaded from a playlist. Currently, there's no straightforward way to achieve this, and implementors required to retrieve the entire playlist and then manually trim it if necessary.

Based on my performance tests done with @mariusbegby, loading a playlist consisting of approximately 16,000 tracks did not significantly impact the user experience (for example, there was not a lag in player). However, it did noticeably affect memory consumption.

Discord Player typically implements an in-memory cache to reduce network calls for tracks that might be loaded again in the future. In other words, if link `x` is used for the first time, it is actually fetched and stored in a cache. When another request is made with a matching link to `x`, the result is fetched from the cache instead of making another api call, which results in faster response as well as somewhat lower chance of getting rate limited. This cache is temporary and each item in it has a lifespan of approximately 5 hours. Loading such large playlists can strain the bot's overall performance.

For those who wish to optimize memory usage and enhance performance, I suggest the following implementation:

1. Initiate a call to `player.search(query)`.
2. `player.search()` will intelligently determine which extractor to employ and execute it.
3. The extractor will first load metadata, including the expected total number of items in the playlist, and then promptly return a preliminary response to me. At this stage, implementor should have the option to set a limit on the number of tracks to be loaded into the queue or even cancel the operation altogether.

By adopting this approach, implementors can have finer control over playlist loading, reduce memory consumption, and enhance overall performance while ensuring a smooth and responsive user experience.

**Comment by mariusbegby** [comment]
Would it be possible to add pagination along with limit?

That way we could set a limit, e.g. 100 then load next 100 based on user input through button or similar.

**Comment by twlite** [comment]
That is a good idea. Playlists are already fetched in a chunk of maximum 100 tracks at a time. We can possibly integrate this with Playlist object for the implementor to handle.

**Comment by twlite** [comment]
This is a smart idea but it would result in a breaking change, as it affects `queue.tracks`.
