### ISSUE TITLE
Playing random track instead of the queued one.

### ISSUE THREAD

**Issue by brunodecided** [Androz2091/discord-player#1845]
**Describe the bug**
Playing random track instead of the queued one when excluding youtube ectractor.
I found it in only 2 spotify tracks.

**To Reproduce**
1. Exclude the youtube extractor
```js
await player.extractors.loadDefault(ext => ext != 'YouTubeExtractor');
```
2. Queue any of the track listed below
 - https://open.spotify.com/track/10Ve2mQ4hTWtgqR6MbmJyf?si=6529d39b1c6a4846
 - https://open.spotify.com/track/0C540XHxgxKAD7CoFJ23Uu?si=8f578fd6ec8d4b6c
3. Listen in spotify and by using the bot. You can see the difference..

**Expected behavior**
Playing the right track.. There is no problem when YoutubeExtractor included

**Version:**
 - Node Version: 18.18.2
 - Discord Player Version: 6.6.4
 - Discord.js Version: 14.13.0

**Comment by twlite** [comment]
This is because your bot is using `SoundCloud Bridging` at this point, which has less accuracy. Currently this is not fixable, I will get back to this in the future if I find something about this.
