### ISSUE TITLE
The queue Repeat Mode doesnt work

### ISSUE THREAD

**Issue by ItzHenry1** [Androz2091/discord-player#1857]
**Describe the bug**
Basically when you set the RepeatMode to `Queue` doesnt loop the queue, but instead it loops the last queue song of the queue when it's reached.

**To Reproduce**
1. Play anything like a playlist but the queue needs to have more than 1 song
2. Set the repeatMode to queue.
3. Wait until you reach the end of the queue.
4. The queue doesnt repeat but instead loops the last queue song.

**Expected behavior**
To loop the queue and go again to the first queue song.

**Screenshots**
![image](https://github.com/Androz2091/discord-player/assets/100813971/58d055f1-65ef-4913-b643-ca5fac844141)

(I skipped to **I got no time** song, and when skipped it again, it didnt go **NIGHT DANCER** song but looped the **I got no time** song.

**Please complete the following information:**
 - Node Version: 20.8.1
 - Discord Player Version: 6.6.6
 - Discord.js Version: 14.13.0

**Comment by ItzHenry1** [comment]
Btw this happens to me in my bot and it also happen in **discord-player.fr** bot.

**Comment by Rizina** [comment]
Hi, I would like to work on this issue
