### ISSUE TITLE
play a song directly without collectors

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-player#186]
how to make the song play automatically by name, without having to choose in the text channel which song you want to hear?

i'm trying to learn and i can't i'm using the example bot made by Music-bot by ZerioDev

when I use the command !play name of the song, a top 19 songs appear for me to choose which one I want to listen to, I want it to work the way, !play name of the song and the bot is already playing the song

**Comment by Androz2091** [comment]
This is not currently possible, but this could be added 👍

**Comment by Akurejs** [comment]
> No momento, isso não é possível, mas pode ser adicionado 👍

Thank you very much Androz2091, I didn't know Discord-Player yet and it is very good, I will wait for this update!

**Comment by IdkWhosThis** [comment]
@Androz2091 can I ask when this would be added? Because this is something that I really need to have.
