### ISSUE TITLE
Nothing happens when I use client.player.play() for version 3.0.3

### ISSUE THREAD

**Issue by jamesthejames123** [Androz2091/discord-player#187]
```js
module.exports.run = async (client, message, args, Discord) => {
    await client.player.play(message, "coffin dance")
}

module.exports.config = {
    command: "play",
}
```
This is my code, when I type: ;play coffin dance nothing happens, the bot doesn't join the voice chat. No errors

**Comment by hands8142** [comment]
Did you add the searchResults event? Otherwise, it only works with YouTube url.

**Comment by geraldlol10** [comment]
Enable intents... that worked for me

**Comment by Androz2091** [comment]
> Enable intents... that worked for me

Pretty weird, intents shouldn't be related with that command...

**Comment by jamesthejames123** [comment]
> Did you add the searchResults event? Otherwise, it only works with YouTube url.

This worked thank you @Androz2091 can you add that event to the example on the readme file? because i only added the trackstart
