### ISSUE TITLE
Fin de musique

### ISSUE THREAD

**Issue by ViTraX** [Androz2091/discord-player#188]
Salut, j'ai fait un Interval pour edit mon now playing mais le problème c'est que je trouve pas comment voir si la musique et a la fin donc mon clearInterval fonctionne pas qui serais comme faire ?

**Comment by Androz2091** [comment]
Salut, tu peux écouter l'évènement `trackStart`, qui marque le début d'une nouvelle chanson (et la fin de la précédente).

**Comment by ViTraX** [comment]
Je peux pas trackEnd? pour exemple clearInterval(trackEnd) ?

**Comment by ViTraX** [comment]
Mon code et celui si

**

exports.run = async (client, message) => {

    if (!message.member.voice.channel) return message.channel.send(`${client.emotes.error} - Vous n'êtes pas dans un canal vocal !`);

    if (!client.player.getQueue(message)) return message.channel.send(`${client.emotes.error} - Aucune musique en cours de lecture !`);

    const track = await client.player.nowPlaying(message);
    const filters = [];

    Object.keys(client.player.getQueue(message).filters).forEach((filterName) => {
        if (client.player.getQueue(message).filters[filterName]) filters.push(filterName);
    });

    var my_interval;

    message.channel.send({
        embed: {
            color: 'RED',
            author: { name: track.title },
            footer: { text: 'Bot créer par Sushi !' },
            fields: [
                { name: 'Channel', value: track.author, inline: true },
                { name: 'Demandé par', value: track.requestedBy.username, inline: true },
                { name: 'De la playlist', value: track.fromPlaylist ? 'Oui' : 'Non', inline: true },

                { name: 'Vues', value: track.views, inline: true },
                { name: 'Temps', value: track.duration, inline: true },
                { name: 'Filtre activer', value: filters.length, inline: true },

                { name: 'Bar de progression', value: client.player.createProgressBar(message, { timecodes: true }), inline: true }
            ],
            //thumbnail: { url: track.thumbnail },
            timestamp: new Date(),
        },
    }).then((msg) => {

        my_interval = setInterval(() => {
            msg.edit({
                embed: {
                    color: 'RED',
                    author: { name: track.title },
                    footer: { text: 'Bot créer par Sushi !' },
                    fields: [
                        { name: 'Channel', value: track.author, inline: true },
                        { name: 'Demandé par', value: track.requestedBy.username, inline: true },
                        { name: 'De la playlist', value: track.fromPlaylist ? 'Oui' : 'Non', inline: true },
        
                        { name: 'Vues', value: track.views, inline: true },
                        { name: 'Temps', value: track.duration, inline: true },
                        { name: 'Filtre activer', value: filters.length, inline: true },
        
                        { name: 'Bar de progression', value: client.player.createProgressBar(message, { timecodes: true }), inline: true }
                    ],
                    //thumbnail: { url: track.thumbnail },
                    timestamp: new Date(),
                },
            })
        }, 2000)
        clearInterval()
    },
 
)}
**

**Comment by Androz2091** [comment]
let intervalID;
    let songName = track.title;
	let editFunction = () => {
       if (songName !== client.player.getQueue(message).tracks[0].title) return clearInterval(intervalID);
 		msg.edit({
            embed: {
                color: 'RED',
                author: { name: track.title },
                footer: { text: 'Bot créer par Sushi !' },
                fields: [
                    { name: 'Channel', value: track.author, inline: true },
                    { name: 'Demandé par', value: track.requestedBy.username, inline: true },
                    { name: 'De la playlist', value: track.fromPlaylist ? 'Oui' : 'Non', inline: true },
    
                    { name: 'Vues', value: track.views, inline: true },
                    { name: 'Temps', value: track.duration, inline: true },
                    { name: 'Filtre activer', value: filters.length, inline: true },
    
                    { name: 'Bar de progression', value: client.player.createProgressBar(message, { timecodes: true }), inline: true }
                ],
                //thumbnail: { url: track.thumbnail },
                timestamp: new Date(),
            },
        })
    }
	intervalID = setInterval(() => editFunction(), 2000);

**Comment by Androz2091** [comment]
tu pourrais faire un truc un peu comme ça. On peut faire mieux mais ça devrait marcher sans aucun problème

**Comment by ViTraX** [comment]
TypeError: Cannot read property 'tracks' of undefined

Pour le .tracks[0].title

**Comment by ViTraX** [comment]
J'ai même testé avec .track mais je savais que sa n'allais pas fonctionner

**Comment by Androz2091** [comment]
let intervalID;
let songName = track.title;
let editFunction = () => {
   if (!client.player.getQueue(message)) return;
   if (songName !== client.player.getQueue(message).tracks[0].title) return clearInterval(intervalID);
	msg.edit({
        embed: {
            color: 'RED',
            author: { name: track.title },
            footer: { text: 'Bot créer par Sushi !' },
            fields: [
                { name: 'Channel', value: track.author, inline: true },
                { name: 'Demandé par', value: track.requestedBy.username, inline: true },
                { name: 'De la playlist', value: track.fromPlaylist ? 'Oui' : 'Non', inline: true },

                { name: 'Vues', value: track.views, inline: true },
                { name: 'Temps', value: track.duration, inline: true },
                { name: 'Filtre activer', value: filters.length, inline: true },

                { name: 'Bar de progression', value: client.player.createProgressBar(message, { timecodes: true }), inline: true }
            ],
            //thumbnail: { url: track.thumbnail },
            timestamp: new Date(),
        },
    })
}
intervalID = setInterval(() => editFunction(), 2000);

**Comment by Androz2091** [comment]
Tu peux essayer ça, sinon viens sur le discord pour plus d'aide https://androz2091.fr/discord

**Comment by ViTraX** [comment]
Sayez merci ^^ je suis présent sur le discord mais il y a pas beaucoup de personne qui répond avec un temps records merci de ton aide sa fait plaisir ^^
