### ISSUE TITLE
SocketError: other side closed

### ISSUE THREAD

**Issue by skillzl** [Androz2091/discord-player#1883]
**Describe the bug**
Application works without any error, plays music but the thing is that the music will not end and just "crash". After that the play command will not work again.

**To Reproduce**
idk what to reproduce here

**Expected behavior**
idk, work?

**Screenshots**
https://imgur.com/E84H6rJ

**Please complete the following information:**
 - Node Version: node.js: ^v18.16.0
 - Discord Player Version: ^6.6.6
 - Discord.js Version: discord.js: ^14.14.1

**Additional context**
the project Im running is open-source : https://github.com/skillzl/eres

**Comment by twlite** [comment]
@skillzl hi, could you try switching `youtube-ext` (https://github.com/skillzl/eres/blob/d0671cc14c8483a247389eb9de94b6cb623de224/package.json#L55) with an alternative lib?

**Comment by skillzl** [comment]
@twlite thanks for advice, using `play-dl` fixed the issue
