### ISSUE TITLE
Spotify & Apple Music don't work ERR_NO_RESULT: [ERR_NO_RESULT] No results found for "the music" (Extractor: com.discord-player.spotifyextractor)

### ISSUE THREAD

**Issue by loulou133** [Androz2091/discord-player#1888]
Hello, from one day to the next, when I try to load a playlist or search for a song, I get an error: 

No results found for "https://open.spotify.com/playlist/37i9dQZF1DZ06evO39vOFi" (Extractor: com.discord-player.spotifyextractor)

I have @discord-player/extractor

Whereas before I had nothing, and i got the same error for Apple Music : 
ERR_NO_RESULT: [ERR_NO_RESULT] No results found for "L'hymme de nos campagnes" (Extractor: com.discord-player.applemusicextractor)

Any solutions? Thanks
![image](https://github.com/Androz2091/discord-player/assets/72643424/6c9072aa-9d12-4946-a15e-0f64dd6ded28)

**Comment by JayXTQ** [comment]
I think it would be great if you shared your code

**Comment by twlite** [comment]
reopen if it happened again
