### ISSUE TITLE
i have this bug when my bot start playing a song

### ISSUE THREAD

**Issue by zrSadek** [Androz2091/discord-player#1889]
![image](https://github.com/Androz2091/discord-player/assets/114314659/23b97ee7-d92b-45e0-a0a0-0ea1f923a809)

const channel = message.member.voice.channel;

        const { track } = await client.player.play(channel, args.join(" "), {
            nodeOptions: {
                // nodeOptions are the options for guild node (aka your queue in simple word)
                metadata: message // we can access this metadata object using queue.metadata later on
            }
        });
        return message.reply(`**${track.title}** enqueued!`);

**Comment by jermorg** [comment]
I have the same problem, did you manage to solve it?

**Comment by needhamgary** [comment]
@jermorg @zrSadek out of curiosity,  do you guys bots have guild # permissions (CONNECT and SPEAK)? If so, please ensure the bot has access to the channel that the song requester is connected to. If this doesn't help, try reinviting the bot to the server with default permissions of at least the 2 I mentioned and SEND_MESSAGES. Hope this helps

**Comment by twlite** [comment]
Use something else than youtube-ext

**Comment by jermorg** [comment]
@zrSadek
 I found out what the problem is, for some reason `YouTubeExtractor` and `SpotifyExtractor` give this error, I just disabled them like this:
```JavaScript
await player.extractors.loadDefault((ext) => ext !== 'YouTubeExtractor' && ext !== 'SpotifyExtractor');
```
and that's it.

**Comment by zrSadek** [comment]
okay ty everyone
