### ISSUE TITLE
 Cannot play a playlist from youtube

### ISSUE THREAD

**Issue by alexni15** [Androz2091/discord-player#189]
Hi, when I do  ```play <youtube plalist url>``` no music is playing and the bot tells me ```No results found on youtube``` I have no error in the logs

    discordjs/opus: 0.3.3
    discord-player: 3.0.3
    discord.js: 12.5.1

**Comment by hands8142** [comment]
Can you show me the error log?

**Comment by iSamuelCO** [comment]
I also have the same problem, and it doesn't log any errors.

**Comment by hands8142** [comment]
I think it's about youtub-sr.

**Comment by Victorthemachine** [comment]
I am having issues with it as well, it was working but stopped yesterday again. However, there were issues before as well for me.

**Comment by hands8142** [comment]
> I am having issues with it as well, it was working but stopped yesterday again. However, there were issues before as well for me.

Please refer to #184.

**Comment by Victorthemachine** [comment]
I updated the youtube-sr and ytpl per the pull request but still the same issues. If I send a playlist link it can't play it, and if I send a song in a playlist it plays the song and doesn't add the playlist.

**Comment by Guizzoni** [comment]
@Victorthemachine try appliying the PR to your code, I didn't just update the dependencies, I've changed the code aswell.

**Comment by Victorthemachine** [comment]
> @Victorthemachine try appliying the PR to your code, I didn't just update the dependencies, I've changed the code aswell.

Thanks so much. I am new to github so I didn't realize that ^^" It fixed it and works well now, thanks!

**Comment by alexni15** [comment]
It works for me too I say thank you for your help
