### ISSUE TITLE
Impossible de télécharger le module discord-player.

### ISSUE THREAD

**Issue by Pronicio** [Androz2091/discord-player#19]
Je n’arrive pas à télécharger le module npm :
npm i discord-player

Voici l’erreur : 
![CC7C1969-89F5-4C5D-AF79-AA88B21E3213](https://user-images.githubusercontent.com/52421988/80621700-f40c9d80-8a47-11ea-9a6d-dcaf99bfcc79.jpeg)

**Comment by Androz2091** [comment]
Bonjour, cette erreur apparaît car vous essayez de télécharger le module dans un dossier lui aussi appelé `discord-player`. Donnez lui un autre nom comme `music-bot` par exemple, et cela devrez marcher.

**Comment by Pronicio** [comment]
Bonjour, j’ai essayé de modifier le nom mais ça ne marche toujours pas.
![88C71403-C40D-4B79-8160-E75AD04BA482](https://user-images.githubusercontent.com/52421988/80685024-ddf1f200-8ac6-11ea-81ec-71694a1b1af4.jpeg)

**Comment by Androz2091** [comment]
Pouvez-vous ouvrir le fichier `package.json` et remplacer la valeur "name" qui doit être actuellement "discord-player" par "music-bot"?

**Comment by Pronicio** [comment]
Merci beaucoup maintenant ça marche ! 👌
