### ISSUE TITLE
Playing External DNS links not working on Linux

### ISSUE THREAD

**Issue by dfxphoenix** [Androz2091/discord-player#1900]
**Describe the bug**
As the title says, if I play an external link that contains DNS (ex: https://live.example.com/live.mp3), my discord bot that uses this module connects and exits instantly. This only happens on Linux, on Windows everything works perfectly.
If I play a link that contains an IP, it also works on Linux.
**To Reproduce**
I tried to delete the cache from nodejs
I tried my discord bot on several operating systems, as I said, on Ubuntu and Fedora it doesn't work, but on Windows it works
I tried older versions of discord.js and discord-player, but it still doesn't work
I tried other Discord bots that use this module, but none of them work.

**Expected behavior**
To get an error in the console so I can figure out why it doesn't work, but I don't get any error.
**Please complete the following information:**
 - Node Version: 20.12.2
 - Discord Player Version: 6.6.8
 - Discord.js Version: 14.14.1

**Additional context**
I have to say that it was working perfectly on Linux before, but after some time it stopped working, before that I was using Ubuntu 18, and it worked perfectly, I don't know if it still works on Ubuntu 18, but on the latest versions of Fedora and Ubuntu no longer works

**Comment by dfxphoenix** [comment]
After other tests, I saw that it works on Ubuntu 20, I also test on newer versions of ubuntu (23, 24) and come back with an edit

**Comment by twlite** [comment]
Your issue might be related to https://github.com/Androz2091/discord-player/issues/1639#issuecomment-1477466885
