### ISSUE TITLE
Missing dependency on `@web-scrobbler/metadata-filter`

### ISSUE THREAD

**Issue by Sleepy4k** [Androz2091/discord-player#1912]
**Describe the bug**
On latest version (v6.6.9) there is missing dependency for module `@web-scrobbler/metadata-filter`, this problem shown only for the latest version only

**To Reproduce**
1. Create new project
1. Install discord player
2. Run the project
3. See error

**Expected behavior**
When run our project with discord player module version 6.6.9 in it, we will get error message that inform us about missing dependency for `@web-scrobbler/metadata-filter` in `discord-player`

**Screenshots**
![image](https://github.com/Androz2091/discord-player/assets/99236402/2f8e3ed6-5b9c-4827-b866-4e64c03eb664)

**Please complete the following information:**
 - Node Version: 20.11.1
 - Discord Player Version: 6.6.9
 - Discord.js Version: 14.15.3

**Additional context**
Missing dependency used at "discord-player/src/utils/Util.ts" line 19

**Comment by twlite** [comment]
This issue us fixed but hasn't been released https://github.com/Androz2091/discord-player/pull/1911
