### ISSUE TITLE
Expose the track object instead of just the raw URL in createStream()

### ISSUE THREAD

**Issue by retrouser955** [Androz2091/discord-player#1919]
**Describe the feature you would like**
Instead of `createStream(ext, url)` being, expose the actual track instead of just the URL (`createStream(track)`). This would make devx way easier.

`@discord-player/extractor`

**Comment by twlite** [comment]
Can you provide an example

**Comment by retrouser955** [comment]
> Can you provide an example

# Current
```js
player.extractors.register(SpotifyExtractor, {
  async createStream(ext, url) {
    const trackData = await ext.handle(url)
    const search = searchOnYoutube(`${trackData.author} - ${trackData.title}`)
    const streamURL = getStreamURL(search.url)
    return streamURL
  }
})
```
# Change
```js
player.extractors.register(SpotifyExtractor, {
  async createStream(ext, track) {
    const search = searchOnYoutube(`${track.author} - ${track.title}`)
    const streamURL = getStreamURL(search.url)
    return streamURL
  }
})
```

**Comment by twlite** [comment]
Ok doesn't seem complicated, lets add track as the 3rd parameter to avoid breaking changes

**Comment by retrouser955** [comment]
> Ok doesn't seem complicated, lets add track as the 3rd parameter to avoid breaking changes

Alright thanks!
