### ISSUE TITLE
player stucks randomly on queue.

### ISSUE THREAD

**Issue by kensunjaya** [Androz2091/discord-player#1920]
Since last week, player stucks randomly on any queue index. skipping the track doesn't seems to work. After a track ends, the player doesn't continue to the next track on the queue, instead it stops playing audio and stays on the voice channel with no audio. I think it might be a bug on the queue system (?)

```js
player.events.on("playerStart", async (queue, track) => {
    if (guildHandler.get(queue.guild)) {
        // last change here
        try {
            if (guildHandler.get(queue.guild).commandName === 'play' && !queue.tracks.data.length) {
                await guildHandler.get(queue.guild).followUp({embeds : [Embed.musicPlaying(track)]});
            }
            else {
                await guildHandler.get(queue.guild).channel.send({embeds : [Embed.musicPlaying(track)]});
            }
             // guildHandler.set(queue.guild, newInteraction);
        }
        catch (error) {
            console.log(error);
            return void console.log("Error on playerStart : " + error);
        }
        finally {
            console.log("playerStart initiated");
        }
    }
       
});
```
![image](https://github.com/Androz2091/discord-player/assets/93558406/c403cd2b-13bb-432b-a82c-3d1de664aab1)
playerInitiated? but the message doesn't seem to be sent on discord. And error doesn't seem to be caught.
Anyways I'm new to discord-player. Sorry for any misunderstanding.

**Comment by twlite** [comment]
how are you playing the track?

**Comment by retrouser955** [comment]
Hello @kensunjaya. Could you send your debug logs here?
```ts
player.events.on("debug", (queue, msg) => console.log(msg))
player.on('debug', (msg) => console.log(msg))
```
Also send the following
```ts
console.log(player.scanDeps())
```

**Comment by kensunjaya** [comment]
> how are you playing the track?

```js
if (interaction.commandName === "play" || interaction.commandName === "p") {
        await interaction.deferReply();
        
        const query = interaction.options.get("query").value;
        const search_engine = interaction.options.get("search_engine");

        let searchResult = await player
            .search(query, {
                requestedBy: interaction.user,
                searchEngine: search_engine ? search_engine.value : QueryType.AUTO,
            })
            .catch(() => {});

        if (!searchResult || !searchResult.tracks.length) {
            if (search_engine && search_engine.type != 3) return void interaction.followUp({ content: "No results were found!" });
            const availableEngines = [QueryType.SPOTIFY_PLAYLIST,
                QueryType.SPOTIFY_ALBUM,
                QueryType.SPOTIFY_SONG]
            if (!search_engine) {
                availableEngines.push(QueryType.YOUTUBE);
                availableEngines.push(QueryType.YOUTUBE_PLAYLIST);
                availableEngines.push(QueryType.SOUNDCLOUD);
            }
            for (let i=0;i<availableEngines.length;i++) {
                searchResult = await player
                .search(query, {
                    requestedBy: interaction.user,
                    searchEngine: availableEngines[i]
                })
                .catch(() => {});
                if (searchResult) break;
            }
            if (!searchResult || !searchResult.tracks.length) {
                return void interaction.followUp({ content: "No results were found!" });
            }
        }

        const queue = player.nodes.create(interaction.guild, {
            metadata: interaction.channel,
            leaveOnEmpty: false,
            leaveOnEnd: false,
            selfDeaf: true,
            selfMute: false,
            volume: 100,
            bufferingTimeout: 3000,
            connectionTimeout: 20000,
            voiceAutoReconnect: true,
        });
        
        try {
            if (!queue.connection) await queue.connect(interaction.member.voice.channel);
        } catch {
            void player.deleteQueue(interaction.guildId);
            return void interaction.followUp({ content: "Could not join your voice channel!" });
        }

        if (searchResult.playlist) {
            searchResult.playlist.tracks.map(track => {
                queue.addTrack(track);
                
            });
            await interaction.followUp({embeds : [Embed.addPlaylist(searchResult.playlist)]});
        }
        else {
            queue.addTrack(searchResult.tracks[0]);
        }

        if (!queue.isPlaying()) {
            await queue.node.play(queue.tracks.data[0]);
            guildHandler.set(interaction.guild, interaction);
            queue.removeTrack(queue.tracks.data[0]);
            return;
        }

        if (!searchResult.playlist) {
            await interaction.followUp(`📝 | Added **${searchResult.tracks[0].description}** to queue list`);
        }
    } 
```

Here are the full code: https://github.com/kensunjaya/discord-bot/blob/main/src/index.js

**Comment by kensunjaya** [comment]
> Hello @kensunjaya. Could you send your debug logs here?
> 
> ```ts
> player.events.on("debug", (queue, msg) => console.log(msg))
> player.on('debug', (msg) => console.log(msg))
> ```
> 
> Also send the following
> 
> ```ts
> console.log(player.scanDeps())
> ```

Sure
[player scandeps.txt](https://github.com/user-attachments/files/16141098/player.scandeps.txt)
[debug.txt](https://github.com/user-attachments/files/16141099/debug.txt)

**Comment by twlite** [comment]
your code is prone to race conditions, please follow this pattern.

```ts
const queue = player.nodes.create(...);
const result = await player.search(...);

// acquire task entry
const entry = queue.tasksQueue.acquire();

// wait for previous task to be released and our task to be resolved
await entry.getTask();

// add track(s) (this will add playlist or single track from the result)
queue.addTrack(result);

try {
    // if player node was not previously playing, play a song
    if (!queue.isPlaying()) await queue.node.play();
} finally {
    // release the task we acquired to let other tasks to be executed
    // make sure you are releasing your entry, otherwise your bot won't
    // accept new play requests
    queue.tasksQueue.release();
}
```

**Comment by twlite** [comment]
@kensunjaya 

`from {"status":"playing","missedFrames":0,"playbackDuration":152540,"resource":true,"stepTimeout":false}`

after analyzing your log, it seems your bot is indeed playing the track. Do you have your bot muted or something?

**Comment by twlite** [comment]
```
Preparing AudioResource...
Initializing audio player...
state change:
from {"status":"idle","resource":false,"stepTimeout":false}
to {"status":"buffering","resource":true,"stepTimeout":false}
Dispatching audio...
[NW] [WS] >> {"op":3,"d":1720516274223}
[NW] [WS] << {"op":6,"d":1720516274223}
[NW] [WS] >> {"op":3,"d":1720516287977}
[NW] [WS] << {"op":6,"d":1720516287977}
[Lag Monitor] Event loop latency: 15.844399999827147ms
[NW] [WS] >> {"op":3,"d":1720516301734}
[NW] [WS] << {"op":6,"d":1720516301734}
[NW] [WS] >> {"op":3,"d":1720516315497}
[NW] [WS] << {"op":6,"d":1720516315497}
[Lag Monitor] Event loop latency: 15.849799999967217ms
[NW] [WS] >> {"op":3,"d":1720516329256}
[NW] [WS] << {"op":6,"d":1720516329256}
[NW] [WS] >> {"op":3,"d":1720516343013}
[NW] [WS] << {"op":6,"d":1720516343013}
[Lag Monitor] Event loop latency: 16.007000000216067ms
[NW] [WS] >> {"op":3,"d":1720516356777}
[NW] [WS] << {"op":6,"d":1720516356777}
[NW] [WS] >> {"op":3,"d":1720516370531}
[NW] [WS] << {"op":6,"d":1720516370531}
[NW] [WS] >> {"op":3,"d":1720516384289}
[NW] [WS] << {"op":6,"d":1720516384289}
[Lag Monitor] Event loop latency: 15.714800000190735ms
[NW] [WS] >> {"op":3,"d":1720516398047}
[NW] [WS] << {"op":6,"d":1720516398047}
[NW] [WS] >> {"op":3,"d":1720516411810}
[NW] [WS] << {"op":6,"d":1720516411810}
[Lag Monitor] Event loop latency: 15.012499999720603ms
```

this essentially means your bot is sending audio

**Comment by kensunjaya** [comment]
> @kensunjaya
> 
> `from {"status":"playing","missedFrames":0,"playbackDuration":152540,"resource":true,"stepTimeout":false}`
> 
> after analyzing your log, it seems your bot is indeed playing the track. Do you have your bot muted or something?

Not sure if it's playing the track. the bot is not muted. It just stayed quiet after playing some tracks and the queue remains stuck until I stopped the player (also cleared the queue) and play it again. Then it will eventually got stuck again after playing some tracks.

**Comment by jtpotato** [comment]
Set up a similar logging system on my bot:

Logs that look like this:
```
[LOG] [NW] [WS] >> {"op":3,"d":1720531426630}
[LOG] [NW] [WS] << {"op":6,"d":1720531426630}
```
usually results in the bot not emitting audio. I think it might be some kind of keepalive signal for the websockets???

However, the moment we get (after multiple restarts, sometimes randomly)
```
[LOG] [NW] [WS] >> {"op":5,"d":{"speaking":1,"delay":0,"ssrc":19599}}
```
there's some sort of status change and the bot starts emitting audio (with the green activity ring too).

Absolutely no clue why this happens.

**Comment by twlite** [comment]
> state change:
> from {"status":"buffering","resource":true,"stepTimeout":false}
> to {"status":"playing","missedFrames":0,"playbackDuration":0,"resource":true,"stepTimeout":false}

yes, if you see my message above, it includes these lines

```
state change:
from {"status":"buffering","resource":true,"stepTimeout":false}
to {"status":"playing","missedFrames":0,"playbackDuration":0,"resource":true,"stepTimeout":false}
```

this can be used to identify the current stage we are in, in this case playing

**Comment by twlite** [comment]
@kensunjaya I see your bridge provider is youtube, which youtube library are you using? Can you go through each of these until one works https://github.com/Androz2091/discord-player?tab=readme-ov-file#streaming-library? If none of those work, try looking into https://github.com/retrouser955/discord-player-youtubei

**Comment by jtpotato** [comment]
> this can be used to identify the current stage we are in, in this case playing

For some tracks, this line never appears - I think there are examples of a working and not-working track in the logs in this thread, although I haven't looked very closely.

---

After some messing around, setting `skipFFmpeg: false` seems to make it occur much less frequently (haven't run into it yet)

**Comment by twlite** [comment]
> > this can be used to identify the current stage we are in, in this case playing
> 
> For some tracks, this line never appears - I think there are examples of a working and not-working track in the logs in this thread, although I haven't looked very closely.
> 
> After some messing around, setting `skipFFmpeg: false` seems to make it occur much less frequently (haven't run into it yet)

🙂 if this is the case, then the streaming library you are using failed to stream the content. Streaming it via ffmpeg seems to work for you, you can keep it like that. `skipFFmpeg` mode is turned on by default to avoid instantiating ffmpeg when alternative way of streaming exists, which saves a lot of resources.

**Comment by kensunjaya** [comment]
> @kensunjaya I see your bridge provider is youtube, which youtube library are you using? Can you go through each of these until one works https://github.com/Androz2091/discord-player?tab=readme-ov-file#streaming-library? If none of those work, try looking into https://github.com/retrouser955/discord-player-youtubei

After some investigations, turns out that it was the youtube library being unstable. I used ytdl-core and when I switched to discord-player-youtubei it became a lot more stable. Thank you for the help
