### ISSUE TITLE
Player wont start to play the music

### ISSUE THREAD

**Issue by PenDZ-Alter** [Androz2091/discord-player#1921]
**Description**
Since yesterday, when i tried to play the music, the player wont start the music. But, the music is actually inserted into queue.

**Screenshots**
Here's my code in `play.js` : 
![image](https://github.com/Androz2091/discord-player/assets/133771173/9fa80724-2b7f-4021-bee7-fd3852c5a90c)
![image](https://github.com/Androz2091/discord-player/assets/133771173/01d064b5-64af-47dd-8057-4f55a80c64d7)

And here's the debug log file : 
[debug-log.txt](https://github.com/user-attachments/files/16162796/debug-log.txt)

 - Node Version: 20.10.0
 - Discord Player Version: 6.6.7
 - Discord.js Version: 14.15.3

**Additional context**
I tried the debug too. But, seems like the status wont changed into "playing" but "buffering" and stuck at "Dispatching Audio ..."

**Comment by LakhindarPal** [comment]
I was facing similar issues, for me it was only for YouTube links.
Try using SoundCloud links. If it works for SoundCloud, then your problem is related to youtube too.
In that case you can try the [discord-player-youtubei](https://github.com/retrouser955/discord-player-youtubei) plugin.

**Comment by PenDZ-Alter** [comment]
@LakhindarPal You're right, but not only youtube, when i tried to play using spotify, is facing the same problem.

**Comment by retrouser955** [comment]
@PenDZ-Alter Discord Player cannot stream from Spotify. It uses Spotify info to stream from youtube.

**Comment by Duda02** [comment]
I can confirm, since yesterday Youtube/Spotify playback is broken. Seems like Youtube might be taking some actions against bots as other libs/bots are also affected. I've tried implementing [discord-player-youtubei](https://github.com/retrouser955/discord-player-youtubei) but the issue persisted.

Here are some debug logs that were printed after I tried to play a track:
```
Debug Searching https://www.youtube.com/watch?v=dQw4w9WgXcQ
Debug Search engine set to youtubeVideo, fallback search engine set to autoSearch
Debug Protocol https detected in query
Debug Could not find an extractor that supports https protocol. Falling back to default behavior...
Debug Query type identified as youtubeVideo
Debug Checking cache...
Debug Cache miss for query https://www.youtube.com/watch?v=dQw4w9WgXcQ
Debug Executing extractors...
Debug Executing extractor com.discord-player.spotifyextractor...
Debug Executing extractor com.discord-player.applemusicextractor...
Debug Executing extractor com.discord-player.soundcloudextractor...
Debug Executing extractor com.discord-player.youtubeextractor...
Debug Extractor com.discord-player.youtubeextractor executed successfully!
Debug Executing metadata query using com.discord-player.youtubeextractor extractor...
Debug Metadata query was successful!
Debug Adding data to cache...
Debug Executing extractor com.discord-player.spotifyextractor...
Debug Executing extractor com.discord-player.applemusicextractor...
Debug Executing extractor com.discord-player.soundcloudextractor...
Debug Executing extractor com.discord-player.youtubeextractor...
Debug Extractor com.discord-player.youtubeextractor executed successfully!

```

**Comment by twlite** [comment]
> I can confirm, since yesterday Youtube/Spotify playback is broken. Seems like Youtube might be taking some actions against bots as other libs/bots are also affected. I've tried implementing [discord-player-youtubei](https://github.com/retrouser955/discord-player-youtubei) but the issue persisted.
> 
> Here are some debug logs that were printed after I tried to play a track:
> 
> ```
> Debug Searching https://www.youtube.com/watch?v=dQw4w9WgXcQ
> Debug Search engine set to youtubeVideo, fallback search engine set to autoSearch
> Debug Protocol https detected in query
> Debug Could not find an extractor that supports https protocol. Falling back to default behavior...
> Debug Query type identified as youtubeVideo
> Debug Checking cache...
> Debug Cache miss for query https://www.youtube.com/watch?v=dQw4w9WgXcQ
> Debug Executing extractors...
> Debug Executing extractor com.discord-player.spotifyextractor...
> Debug Executing extractor com.discord-player.applemusicextractor...
> Debug Executing extractor com.discord-player.soundcloudextractor...
> Debug Executing extractor com.discord-player.youtubeextractor...
> Debug Extractor com.discord-player.youtubeextractor executed successfully!
> Debug Executing metadata query using com.discord-player.youtubeextractor extractor...
> Debug Metadata query was successful!
> Debug Adding data to cache...
> Debug Executing extractor com.discord-player.spotifyextractor...
> Debug Executing extractor com.discord-player.applemusicextractor...
> Debug Executing extractor com.discord-player.soundcloudextractor...
> Debug Executing extractor com.discord-player.youtubeextractor...
> Debug Extractor com.discord-player.youtubeextractor executed successfully!
> ```

Lol this feels like the words of @mariusbegby, anyways I'd suggest you to join https://androz2091.fr/discord for discussions related to youtubei package.

**Comment by mariusbegby** [comment]
Using youtubei worked fine for my bot, this is what I did: https://github.com/mariusbegby/cadence-discord-bot/commit/bf9c662835a344c2f9fe803f72b6694066ffad83

**Comment by tm-frs** [comment]
> I can confirm, since yesterday Youtube/Spotify playback is broken. Seems like Youtube might be taking some actions against bots as other libs/bots are also affected. I've tried implementing [discord-player-youtubei](https://github.com/retrouser955/discord-player-youtubei) but the issue persisted.
> 
> Here are some debug logs that were printed after I tried to play a track:
> 
> ```
> Debug Searching https://www.youtube.com/watch?v=dQw4w9WgXcQ
> Debug Search engine set to youtubeVideo, fallback search engine set to autoSearch
> Debug Protocol https detected in query
> Debug Could not find an extractor that supports https protocol. Falling back to default behavior...
> Debug Query type identified as youtubeVideo
> Debug Checking cache...
> Debug Cache miss for query https://www.youtube.com/watch?v=dQw4w9WgXcQ
> Debug Executing extractors...
> Debug Executing extractor com.discord-player.spotifyextractor...
> Debug Executing extractor com.discord-player.applemusicextractor...
> Debug Executing extractor com.discord-player.soundcloudextractor...
> Debug Executing extractor com.discord-player.youtubeextractor...
> Debug Extractor com.discord-player.youtubeextractor executed successfully!
> Debug Executing metadata query using com.discord-player.youtubeextractor extractor...
> Debug Metadata query was successful!
> Debug Adding data to cache...
> Debug Executing extractor com.discord-player.spotifyextractor...
> Debug Executing extractor com.discord-player.applemusicextractor...
> Debug Executing extractor com.discord-player.soundcloudextractor...
> Debug Executing extractor com.discord-player.youtubeextractor...
> Debug Extractor com.discord-player.youtubeextractor executed successfully!
> ```

I had the same issue, implementing `discord-player-youtubei` fixed the issue, but when I entered a URL (which is what you did here) it wouldn't work. Does it work for you when you don't use a URL but search instead? @Duda02

**Comment by Duda02** [comment]
@mariusbegby Turns out I had outdated versions of `@discord-player`, `discord-player-youtubei` and was missing the `@discord-player/extractor` package. Now that I updated/installed them I can confirm that using [discord-player-youtubei](https://github.com/retrouser955/discord-player-youtubei) works perfectly. Thanks for linking your commit, it helped me too!

**Comment by Duda02** [comment]
> > I can confirm, since yesterday Youtube/Spotify playback is broken. Seems like Youtube might be taking some actions against bots as other libs/bots are also affected. I've tried implementing [discord-player-youtubei](https://github.com/retrouser955/discord-player-youtubei) but the issue persisted.
> > Here are some debug logs that were printed after I tried to play a track:
> > ```
> > Debug Searching https://www.youtube.com/watch?v=dQw4w9WgXcQ
> > Debug Search engine set to youtubeVideo, fallback search engine set to autoSearch
> > Debug Protocol https detected in query
> > Debug Could not find an extractor that supports https protocol. Falling back to default behavior...
> > Debug Query type identified as youtubeVideo
> > Debug Checking cache...
> > Debug Cache miss for query https://www.youtube.com/watch?v=dQw4w9WgXcQ
> > Debug Executing extractors...
> > Debug Executing extractor com.discord-player.spotifyextractor...
> > Debug Executing extractor com.discord-player.applemusicextractor...
> > Debug Executing extractor com.discord-player.soundcloudextractor...
> > Debug Executing extractor com.discord-player.youtubeextractor...
> > Debug Extractor com.discord-player.youtubeextractor executed successfully!
> > Debug Executing metadata query using com.discord-player.youtubeextractor extractor...
> > Debug Metadata query was successful!
> > Debug Adding data to cache...
> > Debug Executing extractor com.discord-player.spotifyextractor...
> > Debug Executing extractor com.discord-player.applemusicextractor...
> > Debug Executing extractor com.discord-player.soundcloudextractor...
> > Debug Executing extractor com.discord-player.youtubeextractor...
> > Debug Extractor com.discord-player.youtubeextractor executed successfully!
> > ```
> 
> I had the same issue, implementing `discord-player-youtubei` fixed the issue, but when I entered a URL (which is what you did here) it wouldn't work. Does it work for you when you don't use a URL but search instead? @Duda02

Hi, I followed @mariusbegby's implementation and both URL and search work fine.

**Comment by PenDZ-Alter** [comment]
> @PenDZ-Alter Discord Player cannot stream from Spotify. It uses Spotify info to stream from youtube.

Oh really, Thanks for the information.

**Comment by retrouser955** [comment]
If you are having any more problems with `discord-player-youtubei`, please come open an issue on our [repo](https://github.com/retrouser955/discord-player-youtubei)

**Comment by retrouser955** [comment]
Checking a lot of the issues here, it seems you guys both have youtubei and the default extractors activated. I will release `1.1.0` in a while which should fix it even if you accidently registered both.

**Comment by PenDZ-Alter** [comment]
I think this problem solved using youtubei plugin. I will close the issue, because i think there's no discussion anymore.
Thanks to everyone and developers who helped me to solve the problem! :)
