### ISSUE TITLE
|IMPORTANT FEATURE / BUG|

### ISSUE THREAD

**Issue by FS-Santi** [Androz2091/discord-player#193]
When you do ?play <song> and immediately after you do ?play <song> again it should cancel the previous ?play request, (THIS CAUSES alot of issues) Thanks! <3

**Comment by Androz2091** [comment]
@FS-Santi what do you mean exactly? It should stop the collector used to get the index of the song to play?

**Comment by FS-Santi** [comment]
Correct, so if you do ?play and you don't make a valid selection and right after you do ?play again then it plays 2 songs because it was listening for both selections, so it should stop listening for the previous one
