### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by FS-Santi** [Androz2091/discord-player#194]
Instead of sending the song title and then the URL separate how can I make the song title clickable (link)

**Comment by Victorthemachine** [comment]
Use the markdown syntax => [name](link)

Usage for player:
```js
const queue = this.client.player.getQueue(message);
message.channel.send(`[${queue.tracks[index].title}](${queue.tracks[index].url})`);
```
Replace the index with the index of the song you want to display.

**Comment by SimonLeclere** [comment]
Only works in embeds ;)

**Comment by Victorthemachine** [comment]
> Only works in embeds ;)

Right, thanks for the correction, forgot about that ^^"

**Comment by SimonLeclere** [comment]
@FS-Santi Is your problem solved? If yes, can you close this issue?
