### ISSUE TITLE
Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by mrganmak** [Androz2091/discord-player#196]
I have this error, when i try to play any video. What do I need to do to fix this?

**Comment by Androz2091** [comment]
@Snowflake107 any idea why?

**Comment by mrganmak** [comment]
@Androz2091 I took the new version of ytdl from discord-music-player (sorry for the ad) and everything worked, most likely the problem was in the outdated way of getting information about the video.

**Comment by Androz2091** [comment]
Should be fixed in v3.1.0 :tada:
