### ISSUE TITLE
play function executes, and a player is created, bot does not do anything

### ISSUE THREAD

**Issue by AlphaLupine** [Androz2091/discord-player#198]
Hey so I have been trying to setup up a new project that I wish to workon and cannot seem to get around this, I am not sure if I have done the setup wrong or if I am missing a key detail that perhaps someone could point out?

Code Below:
CLIENT:
`const { Client, Collection } = require('discord.js');
const Util = require('../Lib/utils');
const { Player } = require('discord-player');

module.exports = class MoosicClient extends Client {

    constructor(options = {}) {
        super({
            disableMentions: 'everyone'
        });
        this.validate(options);

        this.commands = new Collection();
        this.aliases = new Collection();
        this.events = new Collection();

        this.utils = new Util(this);
        
        this.player = new Player(this, {
            leaveOnEmpty:false,
            leaveOnEnd:false,
            leaveOnStop:true
        });
    }
    validate(options) {
        if(typeof options !== 'object') throw new TypeError('Options should be a type of Object');

        if(!options.token) throw new Error('You must pass the token for the client');
        this.token = options.token;

        if(!options.prefix) throw new Error('You must pass a prefix for the client');
        if(typeof options.prefix !== 'string') throw new TypeError('Prefix should be a type of String');
        this.prefix = options.prefix;
    }
    async start(token = this.token) {
        this.utils.loadCommands();
        this.utils.loadEvents();
        super.login(token);
    }
}`
COMMAND STRUCTURE:
`module.exports = class Command {

    constructor(client, name, options = {}) {
        this.client = client;
        this.name = options.name || name;
        this.aliases = options.aliases || [];
        this.description = options.description || 'No Description';
        this.category = options.cateogry || 'Misc';
        this.usage = options.usage || 'No Usage';
    }

    async run() {
        throw new Error(`Command ${this.name} does not provide a run method`);
    }
}`
PLAY COMMAND WIP:
`const Command = require('../../Structures/Command');

module.exports = class Play extends Command {
    
    constructor(...args) {
        super(...args, {
            
        })
    }

    async run(message, args) {

        await this.client.player.play(message, args.join(" "))
    }
};`

**Comment by AlphaLupine** [comment]
Apologies for the poor code formatting, github is being weird a messing up the code blocks

**Comment by Victorthemachine** [comment]
Looking at your code my guess is that you are following MenuDocs. So you should have a function loadCommands in Util.js. I have had similar issues, basically you want to change this:
```js
	async loadCommands() {
		return glob(`${this.directory}commands/**/*.js`).then(commands => {
```

to:
```js
	async loadCommands() {
		return glob(`${this.directory}Commands/**/*.js`).then(commands => {
```

This should allow the play command to load and function.

**Comment by Androz2091** [comment]
Closed due to inactivity
