### ISSUE TITLE
Queue Issue

### ISSUE THREAD

**Issue by hydraindia** [Androz2091/discord-player#2]
If I am currently playing a song in a server then I add a song in queue then the bot starts to play the current song again.

**Comment by Androz2091** [comment]
Can you send the part of your code where you use discord-player functions?

**Comment by Androz2091** [comment]
@hydraindia did you see my message? 😅

**Comment by hydraindia** [comment]
> @hydraindia did you see my message? 😅

Sorry for late reply

**Comment by hydraindia** [comment]
` if(!message.member.voice.channel) return message.channel.send(`**You're not in a voice channel ${emotes.error}**`)

    if (!args[0]) return message.channel.send(`**Please enter a music ${emotes.error}**`)
  
    let aSongIsAlreadyPlaying = client.player.isPlaying(message.guild.id);
    // If there's already a song playing 
    let song = await client.player.play(message.member.voice.channel, args.join(" "));
    song.queue.on('end', () => {
            message.channel.send('**The queue is empty, please add some songs!**');
    });
  
    song.queue.on('songChanged', (oldSong, newSong, skipped, repeatMode) => {
            if(repeatMode){
                message.channel.send(`**Repeating, ${newSong}**`);
            } else {
                message.channel.send(`Now playing ${newSong}...`);
            }
        });
    if(aSongIsAlreadyPlaying){
        // Add the song to the queue
        let song = await client.player.addToQueue(message.guild.id, args.join(" "));
        message.channel.send(`**${song.name} added to queue **`);
    } else {
        // Else, play the song
        let song = await client.player.play(message.member.voice.channel, args.join(" "));
        message.channel.send(`**Currently playing ${song.name} ${emotes.music}**`);
    }`

**Comment by Androz2091** [comment]
That's normal. You must do it this way:
```js
if (!args[0]) return message.channel.send(`**Please enter a music ${emotes.error}**`)

let aSongIsAlreadyPlaying = client.player.isPlaying(message.guild.id);

if(aSongIsAlreadyPlaying){
    // Add the song to the queue
    let song = await client.player.addToQueue(message.guild.id, args.join(" "));
    message.channel.send(`**${song.name} added to queue **`);
} else {
    // Else, play the song
    let song = await client.player.play(message.member.voice.channel, args.join(" "));
    message.channel.send(`**Currently playing ${song.name} ${emotes.music}**`);
    song.queue.on('end', () => {
        message.channel.send('**The queue is empty, please add some songs!**');
    });

    song.queue.on('songChanged', (oldSong, newSong, skipped, repeatMode) => {
        if(repeatMode){
            message.channel.send(`**Repeating, ${newSong}**`);
        } else {
            message.channel.send(`Now playing ${newSong}...`);
        }
    });
}
```

**Comment by hydraindia** [comment]
Okay let me try

**Comment by hydraindia** [comment]
Thanks for solving my issue
