### ISSUE TITLE
AddToQueue not working

### ISSUE THREAD

**Issue by vlfz** [Androz2091/discord-player#20]
I tried to add two tracks. One track is successfully added, app crashed after adding two track with error:
![image](https://user-images.githubusercontent.com/32297717/81494131-aaca1280-92bf-11ea-920f-1f33907bc827.png)

**Comment by Androz2091** [comment]
Hello,
Looks like you didn't use the `play()` method before adding the song to the queue. Please read [this section](https://github.com/Androz2091/discord-player#addtoqueue) of the README.

**Comment by vladciphersky** [comment]
Hmm, i use "aSongIsAlreadyPlaying", but error.
