### ISSUE TITLE
TypeError: Cannot read property 'guild' of null

### ISSUE THREAD

**Issue by chiquicalris-dev** [Androz2091/discord-player#201]

**Comment by hands8142** [comment]
Please explain in detail.

**Comment by chiquicalris-dev** [comment]
![image](https://user-images.githubusercontent.com/38810865/103008399-5b2a1580-4535-11eb-8cd4-e137ea55ea54.png)
@hands8142

**Comment by imLinguin** [comment]
What node version are you using? Also make sure all dependencies such as discord.js and discord-player are up to date.

**Comment by chiquicalris-dev** [comment]
Everything is update, I use discord.js-light and I have all caches enabled except emojis...

**Comment by chiquicalris-dev** [comment]
![image](https://user-images.githubusercontent.com/38810865/103024754-bb7a8080-4550-11eb-8597-c9b22b5ba7cd.png)
@imLinguin

**Comment by imLinguin** [comment]
There might be an issue with discord.js-light itself. I read their docs and found that voiceState have user informations. I didn't found anything about guild data. I will check that later in code itself.

**Comment by chiquicalris-dev** [comment]
Okay, thanks!
