### ISSUE TITLE
Divers bugs & suggestions

### ISSUE THREAD

**Issue by ZerioDev** [Androz2091/discord-player#204]
Hey Androz voici une petite liste de suggestions et de bugs récemment signalés 👋

- Ajouter une fonction pour détecter automatiquement la première musique (je crois que cela est ajouté dans la branche dev).
- L'évent `channelEmpty` n'est jamais détecté ainsi que l'évent `queueEnd`.
- La fonction `clear-queue` supprime toutes les musiques même celle actuelle (la musique actuelle est encore en lecture mais les fonctions telles que nowplaying renvoient des undefined & null).
- Le filtre bassboost est dangereux si on l'active et si par la suite nous modifions le volume (avec un petit nombre ou non) qui va déclencher un son fort et très saturé.
- Ajouter une fonction 'cancel' ou 'stop' pour la partie sélection avec l'évent `searchResults` pour annuler la sélection.
- Si nous mettons le lien d'un live YouTube le bot devra renvoyer un message d'erreur comme quoi les lives ne sont pas supportés, actuellement le bot détecte bien le live (l'évent `trackStart` est bien reconnu) mais ne déclenche aucun contenu audio et affiche des valeurs telles que '0:0' en durée.
- Les playlists ne sont pas supportées.
- Les modules Spotify & SoundCloud ne sont pas reconnus.
- Cet avertissement (ci-dessous) qui apparait à chaque lancement d'une nouvelle musique.

![image](https://user-images.githubusercontent.com/43386412/103137132-9d369100-46c6-11eb-809c-a8c7477315c3.png)

Je crois que j'ai fait le tour, courage 👍

**Comment by Androz2091** [comment]
Salut :wave:

> Ajouter une fonction pour détecter automatiquement la première musique (je crois que cela est ajouté dans la branche dev).

Développé ✅ 

> L'évent channelEmpty n'est jamais détecté ainsi que l'évent queueEnd.

Bug trouvé et réglé ✅ 

> La fonction clear-queue supprime toutes les musiques même celle actuelle (la musique actuelle est encore en lecture mais les fonctions telles que nowplaying renvoient des undefined & null).

Bug trouvé et réglé ✅ 

> Le filtre bassboost est dangereux si on l'active et si par la suite nous modifions le volume (avec un petit nombre ou non) qui va déclencher un son fort et très saturé.

Ça c'est assez subjectif, j'ai pu faire des tests ça dépend vraiment de la musique. Tu peux appliquer des filtres custom si tu préfères un bassboost plus léger

> Ajouter une fonction 'cancel' ou 'stop' pour la partie sélection avec l'évent searchResults pour annuler la sélection.

C'est déjà possible (en utilisant l'objet collector, [exemple](https://hastebin.androz2091.fr/iyutijeqov.less))

> Si nous mettons le lien d'un live YouTube le bot devra renvoyer un message d'erreur comme quoi les lives ne sont pas supportés, actuellement le bot détecte bien le live (l'évent trackStart est bien reconnu) mais ne déclenche aucun contenu audio et affiche des valeurs telles que '0:0' en durée.

C'est développé ✅ 
**[Exemple](https://hastebin.androz2091.fr/gexiwufipa.js)**

> Les playlists ne sont pas supportées.

Bug trouvé et réglé ✅ 

> Les modules Spotify & SoundCloud ne sont pas reconnus.

Ça fonctionne bien chez moi (c'est correct si ça renvoie un embed de sélection, c'est ce qui est prévu, il analyse juste le lien pour ressortir des mots clef et ensuite il fait une recherche youtube).

> Cet avertissement (ci-dessous) qui apparait à chaque lancement d'une nouvelle musique.

Je n'ai pas ce problème sur la develop, j'avais déjà arrêté d'utiliser ces propriétés, n'hésite pas à me dire si c'est réglé en mettant à jour le module !

**Comment by ZerioDev** [comment]
Salut salut 👋

Merci pour tout ces correctifs !

Je suis actuellement en train de tester la branche `develop`.
Je reviens vers toi en cas de divers soucis particulier.

Passe une bonne soirée !

**Comment by Androz2091** [comment]
Je viens de publier la v3.1.0, n'hésite pas à réouvrir une issue s'il y a toujours des bugs 👍
