### ISSUE TITLE
✨ Suggestions

### ISSUE THREAD

**Issue by Androz2091** [Androz2091/discord-player#208]
Here is a list of the suggestions received on GitHub or on Discord. I will keep this list synchronized with future updates. Use the [discord server](https://androz2091.fr/discord) **or** GitHub discussions to discuss/debate.

* `player.moveTo(guild, channel)` - Pauses the music playback, moves to a different voice channel specified and then resumes the playback.
* support Reverbnation links (using [Snowflake107/reverbnation-scraper](https://github.com/Snowflake107/reverbnation-scraper)) to get the song name and the song author and then search with these terms on YouTube.
* `player.seek(duration)` - Seek X amount of time
* Handle Spotify playlists and albums

**Comment by Snowflake107** [comment]
`+` Discord attachments support
I think it is a good idea to add discord attachments support where users can play audio/video file(s)

`+` Facebook videos support
Using **[fbdl](https://npmjs.com/package/fbdl-core)** (currently under maintenance)

`+` TikTok videos support
Probably adding TikTok videos support 🙄

more later on...

**Comment by tovade** [comment]
+ add playlist support
(current one broke)

**Comment by Snowflake107** [comment]
Reverbnation implemented #236

**Comment by Klairm** [comment]
I think it would be cool being able to skip tracks of a playlist, right now if you skip when a playlist is added, it will skip the whole playlist and not the current song
