### ISSUE TITLE
Get two lists of song and bot self-muted

### ISSUE THREAD

**Issue by Zargith** [Androz2091/discord-player#210]
I just updated to v3.2.0 and now, when I want to play a music, it shows me two times the results of the query :
![Capture](https://user-images.githubusercontent.com/36247975/103166940-4cf83400-486a-11eb-8d75-3ec240246b1c.PNG)

I guess it comes from the event emiter baceause there is where I call for the display :
![Capture3](https://user-images.githubusercontent.com/36247975/103167083-6c439100-486b-11eb-808b-37e454ab1332.PNG)

Also since the update, the bot is self-muted but still playing :
![Capture2](https://user-images.githubusercontent.com/36247975/103166942-51245180-486a-11eb-939a-d34f1e811497.PNG)

But I don't know if you did something or if it comes from discord.js because I had a discord.js update at the same time (discord.js@12.5.1)

**Comment by Androz2091** [comment]
For the first issue (embed sent twice), are you sure that there is only one instance of the bot started? I can't see any other reason why

For the second issue, this is excepted (the bot turned its headphones off). You can change this by using:
```js
client.player = new Player(client, {
    autoSelfDeaf: false,
    // other options
});
```

**Comment by Zargith** [comment]
For the first issue (embed sent twice), I checked and there is only one instance of the bot started. I restarted it but the problem stills. I tryed my other commands too and same result. I don't know how and why it looks that there is two instances but it may not comes from your module 👍 

And for the second issue it's resolved thanks to your suggestion. Thanks !

**Comment by Androz2091** [comment]
All right 😄 
You can check [this post](https://stackoverflow.com/a/59255618/11856499), it could help you to solve the first issue
