### ISSUE TITLE
fix events

### ISSUE THREAD

**Issue by tovade** [Androz2091/discord-player#214]
+ voiceEmpty
doesnt even emit at all

+ playlistAdd
sometimes it emits sometimes it doesnt

`Thank you for your time looking at this!`

**Comment by Androz2091** [comment]
> voiceEmpty
doesnt even emit at all

This event doesn't exist :wink:
Use `channelEmpty`

> playlistAdd
sometimes it emits sometimes it doesnt

It only emits if there is another song in the queue (it is the same as `trackAdd`, but for playlists)

:arrow_right: If you still need help, please join [our support server](https://androz2091.fr/discord)

**Comment by tovade** [comment]
hey i messd up my typing i meant channelEmpty dint emit

**Comment by tovade** [comment]
i see this is fixed in next update?

**Comment by Androz2091** [comment]
Yes, upgrade to v3.2.0, it should work
