### ISSUE TITLE
Connect and playing message to disconnect bot

### ISSUE THREAD

**Issue by zarar2312** [Androz2091/discord-player#215]
After connecting, it goes out of sound. You said it has multi server feature?

**Comment by hands8142** [comment]
Is there an error? Please show me if an error occurs.

**Comment by zarar2312** [comment]
does not show error. 34k server in this module use shard I don't understand the problem either 

small is happening

big bot is not work

**Comment by hands8142** [comment]
Can you show me the code?

**Comment by zarar2312** [comment]
the same man I just did the same as what you put in the module menu big bot in not work

https://user-images.githubusercontent.com/24358398/103208149-fc87e180-4910-11eb-9ac8-3e5611b8363c.mp4

**Comment by zarar2312** [comment]
join channel and close now

**Comment by zarar2312** [comment]
queueEnd problem options

**Comment by zarar2312** [comment]
system: win server r2 2012

**Comment by hands8142** [comment]
I'm not sure.

**Comment by zarar2312** [comment]
well done! fixed man thanks for this music module good 👍🏻
