### ISSUE TITLE
If you follow the example in README, an error will occur.

### ISSUE THREAD

**Issue by hands8142** [Androz2091/discord-player#216]
If you follow the example in README, an error will occur. Modify README or set false as the default for firstResult.

**Comment by Androz2091** [comment]
Hello, did you test it too? Because if you use `play(message, 'All I Want for Christmas Is You');`, it will consider that `firstResults` is equal to `false`.

**Comment by hands8142** [comment]
An error will occur.
An argument for 'firstResult' was not provided.

**Comment by hands8142** [comment]
#222
