### ISSUE TITLE
Addition to the getQueue() function [NECCESSARY]

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#22]
Hi there. I just thought I would make this suggestion because its probably a necessary feature to have for easy code management. So I am currently trying to add pagination to my queue however I am having a hard time because the `getQueue()` function also returns the currently playing result; an option to configure this would be a nice addition to this module!

Here is the scenario:
```
Add an option to getQueue() to return everything in the queue but the currently playing song
So getQueue(guild, andCurPlaying) - guild will be just the normal guild ID to get the queue from. andCurPlaying - if this is **false**, it will not return the currently playing song but the rest of the queue, if this is **true** it will return the currently playing song and the rest of the queue.
```

**Comment by Androz2091** [comment]
@thomasthebro1 All right, it'll be added.

Feel free to give us more feedback on the simplicity of the module. I know for example that some packages don't have an addToQueue function like erela.js. Maybe it's better, I don't know because I'm not the one who use the most my package 😅

**Comment by thomasthebro1** [comment]
Yea it would be cool if the `play` function was automatically determine if there is a song already playing (as well as including the `isPlaying` function) to make the play command look more tidy and clean :)

**Comment by thomasthebro1** [comment]
I am also looking forward to the new features such as bass boost and effect controls for this version. I love your module, its simplistic and very easy to use compared to lavalink

**Comment by APartOfMe1** [comment]
I know this is old, but you can use `const queue = client.player.getQueue(msg.guild.id)`, then `queue.songs.slice(1)` to get everything except the current song

**Comment by thomasthebro1** [comment]
@APartOfMe1 Yes I already know that, but to keep our bot's code to a minimum it would be nice if it was already integrated into the package. :)

**Comment by thomasthebro1** [comment]
Solved
