### ISSUE TITLE
Nombre de vues - client.player.nowPlaying(message)

### ISSUE THREAD

**Issue by Swarwerth** [Androz2091/discord-player#221]
Bonjour !
Je pense avoir trouvé un bug. Lorsque je souhaite afficher le nombre de vues d'une musique dans une playlist, cela m'affiche pour n'importe quelle musique 0. Voici un screenshot de l'eval de `client.player.nowPlaying(message)` :

![image](https://user-images.githubusercontent.com/26115962/103287922-fe6ea500-49e3-11eb-9aaa-f8bf752a0651.png)

Voici les étapes pour trouver ce bug :
- lancer une playlist Youtube (exemple : https://www.youtube.com/playlist?list=PLbZIPy20-1pN7mqjckepWF78ndb6ci_qi)
- utiliser la commande `nowplaying` pour afficher le nombre de vues de la vidéo / évaluer `client.player.nowPlaying(message)`

Bonne journée et bon courage !

**EDIT: Je remarque qu'il ne détecte pas que la musique vient d'une playlist aussi 🤔*

**Comment by hands8142** [comment]
I think this is a YouTube-sr problem.

**Comment by Androz2091** [comment]
This is indeed a YouTube SR bug, but looks like there is no way to obtain this data (without fetching each song). I'm closing this, if someone has a solution feel free to open another issue 👍
