### ISSUE TITLE
client.on is not a function

### ISSUE THREAD

**Issue by subtocodexlol** [Androz2091/discord-player#228]
While trying to use **Discord Player** I turned on my bot and got the error of:

```
TypeError: client.on is not a function
```
Keeping **Discord Player** and my discord bot from working

https://user-images.githubusercontent.com/67366721/103469836-c5119e80-4d2f-11eb-8a7f-9c24b5dd3ca2.mp4

**Comment by Androz2091** [comment]
Hello, can you send your code please?

**Comment by subtocodexlol** [comment]
> Hello, can you send your code please?

I managed to fix the error. I forgot to edit the message saying that it was broken.

**Comment by mattgeowild** [comment]
> I managed to fix the error. I forgot to edit the message saying that it was broken.

How did you fix it?
