### ISSUE TITLE
Not catching all errors.

### ISSUE THREAD

**Issue by dannysmc95** [Androz2091/discord-player#230]
Hello,

There is a bug in the player, where sometimes a video fails to play, apparently ytdl-core has fixed this? Maybe you need to update your dependency (please).

To note you are also not preventing errors, I see the following:

![](https://i.imgur.com/SD9GSHd.png)

And it is being thrown as an uncaughtException and exiting my application.

Can you please either make sure the error is caught, or can you try and update the ytdl-core dep to the latest, to see if the issue is fixed or not.

Thanks and great work!!

**Comment by Androz2091** [comment]
Hello @dannysmc95, can you send me the link of the video you're trying to play?

**Comment by dannysmc95** [comment]
Hey @Androz2091 so it looks like the video is unavailable:

https://www.youtube.com/watch?v=bNU_AA0aALM&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10&index=4

But if that is the case I would assume you would still catch it without causing the whole app to crash and quit, or even just skip to the next one, I am using it to play the following playlist: https://www.youtube.com/playlist?list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10 as I test, and it's the fourth song, it just gets stuck and then ends up disconnecting after a minute.

Would be awesome if you could add a callback for song failure errors, which would allow you to change to the next song, as I can't do it manually on catching an uncaughtException, because you need to have a "Message" instance to pass to the skip command...

**Comment by Androz2091** [comment]
Yes. I think the best is to add something like
```js
client.player.on('error', (error, message) => {
    switch(error){
        case 'NotPlaying':
            message.channel.send('There is no music being played on this server!')
            break;
        case 'NotConnected':
            message.channel.send('You are not connected in any voice channel!')
            break;
        case 'UnableToJoin':
            message.channel.send('I am not able to join your voice channel, please check my permissions!')
            break;
        case 'LiveVideo':
            message.channel.send('YouTube lives are not supported!')
            break;
 		case 'VideoUnavailable': // new error
			message.channel.send('This video is unavailable!');
			break;
        default:
            message.channel.send(`Something went wrong... Error: ${error}`)
    }
})
```

And it automatically skips to the next song

**Comment by dannysmc95** [comment]
@Androz2091 that would be pretty much perfect! But I would note you may want to check that your errors are being handled, I know it sounds silly, but maybe some higher try catch, to catch all other errors and send them to the "default" at least, as really it should never cause the app the exit.

**Comment by dannysmc95** [comment]
Also is there a volume control? I couldn't find one? Some videos are quite quiet, would be good to up the volume.

**Comment by Androz2091** [comment]
Yes, sure https://discord-player.js.org/Player.html#setVolume
You can join our [discord server](https://androz2091.fr/discord) if you need more help

**Comment by Androz2091** [comment]
Moved to #270
