### ISSUE TITLE
bot enters the channel and leaves quickly.

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-player#231]
the bot on heroku plays music perfectly, but on my vps it connects to the channel and leaves saying that there is not enough music in the playlist, and does not generate any errors in the terminal

Play command

`exports.run = async (bot, message, args, prefix) => {
    if (!message.member.voice.channel) return message.channel.send(`${bot.emotes.error} - Você não está em um canal de voz !`);

    if (!args[0]) return message.channel.send(`${bot.emotes.error} - Indique o título de uma música !`);

    bot.player.play(message, args.join(" "));
    message.react(`▶️`)
}
exports.help = {
    name: 'play',
    aliases: ['p'],
    category: 'music'
}`

**Comment by Androz2091** [comment]
@Akurejs Are you still facing this issue? What song are you trying to play?

**Comment by Akurejs** [comment]
> @Akurejs Are you still facing this issue? What song are you trying to play?

in my vps yes, he doesn't play any music.

any music that I connect it to the channel and then disconnects, it seems to be a problem with @discordjs/opus

**Comment by Androz2091** [comment]
Yes, try to install another opus encoder
