### ISSUE TITLE
Add soundcloud support

### ISSUE THREAD

**Issue by xBeastMode** [Androz2091/discord-player#232]
I would like to see soundcloud track and playlist support. Not just forwarding it to youtube as "author - track name" but streaming it directly from soundcloud. Maybe you can add a `streamType` field to the Track class to tell between youtube, soundcloud, etc. There's this library that creates a readable stream so maybe you can use that? https://www.npmjs.com/package/soundcloud-downloader

**Comment by Snowflake107** [comment]
Currently, this package uses `soundcloud-scraper` which also supports downloading audio. Downloading was added later on which is not implemented here yet. Before soundcloud-scraper could only get song details (no downloading) and that's the reason. Soundcloud will be implemented properly soon and it should work like regular ytdl streams (with audio filters)

**Comment by Snowflake107** [comment]
#236 Implemented
