### ISSUE TITLE
Next function should be smart & Error Handling.

### ISSUE THREAD

**Issue by dannysmc95** [Androz2091/discord-player#234]
So while I have been using this, I have noticed there are a lot of "errors" that are just not being caught and actually exiting my application. So for my next command, I just make a call to the client to change song. I have noticed though that sometimes the next function will not find a next song and throw an error, I think it should be checking ahead before trying to go to a next song if it doesn't error.

All these errors cause the application to exit, I have seen a fair few, can you look at doing something that stops this? as noted in my previous issue, can we get some kind of catch-all error handler in the switch statement, that can and will catch ALL/ANY errors that even you may not have thought of, as at the moment, I am having to use process.on() to prevent the application from exiting but I personally believe there should be no reason for this, and really you should catch any errors in the player and give them to use nicely, because I have seen a few errors, where the websocket crashes on sending audio and it just stops the whole application, whereas I think it would be better for us to be able to clear the old player and make a new one, for as little as possible downtime.

**Comment by Androz2091** [comment]
Thank you for opening this issue. This commit (4a75dae) could resolve a lot of issues, I will try.

**Comment by Androz2091** [comment]
These errors are now handled!

**Comment by Androz2091** [comment]
Thank you for reporting this, everything has been added in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1).
