### ISSUE TITLE
error when ordering songs

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-player#235]
I have a problem, every time I put on the song The Weeknd - Blinding Lights (Official Music Video) the bot doesn't play, it is muted and if you ask for other songs it doesn't play either, if you skip, it doesn't skip music. If you use stop it does not disconnect from the channel and gives these errors at the terminal.

it is necessary to disconnect it manually and then request other songs again, but this song The Weeknd - Blinding Lights (Official Music Video) does not play.

`(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of null
    at Player.skip (/home/node/node_modules/discord-player/src/Player.js:478:42)
    at Object.exports.run (/home/node/src/commands/Music/skip.js:9:19)
    at /home/node/src/events/message.js:69:13
    at propagateAslWrapper (/etc/node_modules/async-listener/index.js:504:23)
    at /etc/node_modules/async-listener/glue.js:188:31
    at /etc/node_modules/async-listener/index.js:541:70
    at /etc/node_modules/async-listener/glue.js:188:31
    at runMicrotasks (\u003canonymous\u003e)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of null
    at Player.skip (/home/node/node_modules/discord-player/src/Player.js:478:42)
    at Object.exports.run (/home/node/src/commands/Music/skip.js:9:19)
    at /home/node/src/events/message.js:69:13
    at propagateAslWrapper (/etc/node_modules/async-listener/index.js:504:23)
    at /etc/node_modules/async-listener/glue.js:188:31
    at /etc/node_modules/async-listener/index.js:541:70
    at /etc/node_modules/async-listener/glue.js:188:31
    at runMicrotasks (\u003canonymous\u003e)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of null
    at Player.stop (/home/node/node_modules/discord-player/src/Player.js:423:42)
    at Object.exports.run (/home/node/src/commands/Music/stop.js:10:19)
    at /home/node/src/events/message.js:69:13
    at propagateAslWrapper (/etc/node_modules/async-listener/index.js:504:23)
    at /etc/node_modules/async-listener/glue.js:188:31
    at /etc/node_modules/async-listener/index.js:541:70
    at /etc/node_modules/async-listener/glue.js:188:31
    at runMicrotasks (\u003canonymous\u003e)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)`

**Comment by arda858** [comment]
This is the same problem I am having. The video is likely not available in OP's country.

**Comment by Androz2091** [comment]
Yes, moved to #270
