### ISSUE TITLE
trackStart event: parameter queue is missing

### ISSUE THREAD

**Issue by Linux123123** [Androz2091/discord-player#238]
So in [documentation](https://discord-player.js.org/Player.html#event:trackStart) it is written that `trackStart` event includes `queue`, but as far as I can tell when it is emitted (for example in `play`) I don't see it included. It is pretty imporntant if you need to update something using the queue when every song starts.
https://github.com/Androz2091/discord-player/blob/47a54690fe537e178d224bec619ec11c0efe63d2/src/Player.js#L374
If i am seeing something wrong correct me :)
Thanks

**Comment by hands8142** [comment]
There seems to be a problem with the document.

**Comment by Linux123123** [comment]
Ok, I didn't see another event emitter. There is another emitter when a new song plays when it is already in queue, which includes queue parameter. This doesn't solve the problem that the first event doesn't include queue parameter, but it could be easily fixed by including queue at the end of emitter parameters, which is already generated and available to include.
