### ISSUE TITLE
Player freezes when playlist contains a video that's not available in your country.

### ISSUE THREAD

**Issue by arda858** [Androz2091/discord-player#239]
-Pass a youtube playlist URL to Player.play() method. Videos are added to queue.
-When queue reaches the video that's not available in the country, player freezes. Can't skip, can't stop. 

This is the error thrown when I try to skip.
```
TypeError: Cannot read property 'end' of null
node_modules/discord-player/src/Player.js:478:42
```

**Comment by Androz2091** [comment]
Hello :wave:
Thank you for reporting this issue. It has been fixed in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1). You now have a `VideoUnavailable` error!
