### ISSUE TITLE
Erreur 'url' argument 

### ISSUE THREAD

**Issue by Pronicio** [Androz2091/discord-player#24]
Bonjour,
Quand je lance la commande !play cela ne marche pas et met cette erreur :
![C9471B93-F7F9-441C-83BC-C5766218E508](https://user-images.githubusercontent.com/52421988/83331042-c3f92a00-a293-11ea-8098-d8a049c2d030.jpeg)
Merci.

**Comment by Androz2091** [comment]
Merci d'avoir reporté ce bug. Je regarderai ça pour le régler dès que possible!

**Comment by Pronicio** [comment]
D’accord merci !

**Comment by Androz2091** [comment]
Bonjour
Ce bug est du à une version trop ancienne de ytdl-core. Mettez le à jour ou utilisez la branche develop de discord-player.
