### ISSUE TITLE
Live stream support

### ISSUE THREAD

**Issue by ThaddeusKKR** [Androz2091/discord-player#241]
Hi, I have a quick question.

Are YouTube live streams not supported and if they are, why?

**Comment by Snowflake107** [comment]
Yes live videos are ignored 
![image](https://user-images.githubusercontent.com/46562212/104308575-00168d80-54f9-11eb-922c-033920ea37fe.png)

**Comment by ThaddeusKKR** [comment]
Yeah, but why tho?

**Comment by Androz2091** [comment]
Because this is not something we want to implement into discord-player, at least for the moment. It would be pretty complicated, like how to handle them in the queue? Will the users be able to add new songs after a live video? If so, will they be played after the live is finished?

**Comment by Edqe14** [comment]
I've worked on some music bots and for live videos isn't that much different from normal videos. Live videos will work normally when you feed it to ytdl, so the users still can put new songs to the queue since they technically still be able to skip the live video.

**Comment by Snowflake107** [comment]
Not only queue - it's hard to manage audio filters and stuff for live contents

**Comment by Edqe14** [comment]
@Snowflake107 Can you tell/explain what is "stuff"? If audio filters cannot be used on live contents, just add a check if  its live or not.

**Comment by devksingh4** [comment]
Currently, it only seems to play for the first 10 seconds, and then stops playing. I am under the impression that ytdl functionality is the same for normal videos and streams, so this is odd indeed

**Comment by ItzMeRM** [comment]
> Not only queue - it's hard to manage audio filters and stuff for live contents

Perform a check if its live and if it is just ignore Nightcore only. All other filters works for live streams except nightcore/speed changing filters. :feelsInvisibleMan:

**Comment by Snowflake107** [comment]
bfed268
