### ISSUE TITLE
'trackStart' sends x number of messages

### ISSUE THREAD

**Issue by jonzeleznik** [Androz2091/discord-player#242]
When I use `client.player.on('trackStart' ...` sends x number of messages. For example I send a request to play music, the bot joins, plays music and sends a title of the song. The if you do the same the bot will send two same messages. Why is that?
Like This:
![Screenshot_19](https://user-images.githubusercontent.com/57703270/104307482-903fdd00-54cf-11eb-9b99-cfb7d16031f6.png)
This is my code:

```javascript
module.exports = {
    commands: ['play', 'p', 'Play'],
    expectedArgs: '[ song title ]',
    minArgs: 1,
    callback: (message, arguments) => {
        
        client.player.on('trackStart', (message, track) => message.channel.send({embed: {
            color: '#6bd2ff',
            title: track.title,
            url: track.url,
            description: `${track.duration}`,
            thumbnail: {
                url: track.thumbnail,
            },
          }
        }))

        const args = arguments.join(" ");
        client.player.play(message, args, true);

    },
}
```

**Comment by arda858** [comment]
Try putting   ` client.player.on('trackStart'`, function on your main index.js, not in the command module

**Comment by jonzeleznik** [comment]
If I do this, the bot don't even send those messages.

**Comment by IdkWhosThis** [comment]
> If I do this, the bot don't even send those messages.

If you have event handler (not command handler), you can make it the same way you have your event handler, but instead of using client.on inside of it, you will use client.player.on. I had completly same issue and creating a "player handler" solved it for me.
