### ISSUE TITLE
Suggestion: API key option in Player (Youtube, maybe Spotify)

### ISSUE THREAD

**Issue by Bicepsfako** [Androz2091/discord-player#245]
To get faster results and optimize ram cpu usage, there should be an api key option, when we set our api key there, module must make queries through the api, not via youtube-sr. If the api key is not specified, module must make search through youtube-sr.

**Comment by ThaddeusKKR** [comment]
This is a good idea, but it may be better if there was maybe an automatic detection for when the API key has run out of credits (i forgot what they're called) so that ytsr can be automatically used then.

**Comment by Snowflake107** [comment]
🤔 not a bad idea tbh. I think discord-player should detect api keys from `process.env` instead of having options?

**Comment by Androz2091** [comment]
Yes, it could be possible. Actually we switched to scraping because a lot of users were ratelimited in a short period of time, but we could support both scraping and the official API.

**Comment by Bicepsfako** [comment]
> 🤔 not a bad idea tbh. I think discord-player should detect api keys from `process.env` instead of having options?
> for example: `process.env.YOUTUBE_API_KEY` or `process.env.SPOTIFY_API_KEY`

Good idea.

**Comment by Majoramari** [comment]
> Yes, it could be possible. Actually we switched to scraping because a lot of users were ratelimited in a short period of time, but we could support both scraping and the official API.

i think discord-player should support ipv6 for requests to avoid ratelimit

**Comment by Spencer-0003** [comment]
This would be really helpful as my bot is getting rate limited.

**Comment by kimoVoid** [comment]
Fully agree with this

**Comment by Snowflake107** [comment]
> This would be really helpful as my bot is getting rate limited.

you mean youtube 429? If you are talking about youtube 429 then no, api keys wont solve your problem

**Comment by ThaddeusKKR** [comment]
API keys is a good idea and it would be even better if the module detected ratelimits and switched to scraping automatically so there would be lesser errors / close to none

+1

**Comment by Snowflake107** [comment]
@ThaddeusKKR yeah, if you are okay with slow response (api request > failed > scrape) 😀

**Comment by ThaddeusKKR** [comment]
> @ThaddeusKKR yeah, if you are okay with slow response (api request > failed > scrape) 😀

i guess once the api fails once it could be disabled until the bot instance is restarted / api is manually reenabled so the lag will only occur once, toggleable in player options would also work

**Comment by Snowflake107** [comment]
@ThaddeusKKR yeah, good idea. I will start working on api based youtube search

**Comment by Snowflake107** [comment]
You should be able to use `youtube api` like this:

```js
require("youtube-sr").default.set("api", "YOUTUBE_API_KEY");
```

it should automatically switch to `api mode`. And to go back to `scraper`, you can set it to `false` or use `YouTube.delete("api")`

**Comment by Snowflake107** [comment]
done for `YouTube`, not gonna do it for others (`soundcloud` uses api key when required)
