### ISSUE TITLE
Bug when disabling leaveOnEnd

### ISSUE THREAD

**Issue by Jimminer** [Androz2091/discord-player#247]
If leaveOnEnd is set to false, when the queue ends the last song remains in the queue and when you try to add another song the bot doesn't play anything. I searched inside the code and figured that this event would delete the empty queue but it doesn't work.

`bot.player.on('queueEnd', (message, queue) => {
    msg.channel.send(`The queue is empty!`);
    queue.stream.destroy();
    bot.player.queues.delete(queue);
} );`

Am I doing something wrong or is this an issue?

Edit: Fixed by doing this: `bot.player.queues.delete(queue.guildID);` instead of this: `bot.player.queues.delete(queue);`

**Comment by Bicepsfako** [comment]
I have opened [Pull Request](https://github.com/Androz2091/discord-player/pull/237) to fix that, @Androz2091 needs review it to commit.
