### ISSUE TITLE
voiceChannel.join is not a function

### ISSUE THREAD

**Issue by DeathMario** [Androz2091/discord-player#248]
I have this error when I try to play a song `voiceChannel.join is not a function`

**Comment by DeathMario** [comment]
Now nothing is happenning when i do m?play song

**Comment by andretunes** [comment]
Hello!

Can you add me on Discord so I can help you out? It's on my profile description.

Kind regards,
André

**Comment by Androz2091** [comment]
Closed due to inactivity
