### ISSUE TITLE
Win server r2 12 Not playing music

### ISSUE THREAD

**Issue by zarar2312** [Androz2091/discord-player#251]
Yeah big problem I wonder if there is a module missing? going in and out again

**Comment by Dark25** [comment]
The same thing happens to me.

**Comment by zarar2312** [comment]
something missing but what?

**Comment by Dark25** [comment]
I've found the solution

**Comment by zarar2312** [comment]
what? Would you tell me

**Comment by Dark25** [comment]
Yes

**Comment by Dark25** [comment]
![Screenshot_20210126_102853_com microsoft rdc android](https://user-images.githubusercontent.com/21024973/105826720-5556a280-5fc1-11eb-8353-da4e85249158.png)

You have to put .dll in that folder and then restart your bot

**Comment by zarar2312** [comment]
mfplat.dll ffmpeg-static module in paste?

**Comment by Dark25** [comment]
Yes

**Comment by zarar2312** [comment]
the listen command is not responding this time

**Comment by Dark25** [comment]
To see a screenshot

**Comment by zarar2312** [comment]
No log errors omg

**Comment by Dark25** [comment]
Have you modified anything?

**Comment by zarar2312** [comment]
npm i and start bot nothing modified .-.

**Comment by Dark25** [comment]
Before, what mistake did I give you?

**Comment by zarar2312** [comment]
no error appears :( bir şey eksik

**Comment by zarar2312** [comment]
my normal pc working on. and win server r2 12 server in not work

**Comment by zarar2312** [comment]
download link give me for mfplat.dll

**Comment by zarar2312** [comment]
l now have fixed problem. Server manager in server add roles in Features in:
![Screenshot_2021-03-02_201455](https://user-images.githubusercontent.com/24358398/109687191-0f7a9480-7b94-11eb-9757-fc2b5470bef4.jpg)
