### ISSUE TITLE
Pausing and Resuming the music

### ISSUE THREAD

**Issue by Twenty2kay** [Androz2091/discord-player#252]
Whenever I play a song and I pause the song when I try to resume the song it wont resume, but I wont get any errors in my console. I went to Zerio Dev's Discord for help  and it appears he is having the same exact issue as me.

**Comment by jameslinimk** [comment]
Same problem.

**Comment by Androz2091** [comment]
I will try to reproduce the issue

**Comment by aditya-learns** [comment]
Yes, I am having the same issue

**Comment by BearTS** [comment]
I can reproduce it

**Comment by BearTS** [comment]
Look at https://github.com/discordjs/discord.js/issues/5300
Seems to be a bug there

**Comment by jameslinimk** [comment]
Fix. Just do `npm i n -g`. Then do `n <version>` or if your on linux, `sudo n <version>`. Just select the latest v14 version. Hope this helps!

**Comment by BearTS** [comment]
> Fix. Just do `npm i n -g`. Then do `n <version>` or if your on linux, `sudo n <version>`. Just select the latest v14 version. Hope this helps!
> 
> Edit: Run `n`, and select your version. You might have to rebuild, reinstall, or delete your node_modules folder.

Bruh you are just saying to instal node v14 
We can do that with nvm or by any other method 
This is not a fix!!

**Comment by BearTS** [comment]
@Xapu1337 Actually resume does work, but only on 2nd attempt and it only happens in node v15.x 
Previous version of node js are not affected

**Comment by Snowflake107** [comment]
Use this if you are still getting this issue

```js
client.player.resume(message);
client.player.pause(message);
client.player.resume(message);
```
