### ISSUE TITLE
TypeError: client.on is not a function

### ISSUE THREAD

**Issue by isak-dombestein** [Androz2091/discord-player#254]
I just started implementing discord-player into my play command but just recently got this error that I'm having issues to figure out how to fix. 

![Screen Shot 2021-01-27 at 19 02 48](https://user-images.githubusercontent.com/50325393/106033693-50354880-60d2-11eb-82b6-ab75ccc768ca.png)

"client.on is not a function" in the Player.js file, line 113;
`// Listener to check if the channel is empty
        client.on('voiceStateUpdate', (oldState, newState) => this._handleVoiceStateUpdate(oldState, newState))`

I'm thinking it might be something to do with how I've set it up in my document. I've attached the code I have in my play.js command file below.

Could it be that the way I've set up my play command makes it incompatible with discord-player in it's current state? I've tried looking through some of the documentation to see how I could implement it better but I didn't see any other way that didn't mean completely rewriting the entire document.

`
module.exports = {
  name: "?play",
  description: "Plays a song or video from YouTube",
  async execute(msg, args) {

    // Discord and Client import
    const discord = require('discord.js');
    const { Util } = require("discord.js");
    const client = require("../bot_old.js");

    //EMBED SETUP
    //Set up the playEmbed for later use
    const playEmbed = new discord.MessageEmbed();
    playEmbed.setTitle("Play command usage");
    playEmbed.setColor("AQUA");
    playEmbed.addField("Usage", "To use this command, type =play and copy in the link to the YouTube video you want played or enter a search term.", "");
    playEmbed.setTimestamp();

    //Set up an errorVoiceEmbed in case someone is not in a voice channel
    const errorVoiceEmbed = new discord.MessageEmbed();
    errorVoiceEmbed.setTitle("Play Error");
    errorVoiceEmbed.setColor("RED");
    errorVoiceEmbed.addField("Error:", "You must be in a voice channel before you can play a song!", "");
    errorVoiceEmbed.setTimestamp();

    //Set up an wrongChannelEmbed in case the user is in a different voice channel than the bot
    const wrongChannelEmbed = new discord.MessageEmbed();
    wrongChannelEmbed.setTitle("Play Error");
    wrongChannelEmbed.setColor("RED");
    wrongChannelEmbed.addField("Error:", "You're in a different voice channel than me! Move me or join the same channel I'm in before playing music.");
    wrongChannelEmbed.setTimestamp();

    //Set up a noResultsEmbed if we can't find any results for the search query
    const noResultsEmbed = new discord.MessageEmbed();
    noResultsEmbed.setTitle("Play error");
    noResultsEmbed.setColor("RED");
    noResultsEmbed.addField("Whoops...", "No results were found for that search term. Please try again.");
    noResultsEmbed.setTimestamp();

    //Set up our queuedEmbed
    const queuedEmbed = new discord.MessageEmbed();
    queuedEmbed.setTitle("Play");
    queuedEmbed.setColor("AQUA");
    queuedEmbed.addField("Queue", "Added track to the queue");
    //queuedEmbed.addField("Queue", `Added ${Util.escapeMarkdown(song.name)} by ${Util.escapeMarkdown(song.author)} to the queue!`);
    queuedEmbed.setTimestamp();

    //Set up our playingEmbed
    const playingEmbed = new discord.MessageEmbed();
    playingEmbed.setTitle("Play");
    playingEmbed.setColor("AQUA");
    //playingEmbed.addField("Play", `Now playing:\n${song.name}`);
    playingEmbed.setTimestamp();

    //Set up the completedEmbed
    const completedEmbed = new discord.MessageEmbed();
    completedEmbed.setTitle("Play");
    completedEmbed.setColor("AQUA");
    completedEmbed.addField("Queue", "Queue finished. Add some more tracks to enjoy!");
    completedEmbed.setTimestamp();

    // permsEmbed for when we don't have perms
    const permsEmbed = new discord.MessageEmbed();
    permsEmbed.setTitle("Play Error");
    permsEmbed.setColor("RED");
    permsEmbed.addField("Error:", "You do not have the correct permissions to execute this command!", "");
    permsEmbed.setTimestamp();

    //Setting up dependencies
    const ytdl = require("ytdl-core");
    const ytSearch = require("yt-search");
    const voiceChannel = msg.member.voice.channel;
    const { Player } = require("discord-player");
    const player = new Player(client);
    client.player = player;

    // Create our Queue Array for later
    var servers = {};
    var server = servers[msg.guild.id];

    server.queue.shift();

    // Check if user is in voiceChannel
    if (!voiceChannel) return msg.channel.send(errorVoiceEmbed);

    //Check if the user is in the same voice channel as the bot. Returns error if not.
    if (msg.guild.me.voice.channel && msg.member.voice.channel.id !== msg.guild.me.voice.channel.id) {
      msg.channel.send(wrongChannelEmbed);
    }

    // Check if we have the correct permissions
    const permissions = voiceChannel.permissionsFor(msg.client.user);
    if (!permissions.has("CONNECT")) return msg.channel.send(permsEmbed);
    if (!permissions.has("SPEAK")) return msg.channel.send(permsEmbed);

    // Check if a second argument has been passed
    if (!args.length) return msg.channel.send(playEmbed);

    // Validating the passed URL
    const validURL = (str) => {
      var regex = /(http|https):\/\/(\w+:{0,1}\w*)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%!\-\/]))?/;
      if (!regex.test(str)){
          return false;
        } else {
          return true;
        }
      }

      // If we have a valid URL, load it and play the audio
      if(validURL (args[0])){
        const connection = await voiceChannel.join();
        const stream = ytdl(args[0], queue[0], {filter: 'audioonly'});

        connection.play(stream, {seek: 0, volume: 1})

        // Leave when done
        .on('finish', () => {
          if (server.queue[0]){
            voiceChannel.leave();
            msg.channel.send(completedEmbed);
          }
        });
        await msg.reply(playingEmbed);

        return
      }

      const connection = await voiceChannel.join();

      // If a user enters a search query instead of a link, Search YouTube and play a result.
      const videoFinder = async (query) => {
        const videoResult = await ytSearch(query);

        return (videoResult.videos.length > 1) ? videoResult.videos[0] : null;
      }

      const video = await videoFinder(args.join(' '));

      if (video) {
        const stream = ytdl(video.url, {filter: 'audioonly'});

        connection.play(stream, queue[0], {seek: 0, volume: 1})
        .on('finish', () => {
          if (server.queue[0]) {
            voiceChannel.leave();
            msg.channel.send(completedEmbed);
          }
        });

        await msg.reply (playingEmbed);
      } else {
        msg.channel.send(noResultsEmbed);
      }
    }
  }
`

My code might also just be flawed although it works pretty nicely on it's own from the testing I did before I added discord-player. I'm just resorting to it for the queue functionality it has.

**Comment by Snowflake107** [comment]
you are not supposed to instantiate discord player in each command files. Add `client.player = new Player(client)` in your main file where you have declared `client` (instantiated discord.js client).
