### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by mozzi-berilinky** [Androz2091/discord-player#259]
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closing listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit
how to fix it??
I think this link can solve the problem, but I don't know how to do it.

https://github.com/eritislami/evobot/issues/203

**Comment by Snowflake107** [comment]
It's because your code is adding an event listener each time you call discord player's play method.

**[ref](https://github.com/eritislami/evobot/blob/93351dd73d9eef23268fa4f770ac00d992164504/include/play.js#L48)**

**Comment by Snowflake107** [comment]
If you are using that code or something similar to that, you are probably adding one event listener (+1 basically) when a command is executed.
