### ISSUE TITLE
Improvement to addToQueue

### ISSUE THREAD

**Issue by atulya2109** [Androz2091/discord-player#26]
Fetch song details when the song changes instead of fetching them as soon as the song is queued. Without this, developers need to implement a setTimeout in case they need to queue multiple songs or else they are rate limited by the Youtube API. This problem could be solved if song data is fetched before it starts playing.

**Comment by Androz2091** [comment]
Yes, it's a good idea

**Comment by Androz2091** [comment]
Also, when you said "fetching" the song, can you give me the line? You mean with SimpleYoutubeAPI? or with ytdl?

**Comment by atulya2109** [comment]
I meant SimpleYoutbeApi and I don't think ytdl uses any kind of API. By the way, I used your library to code my own discord bot to play songs playlists on Spotify but I figured out that I was exhausting my 10k queries a day quota pretty quick. 
With some googling around, I found out that each API call is not counted as one but has a cost associated with it. For example, the search endpoint has a 100 cost, so one query to that endpoint cost 100 from the daily quota. 
With a playlist of 37 songs, I reached my daily quota after I queued the playlist 8 times during development. And that is on one guild if a bot joins several guilds, it will exhaust the quota pretty quick. So, instead of fetching results from the youtube API, it's better if the library does some web scraping. That way the developers wouldn't have to care about crossing the daily limits and I believe that's pretty much what other music bots on spotify are doing.
This enhancements warrants a issue of its own so I'm going to open one

**Comment by atulya2109** [comment]
#27

**Comment by atulya2109** [comment]
If #27 is implemented then this issue won't be a problem

**Comment by Androz2091** [comment]
#27 has been implemented, I'm closing this issue.
