### ISSUE TITLE
This video is only available to Music Premium members 

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-player#262]
![image](https://user-images.githubusercontent.com/63650909/106372177-2468cb80-633b-11eb-8a08-32e42ebb5c96.png)
Song: 心臓を捧げよ！
Link: https://www.youtube.com/watch?v=8QPyFlJNmus&list=PLc4FwQ3tNBinaDSpgqf30cjBTpMZU0kI5&index=22

**Comment by Snowflake107** [comment]
This error is not from `discord-player`. Try asking **[here](https://github.com/fent/node-ytdl-core/issues)**
