### ISSUE TITLE
[BUG] Queue on end keep showing as playing.

### ISSUE THREAD

**Issue by jurgenjacobsen** [Androz2091/discord-player#264]
When the last song of a queue gets to it's end the bot still show that the song is playing and when I try to play something else it just add to queue and never plays it.

**Comment by BySantino12** [comment]
I'm have the same problem, but i'm say (prefix)!skip and the bot crash

**Comment by Androz2091** [comment]
> the bot crash

Are you getting any error in the terminal?

**Comment by Androz2091** [comment]
@jurgenjacobsen we will need more information.. I mean I can't reproduce the bug so if you still have the problem can you provide more information? The song you're trying to play, the version of discord-player, discord.js, the encoder you're using, etc.

**Comment by jaypm123** [comment]
same with me when I add leaveonend = false
