### ISSUE TITLE
 Auto disconnection at the end of the queue

### ISSUE THREAD

**Issue by RMFireSteel** [Androz2091/discord-player#265]
Good morning all,
Here I would like to be able to implement a delay before the bot disconnects when there is no more music in the queue. Do you have a solution ?

**Comment by LePtitMetalleux** [comment]
See https://discord-player.js.org/global.html#PlayerOptions

**Comment by Snowflake107** [comment]
You should do something like this:

```js
const player = new Player(client, {
    leaveOnEndCooldown: 5000, // wait for 5 seconds
    leaveOnEnd: true
})
```

Other options are mentioned **[here](https://discord-player.js.org/global.html#PlayerOptions)**
![image](https://user-images.githubusercontent.com/46562212/106997700-6e263b80-67ab-11eb-89d2-e65d61d7cdbe.png)

**Comment by RMFireSteel** [comment]
@Snowflake107  It works perfectly thanks to you. Thank you for responding so quickly. Have a good day !

**Comment by TauchMe** [comment]
In which file?

**Comment by TauchMe** [comment]
> You should do something like this:
> 
> ```js
> const player = new Player(client, {
>     leaveOnEndCooldown: 5000, // wait for 5 seconds
>     leaveOnEnd: true
> })
> ```
> 
> Other options are mentioned **[here](https://discord-player.js.org/global.html#PlayerOptions)**
> ![image](https://user-images.githubusercontent.com/46562212/106997700-6e263b80-67ab-11eb-89d2-e65d61d7cdbe.png)

In which file?
