### ISSUE TITLE
Skip probably don't work properly

### ISSUE THREAD

**Issue by AkumaKitty** [Androz2091/discord-player#266]
When you skip a song and there is any songs in the queue, queue still show up even if I change in your code lastSkipped on false. But this is not probably a problem. The problem is when I skip the last song and there are no songs in the queue I can't add a new song to queue because against playing it writes "Queued a song" and after leaveOfEnd time it leave. It add a new track to the Queue but it add it on second position and don't play it after queue end. Something is probably wrong in your code.
![3](https://user-images.githubusercontent.com/65132581/107158975-a5ecd900-698d-11eb-8507-c722749935b6.png)

![1](https://user-images.githubusercontent.com/65132581/107158896-2a8b2780-698d-11eb-9e9d-9d02fbf9af99.png)
![2](https://user-images.githubusercontent.com/65132581/107158898-2b23be00-698d-11eb-8711-ac3e45913dcc.png)

**Comment by Androz2091** [comment]
Hello :wave:
Thank you for reporting this issue. It has been fixed in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1).
