### ISSUE TITLE
Seek Feature

### ISSUE THREAD

**Issue by saeed-Underline** [Androz2091/discord-player#267]
is it possible to seek through song duration ?

**Comment by Snowflake107** [comment]
Implemented in #236

**Comment by saeed-Underline** [comment]
thanks it helped a lot.

**Comment by Androz2091** [comment]
This is going to be added in the next release 👍

**Comment by Androz2091** [comment]
Hello :wave:
This has been added in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1).
