### ISSUE TITLE
Maybe 700+ websites support with youtube-dl?

### ISSUE THREAD

**Issue by TheSpoiledSnail** [Androz2091/discord-player#269]
## Maybe using youtube-dl for 700+ website support?

Idk, but I heard youtube-dl supports 700+ websites; and it may help the package to support a lot of URLs. This is only my opinion, I accept criticism on this suggestion.

**Comment by Snowflake107** [comment]
No, it makes the library too heavy. If you want to use youtube-dl based library, you can try **[distube](https://npmjs.com/package/distube)**.
