### ISSUE TITLE
[ENHANCEMENT] Move from Youtube API to traditional web scraping

### ISSUE THREAD

**Issue by atulya2109** [Androz2091/discord-player#27]
It is not feasible to use `simple-youtube-api` or the **Youtube API** because the daily quota exhausts pretty quickly.

With some googling around, I found out that each API call is not counted as one but has a cost associated with it. For example, the search endpoint has a **100 cost**, so one query to that endpoint cost 100 from the daily quota.

With a playlist of **37 songs**, I reached my daily quota after I queued the playlist **8 times** during development. And that is on one guild, if a bot joins several guilds it will exhaust the quota pretty quick. So, instead of fetching results from the Youtube API, it's better if the library does some **web scraping**. 

That way the developers wouldn't have to care about crossing the daily limits and I believe that's pretty much what other music bots on **_Discord_** are doing.

**Comment by APartOfMe1** [comment]
This issue is annoying, but somewhat preventable. I use quite a few api keys and have the bot choose a random one to use whenever a music command is run. It's obviously not a perfect solution by any means, but it's definitely better than just using one key.

**Comment by Androz2091** [comment]
@APartOfMe1 we are currently working on the next discord-player version ([develop](https://github.com/Androz2091/discord-player/tree/develop) branch) which is now using scraping.

**Comment by Androz2091** [comment]
Discord Player v2 is now using scraping.
