### ISSUE TITLE
Not playing same songs from spotify like other music bots

### ISSUE THREAD

**Issue by jaypm123** [Androz2091/discord-player#272]
I am facing an issue with spotify links. It plays the songs from spotify links but other songs from the same author. Some people will say that that happens because that song does not exist on youtube. But that's not possible. Because other music bots are playing same songs from youtube. So please fix this issue. 🤗
BTW, my honest review is 9/10.

**Comment by Androz2091** [comment]
Hello @jaypm123, could you send an example please? (the spotify link of the song you're trying to play and the name of the song the package plays instead)

**Comment by jaypm123** [comment]
Hello sir,

Here is the list of those Spotify links which I found that playing other songs:
https://open.spotify.com/track/018eOid2aGaPdxon7T6GsC?si=2Vbo_RfaRSu9WGuBAoqF0w
https://open.spotify.com/track/1wbxjQnN7MTk8MKt3SumyY?si=KmtGlNCFQACQqtMSHCBvzA
https://open.spotify.com/track/7fyiYhn7STpHvT5g0lbncC?si=uq1JcqVPR6isSKcNoT5avw
https://open.spotify.com/track/6TFESXMfJJWwccviaxGAMa?si=_jwXX6xERa-vnVF7-GKYYQ
https://open.spotify.com/track/5w0Xpt2YHT2Y3z3e4UUJP7?si=t-dcVSERSJmzX_RQ7_m6lw
https://open.spotify.com/track/3hkC9EHFZNQPXrtl8WPHnX?si=f1Nb_QebQz-7a4nOMPbSIw

And I have some other questions also:
1) When will it support Spotify playlists?2) Remove command- I added but when I give `remove 3` bot removes 2nd song! Suggest me how to solve that(const of a track)
3) I added leaveonempty = false (so the problem is when a song finishes or skips bot still shows that song as now playing song and using play command bot shows that song added in the queue.)

Please solve my these queries!!!

**Comment by jameslinimk** [comment]
> Hello sir,
> 
> Here is the list of those Spotify links which I found that playing other songs:
> https://open.spotify.com/track/018eOid2aGaPdxon7T6GsC?si=2Vbo_RfaRSu9WGuBAoqF0w
> https://open.spotify.com/track/1wbxjQnN7MTk8MKt3SumyY?si=KmtGlNCFQACQqtMSHCBvzA
> https://open.spotify.com/track/7fyiYhn7STpHvT5g0lbncC?si=uq1JcqVPR6isSKcNoT5avw
> https://open.spotify.com/track/6TFESXMfJJWwccviaxGAMa?si=_jwXX6xERa-vnVF7-GKYYQ
> https://open.spotify.com/track/5w0Xpt2YHT2Y3z3e4UUJP7?si=t-dcVSERSJmzX_RQ7_m6lw
> https://open.spotify.com/track/3hkC9EHFZNQPXrtl8WPHnX?si=f1Nb_QebQz-7a4nOMPbSIw
> 
> And I have some other questions also:
> 
> 1. When will it support Spotify playlists?
> 2. Remove command- I added but when I give `remove 3` bot removes 2nd song! Suggest me how to solve that(const of a track)
> 3. I added leaveonend = false (so the problem is when a song finishes or skips bot still shows that song as now playing song and using play command bot shows that song added in the queue.)
> 
> Please solve my these queries!!!

**Bro read the docs**
1: Yes, read the docs
2: An array starts from 0. IE: It counts 0, 1, 2, 3. So just subtract 1.
3: Read the docs -_-.
```js
const player = new Player(client, {
	leaveOnEmpty: false
});
```

**Comment by jaypm123** [comment]
1: Done!

2: 
`const removesong = (args[0] - 1);`
`this.client.player.remove(message, removesong)`
(Not solved)

3: 
```this.player = new Player(this, {
			leaveOnEmpty: false,
			leaveOnEnd: false
})```
(Still having the same issue, https://github.com/Androz2091/discord-player/issues/264)

**Comment by jaypm123** [comment]
BTW, Spotify playlists are working perfectly.
I mean playing the same songs.

**Comment by jameslinimk** [comment]
> 1: Done!
> 
> 2:
> `const removesong = (args[0] - 1);`
> `this.client.player.remove(message, removesong)`
> (Not solved)
> 
> 3:
> `this.player = new Player(this, { leaveOnEmpty: false, leaveOnEnd: false })`
> (Still having the same issue, #264)
> edit: 3rd issue has been solved

Learn JS. args[0] is a **string**. You can subtract a **number** from a **string**. Use `parseInt(args[0])` instead.

**Comment by jaypm123** [comment]
sorry, but I am new admission in coding!!!
