### ISSUE TITLE
[BUG] with leaveOnEndCooldown

### ISSUE THREAD

**Issue by RMFireSteel** [Androz2091/discord-player#276]
Hello World !
When the leaveOnEndCooldown is active, the bot waits for the time chosen beforehand but it does not execute any more commands during this waiting period ... Do you know how to solve this problem?

**Comment by Androz2091** [comment]
Hello :wave:
Thank you for reporting this issue. It has been fixed in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1).
