### ISSUE TITLE
Handle YTDL stream errors

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-player#278]
Go to `/node_modules/discord-player/src/Player,js`, and on line 688 (right before the `setTimeout()`) add this:
```js
newStream.on('error', (error) => this.emit('error', error, queue.firstMessage))
```
Now on any discord-yltd-player error, instead of crashing your bot, it will emit a new error on the player.

**Comment by Androz2091** [comment]
Hello @jameslinimk, thank you for sharing this! it will be added soon 👍

**Comment by jameslinimk** [comment]
> Hello @jameslinimk, thank you for sharing this! it will be added soon 👍

Thanks!!!!!!!!
