### ISSUE TITLE
Error: Video unavailable

### ISSUE THREAD

**Issue by L061571C5** [Androz2091/discord-player#279]
Whenever I try to play any link from Youtube I get this error 
`(node:4692) UnhandledPromiseRejectionWarning: Error: Video unavailable
    at Object.exports.playError (C:\TubbBot\node_modules\ytdl-core\lib\utils.js:124:12)
    at validate (C:\TubbBot\node_modules\ytdl-core\lib\info.js:53:25)
    at pipeline (C:\TubbBot\node_modules\ytdl-core\lib\info.js:174:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (C:\TubbBot\node_modules\ytdl-core\lib\info.js:62:14)
(node:4692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`.

**Comment by Androz2091** [comment]
Looks like you're trying to play a song unavailable in your country

**Comment by L061571C5** [comment]
> Looks like you're trying to play a song unavailable in your country

Hmm, I can play it on youtube, or is that different?

**Comment by Snowflake107** [comment]
> > Looks like you're trying to play a song unavailable in your country
> 
> Hmm, I can play it on youtube, or is that different?

is your bot running from your computer? or is it hosted somewhere else??

**Comment by L061571C5** [comment]
> > > Looks like you're trying to play a song unavailable in your country
> > 
> > 
> > Hmm, I can play it on youtube, or is that different?
> 
> is your bot running from your computer? or is it hosted somewhere else??

Yes, I host it on my computer.

**Comment by L061571C5** [comment]
This is an issue with ytdl-core because I ran `console.log(ytdl.getInfo('https://www.youtube.com/watch?v=dQw4w9WgXcQ'))` and it still returned the error.

**Comment by L061571C5** [comment]
> Looks like you're trying to play a song unavailable in your country

Well, I'm an idiot and lowercased the links so yea...
