### ISSUE TITLE
Multiple event emitting

### ISSUE THREAD

**Issue by L061571C5** [Androz2091/discord-player#280]
Some events are emitted more than once like 'trackStart' and 'trackAdd'.
![discord-player bugs](https://user-images.githubusercontent.com/70660308/108444994-3f837880-7221-11eb-8391-85e9dc7f6f99.PNG)

**Comment by jameslinimk** [comment]
> Some events are emitted more than once like 'trackStart' and 'trackAdd'.
> ![discord-player bugs](https://user-images.githubusercontent.com/70660308/108444994-3f837880-7221-11eb-8391-85e9dc7f6f99.PNG)

Weird... That doesn't happen with me. May you send some code? For me, it only emits trackAdd when there is a song playing in the queue.

**Comment by L061571C5** [comment]
` client.player.on('trackAdd', (message, queue, track) => {
            const embed = new Discord.MessageEmbed()
                .setColor('#FFED00')
                .setTitle(`:musical_note: ${track.title}`)
                .addField(
                    `Has been added to queue. `,
                    `This song is #${queue.tracks.length} in queue`
                )
                .setThumbnail(track.thumbnail)
                .setURL(track.url)
            message.channel.send(embed)
        })` Heres my code for 'trackAdd'.

**Comment by Androz2091** [comment]
Can you send your complete code please? (of all your bot)

**Comment by L061571C5** [comment]
> Can you send your complete code please? (of all your bot)

Yes I have a repository for it [here](https://github.com/L061571C5/TubbBot).

**Comment by Androz2091** [comment]
@L061571C5 You **should not** use the `trackStart` event **inside** your play.js file. It should only be in your main file.

**Comment by L061571C5** [comment]
Ok, thanks.
