### ISSUE TITLE
Use channel.join() instead of message.guild.voice.setChannel()

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-player#282]
Change line `490` to `channel.join()` instead of `message.guild.voice.setChannel()` channel.join is much more reliable, and for me message.guild.voice is undefined half of the time.

**Comment by Androz2091** [comment]
Thank you, it has been fixed. Yes, because you can't access `message.guild.voice` if the bot is not connected to a voice channel

**Comment by jameslinimk** [comment]
> Thank you, it has been fixed. Yes, because you can't access `message.guild.voice` if the bot is not connected to a voice channel

Tf i go away for like 2.7 seconds and you replied? It 2am here jeez!

**Comment by Androz2091** [comment]
Haha, it's 8:27 am for me in France :smile:
