### ISSUE TITLE
Idea: createProgressBar for queue

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-player#283]
On `createProgressBar` add an option to either get a progress bar of the current song, or whole queue. The way I got it is by looping through each track in the tracks, and adding it to an array, then using that as the totalTime.

**Comment by Androz2091** [comment]
Use #281 for discussing this feature

**Comment by Androz2091** [comment]
This has been added in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1).
