### ISSUE TITLE
[BUG] leaveOnEndCooldown

### ISSUE THREAD

**Issue by RMFireSteel** [Androz2091/discord-player#289]
Hello World ! 
Despite the update of discord player to 3.3.2, the Player leaveOnCoolDown function does not allow you to execute commands once the count has been started ... 
Can you help me ? Thanks

**Comment by Androz2091** [comment]
Hello,
I can't reproduce the bug, it works perfectly for me:

![Capture d’écran 2021-02-20 à 19 08 35](https://user-images.githubusercontent.com/42497995/108604571-0f69e000-73af-11eb-9eb4-00c29ea9d4ae.png)

(the bot has not left the channel between the end and the new play)

**Comment by RMFireSteel** [comment]
The problem comes from the fact that it does not execute any more commands during its waiting time. Whereas before the commands were working. 
The bot waits the time requested before leaving the voice room but it does not execute the requested commands.
