### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by ba-e** [Androz2091/discord-player#29]
You can add [youtube-dl](https://www.npmjs.com/package/youtube-dl) option because its better

**Comment by cembkoztekin** [comment]
Maybe it can be good

**Comment by Androz2091** [comment]
We won't use [youtube-dl](https://www.npmjs.com/package/youtube-dl) as the next version of discord-player will support filters, and we will use [discord-ytdl-core](https://npmjs.com/discord-ytdl-core). You can also fork the repository to use youtube-dl but I think filters are more interesting than this small improvement 👍
