### ISSUE TITLE
queueCreate event is also working as trackStart event

### ISSUE THREAD

**Issue by jaypm123** [Androz2091/discord-player#292]
when you play a song 1st-time bot will declare song two times.
Once as playlist started(queueCreate) and now playing(trackStart)

And please help me with these doubts:
1. How to add playlist track count, name in `queueCreate` event
2. How to add playlist track count, name in `playlistAdd` event

**Comment by Androz2091** [comment]
You don't need to listen to the queueCreate event

**Comment by Androz2091** [comment]
```js
.on('playlistAdd', (message, queue, playlist) => {
	console.log(playlist.tracks.length);
}); 
```
