### ISSUE TITLE
Add queue duration property

### ISSUE THREAD

**Issue by MrPerfectShot** [Androz2091/discord-player#293]
I think its a good idea add duration of all music/videos on queue. Like One Video have 5 minutes and another video have 1 hour, the duration is 1 hour and 5 minutes. Sorry If its not the best place to send my suggestion.

**Comment by jameslinimk** [comment]
> I think its a good idea add duration of all music/videos on queue. Like One Video have 5 minutes and another video have 1 hour, the duration is 1 hour and 5 minutes. Sorry If its not the best place to send my suggestion.

Good idea! But theres a way to do it currently. Just install `npm i pretty-ms`, and use this:
```js
let totalLength = 0;
queue.tracks.forEach(e => totalLength = totalLength + e.durationMS);
```
And then:
```js
const prettyMilliseconds = require('pretty-ms');
totalLength = prettyMilliseconds(totalLength);
```

**Comment by Androz2091** [comment]
We could add a `queue.durationMS` or something like that yes

**Comment by L0SER8228** [comment]
Add `queue.currentDurationMS` too

**Comment by Androz2091** [comment]
already available at `currentStreamTime`
