### ISSUE TITLE
Support for deezer links

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#295]
support [Deezer](https://www.deezer.com) links ( [deezer-public-api](https://www.npmjs.com/package/deezer-public-api) can be used) to get the song name and the song author and then search with these terms on YouTube

**Comment by Snowflake107** [comment]
marking this as `done`. You can always use `Extractor API` to build your custom extractor (rewrite version)

**Comment by skdhg** [comment]
https://github.com/retrouser955/discord-player-deezer
