### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('NotPlaying')

### ISSUE THREAD

**Issue by Bruno963max** [Androz2091/discord-player#298]
When a use "pause command": 

    if(command == prefix + "pause") {
        if(!message.member.voice.channel) return message.reply("You are not in a voice")
        client.player.pause(message);
    }

he send me in the console : Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('NotPlaying') #

**Comment by jameslinimk** [comment]
> When a use "pause command":
> 
> ```
> if(command == prefix + "pause") {
>     if(!message.member.voice.channel) return message.reply("You are not in a voice")
>     client.player.pause(message);
> }
> ```
> 
> he send me in the console : Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('NotPlaying') #

**read**. It says **NotPlaying**. It means nothing is playing on the server...

**Comment by KASav1** [comment]
Yes, but a single is saying is that the problem.

**Comment by KASav1** [comment]
I have the same problem, but a music is playing
