### ISSUE TITLE
New README

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#30]
Hey! I am currently in the process of rewriting the README for the Discord Player package so that it is up to date for everyone. Once I complete it, would you be happy for me to make a pull request with the new README?

Here is what I have so far:
![image](https://user-images.githubusercontent.com/43547293/84680769-1e001d80-af2b-11ea-9122-6c5e7d97c47c.png)

**Comment by Androz2091** [comment]
Nice! All right yes.

**Comment by thomasthebro1** [comment]
Will reopen when I come around to do this again.
