### ISSUE TITLE
Error cannot read property 'player' of undefined

### ISSUE THREAD

**Issue by FSCYT** [Androz2091/discord-player#301]
I get this error `TypeError: Cannot read property 'player' of undefined`

My code:
```js
this.client.player.on('trackAdd', (message, queue, track) => {
    const durBar = client.player.createProgressBar(message, {
        timecodes: true,
    });
    const embed = new MessageEmbed()
        .setColor('RANDOM')
        .setTitle(track.title)
        .setAuthor('Song added to queue!')
        .setFooter(message.author.username, message.author.displayAvatarURL())
        .setURL(track.url)
        .setThumbnail(track.thumbnail)
        .setDescription(
            `
        **Song duration:** ${track.duration}`
        );
    message.channel.send(embed);
})
```

Client file:
```js
const {Player} = require("discord-player")

class client extends Client {
    constructor() {
        super({
            /* Discord.js Client Options */
            disableMentions: 'everyone',
        });

        this.player = Player;

```

Even my IDE (WebStorm) Can Identify:
![image](https://user-images.githubusercontent.com/73798815/108972730-a88d4500-7694-11eb-9c03-d925ede7a465.png)

**Comment by Dev-CasperTheGhost** [comment]
You're setting the value incorrectly. Should be like this:

```js
class Client extends Client {
   constructor() {
        super({
            /* Discord.js Client Options */
            disableMentions: 'everyone',
        });

        this.player = new Player({
 			// options
		});
   ...
}

**Comment by FSCYT** [comment]
> You're setting the value incorrectly. Should be like this:
> 
> ```js
> class Client extends Client {
>    constructor() {
>         super({
>             /* Discord.js Client Options */
>             disableMentions: 'everyone',
>         });
> 
>         this.player = new Player({
>  			// options
> 		});
>    ...
> }
> ```

I realized that after posting this. Im quite new to making a seperate file for the Client so I didn't understand much.
But thanks for replying!
