### ISSUE TITLE
play / pause doesn't work.

### ISSUE THREAD

**Issue by Xapu1337** [Androz2091/discord-player#303]
When pausing the current song i can't resume, It just doesn't do anything.

**Comment by Xapu1337** [comment]
`case "pause":
                   await client.player.pause(message);
                   client.api.interactions(interaction.id, interaction.token).callback.post({
                   data: {
                       type: 3,
                       data: {
                           flags: 64,
                           content: "✔ | Pausing..."
                       }
                    }
                   });                   
                   break;
               case "resume":
                   await client.player.resume(message);
                   client.api.interactions(interaction.id, interaction.token).callback.post({
                       data: {
                           type: 3,
                           data: {
                               flags: 64,
                               content: "✔ | Resuming..."
                           }
                       }
                   });
                   break;`

**Comment by hands8142** [comment]
The same problem happens to me, but I don't know how to solve it. I'm sorry I couldn't be of help.

**Comment by Androz2091** [comment]
Duplicate of #252
