### ISSUE TITLE
QueueEnd Event emitted when you add music - Bug

### ISSUE THREAD

**Issue by MrPerfectShot** [Androz2091/discord-player#304]
Hello now i have the latest version (3.4.0) and when i try to play a music by link or name bot joins in channel but leaves after 3 seconds emitting QueueEnd Event. My code is working on 3.3.2.
`bot.player.play(message, args.join(" "), { firstResult: true });` - play Command And events its are the same as the documentation basically

**Comment by MrPerfectShot** [comment]
Yeah i confirm when you update for lastest version if you try to play a song bot joins in channel but leaves after 3 seconds

**Comment by hands8142** [comment]
I'm working normally. Can you send me a YouTube video url?

**Comment by hands8142** [comment]
https://discord-player.js.org/Player.html#play

Look at this. You should write like this.

`bot.player.play(message, args.join(" "), true);`

**Comment by MrPerfectShot** [comment]
I tried with any music from youtube, and i just update Packard to latest version and all stopped working. And if i tried to revert and try to install 3.3.2 again i cam install it but dont work. But if i dont do nothing and use 3.3.2 all code its working

**Comment by MrPerfectShot** [comment]
I tried again uninstalling discord-player and install it again and i cant play music bot disconnect after 3 seconds

**Comment by Dev-CasperTheGhost** [comment]
> I tried again uninstalling discord-player and install it again and i cant play music bot disconnect after 3 seconds.

You have `FFMpeg` and `@discordjs/opus` installed?

**Comment by MrPerfectShot** [comment]
Yes, all worked before i tried to install new version of discord-player

**Comment by MrPerfectShot** [comment]
I tried to transfer through Github and replace everything works if you do npm i discord-player stops working

**Comment by MrPerfectShot** [comment]
Im the only one with this bug?

**Comment by Beowulf50** [comment]
> Im the only one with this bug?

I'm having the same issue
