### ISSUE TITLE
error with node_modules

### ISSUE THREAD

**Issue by Anto010** [Androz2091/discord-player#306]
when i start the bot i get this error: /home/runner/papera-music/node_modules/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails? .default.url,
                                                                 ^

SyntaxError: Unexpected token '.'

**Comment by zyrouge** [comment]
Code?

**Comment by Dev-CasperTheGhost** [comment]
@Anto010 Make sure that you're on version 14 of node.js

**Comment by Anto010** [comment]
i just noticed that node moved from version 14 to 12, thanks for the support
