### ISSUE TITLE
FFMPEG is not installed, not precise error message ?

### ISSUE THREAD

**Issue by Zargith** [Androz2091/discord-player#307]
Longtime I didn't wokd on my bot so I updated my depndencies and when starting my bot I got this error message:
`FFMPEG is not installed. Install with "npm install ffmpeg-static" or download it here: https://ffmpeg.org/download.html.`

But I have FFMPEG installed (and up-to-date) since a long time !
Tryed many things, like to install ffmpeg-static, and update my dependencies but nothing worked.

So I went in source code to find where the message came from. And I found this function :
https://github.com/Androz2091/discord-player/blob/bc2f44520d5a162ad96f768dd51d05545adaadf8/src/Util.js#L16

And if I understand well, you're getting the dependence *prism-media* (that is installed through another dependency (like@discordjs/opus))

So to fix the error I just had to update to @discordjs/opus to **latest** (don't know why npm wouldn't install latest just by using `npm i @discordjs/opus`)!

I think to add to the message to update (to latest) dependencies could help people to understand the error ! 😃 

NB to those who may read later this issue and that don't know how to update to latest:
`the_dependence_name@latest`

**Comment by Snowflake107** [comment]
👍🏻
