### ISSUE TITLE
Add queue.currentStreamTime to the docs? And add queue.totalTime to the docs.

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-player#309]
`queue.currentStreamTime` seems very useful sometimes, and it would be nice to see this in the docs. Also, `queue.totalTime` is missing from the docs.

**Comment by Dev-CasperTheGhost** [comment]
Made a PR for this :) #308

**Comment by jameslinimk** [comment]
> Made a PR for this :) #308

Thanks!
