### ISSUE TITLE
queueEnd is emitted when queue length is 1

### ISSUE THREAD

**Issue by YayLOfficial** [Androz2091/discord-player#312]
![image](https://user-images.githubusercontent.com/75476395/109426725-62ffad80-79ef-11eb-95ce-562e66e14060.png)

This line causes an issue where if the queue length is 1 it will just quit the queue meaning you are not able to use the play feature.
`if (queue.tracks.length === 1 && !queue.loopMode && !queue.repeatMode && !firstPlay) {`

I could have miss interpreted the code but I believe the 1 should be changed to a 0

The problem was brought upon because the bot kept just leaving the channel and sending the message brought upon by the 'queueEnd' event. So I searched for the problem in my code but was eventually unable to find something which would cause it so looked into the player and find this in the _playTrack.

**Comment by YayLOfficial** [comment]
And isn't the queue.stopped part of:
![image](https://user-images.githubusercontent.com/75476395/109428343-0bfdd680-79f7-11eb-9f99-4e5238acd521.png)
redundant because of the `if(queue.stopped) return` at the top

**Comment by Snowflake107** [comment]
looks like this is not happening in the latest version

# Ref 1
![image](https://user-images.githubusercontent.com/46562212/116722319-f5c3c500-a9fd-11eb-8f22-33c9c59e109a.png)

# Ref 2
![image](https://user-images.githubusercontent.com/46562212/116722369-070cd180-a9fe-11eb-8173-47e71c2e0adf.png)
