### ISSUE TITLE
_playYTDLStream called twice and queue.playing is undefined second time

### ISSUE THREAD

**Issue by YayLOfficial** [Androz2091/discord-player#313]
Upon issuing the play command with a song title like "legends" it gets the youtube video but then it does not continue to play it and throws the following error

![image](https://user-images.githubusercontent.com/75476395/109427018-b7575d00-79f0-11eb-8e5e-3fc84d64d6ec.png)

![image](https://user-images.githubusercontent.com/75476395/109427031-c76f3c80-79f0-11eb-8346-7f2bda6350c7.png)

**Comment by hands8142** [comment]
I didn't have an error. Please check if node version 14 or higher and ffmpeg and @discordjs/opus are installed.

**Comment by Snowflake107** [comment]
inactivity, feel free to re-open
