### ISSUE TITLE
play function bug?

### ISSUE THREAD

**Issue by xBeastMode** [Androz2091/discord-player#314]
While investigating the cause of this error: 
```
UnhandledPromiseRejectionWarning: Error: Play function requires search query but received none!
```
I found a possible bug in the play function code. Checking if `query` is type `string` makes the condition `query instanceof Track` reduntant:
![Capture1](https://user-images.githubusercontent.com/16060686/109457385-63646c80-7a20-11eb-93c6-33d5093627e3.PNG)

**Comment by xBeastMode** [comment]
Also `query.replace` will not apply to object Track. I think query type be checked first of all.

**Comment by Snowflake107** [comment]
fixed on v4
