### ISSUE TITLE
Quelques bugs 🐛

### ISSUE THREAD

**Issue by ZerioDev** [Androz2091/discord-player#318]
Salut Androz 👋

Je me suis donc mis à la page pour mettre à jour mon code source.
Cependant, j'ai pu remarquer quelques soucis mineurs.

- Vis-à-vis de la nouvelle fonction `seek`, quand je modifie le temps et que j'essaye d'obtenir la barre de progression avec la méthode `client.player.createProgressBar(message, { timecodes: true })`, je peux constater que pendant 2 ou 3 secondes le temps indiqué n'est pas correct. Tu pourras mieux comprendre avec la capture d'écran ci-dessous en regardant la partie avec les timecodes. Capture d'écran juste [ici](https://user-images.githubusercontent.com/43386412/109703781-2ae69f00-7b96-11eb-8900-96e53b6894cc.png).

- La fonction `resume` ne reprend pas la musique mise en pause auparavant.
- Les nouveaux filtres ne fonctionnent pas et stoppent la musique directement.

Sinon petite question ou peut être est ce un bug ?

-  Pourquoi dans `client.player.nowPlaying(message)`, on ne peut pas trouver `durationMS` mais que `client.player.nowPlaying(message).durationMS` fonctionne ?

Version de Node utilisée, `15.6.0` & version du module `3.4.0`.
Bonne soirée et bon courage, Zerio.

**Comment by SimonLeclere** [comment]
Tu vois pas durationMS parceque c'est un getter.
En gros c'est comme un attribut normal sauf que quand tu y accède une fonction s'exécute pour te renvoyer une valeur dynamiquement.

**Comment by Snowflake107** [comment]
@ZerioDev 
- for `resume`, try
```js
client.player.resume(message);
client.player.pause(message);
client.player.resume(message);
```

- for `filters`, I don't know.. Maybe your `FFmpeg` is outdated? Because I checked every filters before publishing it here
- for progressbar, will do something about it 👍🏼
