### ISSUE TITLE
QUESTION/SUGGESTION: Will be .mp3 links supported?

### ISSUE THREAD

**Issue by PetyXbron** [Androz2091/discord-player#325]
So, I want to listen with my friends to a favorite radio.
I installed develop version, but then I realized that I can play only discord links.
I know, that I can play from links like `connection.play(link)`, but then I can't change volume, it's harder for me to stop the music and more. So I just want to ask if I can do it now, or if not, just suggesting it.

Some links if you want: [Radio link 1](http://icecast8.play.cz/freeradio128.mp3) [Radio link 2](https://20423.live.streamtheworld.com/FAJN_RADIO_128.mp3)

**Comment by pardeepsingh12365** [comment]
Please make it playable for radio mp3 links
I'm also using radio links
