### ISSUE TITLE
Error: input stream: Status code: 503

### ISSUE THREAD

**Issue by ViTraX** [Androz2091/discord-player#328]
Salut ! j'ai un problème avec le bot j'ai l'erreur **Error: input stream: Status code: 503**

Quand je play une musique il dit Ok je rejoint + Je montre l'embed des informations et la il me dit erreur **La musique c'est arrêter car il n'y a plus de musique dans la file d'attente !**

Si vous s'avez d'où sa viens je serais ravis de l'apprendre

**Comment by Snowflake107** [comment]
> Service Unavailable server error response code
The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded.

**Comment by Snowflake107** [comment]
This has nothing to do with `discord-player`
