### ISSUE TITLE
Unexpected Token .

### ISSUE THREAD

**Issue by Zopenzop** [Androz2091/discord-player#330]
```
/home/runner/MyBot/node_modules/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^

SyntaxError: Unexpected token '.'
```

The package was working perfectly but after I reinstalled it a few days back, it stopped working.

**Comment by Snowflake107** [comment]
Use `node.js v14` @Zopenzop

**Comment by Zopenzop** [comment]
> Use `node.js v14` @Zopenzop

I just read about that, the problem is I am using repl.it and repl.it has uses node v12, and we cant change the node version. Maybe I will have to try some other npm packages.

**Comment by Snowflake107** [comment]
![image](https://user-images.githubusercontent.com/46562212/110921941-3df03080-8347-11eb-97e7-9d1452a94e9a.png)

**Comment by Zopenzop** [comment]
Thanks for trying to help me, however repl.it doesn't give enough permissions to change the node version. I will try to host the bot locally.

**Comment by udit2303** [comment]
You can *by using a sort of hack* which is exactly the way I use it but it's hard. Use nvm to install a new node version and then use pm2 to run the file (using the shell and npx) and run some simple webserver using the Run button

**Comment by DylanGS9** [comment]
> Thanks for trying to help me, however repl.it doesn't give enough permissions to change the node version. I will try to host the bot locally.

You could use my vps if ya want. Shoot me a pm on discord: D y l a n#2024

**Comment by Snowflake107** [comment]
I guess resolved?
