### ISSUE TITLE
Soundcloud Support?

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-player#340]
Does this package support Soundcloud? If not, is it being worked on?

**Comment by Dragonizedpizza** [comment]
Also, YouTube playlist support?

**Comment by Snowflake107** [comment]
yes it supports both of them @Dragonizedpizza

**Comment by Dragonizedpizza** [comment]
What about SoundCloud playlist support?

**Comment by Snowflake107** [comment]
it should support soundcloud playlists as well, however currently it should pick 5 tracks only (will try to fix it in the future)

**Comment by Dragonizedpizza** [comment]
and what's the limit for spotify and youtube playlists?

**Comment by Snowflake107** [comment]
as far as I know, it should be `100` (parsing from widgets)
