### ISSUE TITLE
ReferenceError: settings is not defined

### ISSUE THREAD

**Issue by luqz666** [Androz2091/discord-player#341]
I type: node index.js to run bot and when I write: ${prefix}play (song) it gives me the title error (ReferenceError: settings is not defined)

**Comment by Snowflake107** [comment]
can you show us your full code?

**Comment by luqz666** [comment]
> 
> 
> can you show us your full code?

nevemind my bad I didn't wrote settings part so thank you anyways :)

**Comment by luqz666** [comment]
> 
> 
> > can you show us your full code?
> 
> nevemind my bad I didn't wrote settings part so thank you anyways :)

but the bot doesn't join neither plays music :(

code:
const Discord = require("discord.js"),
client = new Discord.Client(),
settings = {
    prefix: "-",
    token: "not showing my token"
};

const { Player } = require("discord-player");
// Create a new Player (you don't need any API Key)
const player = new Player(client);
// To easily access the player
client.player = player;
// add the trackStart event so when a song will be played this message will be sent
client.player.on('trackStart', (message, track) => message.channel.send(`Now playing ${track.title}...`))

client.on("ready", bot => {
  console.log("Logged in!");

  client.user.setPresence({
      status: 'dnd',
      activity: {
          name: "-help",
          type: "LISTENING"
      }
  });
});

client.on("message", async (message) => {

    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();

    // !play Despacito
    // will play "Despacito" in the member voice channel

    if(command === "play"){
        client.player.play(message, args[0]);
        // as we registered the event above, no need to send a success message here
    }

});

client.login(settings.token);

**Comment by Michael7020** [comment]
you didnt told your bot which song result to play
`client.player.play(message, args.join(" "), { firstResult: true });`

**Comment by Snowflake107** [comment]
`settings` has nothing to do with `discord-player`
