### ISSUE TITLE
resume isnt working

### ISSUE THREAD

**Issue by astrex1969** [Androz2091/discord-player#342]
idk why resume isnt working my code 

async execute(bot, message) {
    const lang = await bot.getGuildLang(message.guild.id);
    if (!message.member.voice.channel) {
      return message.channel.send(lang.MUSIC.MUST_BE_IN_VC);
    }

    if (!bot.player.isPlaying(message)) {
      return message.channel.send(lang.MUSIC.NO_QUEUE);
    }

    bot.player.resume(message);
    console.log(`test`);
  },
};

**Comment by Snowflake107** [comment]
Looks like discordjs/discord.js#5300

**Comment by Snowflake107** [comment]
This is a bug in `discord.js` itself. Try using this for a quick fix

```js
bot.player.resume(message);
bot.player.pause(message);
bot.player.resume(message);
```
