### ISSUE TITLE
playlistAdd event doesn't work when the queue is empty.

### ISSUE THREAD

**Issue by TheLastGamer18** [Androz2091/discord-player#343]
The playlistAdd event only works when the queue has some other tracks in it, not when it is empty. When the queue is empty it just emits the trackStart event. The version I am using is 3.4.0.

YouTube playlists work fine, but this happens to only Spotify playlists

So I took a look at the code and it appears that the playlistAdd event isn't emitted in _handleSpotifyPlaylist if there is no queue.

**Comment by Snowflake107** [comment]
Use the latest version 👍
