### ISSUE TITLE
🐛 Erreur de Timecodes sur la Progess bar

### ISSUE THREAD

**Issue by Swarwerth** [Androz2091/discord-player#357]
En utilisant la fonction `client.player.createProgressBar(message, {timecodes: true})`, j'ai pu trouver une erreur. Si la durée de la vidéo dépasse l'heure et que ses minutes sont à 00, le Timecode affiché à la droite de la barre est faussé.

## ✨ Reproduire l'erreur
- Trouver une musique durant plus d'une heure avec des minutes à 00 sur Youtube *(par exemple [celle-ci](https://www.youtube.com/watch?v=W6YI3ZFOL0A))*
- Utiliser la fonction `createProgressBar` avec les Timecodes d'activés

## 📺 Screenshots illustrant l'erreur
*Sachant que j'ai pris cette vidéo sur Youtube, d'une durée de 1h00m41s* 

![image](https://user-images.githubusercontent.com/26115962/115318968-1d559a80-a17f-11eb-9b6c-eb21d4241c1e.png)

![image](https://user-images.githubusercontent.com/26115962/115319049-4118e080-a17f-11eb-84ac-ef87070c908a.png)

Des bisous,
Swarwerth

**Comment by Snowflake107** [comment]
@Swarwerth Just tested it in **[AtlantaBot](https://github.com/Androz2091/AtlantaBot)**..
![image](https://user-images.githubusercontent.com/46562212/115341621-a6dd8a80-a1c8-11eb-8c67-fa971761fc90.png)

**Comment by Swarwerth** [comment]
> @Swarwerth Just tested it in **[AtlantaBot](https://github.com/Androz2091/AtlantaBot)**..
> ![image](https://user-images.githubusercontent.com/46562212/115341621-a6dd8a80-a1c8-11eb-8c67-fa971761fc90.png)

Atlanta is using `v.3.0.3` of `discord-player` *([here](https://github.com/Androz2091/AtlantaBot/blob/master/package.json))*. I am using the version `v.3.4.0` of the module, with Nodejs `v.14.16.0`

**Comment by Snowflake107** [comment]
alright, and this should not happen in `v4`

**Comment by Swarwerth** [comment]
> alright, and this should not happen in `v4`

Ok thanks!
