### ISSUE TITLE
add a way to add custom filters

### ISSUE THREAD

**Issue by SourCreamCulture** [Androz2091/discord-player#358]
Let people define their own custom filters in their project in addition to the ones already in discord-player.

**Comment by Snowflake107** [comment]
hello, this is already done in `rewrite` version, you can define filters in rewrite version like this:

```js
const { AudioFilters } = require("discord-player");

AudioFilters.define("3D", "apulsator=hz=0.128");

// later, it can be used like this
player.setFilters(message, { "3D": true });
```
