### ISSUE TITLE
build a queue from an array

### ISSUE THREAD

**Issue by SourCreamCulture** [Androz2091/discord-player#359]
add a function so we can build a queue from an array to support the creation of save playlist commands.

**Comment by Snowflake107** [comment]
there is a private method called `_addTracksToQueue` which takes `message` and `Track[]`. You could use that

**Comment by Snowflake107** [comment]
or you can use `queue.tracks.push` to push the tracks manually

**Comment by SourCreamCulture** [comment]
Thanks ill try those

**Comment by Snowflake107** [comment]
I guess resolved?
