### ISSUE TITLE
Bug ? - this.client.player.resume ERROR

### ISSUE THREAD

**Issue by ThatGuyJamal** [Androz2091/discord-player#360]
I made a pause and resume command, only pause works is it an error with the `this.client.player.resume(message)` thing from the thing...

I don't see any logical errors with my code if anyone knows a fix let me know thanks.

Code: [HERE](https://srcb.in/qgI7ZanSV6)

**Comment by Snowflake107** [comment]
bug in discord.js

try

```js
client.player.resume(message);
client.player.pause(message);
client.player.resume(message);
```

**Comment by Snowflake107** [comment]
#252
