### ISSUE TITLE
Add SkipTo/Jump 

### ISSUE THREAD

**Issue by AdlerVaz** [Androz2091/discord-player#361]
add a jump/skipto method to discord-player  like .skipto(message , track) . only a suggestion

**Comment by ThatGuyJamal** [comment]
I agree, or maybe how we could add this ourselves?

**Comment by AdlerVaz** [comment]
> I agree, or maybe how we could add this ourselves?

yes i tried to....  but it was a suggestion . also why not ?

**Comment by Snowflake107** [comment]
we could add this in the library. But it is also possible to do so with `.remove`

- Use `.remove()` to remove particular track that you wanna jump to (returns that track)
- place that track in next position
- skip current track

**Comment by Snowflake107** [comment]
Available in version **[4.0.3](https://www.npmjs.com/package/discord-player/v/4.0.3)**
