### ISSUE TITLE
Current Track Position 

### ISSUE THREAD

**Issue by AdlerVaz** [Androz2091/discord-player#364]
I tired finding a way to get the current track position in MS/ seconds ... but didnt find one ... is there  a way to get it ?
becuz it can be really useful to make commands like rewind and fastforward if we combine  that with seek method .

**Comment by Snowflake107** [comment]
`queue.currentStreamTime`

**Comment by AdlerVaz** [comment]
> `queue.currentStreamTime`

```
const queue = client.player.getQueue(message);
const currentTrackPosition = queue.currentStreamTime
```

**Comment by Snowflake107** [comment]
I guess resolved?
