### ISSUE TITLE
The remove command is bug

### ISSUE THREAD

**Issue by devPhytols** [Androz2091/discord-player#365]
Hello, could help me?
when trying to remove a song from the queue, I type "prefix!remove 2" and it does not remove the track that is in position 2, but the track that is in position 3, and the rest of the tracks is the same.
I'll leave my code below in case you can help me!

`const track = parseInt(args)

        client.player.remove(message, track)

        message.channel.send({
            embed: {
                color: (client.config.discord.EMBED_SUCCESS),
                description: `${client.emotes.success}︙A música ` + track + ` acaba de ser **removida**!`
            },
        });`

**Comment by TheLastGamer18** [comment]
It is because in js indexing starts from 0, so you need to do track - 1 to remove that particular track

**Comment by devPhytols** [comment]
> It is because in js indexing starts from 0, so you need to do track - 1 to remove that particular track

could you give me a code example? or do based on this? I need this a lot.

**Comment by devPhytols** [comment]
> It is because in js indexing starts from 0, so you need to do track - 1 to remove that particular track

I managed to solve my problem, thanks for the support!
