### ISSUE TITLE
[Feature Request] 24/7

### ISSUE THREAD

**Issue by tovade** [Androz2091/discord-player#366]
**Is your feature request related to a problem? Please describe.**
Nope just a new feature request :)

**Describe the solution you'd like**
I want a 24/7 music option because that would be awesome!

**Describe alternatives you've considered**
The bot stays inside the voice channel but automaticly loops the whole queue

**Comment by Snowflake107** [comment]
What type of 24/7? You can do that with the `Autoplay` or `Loop` feature right?

**Comment by tovade** [comment]
Like the bot never leaves the voice channel like groovy

**Comment by Snowflake107** [comment]
> Like the bot never leaves the voice channel like groovy

if the loop is enabled, bot wont leave the channel. Also, make sure to disable **[PlayerOptions#leaveOnEmpty](https://discord-player.js.org/#/docs/main/master/typedef/PlayerOptions)** which makes the bot stay in vc when there are no users
