### ISSUE TITLE
TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by astrex1969** [Androz2091/discord-player#369]
const Discord = require("discord.js");
const tools = require("../modules/Tools.js");
const { prefix } = require('../config.json');
const db = require('./../database.js');
const moment = require("moment");
const { stripIndents } = require('common-tags');
const { Player } = require("discord-player");

module.exports = {
    // CMD INFORMATION
    name: 'play',
    aliases: ["p"],
    description: "Plays a song",
    category: "Music",

    async execute(client, message, args) {
   if(message.channel.type === "dm") return;
    let user = message.author;
    let blacklist = await db.get(`blacklist_${user.id}`);
    if(blacklist == true) return;

        if (!message.member.voice.channel) return message.channel.send(` - You're not in a voice channel !`);

        if (message.guild.me.voice.channel && message.member.voice.channel.id !== message.guild.me.voice.channel.id) return message.channel.send(` - You are not in the same voice channel !`);

        if (!args[0]) return message.channel.send(` - Please indicate the title of a song !`);

        await client.player.play(message, args[0]);
    },
};

**Comment by Positive2022** [comment]
its not a bug or anything ..
1. make sure you defined player in index.js file
2. it should be `client.player.play(message, args.join(" "), {firstResult: true}) ;`
