### ISSUE TITLE
Version 2 Suggestions

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#37]
I have noticed that the development branch for discord-player has been receiving daily updates and important bug fixes recently, so I thought that I would throw in some new ideas.

1) `player.dumpQueue(guild)` - Creates a new JSON file with the queue current queue array which holds all of the current tracks in the queue that are ready to be played. When this function is run, the idea is that it will create a new JSON file, add the queue array to it and then resolve the file at the end of the process.
2) `player.loadQueue(guild, file)` - This is what the dumpQueue idea is for. The user using the command attaches a JSON file containing the queue and then the player automatically loads the queue into this list. It will not remove any songs which are currently waiting in the queue to be played.
3) Add some functionality so that the skip function can be used for vote skipping aswell as instantly skipping the song. `player.skip(guild, useVoting)` - `useVoting` would be a boolean

**Comment by thomasthebro1** [comment]
4) `player.moveTo(guild, channel)` - Pauses the music playback, moves to a different voice channel specified and then resumes the playback.
5) `player.skipTo(guild, number)` - Skips X amount of songs in the queue and plays the song specified by the `number` value. For example: `player.skipTo(msg.guild, 5)` - Skips 4 tracks and removes them from the queue and plays track 5 simultaneously

**Comment by Naxey** [comment]
and let us add a DJ role to bypass the voting :)

**Comment by Androz2091** [comment]
You can do that, you have to code it :wink:

**Comment by Androz2091** [comment]
Suggestion 1 and 2 are already possible using queue.tracks property
Suggestion 3 can be done too using some code

Suggestion 4 and 5 are useful, I will add them to the list (see pinned issues)
