### ISSUE TITLE
[QUESTION] how to use youtube and spotify?

### ISSUE THREAD

**Issue by devPhytols** [Androz2091/discord-player#370]
**Question**

Hello my friends, I hope you are well.

well, my bot is searching only on youtube, but i would like that in the same command "prefix! play", it will also play a Spotify playlist!

How can I do this?
can you give me a code example?

**Comment by Snowflake107** [comment]
It should automatically play your spotify links like it does normally

**Comment by Snowflake107** [comment]
FYI: you cannot play from spotify, so the lib instead finds your song in youtube to play

**Comment by devPhytols** [comment]
> It should automatically play your spotify links like it does normally

I tried to play a Spotify link and he didn't recognize it, did he play another YouTube song? does the library allow it to play from spotify? if so how can i define it?

**Comment by Snowflake107** [comment]
@devPhytols just now tested spotify link 
![image](https://user-images.githubusercontent.com/46562212/116407130-29152100-a851-11eb-8f9a-dfdbf9c4d28f.png)

**Comment by devPhytols** [comment]
> @devPhytols just now tested spotify link
> ![image](https://user-images.githubusercontent.com/46562212/116407130-29152100-a851-11eb-8f9a-dfdbf9c4d28f.png)

are you using the latest version? I'm on 3.4.0

**Comment by Snowflake107** [comment]
Yes I'm on the latest version which is `4.0.5`

**Comment by devPhytols** [comment]
Solved, thanks bro!
