### ISSUE TITLE
[BUG] Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by earearray** [Androz2091/discord-player#371]
**Describe the bug**
My bot has commands that allow to turn on sound effects that might be funny, but when running these commands, the console sometimes has an error with some commands and the song won't open due to this error.

**To Reproduce**
1. Run `this.client.player.play(message, "https://youtu.be/pFqS716gUzo");` code
4. See `Cannot call write after a stream was destroyed` error

**Expected behavior**
The behavior I expected was for the song to start playing

**Please complete the following information:**
 - Node Version: 12.5.3
 - Discord.js Version: 12.22.1

**Additional context**
Normally this code was working properly until a few days ago but it no longer works and gives `Cannot call write after a stream was destroyed` error

**Comment by Snowflake107** [comment]
Hey, please include your library version as well

**Comment by earearray** [comment]
> Hey, please include your library version as well

Do you mean the library version is the version of this module or the version of the Discord.js library I use?

**Comment by Snowflake107** [comment]
library version means the version of Discord Player. In the issue templates, there are 3 different fields for versions: `node`, `discord.js` and `library (discord-player)` but you included `Node` and `Discord.js` versions only

**Comment by earearray** [comment]
Library Version: 4.0.5

**Comment by Snowflake107** [comment]
Does the process crash?

Also, it is not a bug of `discord-player`. This error comes from `discord-ytdl-core`

**Comment by earearray** [comment]
Yes

**Comment by Vins2106** [comment]
I've gotten this error once, but this fixes it:
```
const <player> =  new DiscordPlayer.Player(client, {
      ytdlDownloadOptions: {filter: "audioandvideo"}
    });
```
if not please forgive me :)
I've tried it and it works.

**Comment by Vins2106** [comment]
maybe you can try without install `ytdl-core`.
who knows can 🤷‍♂️

**Comment by earearray** [comment]
> I've gotten this error once, but this fixes it (instal `ytdl-core` latest version first):
> 
> ```
> const <player> =  new DiscordPlayer.Player(client, {
>       ytdlDownloadOptions: {filter: "audioandvideo"}
>     });
> ```
> 
> if not please forgive me
> I've tried it and it works.

problem was solved thanks to this code thank you very much
