### ISSUE TITLE
[BUG] No playlist type found

### ISSUE THREAD

**Issue by hands8142** [Androz2091/discord-player#374]
**Describe the bug**
I updated the version, but suddenly it says that I can't find the playlist type. Is this intended?

**To Reproduce**
Occurs when attempting to load playlist type from typecript

**Expected behavior**
Documentation does not contain the playlist type.

**Screenshots**
![스크린샷 2021-04-29 오후 5 07 32](https://user-images.githubusercontent.com/46277532/116520308-853d7b00-a90d-11eb-8923-84efd5a74f73.png)

**Please complete the following information:**
 - Node Version: 16.0.0
 - Library Version: 4.0.5
 - Discord.js Version: 12.5.3

**Comment by Snowflake107** [comment]
That's not a bug, `discord-player` does not have `Playlist`

**Comment by hands8142** [comment]
https://discord-player.js.org/#/docs/main/master/class/player?scrollTo=e-playlistAdd Here is the playlist, but the type is listed as an object.

**Comment by Snowflake107** [comment]
@hands8142 that playlist is not really defined properly. It just adds other additional props to the original playlist (youtube/soundcloud) which are completely different types. Thus, there is not any defined playlist structure

**Comment by hands8142** [comment]
Thank you.
