### ISSUE TITLE
General Enhancements

### ISSUE THREAD

**Issue by APartOfMe1** [Androz2091/discord-player#38]
### Bugs
First off I wanted to say that I absolutely love this module. Writing music playback commands for discord bots can be incredibly hard/tedious, so thank you for taking the time to make this. With that said, I did notice a couple bugs

- Trying to play a string of random characters (ex: `player.play(msg.member.voice.channel, "ajhknmnbafca")`) returns a console error, shown below. 

```
(node:25360) UnhandledPromiseRejectionWarning: Not found
(node:25360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is not fixed by using .catch(), or even using the default code found in the [readme](https://github.com/Androz2091/discord-player#handle-errors). This might be an issue on my end, I'm not entirely sure

- The way song duration is stored is a bit strange. As it is, I have to multiply by 10 to get ms, or divide by 10 to get seconds. Having duration stored as one or the other would be ideal compared to how it's currently stored

### Suggestions
While using this module, I had a couple ideas on how it could be improved. All of my suggestions are possible with the current module and a bit of extra code, but adding them natively would greatly improve/simplify the user experience

- player.setRepeatMode should be able to be toggled. Ex: `player.setRepeatMode(msg.guild.id, toggle)` instead of making you use true or false.  This would remove the need to code a toggle manually

- A built-in playskip function would be amazing. This can currently be accomplished by clearing the queue, adding the song, and skipping the current one

- There should be a stopwatch-esque feature for the currently playing song. Basically it would be nice to be able to see how long the current song has been playing for

- A search function is probably what I want the most. Returning the top 10 results for a search and allowing the user to choose between them would honestly be fantastic. I do understand that this could be hard to implement though

**Comment by Androz2091** [comment]
Many things you said have already been added or there are already issues for them so I'm closing this :wink:
