### ISSUE TITLE
I have @discor-player/extractor already installed then also i am not able to use lyrics

### ISSUE THREAD

**Issue by GLITCHEDITZ16** [Androz2091/discord-player#380]
I have installed @discord-player/extractor but it is giving error that `UnhandledPromiseRejectionwarning: PlayerError: Cannot call 'Player.lyrics()' without '@discord-player/extractor'` 
![error](https://user-images.githubusercontent.com/75305865/116773761-301c7900-aa75-11eb-968b-6258be553d75.PNG)

**Comment by Snowflake107** [comment]
@GLITCHEDITZ16 try restarting?

**Comment by GLITCHEDITZ16** [comment]
I restarted many times but same error on repl

**Comment by GLITCHEDITZ16** [comment]
I tried the code in vsc which is like this
```const result = await client.player.lyrics(args.join(" "))
  
      message.channel.send(result.lyrics)```
      
      But now i am getting error that lyrics in undefined in result.lyrics

**Comment by Snowflake107** [comment]
Lyrics is sometimes empty when it can't parse data properly

**Comment by GLITCHEDITZ16** [comment]
So what to do @Snowflake107

**Comment by Snowflake107** [comment]
@GLITCHEDITZ16 You can try using your genius api key
For that, just add `GENIUS_API_KEY` in `.env` file
