### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by aadhikesh-gif** [Androz2091/discord-player#381]
**Question**
When I use jump command it said Track is not defined. What should I define it as tho ;-;. I tried jump [songname] and also jump [song number in queue]. On both cases it said track not defined so what should I define ;-;

**Comment by Snowflake107** [comment]
You should use it like this:

```js
player.jump(message, TrackObject | number);
```

where the track can be the **[Track](https://discord-player.js.org/#/docs/main/master/class/Track)** object or its index in queue.
Keep in mind that index always starts from `0`. So, if you wanna jump to track number 4 and you are not counting it from 0, you should use `index - 1` which would give the actual index of track 4 which is 3

**Comment by aadhikesh-gif** [comment]
Thanks a lot
