### ISSUE TITLE
[BUG]  Youtube playlist

### ISSUE THREAD

**Issue by Wolletje01** [Androz2091/discord-player#389]
**Describe the bug**

When I upgrade to discord player 4.0.5 then the yt playlist doesnt work anymore. When i downgrade to 3.4.0 then it works again

How to fix it.

**Screenshots**
https://ibb.co/ZG7vXSX
https://ibb.co/SPqHGC3

**Please complete the following information:**
 - Node Version: 15.10.0
 - Library Version: ?
 - Discord.js Version: 12.5.3

**Additional context**
https://www.youtube.com/watch?v=SNq4VxhzaoQ&list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4&index=1
```

client.on("message", async (message) => {
    if (!message.content.startsWith(settings.prefix) || message.author.bot || message.channel.type === "dm") return;
    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    var argAll = args.join(" ");
    
    if (command === play){
        client.player.play(message, argAll, true);
    }

}
```

**Comment by Snowflake107** [comment]
Your link does work for me but only one video from that playlist is parsed

**Comment by Wolletje01** [comment]
What I mean with the bug is that the yt playlist doesnt work on 4.0.5. But it does work on 3.4.0.
4.0.5: 1 vid added to queue
3.4.0: 160 vids added to the queue.

My question is, how to get that link working in 4.0.5 that is adds 160 vids to the queue.

**Comment by Snowflake107** [comment]
hmm does this type of link work? **[https://www.youtube.com/playlist?list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4](https://www.youtube.com/playlist?list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4)**

**Comment by Klairm** [comment]
> hmm does this type of link work? **https://www.youtube.com/playlist?list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4**
I can confirm that using that type of link works correctly, now getting the link of the video inside a playlist (which is the thing that doesn't work), I've seen that maybe the only way to identify that is a playlist would be with this part of the link `&list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4&index=1`   ( this is the original link https://www.youtube.com/watch?v=SNq4VxhzaoQ&list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4&index=1 )

**Comment by xHyroM** [comment]
it fixed in new version

**Comment by Wolletje01** [comment]
That type indeed does work. So the only thing i have to do is to transform this link [1] to this link [2].
[1]: https://www.youtube.com/watch?v=SNq4VxhzaoQ&list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4&index=1
[2]: https://www.youtube.com/playlist?list=PL23zndsUrACAc5ticN3mjk_FI9ZwpwGI4
