### ISSUE TITLE
[BUG] Error: input stream: write EPIPE 

### ISSUE THREAD

**Issue by Pressure145** [Androz2091/discord-player#392]
Error: input stream: write EPIPE anyone know how to fix that (ffmpeg) it worked when i selfhosted it (windows) but when i put it on my vps (linux) it got that error so i think its a linux problem

**Comment by Snowflake107** [comment]
Hello, you can catch that error with **[Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error)** event. Also, in some cases, using `filter: "audioonly"` fixed the issue.

You can supply the `filter` option from **[PlayerOptions](https://discord-player.js.org/#/docs/main/master/typedef/PlayerOptions)**

```js
const player = new Player(client, {
    ytdlDownloadOptions: {
        filter: "audioonly"
    }
})
```

**Comment by zyrouge** [comment]
Dont use `filter: "audioonly"` if u have `enableLive` enabled. Try with some other filters.

**Comment by Pressure145** [comment]
> Hello, you can catch that error with **[Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error)** event. Also, in some cases, using `filter: "audioonly"` fixed the issue.
> 
> You can supply the `filter` option from **[PlayerOptions](https://discord-player.js.org/#/docs/main/master/typedef/PlayerOptions)**
> 
> ```js
> const player = new Player(client, {
>     ytdlDownloadOptions: {
>         filter: "audioonly"
>     }
> })
> ```

did not work

**Comment by Klairm** [comment]
From what I read, seems to be related to Linux FFMPEG pipes, https://github.com/phaux/node-ffmpeg-stream/issues/14 
Maybe this should be treated in the framework code

**Comment by Samiul30** [comment]
> From what I read, seems to be related to Linux FFMPEG pipes, https://github.com/phaux/node-ffmpeg-stream/issues/14 
> Maybe this should be treated in the framework code

Can you fix this?

**Comment by Pressure145** [comment]
> Does all the videos cause EPIPE? If no, which youtube video causes it? Maybe I'll try to reproduce and find a solution.

yea all vids cause EPIPE

**Comment by Positive2022** [comment]
> Does all the videos cause EPIPE? If no, which youtube video causes it? Maybe I'll try to reproduce and find a solution.

No. I mostly got epipe error when i stopped a song when its about to finish.
I hosted my bot on high ping server (300ms) and i was able to produce it.

**Comment by DeathMario** [comment]
update to node.js 14x or up

**Comment by Klairm** [comment]
> update to node.js 14x or up

This so far has worked for me

**Comment by Snowflake107** [comment]
> update to node.js 14x or up

I am using node.js v14 and discord.js master. This happens to few songs 🤔

**Comment by Snowflake107** [comment]
ok since this issue is similar to #378, let's move the discussions there
