### ISSUE TITLE
[BUG] ERROR IN LIVE VIDEO

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#396]
**Describe the bug**
After enabling live video I got this error ":warning: - Something went wrong ... Error : Error: input stream: connect ETIMEDOUT 74.125.164.39:443" after 5 or 6 seconds.

**To Reproduce**
enable live option in player and play any live video.
**Expected behavior**
It should play the live url.

**Please complete the following information:**
 - Node Version: [16.1.0]
 - Library Version: []
 - Discord.js Version: [12.5.1]

**Additional context**

**Comment by Snowflake107** [comment]
hey @Samiul30, I just tried to reproduce your error but it's working for me

The live video I am playing is **[https://www.youtube.com/watch?v=oCuLbu19j_k](https://www.youtube.com/watch?v=oCuLbu19j_k)**

![image](https://user-images.githubusercontent.com/46562212/117534601-e18d5280-b011-11eb-9c06-1ae8887cae6f.png)

**Comment by Samiul30** [comment]
I am hosting the bot in repl.it. When I try to reproduce it on my machine it won't reproduce. But when I host it in repl.it it is reproducing every time when I use stop or skip command.

**Comment by Snowflake107** [comment]
Looks like there's some problem with **repl.it** 🤔try asking the **[repl.it community](https://discord.com/invite/5gcPC6B)**

**Comment by Swarwerth** [comment]
Hey!

**Description**
I have the same issue. I am hosting the bot on my computer. I was listenning some musics and when this error came: `Error: input stream: connect ETIMEDOUT 173.194.183.232:443`. When the 3rd song on 4 ended, the error appeared. The bot does not want to play the last song (blocked on 0:00).

**To reproduce**
- Play some musics (I was playing 4 songs)

**Versions**
- Node version: v.14.16.0
- Discord-player: v.4.0.5
- Discord.js: 12.5.3
