### ISSUE TITLE
[BUG] youtube music and some links don't work when latest version is installed

### ISSUE THREAD

**Issue by The65Dude** [Androz2091/discord-player#399]
**Describe the bug**

**To Reproduce**
 1. Go to your bot and type -play or whatever command is used and use an https://music.youtube.com/
2. I used a playlist from youtube music if normal youtube music works for you then try a playlist

**Expected behavior**
The playlist or song should be played normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/32855137/117555847-e5c06c80-b01f-11eb-9f00-5263a512f18e.png)

**Please complete the following information:**
 - Node Version: [16.1.0]
 - Discord Player Version: [The one downloaded from npm i discord-player@latest]
 - Discord.js Version: [7.12.0]

**Additional context**

**Comment by dopekilla** [comment]
The message in the screenshot says that there is no result for that link

**Comment by Snowflake107** [comment]
is it working with normal `youtube.com`?

**Comment by dopekilla** [comment]
> is it working with normal `youtube.com`?

yup

**Comment by dopekilla** [comment]
I'm using Zerio's bot btw

**Comment by DevAndromeda** [comment]
Hello, could you transfer this issue to https://github.com/DevSnowflake/youtube-sr ?
