### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by commandxz** [Androz2091/discord-player#400]
If the loop playback mode is on But want the song to loop the whole queue Not just one current song In which part do I need to fix it?

**Comment by Snowflake107** [comment]
There are two different methods: **[Player#setLoopMode](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=setLoopMode)** (for queue) and **[Player#setRepeatMode](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=setRepeatMode)** (for track)

**Comment by commandxz** [comment]
I didn't expect the answer to be so quick. Thanks for the quick reply.

**Comment by Snowflake107** [comment]
I am marking this issue as `resolved`. Feel free to re-open if you have anything to ask!
