### ISSUE TITLE
[BUG] WRITE EPIPE

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#401]
**Describe the bug**
I faced this err 'warning - Something went wrong ... Error : Error: input stream: write EPIPE' when I use skip command and stop command.

**To Reproduce**
I have added spotify playlist and then give the command skip. It sends the err but the song is started playing after the err message was sent. 

**Expected behavior**
It should skip the current song and send the now playing song message and then started to play the song in VC.

**Screenshots**

**Please complete the following information:**
 - Node Version: [14.16.1]
 - Discord Player Version: [4.0.6]
 - Discord.js Version: [12.5.3]

**Additional context**

**Comment by Klairm** [comment]
#392
