### ISSUE TITLE
[BUG]  Spotify Playlists bug

### ISSUE THREAD

**Issue by Klairm** [Androz2091/discord-player#402]
**Describe the bug**
One problem with spotify playlists is , that when you parse a playlist, it won't play the songs of the playlist, somehow it will play other random songs, this doesn't happens if you parse the exactly song.

**To Reproduce**
1. Parse a spotify playlist to the bot using discord-player
2.  Wait almost 30seg to load up the playlist
3. It will start playing other random songs instead of the playlists songs

**Expected behavior**
It should play the correct songs from the playlist parsed.

**Screenshots**
https://i.imgur.com/839boz3.png

**Please complete the following information:**
 - Node Version: [8.10.0]
 - Discord Player Version: [12.5.1]
 - Discord.js Version: [4.0.5]

**Comment by SidisLiveYT** [comment]
> **Describe the bug**
> One problem with spotify playlists is , that when you parse a playlist, it won't play the songs of the playlist, somehow it will play other random songs, this doesn't happens if you parse the exactly song.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Parse a spotify playlist to the bot using discord-player
> 2. Wait almost 30seg to load up the playlist
> 3. It will start playing other random songs instead of the playlists songs
> 
> **Expected behavior**
> It should play the correct songs from the playlist parsed.
> 
> **Screenshots**
> https://i.imgur.com/839boz3.png
> 
> **Please complete the following information:**
> 
> * Node Version: [8.10.0]
> * Discord Player Version: [12.5.1]
> * Discord.js Version: [4.0.5]

I am also facing quite a few days ! Btw it is occurring with albums and playlist , Luckily We got correct Song Track ! And 

I am Using  :-
> * Node Version: [15.14.0]
> * Discord Player Version: [4.0.6]
> * Discord.js Version: [12.5.3]

**Comment by Snowflake107** [comment]
We can't really do anything about this because:
1. Spotify does not allow us to download their content
2. We are parsing basic details and searching each of your songs in youtube
3. Since spotify and youtube are different thing, search result would not be the same at all

**Comment by Klairm** [comment]
What about in integrating this https://github.com/lavalibs/lavalink.js#readme + https://www.npmjs.com/package/lavasfy

**Comment by Snowflake107** [comment]
> What about in integrating this https://github.com/lavalibs/lavalink.js#readme + https://www.npmjs.com/package/lavasfy

I guess no, current method is kind of accurate too.

![image](https://user-images.githubusercontent.com/46562212/117583149-4ab1ba80-b125-11eb-9032-2be0f8e6a896.png)

**Comment by Snowflake107** [comment]
This usually happens when youtube does not have accurate results. Most of the time, it should work tho because youtube does have a lot of songs

**Comment by Klairm** [comment]
Yes but it's kinda weird, because if I try to play the same songs individually it will work perfectly, so it's really getting the song from youtube, but somehow when it's from playlist sometimes doesn't get it correctly, like here: 
https://imgur.com/7H93WMQ.png 

I guess that when accesing the data from spotify is worst than getting the strings of the search

**Comment by SidisLiveYT** [comment]
> > What about in integrating this https://github.com/lavalibs/lavalink.js#readme + https://www.npmjs.com/package/lavasfy
> 
> I guess no, current method is kind of accurate too.
> 
> ![image](https://user-images.githubusercontent.com/46562212/117583149-4ab1ba80-b125-11eb-9032-2be0f8e6a896.png)

**you are right but custom playlists or some other random Playlists present globally made by some other people in spotify doesn't work correctly ! kinda feels like it searches for** `artist/author`

**Comment by Snowflake107** [comment]
> > > What about in integrating this https://github.com/lavalibs/lavalink.js#readme + https://www.npmjs.com/package/lavasfy
> > 
> > 
> > I guess no, current method is kind of accurate too.
> > ![image](https://user-images.githubusercontent.com/46562212/117583149-4ab1ba80-b125-11eb-9032-2be0f8e6a896.png)
> 
> **you are right but custom playlists or some other random Playlists present globally made by some other people in spotify doesn't work correctly ! kinda feels like it does searches for** `artist/author` **for those Custom Playlists**

I've added an option to disable artist search for spotify. Ex: by default it would search `artist - track` and when it is disabled, it goes with the another option i.e. `track`

**Comment by SidisLiveYT** [comment]
> > > > What about in integrating this https://github.com/lavalibs/lavalink.js#readme + https://www.npmjs.com/package/lavasfy
> > > 
> > > 
> > > I guess no, current method is kind of accurate too.
> > > ![image](https://user-images.githubusercontent.com/46562212/117583149-4ab1ba80-b125-11eb-9032-2be0f8e6a896.png)
> > 
> > 
> > **you are right but custom playlists or some other random Playlists present globally made by some other people in spotify doesn't work correctly ! kinda feels like it does searches for** `artist/author` **for those Custom Playlists**
> 
> I've added an option to disable artist search for spotify. Ex: by default it would search `artist - track` and when it is disabled, it goes with the another option i.e. `track`

okk thats nice and helpful ,how to disable it ? I can't find it anywhere !

**Comment by Snowflake107** [comment]
@SidisLiveYT I don't think that would help much but searching track title would kind of increase accuracy I guess?

and to use this feature, you need the `develop` version of `discord-player`

**Comment by SidisLiveYT** [comment]
> @SidisLiveYT I don't think that would help much but searching track title would kind of increase accuracy I guess?
> 
> and to use this feature, you need the `develop` version of `discord-player`

yeah seeing current issue , searching title will help it alot ! and how to use the develop ??

**Comment by Snowflake107** [comment]
develop version should be merged into master in few days. It will be available as soon as it gets merged

**Comment by SidisLiveYT** [comment]
> develop version should be merged into master in few days. It will be available as soon as it gets merged

Okk Thanks ! I will be waiting for it !!

**Comment by Snowflake107** [comment]
ok this issue seems to be fixed by https://github.com/Androz2091/discord-player/commit/5386bbc91427bc727986996d7e0215f1930c4c16 and https://github.com/Androz2091/discord-player/commit/de40d183a65f1453a14c5bb84359937c7486708c
