### ISSUE TITLE
[BUG] Volume doesn't works

### ISSUE THREAD

**Issue by ghost** [Androz2091/discord-player#406]
**Describe the bug**

**To Reproduce**
1. Play a song
2. Try to change volume
3. Volume doesn't change
4. No errors

**Expected behavior**

I try to change volume it doesn't do anything
**Screenshots**

**Please complete the following information:**
 - Node Version: 14x
 - Discord Player Version: 4.0.6
 - Discord.js Version: idk lastest

**Additional context**

**Comment by DeathMario** [comment]
yes

**Comment by Snowflake107** [comment]
hey @DeathMario, does adding `DP_REPL_NOCHECK=true` in `.env` fix the issue?

**Comment by DeathMario** [comment]
> hey @DeathMario, does adding `DP_REPL_NOCHECK=true` in `.env` fix the issue?

Yes, but in some songs the bot crashes with stream epip error

**Comment by Snowflake107** [comment]
ok, let's move epipe to #378
