### ISSUE TITLE
[QUESTION] SoundCloud APP Mobile Playlist

### ISSUE THREAD

**Issue by devPhytols** [Androz2091/discord-player#408]
**Question**
he is not pulling the songs from the playlist via the app link, just the first song!

tested playlist:
https://soundcloud.app.goo.gl/bfTya

**Comment by Snowflake107** [comment]
@devPhytols do all playlist links have 5 characters after `/`?

**Comment by devPhytols** [comment]
> @devPhytols todos os links da lista de reprodução têm 5 caracteres depois `/`?

Yes! all tracks.

**Comment by devPhytols** [comment]
> @devPhytols do all playlist links have 5 characters after `/`?

Yes! all tracks.
