### ISSUE TITLE
Issue with installing the package using NPM

### ISSUE THREAD

**Issue by Clsxsy** [Androz2091/discord-player#41]
Im trying to download npm i discord-player but all i get is errors:/

PS C:\Users\Clasxsy\Desktop\Music Bot> npm i discord-player
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/derhuerst/http-basic.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Clasxsy\AppData\Roaming\npm-cache\_logs\2020-07-02T20_23_33_500Z-debug.log

**Comment by ba-e** [comment]
You need the install [Git](https://git-scm.com).
