### ISSUE TITLE
[QUESTION] What does this error mean?

### ISSUE THREAD

**Issue by Wolletje01** [Androz2091/discord-player#410]
**Question**

Something went wrong... Error: MusicStarting
The music works but what does the error mean.

node: 15.10
npm: 7.11.2
discord-player: 3.4.0

My code:
client.player.on('error', (error, message) => {
    switch (error) {
        case 'NotPlaying':
            message.channel.send('There is no music being played on this server!');
            break;
        case 'NotConnected':
            message.channel.send('You are not connected in any voice channel!')
            break;
        case 'UnableToJoin':
            message.channel.send('I am not able to join your voice channel, please check my permissions!')
            break;
        case 'LiveVideo':
            message.channel.send('YouTube lives are not supported!')
            break;
        case 'VideoUnavailable':
            message.channel.send('This YouTube video is not available!');
            break;
        default:
            message.channel.send(`Something went wrong... Error: ${error}`)
    }
})

**Comment by Wolletje01** [comment]
> Also, why are you still using discord player v3?

6 line original message
discord-player: 3.4.0

**Comment by Snowflake107** [comment]
sure, I have fixed the playlist validation in **[youtube-sr](https://github.com/DevSnowflake/youtube-sr)** yesterday

**Comment by Wolletje01** [comment]
How to install v4.0.8 on npm?

**Comment by Snowflake107** [comment]
not possible, you have to build from source
