### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by SolarionSch** [Androz2091/discord-player#414]
**Is your feature request related to a problem? Please describe.**
I requested this feature due to the Write EPIPE error that happens, that can crash your bot (It may crash your bot)

**Describe the solution you'd like**
Add an dedicated error handler for Write EPIPE to [Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error)

**Comment by RifksSch** [comment]
I did exactly that.

i did

default: message.channel.send('error')

but still the same error happens, and sometimes it will even crash the bit

**Comment by Snowflake107** [comment]
It wont crash your process after using `.on("error")`. Discord player automatically destroys your queue when that error occurs (if it's last song, else moves to next song).

**Comment by RifksSch** [comment]
I see. Also If you are wondering, this error exist in 4.0.0 or higher. In 3.4.0 this error does not exist.

**Comment by Snowflake107** [comment]
what do you mean? your bot completely restarts with that error?

**Comment by RifksSch** [comment]
I tried your code, still, it will sometimes crash my bot, if it doesn't crash the bot, it wouldn't even send the error message.
Please add a dedicated error handler in [Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error) for EPIPE

**Comment by Klairm** [comment]
> After it crashes, it reboots.

This is not related to the error but with PM2, I also use PM2 and when there's an error PM2 will restart the application.



> I tried your code, still, it will sometimes crash my bot, if it doesn't crash the bot, it wouldn't even send the error message.
> Please add a dedicated error handler in [Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error) for EPIPE

About this, I think this is not an error 100% related with discord-player but  with nodeJS

**Comment by Snowflake107** [comment]
dont know what you mean by the `dedicated error handler`. We are already forwarding the `error` event for epipes aka handling the error on our side. Users will have to handle the forwarded error emitted by `Player.on("error")` on their side
