### ISSUE TITLE
[BUG] Spotify

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#415]
**Describe the bug**
When Playing Single Track or Song by Spotify Link , it Plays song related to the author or sometimes unrelated to it ! But it plays it easily and 100% in album and playlists . Tested many times with many playlists and albums 

**To Reproduce**
1, Play  a Single Track or Spotify Song like ->https://open.spotify.com/track/6qajA2wXvAI4HMey8b1JVK?si=wv-cerRhQQi2NYmGtu6-NA&utm_source=copy-link&dl_branch=1   [  Seher ki ladki Song ]
2, Bot Plays Another Song by the same author .
3. See error --> https://i.imgur.com/ujTMN2O.png

**Expected behavior**
Song will be Played But related to the Author of the Request Song mentioned in spotify link , and its only happening with Spotify Track or Song .  But on Playlist and Albums , Bot give correct Song its mostly 100% accurate after the 4.0.7 Update , But I guess its only occurring in Single Track .

**Screenshots**
https://i.imgur.com/ujTMN2O.png

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.0.7]
 - Discord.js Version: [12.5.3]

**Additional context**

**Comment by Snowflake107** [comment]
#402

**Comment by SidisLiveYT** [comment]
> #402

I saw but that was Playlist Issue that has been Fixed ! But its occurring in Single Track and I send the Screenshot as a Proof !

**Comment by Snowflake107** [comment]
> > #402
> 
> I saw but that was Playlist Issue that has been Fixed ! But its occurring in Single Track and I send the Screenshot as a Proof !

looks like your issue is occurring in that particular song. I have tested multiple other songs which worked as expected. And remember, `discord-player` does not play from spotify so there might have been issues searching your song on youtube. This is not really considered bug because most of the spotify tracks work as expected. If you want accuracy, you might wanna use the Extractors api :smile:
This might happen when the spotify track is not from the official artist or has something else titled because the way discord-player handles spotify tracks is by making a youtube search: `{track name} - {artist name}`

**Comment by SidisLiveYT** [comment]
> > > #402
> > 
> > 
> > I saw but that was Playlist Issue that has been Fixed ! But its occurring in Single Track and I send the Screenshot as a Proof !
> 
> looks like your issue is occurring in that particular song. I have tested multiple other songs which worked as expected. And remember, `discord-player` does not play from spotify so there might have been issues searching your song on youtube. This is not really considered bug because most of the spotify tracks work as expected. If you want accuracy, you might wanna use the Extractors api 😄
> This might happen when the spotify track is not from the official artist or has something else titled because the way discord-player handles spotify tracks is by making a youtube search: `{track name} - {artist name}`

Actually its happening with every track i play but they are okay when they are in official or custom playlists or albums , But it is only happening with single track of spotify . these Songs are okay and 100% accurate when they are played with their playlist with other songs , and i guess its only happening when i am playing them as a single track ! see the below screenshot if you think previous song's link was having problems !
Proof - https://i.imgur.com/Yh29Mmw.png

> Can you give me the link you played so i can play on my bot for checking !

**Comment by Snowflake107** [comment]
@SidisLiveYT opsie, just checked the internal data and looks like we are no longer getting the `info.artist` in the data, I will fix it now

**Comment by SidisLiveYT** [comment]
> @SidisLiveYT opsie, just checked the internal data and looks like we are no longer getting the `info.artist` in the data, I will fix it now

Sure ! I will be waiting , btw You are awesome along with the Package ! <3 Keep it up :)

**Comment by Snowflake107** [comment]
btw do you have `options.disableArtistSearch` enabled?

**Comment by SidisLiveYT** [comment]
> btw do you have `options.disableArtistSearch` enabled? If so, try disabling that option

I didn't mentioned in the Player options , it should have default value , I am doing it !

**Comment by SidisLiveYT** [comment]
> btw do you have `options.disableArtistSearch` enabled? If so, try disabling that option

I did but still its not working ! btw i am in 4.0.7 !

**Comment by Snowflake107** [comment]
I have completely rebuilt the whole spotify track system, hopefully works this time :D

**Comment by Snowflake107** [comment]
yup works properly now 
![image](https://user-images.githubusercontent.com/46562212/118079424-e8341500-b3d7-11eb-9b9b-0d533dcbe9a4.png)

**Comment by SidisLiveYT** [comment]
> yup works properly now
> ![image](https://user-images.githubusercontent.com/46562212/118079424-e8341500-b3d7-11eb-9b9b-0d533dcbe9a4.png)

okk thanks !! I will be checking the thing ! Should I update the Package ???

**Comment by Snowflake107** [comment]
I will try to fix more stuff and release 4.0.8 ~~today~~

**Comment by SidisLiveYT** [comment]
> I will try to fix more stuff and release 4.0.8 ~today~

okkk Sorry for being impatient !
