### ISSUE TITLE
Live videos [BUG] 

### ISSUE THREAD

**Issue by the1minshow** [Androz2091/discord-player#422]
**Describe the bug**
Hey when i play music it works fine but when i do for example !play lofi  24/7 like the music from youtube stream it plays for a second and stops playing but other songs work do you know why?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Node Version: [x.x.x]
 - Discord Player Version: [x.x.x]
 - Discord.js Version: [x.x.x]

**Additional context**

**Comment by Snowflake107** [comment]
@the1minshow Hey, looks like this is not a bug of discord player itself.
According to `ytdl-core` support server:
![image](https://user-images.githubusercontent.com/46562212/118088296-95158e80-b3e6-11eb-8231-17b19fb19d3d.png)

We will publish a patch when it gets fixed don't worry!

**Comment by the1minshow** [comment]
Okay thanks! will ask then if it will get fixed
