### ISSUE TITLE
[BUG] PROBLEM IN RESUME.

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#423]
**Describe the bug**
I paused the music and start it after 1 minutes with the command resume.  But it didn't start at that time. When I give pause command again and resume command for the 2nd time it start to play but this time the speed of the song increased by 2x.

**To Reproduce**
To play a song.
Give command to pause it.
Then give resume command after one minute.

**Expected behavior**
The song should be resumed from where it was paused.

**Screenshots**

**Please complete the following information:**
 - Node Version: [14.x]
 - Discord Player Version: [4.0.7]
 - Discord.js Version: [x.x.x]
- Linux Platform.

**Additional context**

**Comment by Snowflake107** [comment]
Please check: https://discord-player.js.org/#/docs/main/master/faq/pause_resume
Also #342
