### ISSUE TITLE
Spotify Thumbnails BUG

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#424]
**Describe the bug**
1) Thumbnail Image Link of spotify tracks are invalid and tested on browser , image don't popup . This is happening with every Spotify Track as Single / Playlist/ Album [ Tested on all ]
Thumbnail Link Example - https://i.scdn.co/image/a46f5c5745a14fbf826186da8da5ecc3  [ Link format is almost same for all songs ]

2) Second Spotify Links is taking little bit time to play song in all conditions like playing Single Tracks or Playing Song in Playlists / Albums . earlier 4.0.7 the response time was good . May its because in 4.0.8 its fetching song directly from spotify . I mentioned because i thought response time was kind of taking little bit long everytime during starting song or triggering `TrackAdd` event . 

3) Third Bug I found was that , When I play Playlist the first song got played but it also saved in queue too like if we skip it then we will listen it again . Proof - https://i.imgur.com/XJ2O6GX.png    [ Look on Current Track and First Song on Queue ]

**To Reproduce**
1. For First Error - Play any Song of Spotify Track/Playlist/Album , when `TrackStart` event will be triggered , see the track details and look for thumbnail object , link is found invalid in browser

2. For Second Error - Thats happening for all song of Spotify Link , Basically the mentioned update may be

3. Play a Playlist/Album and skip the first the song , you will listen it again like its being added twice at start .

**Expected behavior**
Results like i gave as a Proof

**Screenshots**
1. Thumbnail Link Example - https://i.scdn.co/image/a46f5c5745a14fbf826186da8da5ecc3  [ Link format is almost same for all songs ]

3. Proof - https://i.imgur.com/XJ2O6GX.png    [ Look on Current Track and First Song on Queue ]

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.0.8]
 - Discord.js Version: [12.5.3]

**Additional context**
May be Youtube fetching was good with only title search because the response time is a bit annoying when playing playlists / album just like `v4.0.7` ! [ I am Suggesting only ]

**Comment by Snowflake107** [comment]
yeah, there is something not right with the spotify thumbnails

**Comment by SidisLiveYT** [comment]
> yeah, there is something not right with the spotify thumbnails

yeah ! and the response time has been effected for spotify songs too , and playlist and album also have that bug i mentioned !

**Comment by Snowflake107** [comment]
what do you mean by that? Spotify songs take time as usual. Loading spotify playlists used to take a long time before while it takes like a second now

**Comment by Snowflake107** [comment]
Also, if you think previous spotify handler was faster than the current handler, you can use the old handler by adding `fetchBeforeQueued: true` in player options

**Comment by SidisLiveYT** [comment]
> Also, if you think previous spotify handler was faster than the current handler, you can use the old handler by adding `fetchBeforeQueued: true` in player options

okk ! I will try it !

**Comment by SidisLiveYT** [comment]
But Bug 3 is real , the first song is there twice in the queue , I gave the Screenshot too !

**Comment by Snowflake107** [comment]
#425
