### ISSUE TITLE
[BUG] tracks array in Player object sometimes have the first song missing

### ISSUE THREAD

**Issue by Kai9073** [Androz2091/discord-player#427]
in the event "playlistAdd", there is a parameter 'playlist' which returns a playlist object
but, the "queue" array inside the playlist object sometimes don't include the first song in the playlist
(usually there's about 50% chance to have the first song not included)

**To Reproduce**
1. Play a playlist
2. Use player.on('playlistAdd'); Log the playlist object to console and check the tracks array

**Expected behavior**
Tracks array should include all tracks in the playlist

**Screenshots**
![image](https://user-images.githubusercontent.com/74895715/118201880-1a527f00-b48b-11eb-93cc-0c8e37697aec.png)
![image](https://user-images.githubusercontent.com/74895715/118201901-2d654f00-b48b-11eb-9b42-c17abd76010c.png)

**Code**
```js
client.player.on('playlistAdd', (message, queue, playlist) => {
      console.log('Player emitted playlistAdd Event')
      console.log(playlist)
})
```

**Please complete the following information:**
 - Node Version: 14.15.4
 - Discord Player Version: 4.0.9
 - Discord.js Version: 12.5.3

**Comment by Snowflake107** [comment]
This happens to the first playlist (the playlist which was added in empty queue) where the first song in that playlist starts playing immediately, which is emitted in `trackStart` event instead. Rest of the tracks are emitted with `playlistAdd` event.

This is not really a bug but it's more like a way how discord-player handles playlists.

The first song is always included in queue so you wont have any problem with it, it only happens to the `playlistAdd` event.

**Comment by Kai9073** [comment]
I tried adding the playlist five times in a row
The first time, probably because the first song is being immediately played, the first song is not included
The second and fourth time, the first song is included
However, the first song is still missing in the third and fifth time.

**Comment by Kai9073** [comment]
The queue was not cleared, so the song wasnt being played immediately in the 2nd - 5th time.

**Comment by Snowflake107** [comment]
I changed the `playlistAdd` in v4.0.8 which always includes the first item. If you are uncomfortable with v4.0.9 just for not having the first item in `playlistAdd` event, you can downgrade to v4.0.8. I don't see why `playlistAdd` would be so important here tbh. Discord player always handled the playlist in this way from the beginning (not only v4)

**Comment by Kai9073** [comment]
Okay, thanks for the help.

**Comment by Snowflake107** [comment]
There was an update for `ytdl-core` so I will have to update this lib as well. I am thinking about resolving your issue with it

**Comment by Snowflake107** [comment]
update your dep
