### ISSUE TITLE
[BUG] playlist.videoCount

### ISSUE THREAD

**Issue by hands8142** [Androz2091/discord-player#430]
**Describe the bug**
You can use playlist.videoCount to play YouTube playlists, but undefined when you use Spotify playlists.

**To Reproduce**
When playing https://open.spotify.com/playlist/37i9dQZF1DXbrUpGvoi3TS

**Screenshots**
![스크린샷 2021-05-14 오전 10 07 39](https://user-images.githubusercontent.com/46277532/118205855-4aeee480-b49c-11eb-9aad-6a2d357889cc.png)

**Please complete the following information:**
 - Node Version: 16.1.0
 - Discord Player Version: 4.1.0
 - Discord.js Version: 12.5.3

**Comment by Snowflake107** [comment]
Main reason for this is youtube and spotify are different + discord player currently does not have a playlist structure to define a playlist properly. Playlist structure is planned for v5 which solves this problem

**Comment by Snowflake107** [comment]
For now, you should check the playlist info properly or use `playlist.tracks.length` because playlist structure will be added in v5

**Comment by hands8142** [comment]
okay thank you
