### ISSUE TITLE
[ BUG ] Spotify Autoplay Bug

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#431]
**Describe the bug**
Autoplay doesn't work on Spotify Tracks , gives a console error . like - [Imgur](https://i.imgur.com/pFw8dJI.png) , On 4.0.7 , it was working fine i guess because , song was fetched by Youtube !

**To Reproduce**
1. Play a Track of Spotify and enable autoplay
2. After the ending of Track , as per autoplay it should work but , bot get crashed with console error .

**Expected behavior**
something is undefined OR its like it can't fetch from Spotify , But I remembered on 4.0.7 , it was working fine on both Youtube and Spotify

**Screenshots**
<a href="https://imgur.com/pFw8dJI"><img src="https://i.imgur.com/pFw8dJI.png" title="source: imgur.com" /></a>

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**
May be its a small bug on playing from Spotify !

**Comment by Snowflake107** [comment]
I dont think it is possible to fix this issue because autoplay works for youtube only.

**Comment by SidisLiveYT** [comment]
> I dont think it is possible to fix this issue because autoplay works for youtube only. I can get rid of that error though..
> 
> Also, it is also possible to create fake autoplay using the youtube url assigned to that spotify track but it would not make any sense for spotify

2nd Option will be better because it will be normal as on Previous versions , fetching from Youtube was normal so it will be good , because i guess autoplay should work for spotify track too
**So I suggest to search the track title on youtube at the end of queue on Autoplay Mode , But Don't do** - `artist - title` thing , it kind of broke the search results and the accuracy , Just the `title track` !

**Comment by devPhytols** [comment]
My code works fine, and autoplay works normally...

**Comment by Snowflake107** [comment]
This was marked as `fixed on development` and I've already published the develop version. You can try that and if you find this problem again, feel free to re-open
