### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AbsolutelySteven** [Androz2091/discord-player#432]
!play isn't playing anything

**To Reproduce**

1. Request to play any song

**Expected behavior**
1. Play the song
or
2. Log an error

**Please complete the following information:**
 - Node Version: v12.16.1
 - Discord Player Version: 4.1.0
 - Discord.js Version: 12.5.3

**Additional context**
My bot joins upon requesting a song, has the lil' ring to signify that its speaking when it is not. I try pausing to see if it would do anything but it returns that the bot is loading the song. It stays for minutes and minutes and nothing plays. The queue command does work and shows the requested song(s).

I was getting reports of my bot playing songs but it would spike in latency up to 3000ms for the entirely of the song and would be barely enjoyable. I decided to update the dependencies i had to see if i had something outdated but it now doesnt play anything. 

I use repl for my hosting with the premium repl plan <-- just incase

**Comment by Snowflake107** [comment]
That might be the voice channel region. I never had such problem

**Comment by AbsolutelySteven** [comment]
I mean, it could, but the bot doesnt play the song it was requested to. It just stays there loading it. If you do !np the bot says 0:00 in progress

**Comment by AbsolutelySteven** [comment]
![image](https://user-images.githubusercontent.com/76920178/118382821-01e77f00-b5c7-11eb-9031-4a453d2b5a2c.png)

**Comment by Snowflake107** [comment]
Don't know... Your song works for me

![image](https://user-images.githubusercontent.com/46562212/118382842-f755d580-b618-11eb-9e73-ab5806c22287.png)

**Comment by Positive2022** [comment]
is that music starting error in second image?
If yes, then there is something in the code that stops song upon starting :prayge:
