### ISSUE TITLE
[Feature Request]: PlayerOption: leaveOnAllListenersLeave + timeout

### ISSUE THREAD

**Issue by MaxTechnics** [Androz2091/discord-player#433]
Right now, discord-player disconnects from the voice channel instantly when all the listeners have left. 
I would like to see an option to disable this behavior. And/or a timeout you can set. When the voice channel is empty for x ms, then disconnect. 

This would be cool for people who just briefly disconnect because of a network glitch or something similar.

**Comment by Snowflake107** [comment]
Use the `leaveOnEmptyCooldown` option https://discord-player.js.org/#/docs/main/master/typedef/PlayerOptions

**Comment by MaxTechnics** [comment]
Oh, how did i not see this. Thank you!
