### ISSUE TITLE
[QUESTION] UnrecoverableError

### ISSUE THREAD

**Issue by commandxz** [Androz2091/discord-player#437]
When using my bot to play music for a long time, this error occurs. Can you tell me what the cause is?

![image](https://user-images.githubusercontent.com/78924158/118476218-6f1a2200-b737-11eb-81ee-5d334ab8e147.png)

**Comment by Snowflake107** [comment]
Listen to the `Error` event

**Comment by Snowflake107** [comment]
seems to be fent/node-ytdl-core#921
