### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#439]
**Question**

Can I use @discord-player/downloader and @discord-player/extractor both together ??
discord-player by default support SoundCloud. And @discord-player/downloader also enable support for SoundCloud too (along with 700+ more sites). So my question is that — `is it cause any problems for SoundCloud stream? `

**Comment by Snowflake107** [comment]
custom extractors can block all the built-in default extractors (built-in) if they validate the query properly and have `important` property set to `true`. In case of `@discord-player/downloader` and `@discord-player/extractor`, both of them block the default extractors (built-in)

**Comment by L0SER8228** [comment]
Thank you so much 🙂

**Comment by L0SER8228** [comment]
Hey can you please add support for tidal and deezer on @discord-player/extractor

**Comment by Snowflake107** [comment]
maybe
