### ISSUE TITLE
spotify playlist & album

### ISSUE THREAD

**Issue by GabrielSSQ** [Androz2091/discord-player#44]
We need play the spotify albums or playlists, pls add(?)

**Comment by Androz2091** [comment]
Duplicate of #43

**Comment by GabrielSSQ** [comment]
I checked but I did not understand. can you be more descriptive?

**Comment by Androz2091** [comment]
Your issue is the same as the 43 one. It's useless to have two identical issues. As 43 was opened before your one 44, I closed it.
