### ISSUE TITLE
[BUG] Replit

### ISSUE THREAD

**Issue by Madnesssik** [Androz2091/discord-player#442]
**Describe the bug**
Hey, i found out that if you use Replit as bot host u get errors when try to use filters.

**To Reproduce**
- Upload bot to replit.com
- Install all packages etc.
- Run bot
- If u want to turn on any filter u get error from screenshot

**Expected behavior**
- Filter should turn on normally

**Screenshots**
![Discord_HDcRb1x2co](https://user-images.githubusercontent.com/78844616/118680676-39407080-b7ff-11eb-8152-ea32d402d206.png)

**Please complete the following information:**
 - Node Version: [15.3.0]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.1

**Additional context**
Error message:

```
(node:7427) UnhandledPromiseRejectionWarning: Error
    at Object.exports.playError (/home/runner/Midoriya-G/node_modules/ytdl-core/lib/utils.js:124:12)
    at validate (/home/runner/Midoriya-G/node_modules/ytdl-core/lib/info.js:53:25)
    at pipeline (/home/runner/Midoriya-G/node_modules/ytdl-core/lib/info.js:175:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.getBasicInfo (/home/runner/Midoriya-G/node_modules/ytdl-core/lib/info.js:62:14)
(node:7427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7427) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by zyrouge** [comment]
I'm guessing that some filters don't work on repl (due to older versions of ffmpeg maybe?) Does simple filters like bassboost work?

**Comment by Snowflake107** [comment]
I guess we can discuss more about EPIPE here #378
