### ISSUE TITLE
[BUG] player#resume not actually resuming the song.

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-player#443]
**Describe the bug**

I tried playing a song, and it wasn't being resumed.
`client.player.resume(message);`
No errors.
**To Reproduce**

Just try to normally resume a song?

**Expected behavior**

Expected the song to resume.

**Screenshots**

![image](https://user-images.githubusercontent.com/70718540/118728786-09ac5b00-b835-11eb-8512-fa1c6e6da301.png)
[No green circle on the bot being shown, meaning no audio being played.]
**Please complete the following information:**
 - Node Version: [14.7.0]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**

**Comment by Snowflake107** [comment]
https://discord-player.js.org/#/docs/main/master/faq/pause_resume
