### ISSUE TITLE
[Feature Request] play next

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#446]
**Is your feature request related to a problem? Please describe.**

No

`playSkip` feature, to skip the current song and play a new song (without changing the existing queue)

```md
Possible solution: It can be done by `unshift the song` and skip. If you request a song, it `push` the song to the queue and add it to the last of the queue. But if we use `unshit` instead of `push`, it'll add the song to the beginning of the queue. And then we can skip to play it
```
`playlist search` feature, to search  playlist on YouTube with a playlist name

`soundcloud search` , to search tracks on SoundCloud

**Comment by DeathMario** [comment]
Yes. I would like a playlist feature, but is easy to do without the function in the player.

**Comment by L0SER8228** [comment]
Yea , i can do with any `youtube search` library. But i would be great if we can do it within `discord-player`

**Comment by DeathMario** [comment]
> Yea , i can do with any `youtube search` library. But i would be great if we can do it within `discord-player`

Yes

**Comment by Positive2022** [comment]
For the playskip things, just make a seprate cmd in which u skip current song (if any) and play next song. :feelsInvisibleman:

**Comment by L0SER8228** [comment]
> For the playskip things, just make a seprate cmd in which u skip current song (if any) and play next song. :feelsInvisibleman:

Actually it's not like that, it skip the current song and instantly play the requested song . It doesn't affect the rest of the queue

**Comment by Positive2022** [comment]
> > For the playskip things, just make a seprate cmd in which u skip current song (if any) and play next song. :feelsInvisibleman:
> 
> Actually it's not like that, it skip the current song and instantly play the requested song . It doesn't affect the rest of the queue

thats what u said, `to skip the current song and play a new song (without changing the existing queue)`
it doesnt changes existing queue.
If the current song is only song in queue, then u can just add the song in queue and then skip current song.
It will never affect existing queue.

**Comment by L0SER8228** [comment]
What if there is others song in the queue.
Who just listen to Only one song, i don't

**Comment by Positive2022** [comment]
> What if there is others song in the queue.
> Who just listen to Only one song, i don't

do u mean that playskip should not end queue?

**Comment by L0SER8228** [comment]
Obviously, it just skip the current playing song, don't effect the existing queue. And play the requested song

**Comment by Positive2022** [comment]
oopsie, my bad
I think u can still do that easily!
add the requested song to queue. and use jumpto function to jump to requested song in queue. :o

**Comment by L0SER8228** [comment]
If you use jumpto function it'll skip all the previous song, means still there will be no more songs on the queue

**Comment by L0SER8228** [comment]
It can be done by `unshift the song` and skip

**Comment by Positive2022** [comment]
no it doesnt clears queue. see the ss i sent
![Screenshot_9](https://user-images.githubusercontent.com/70850451/121510828-ac579400-ca05-11eb-913e-cb25c7bfaeef.png)
![Screenshot_10](https://user-images.githubusercontent.com/70850451/121510837-aeb9ee00-ca05-11eb-9a87-e1ba241f3f4b.png)

**Comment by Snowflake107** [comment]
In v5, this will look something like `<GuildPlayer>.play(Track, { immediate: true })`

**Comment by Snowflake107** [comment]
This will not be added in the current (v4.x.x) version. You can test this in v5.x.x (`npm i discord-player@dev`)
