### ISSUE TITLE
[QUESTION] LEAVEONEND

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#451]
**Question**
How can I set leaveOnEnd per server?

**Comment by Snowflake107** [comment]
Not possible but we have planned this for v5

**Comment by Samiul30** [comment]
Sorry for another question. I have set leaveOnEnd false in client options and do some staff with stop.js where if the mongo has the guild id then it will not disconnect otherwise it will disconnect from the VC by the code voice.channel.leave() though I have set leaveOnStop: false. Will there will be any err in further?
