### ISSUE TITLE
[BUG] Soundcloud links not playing properly

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#453]
**Describe the bug**

Cannot playing SoundCloud link properly.
I tried with many links , every time i faced same problem. Sometimes it also play the wrong one, sometimes just don't play
**Expected behavior**

It should play SoundCloud link with ease. As it supports SoundCloud too
**Screenshots**

**Please complete the following information:**
 - Node Version: [14.x]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**

The links which i tests are
https://m.soundcloud.com/bollywoodbhangradj/bollywood-party-mix
https://m.soundcloud.com/omer-austin-wyman/iss-pyar-mein-feat-belly-dancer-bob-sinclar-remix-by-austin
https://m.soundcloud.com/munib-mirza1991/sets/indian-party-mix

**Comment by L0SER8228** [comment]
I think it would better, if you use any soundcloud downloader rather than a scraper. As SoundCloud support for directly playing without any problem

**Comment by Snowflake107** [comment]
This isn't the problem with downloading audio. If you want us to use api based lib then this is a bad idea for bigger bots as they frequently get rate-limited

**Comment by Snowflake107** [comment]
And the reason for your links to not work, I guess your link is from mobile site: `m.soundcloud.com`. I think you should open this issue at https://github.com/DevSnowflake/soundcloud-scraper
