### ISSUE TITLE
[BUG] YouTube Playlist

### ISSUE THREAD

**Issue by MrPerfectShot** [Androz2091/discord-player#454]
**Describe the bug**
Bot dont add  Playlist from youtube.

**To Reproduce**
play https://www.youtube.com/watch?v=j5-yKhDd64s&list=RDEMASZzAB4N6PSfsOwzAhxYyQ&start_radio=1

**Expected behavior**
it’s supposed to add an entire playlist and not just the first song 

**Please complete the following information:**
 - Node Version: v14.16.0
 - Discord Player Version: ^4.1.0
 - Discord.js Version: ^12.5.3

**Additional context**
I tried with this playlist https://www.youtube.com/watch?v=j5-yKhDd64s&list=RDEMASZzAB4N6PSfsOwzAhxYyQ&start_radio=1

**Comment by Samiul30** [comment]
Doesn't playlist of yt contains playlist word in its query string?

**Comment by MrPerfectShot** [comment]
Link have &list=RDEMASZzAB4N6PSfsOwzAhxYyQ and all playlist i found have &link=something

**Comment by Samiul30** [comment]
https://youtube.com/playlist?list=PLRBp0Fe2GpgnSrjNdapocrPGub4AAgNdm

This is the playlist link.

**Comment by MrPerfectShot** [comment]
But before I was able to add a playlist with a link like this https://www.youtube.com/watch?v=j5-yKhDd64s&list=RDEMASZzAB4N6PSfsOwzAhxYyQ&start_radio=1

**Comment by Samiul30** [comment]
> But before I was able to add a playlist with a link like this https://www.youtube.com/watch?v=j5-yKhDd64s&list=RDEMASZzAB4N6PSfsOwzAhxYyQ&start_radio=1

This is not a playlist.

**Comment by MrPerfectShot** [comment]
Sorry, i test this link https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10, and in version ^3.3.2 it works and add 100 musics, and in new version ^4.1.0 doesnt work

**Comment by Snowflake107** [comment]
First of all, `https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10` is a `/watch` page link, not a playlist link. YouTube playlist links look like `youtube.com/playlist?list=PLAYLIST_ID` and video page links look like `/watch?v=VIDEO_ID`

If you need a playlist, you should use the valid playlist link instead of watch page
