### ISSUE TITLE
[ BUG ] Error - Write EPIPE

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#456]
**Describe the bug**
Console Error - Write EPIPE

**To Reproduce**
Actually It happens by itself , there is not Specific Method , May be by Specific Song 

**Expected behavior**
Emit Console Error [ Write Epipe ] like below Screenshot and Crashes the Bot , and I did use `ytdlDownloadOptions: {
        filter: "audioonly"
    }` , but the live streams can't be played after that .

**Screenshots**
<a href="https://imgur.com/gLpoul4"><img src="https://i.imgur.com/gLpoul4.png" title="source: imgur.com" /></a>

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.1.0
 - Discord.js Version: [12.5.3]

**Additional context**
I add Error handling Code , But it Doesn't catch under default error in switch case statement

**Comment by Snowflake107** [comment]
#378
