### ISSUE TITLE
[BUG] <Player>.resume(message) doesn't work.

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#459]
**Describe the bug**

I have tried reinstalling all the dependencies of the package but whenever I try to resume the playback, it simply does not, when I check .getQueue(message) it appears that the playback is not paused, but still it does not play anything at all.
**To Reproduce**

**Expected behavior**

when the .resume(message) function is executed I expect it to resume playback, which does not happen
**Screenshots**

**Please complete the following information:**
 - Node Version: [14.x]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**

When the resume function is actually not resumed the music, though it's showing it's resumed

**Comment by zocker90** [comment]
this is a bug from discord.js.

to fix it, add the following:
```JS
client.player.resume(message)
client.player.pause(message)
client.player.resume(message)
```

**Comment by L0SER8228** [comment]
Thanks, it's fixed now
