### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by Luc210** [Androz2091/discord-player#460]
**Question**

Hello, I have a question, with the module it is possible to make the bot stay online 24/7 in a voice channel only if the member has the role X and who is the server owner? If yes, how to do it?

**Comment by Androz2091** [comment]
Hello,
Yeah, you can. You should just make a loop that checks whether the bot should stay or not in the channel.
```js
setInterval(() => {

	const guild = client.guilds.cache.get('GUILDID');
	const channel = guild.voice.channel;
	const shouldLeave = !channel.members.some((m) => m.roles.cache.has('ROLEID') && guild.ownerID === m.id);
	if (shouldLeave) channel.leave();

}, 5000);
```

**Comment by Luc210** [comment]
I want to make sure that the bot doesn't leave the voice channel even if there is no member in it

**Comment by Androz2091** [comment]
So use the following code:
```js
client.player = new Player({
	leaveOnEmpty: false,
	leaveOnEnd: false
});
```

**Comment by Luc210** [comment]
Thank you!
