### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by avixityyt** [Androz2091/discord-player#462]
**Question**

is there a way to customize the progressbar? If so could you  tell where? Thanks :)

![image](https://user-images.githubusercontent.com/74422918/119259648-e2101680-bbd7-11eb-9966-f44594ab7082.png)

**Comment by Snowflake107** [comment]
https://discord-player.js.org/#/docs/main/master/typedef/PlayerProgressbarOptions

**Comment by avixityyt** [comment]
> https://discord-player.js.org/#/docs/main/master/typedef/PlayerProgressbarOptions

yeah but it doesn't allow to change the eather the ------ or the thing in middle which would be cool.

**Comment by Snowflake107** [comment]
Looks like we forgot to document it. You can modify the `🔘` with `options.indicatior` and the line with `option.line`:

```js
player.createProgressBar(message, { indicator: "🙂" })
```

**Comment by avixityyt** [comment]
> Looks like we forgot to document it. You can modify the `🔘` with `options.indicatior` and the line with `option.line`:
> 
> ```js
> player.createProgressBar(message, { indicator: "🙂" })
> ```

okay but ▬▬▬▬▬▬▬ that? if so then that's dope , i suggest adding it to docs as i won't be only one wanting to change.
