### ISSUE TITLE
[BUG] Confirm Age Error

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#463]
**Describe the bug**
A Random Error Popup on my Console and its asking to Confirm Age and Bot got crashed by it .

**To Reproduce**
1. Actually I don't know , because Bot is in multiple Servers so I can't confirm , the error just came into my console .

**Expected behavior**
Bot got crashed and emit like a Unhandled Error .

**Screenshots**
<a href="https://imgur.com/gyrZ23v"><img src="https://i.imgur.com/gyrZ23v.png" title="source: imgur.com" /></a>

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**
I also want to fix the Unhandled error , it breaks my bot and crashed , though I added the error event for Music Player with switch case , Still my Bot show handled error which is very confusing , So I need a additional tip about unhandled error issue .

**Comment by Tegnio** [comment]
I guess this error occures when discord-player is trying to play age-restricted content from youtube. You can try enabling `safeSearch` in player options, hope this helps.

**Comment by SidisLiveYT** [comment]
> I guess this error occures when discord-player is trying to play age-restricted content from youtube. You can try enabling `safeSearch` in player options, hope this helps.

will the error be ignored , like if such things comes my bot will not crash ?

**Comment by Tegnio** [comment]
discord-player will not get age-restricted content when using `Player#play` or `Player#search` methods, so the error should be gone

**Comment by Snowflake107** [comment]
that looks like `ytdl-core` issue. That's strange because never had that problem, please report here: https://github.com/fent/node-ytdl-core

**Comment by SidisLiveYT** [comment]
> that looks like `ytdl-core` issue. That's strange because never had that problem, please report here: https://github.com/fent/node-ytdl-core

ooo ,Submit the issue there ! But still can't i ignore the future crashes ?? because it effects my Bot uptime !

**Comment by zyrouge** [comment]
> > that looks like `ytdl-core` issue. That's strange because never had that problem, please report here: https://github.com/fent/node-ytdl-core
> 
> ooo ,Submit the issue there ! But still can't i ignore the future crashes ?? because it effects my Bot uptime !

You should be handling those errors instead of it crashing the process.

**Comment by SidisLiveYT** [comment]
> > > that looks like `ytdl-core` issue. That's strange because never had that problem, please report here: https://github.com/fent/node-ytdl-core
> > 
> > 
> > ooo ,Submit the issue there ! But still can't i ignore the future crashes ?? because it effects my Bot uptime !
> 
> You should be handling those errors instead of it crashing the process.

I added a switch statement , EPIPE error got handled but these errors doesn't !

**Comment by SidisLiveYT** [comment]
> that looks like `ytdl-core` issue. That's strange because never had that problem, please report here: https://github.com/fent/node-ytdl-core

I opened the issue and i got a reply ! 
![Capture](https://user-images.githubusercontent.com/67759305/119716716-093e4080-be83-11eb-8db6-a135c6578cb9.PNG)

**Comment by Snowflake107** [comment]
update discord-player
