### ISSUE TITLE
[BUG] Autoplay Bug

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#464]
**Describe the bug**
During Autoplay , Bot usally loop 4 - 7 Songs every time , sometimes shuffled or in same order , and if there is 2 songs with two different theme in queue , and if we on autoplay , Bot usually play songs related to both songs like side by side and it loops like previously i told you . I guess Autoplay Feature needs some Modifications .

**To Reproduce**
1. For First Issue --> Play a Song and Autoplay , wait for 3 - 7 Songs , after that you will expect 90% time Songs will repeat .
2. For Second Issue --> Play a Song and Add another song just after that , then turn on the Autoplay and then you will see next song related to First one and then second song will be related to Second song you added , and it will loop after sometime like First Issue .

**Expected behavior**
1) First Issue --> Songs will come every after few songs 
2) Second Issue --> Songs will be in loop but like side ways 

**Screenshots**
1) As autoplay , i guess i can't give proof for it , its just happen

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**
Modifying Autoplay with better Selecting Songs without picking the Previous one just like other Big bots does , because , it doesn't happen with them , every song of their is diffrent from last on , but relatable . and for Second issue , it will be good if Bot search songs based on last song played by it ! Otherwise song with english and other language will lead to mixup ! and it does happened with me and my Users .

**Comment by Snowflake107** [comment]
Autoplay gets its next song from youtube's video page:
![image](https://user-images.githubusercontent.com/46562212/119265997-b2c5cd80-bc08-11eb-979f-a34a2a81703b.png)

and we dont have control on what comes next

**Comment by SidisLiveYT** [comment]
Hmm thought so , still on Second Issue , can't you just check on last song played ? it really take both songs and play it in that manner !

**Comment by SidisLiveYT** [comment]
> Autoplay gets its next song from youtube's video page:
> ![image](https://user-images.githubusercontent.com/46562212/119265997-b2c5cd80-bc08-11eb-979f-a34a2a81703b.png)
> 
> and we dont have control on what comes next

btw can you check my other issue about Unhandled Error ?
