### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by avixityyt** [Androz2091/discord-player#467]
**Question**
Is there a way  i can improve the music playing without it lagging? Like my all pings are good ( below 50 ) , so idk if i need to config something myself...

**Comment by avixityyt** [comment]
no reply :/

**Comment by VinxVinx** [comment]
Yes, u can modify the quality song when you define <client>.player :

```js
const player = new Player(client, {
     quality: 'highestaudio'
});

**Comment by avixityyt** [comment]
> Yes, u can modify the quality song when you define your [client].player :
> 
> ```js
> const player = new Player(client, {
>      quality: 'highestaudio' // or low, medium or high
> });
> ```

well that didn't do much 🗿

**Comment by VinxVinx** [comment]
Normally your ping is not supposed to increase much

**Comment by avixityyt** [comment]
> Normally your ping is not supposed to increase much

well my ping is normal playing music or not it's same

**Comment by avixityyt** [comment]
well looks like no hope here lmao

**Comment by u-sayuri** [comment]
you can try to see if your program has many synchronous actions. that sometimes interrupt the player from playing, good luck
