### ISSUE TITLE
Player wont play

### ISSUE THREAD

**Issue by blaise69** [Androz2091/discord-player#47]
Good morning,
My name is Blaise.... I am a Discord Bot Developer, i have started using this package for my discord bot, but now it seems to not be able to play any thing...... If you need code lmk

**Comment by Androz2091** [comment]
Hello
Yes, we need the code and the error please.

**Comment by blaise69** [comment]
Hey ```js
 if (!msg.member.voice.channel) return msg.channel.send(`${config.error} | You are not in a voice channel`);
        if (msg.guild.me.voice.channel && msg.member.voice.channel.id !== msg.guild.me.voice.channel.id) return msg.channel.send('**Error** | You are not in my voice channel')
//this is all it sends....
        if (!this.client.player.isPlaying(msg.guild.id)) {
            return msg.channel.send(`${config.error} | I'm not playing anything...`);
        }

        // if(!query) return msg.channel.send(`**Error** | Please provide `)

        let search = await this.client.player.searchTracks(query).catch(e => {
            return msg.channel.send(`${config.error} | No results were found!`);
        });
        let requestedBy = this.client.users.cache.get(msg.author.id).tag
        if (search.length < 1) return msg.channel.send(`**Error** | No results were found!`);
        let track = search[0];
        if ((track.duration.split(":").length >= 3) && parseInt(track.duration.split(":")[0]) >= 3 && parseInt(track.duration.split(":")[2]) >= 1) return msg.channel.send("**Error** | Cannot play the songs that are longer than 3 hours.");
        if (this.client.player.isPlaying(msg.guild.id)) {
            let song = await this.client.player.addToQueue(msg.guild.id, query, requestedBy);
            msg.channel.send({
                embed: {
                    color: config.successColor,
                    description: `${config.sucess} **|** [${song.name}](${song.url}) **Added to the queue!** \n\n Duration: \`${song.duration}\`\n\n Requested : \`${song.requestedBy}\`\n\n Author: \`${song.author}\``,
                    thumbnail: {
                        url: song.thumbnail
                    }

                }
            })
        } else {
          let song = await this.client.player.play(msg.member.voice.channel, query, requestedBy);
            msg.channel.send({
                embed: {
                    color: config.successColor,
                    description: `🎵 **| Now Playing:**\n[${song.name}](${song.url}) \n\n Duration: \`${song.duration}\`\n\n Requested: \`${song.requestedBy}\`\n Author: \`${song.author}\``,
                    thumbnail: {
                        url: song.thumbnail
                    }
                }
            });
```

**Comment by blaise69** [comment]
some reason i think it is a `discordjs/opus` issue

**Comment by blaise69** [comment]
@Androz2091 i have fixed that but i have another question.... 
us there a way i can map out what exact filters are enabled in the player?

**Comment by Androz2091** [comment]
and the error please...

**Comment by Androz2091** [comment]
>  i have fixed that but i have another question....
How did you fix the problem? And what was it?

> us there a way i can map out what exact filters are enabled in the player?
```js
Object.keys(this.client.player.filters); // array with all the filters names.
```

> and if only there was a way to stop the pause when a filter is turned on......
No, it depends of your server performance.

**Comment by blaise69** [comment]
yeah so `discordjs/opus` needed an update and sweet thanks
