### ISSUE TITLE
[QUESTION] first track of parsed playlist got played twice: handled incorrectly or bug?

### ISSUE THREAD

**Issue by u-sayuri** [Androz2091/discord-player#477]
after parsing youtube playlist, it created an empty queue with the first track and merged that with resolved playlist, the result was that the first track of parsed playlist gets played twice
tried skipping on init but got thrown `e: MusicStarting`

initial response `TrackStart` event, but seemed like the queue only had that first song (indicated by the footer of the embed)
![image](https://user-images.githubusercontent.com/54628820/119778407-afc12a80-bef1-11eb-807f-85a3e3994b17.png)

right after that, i called the queue and oh...
![image](https://user-images.githubusercontent.com/54628820/119778739-147c8500-bef2-11eb-82d0-8aabe277ac24.png)

source (ts)
```ts
const track = tracks[0];                        
const queue = (await this._createQueue(message, track).catch((e) =&gt; void this.emit(PlayerEvents.ERROR, e, message))) as Queue;                        
this.emit(PlayerEvents.PLAYLIST_ADD, message, queue, pl);                        
this.emit(PlayerEvents.TRACK_START, message, queue.tracks[0], queue);                        
tracks.shift();                        
this._addTracksToQueue(message, tracks);
```

compiled (js) (commented codes are not from the library)
```js
const track = tracks[0];
const queue = (yield this._createQueue(message, track).catch((e) => void this.emit(Constants_1.PlayerEvents.ERROR, e, message)));
// const queue = (yield this._createQueue(message, tracks).catch((e) => void this.emit(Constants_1.PlayerEvents.ERROR, e, message)));
this.emit(Constants_1.PlayerEvents.PLAYLIST_ADD, message, queue, playlist);
this.emit(Constants_1.PlayerEvents.TRACK_START, message, queue.tracks[0], queue);
// track.shift()?
tracks[0];
this._addTracksToQueue(message, tracks);
// this._addTracksToQueue(message, tracks.slice(1, tracks.length - 1)); (tracks if tracks.shift() is already included)
```

any answer is very appreciated!

**Comment by u-sayuri** [comment]
kind of resolved?
my solution involves modifying the library code 
I changed so that it only emits `trackStart` after resolving & adding the playlist into queue
removed `track.shift()` to prevent an extra element shift in array
```js
const track = tracks[0];
const queue = (yield this._createQueue(message, track).catch((e) => void this.emit(Constants_1.PlayerEvents.ERROR, e, message)));
this.emit(Constants_1.PlayerEvents.PLAYLIST_ADD, message, queue, playlist);
this._addTracksToQueue(message, tracks);
this.emit(Constants_1.PlayerEvents.TRACK_START, message, queue.tracks[0], queue);
```
after modifying
initial track: displayed properly (as indicated in the embed footer)
![image](https://user-images.githubusercontent.com/54628820/119781057-c026d480-bef4-11eb-9f95-b61258c57c79.png)

queue is also fixed 
![image](https://user-images.githubusercontent.com/54628820/119781230-f8c6ae00-bef4-11eb-806c-8b9ce755062f.png)

but still, any answer is very appreciated!

**Comment by u-sayuri** [comment]
kind of resolved?
my solution involves modifying the library code
I changed the order of the code so that it only emits trackStart after resolving & adding new playlist into the queue

modified part (js) `Player._searchTracks` (3 parts total)
```js
const track = tracks[0];
const queue = (yield this._createQueue(message, track).catch((e) => void this.emit(Constants_1.PlayerEvents.ERROR, e, message)));
this.emit(Constants_1.PlayerEvents.PLAYLIST_ADD, message, queue, playlist);
tracks.shift();
this._addTracksToQueue(message, tracks);
this.emit(Constants_1.PlayerEvents.TRACK_START, message, queue.tracks[0], queue);
```
ts equivalent
```ts
const track = tracks[0];                        
const queue = (await this._createQueue(message, track).catch((e) =&gt; void this.emit(PlayerEvents.ERROR, e, message))) as Queue;                        
this.emit(PlayerEvents.PLAYLIST_ADD, message, queue, pl);
tracks.shift();                        
this._addTracksToQueue(message, tracks);                        
this.emit(PlayerEvents.TRACK_START, message, queue.tracks[0], queue);
``` 
initial track 
![image](https://user-images.githubusercontent.com/54628820/119782874-dfbefc80-bef6-11eb-84ae-3d6c27e86b8d.png)

the queue is now shown correctly, and the issue is gone
![image](https://user-images.githubusercontent.com/54628820/119783794-c7031680-bef7-11eb-8124-3d4d020da2f9.png)

any comments are very appreciated!

**Comment by Snowflake107** [comment]
stale
