### ISSUE TITLE
[BUG] leaveOnEmpty (player option) doesn't work after stop(message) method.

### ISSUE THREAD

**Issue by wojciechjablonski96** [Androz2091/discord-player#478]
The bot does not leave the voice room (when empty) after using the stop command.

If you leave the room while the bot is playing music it works.

My stop method: https://pastebin.com/0VLZ9y9S

 - Node Version: 14.17.0
 - Discord Player Version: 4.1.0
 - Discord.js Version: 12.3.1

**Comment by VinxVinx** [comment]
Hello,

Do you have any error in your console?

**Comment by wojciechjablonski96** [comment]
> Hello,
> 
> Do you have any error in your console?

Nope. 


The errors that I find I think concern the bug (already known) of the videos with limited age. (i think)

Error log: https://pastebin.com/ykCUu8ZJ

**Comment by Snowflake107** [comment]
Hey, do you have `leaveOnStop` enabled?

**Comment by Snowflake107** [comment]
you should enable `leaveOnStop` to make the bot leave your vc on stop command

**Comment by wojciechjablonski96** [comment]
> you should enable `leaveOnStop` to make the bot leave your vc on stop command

leaveOnStop and leaveOnEmpty don't they work separately?

if I want the bot to leave the voice room when everyone leaves what should I do? (with or without the stop command)

**Comment by Snowflake107** [comment]
> if I want the bot to leave the voice room when everyone leaves what should I do? (with or without the stop command)
Set `leaveOnEmpty` to `true`

**Comment by wojciechjablonski96** [comment]
> > if I want the bot to leave the voice room when everyone leaves what should I do? (with or without the stop command)
> > Set `leaveOnEmpty` to `true`

leaveOnEmpty is already true and it does not work.

**Comment by DevAndromeda** [comment]
this might be because `stop` kills the queue and since the queue is killed, it no longer checks for empty channels
