### ISSUE TITLE
TypeError: Cannot read property 'on' of null

### ISSUE THREAD

**Issue by Misly16** [Androz2091/discord-player#48]
Hey, whenever i play a song using the queue feature i get TypeError: Cannot read property 'on' of null pointing to this portion.

![image](https://user-images.githubusercontent.com/60405462/87702839-d7a01780-c791-11ea-8e6c-02e1db7a6cdc.png)

**Comment by BenjaminJForster** [comment]
Hey there, have you tried:

   client.player
      .getQueue(message.guild.id)
      .on("end", () => {
        message.channel.send(

message.channel.send(`**Playing ${newSong}**`)

And:

.on("trackChanged", (oldTrack, newTrack, skipped, repeatMode) => {
        if (repeatMode) {
          message.channel.send(`**Repeating ${newSong}**`)
} else {
          message.channel.send(`Now Playing ${newSong}**`)
