### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by AnshhSingh** [Androz2091/discord-player#481]
can we add a option to players to let us choose a custom bitrate currently it's 32kbps (I think) this will let us use best quality possible

**Comment by Snowflake107** [comment]
bitrate is same as the voice channel bitrate

**Comment by AnshhSingh** [comment]
> bitrate is same as the voice channel bitrate

I am not sure about that

**Comment by Snowflake107** [comment]
@AnshhSingh As you can see, discord.js's play function accepts `bitrate` and the **[documentation](https://discord.js.org/#/docs/main/stable/typedef/StreamOptions)** says using `auto` sets the bitrate to voice channel's bitrate

![image](https://user-images.githubusercontent.com/46562212/120218630-bdf8a900-c259-11eb-9925-28ab00cce635.png)

and discord-player uses `auto` as bitrate
![image](https://user-images.githubusercontent.com/46562212/120218685-d49f0000-c259-11eb-8dd6-25a236153a48.png)

**Comment by AnshhSingh** [comment]
> @AnshhSingh As you can see, discord.js's play function accepts `bitrate` and the **[documentation](https://discord.js.org/#/docs/main/stable/typedef/StreamOptions)** says using `auto` sets the bitrate to voice channel's bitrate
> 
> ![image](https://user-images.githubusercontent.com/46562212/120218630-bdf8a900-c259-11eb-9925-28ab00cce635.png)
> 
> and discord-player uses `auto` as bitrate
> ![image](https://user-images.githubusercontent.com/46562212/120218685-d49f0000-c259-11eb-8dd6-25a236153a48.png)

ohh thanks for the info didn't see that
