### ISSUE TITLE
[BUG] INPUT STREAM ERROR

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#485]
**Describe the bug**
I got the error Something went wrong ... Error : Error: input stream: Status code: 404

**To Reproduce**
After updating discord-player to latest version play any song.

**Expected behavior**
It should play

**Screenshots**

**Please complete the following information:**
 - Node Version: [x.x.x]
 - Discord Player Version: [x.x.x]
 - Discord.js Version: [x.x.x]

**Additional context**

**Comment by zyrouge** [comment]
![image](https://user-images.githubusercontent.com/50770114/120214938-c7cade00-c252-11eb-8d07-c1879caa03ed.png)
Please provide those.

**Comment by Samiul30** [comment]
Node Version : 14.x.x
Discord.js: latest
Discord-player: 4.0.1

**Comment by Snowflake107** [comment]
ytdl issue which got fixed recently

**Comment by Samiul30** [comment]
Need to update ytdl?
