### ISSUE TITLE
[BUG] ERR IN SOUNDCLOUD

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#492]
**Describe the bug**
Play any Soundcloud Song with url and the err is node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ERROR_NO_URL".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
[nodemon] app crashed - waiting for file changes before starting...

**To Reproduce**
Play SoundCloud song with url
**Expected behavior**
It should play the song smoothly.

**Screenshots**

**Please complete the following information:**
 - Node Version: [14.x.x]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [latest]

**Additional context**

**Comment by Snowflake107** [comment]
which soundcloud song to be exact?

**Comment by Snowflake107** [comment]
stale, re-open this when needed
