### ISSUE TITLE
How can i get the queue song count? 

### ISSUE THREAD

**Issue by muhitrhn** [Androz2091/discord-player#493]

**Comment by Snowflake107** [comment]
You can get that with **[\<Queue\>.tracks](https://discord-player.js.org/#/docs/main/master/class/Queue?scrollTo=tracks).length**

**Comment by muhitrhn** [comment]
I have tried - 
```
const queue = this.client.player.getQueue(message);
message.channel.send(queue.tracks.length);
```
Replied with **1** track but I had **27** in queue.
