### ISSUE TITLE
[QUESTION] New commands

### ISSUE THREAD

**Issue by EmaVilla** [Androz2091/discord-player#496]
**Question**
How I can add some new command to the bot? I mean, for example !random that sends random message from a list. I created a .js file with the code but it gives me an error, I don't know where I've to go to modify the code and make the command work

**Comment by L0SER8228** [comment]
Wdym by random message. It's a music package. 
Further you have to provide the Error and if possible the code too to fix your Error

**Comment by MathInDOS** [comment]
> **Question**
> How I can add some new command to the bot? I mean, for example !random that sends random message from a list. I created a .js file with the code but it gives me an error, I don't know where I've to go to modify the code and make the command work

It's a music package, and It's not made for send random text messages.
