### ISSUE TITLE
[BUG] An error occurred... Code: `Error: input stream: write EPIPE`

### ISSUE THREAD

**Issue by muhitrhn** [Androz2091/discord-player#504]
Anyone knows a fix for this error?
This error shows after playing the music for 7 hours using queue looping and the music stops but the bot doesn’t leave vc.
I have tried adding this line in player but didn’t help and made the music fully laggy.
```
ytdlDownloadOptions: {
        filter: "audioonly"
    }
```

**Comment by Snowflake107** [comment]
#378
