### ISSUE TITLE
[BUG] Music is laggy.

### ISSUE THREAD

**Issue by muhitrhn** [Androz2091/discord-player#506]
Hi, i found out playing music with `discord-player` is not smooth. Maybe it’s a bitrate issue? What is the proper bitrate for the player to play music without getting stuck?

**Comment by Snowflake107** [comment]
The bitrate is same as your voice channel

**Comment by muhitrhn** [comment]
Is there anything i need to do to make it smoother?

**Comment by sujalgoel** [comment]
what's the bitrate of your voice channel? and also check your internet speed
https://fast.com/

**Comment by muhitrhn** [comment]
> what's the bitrate of your voice channel?
It’s 64kbps (default)

> and also check your internet speed
> https://fast.com/
![89388AD5-0571-47BB-9DDA-00FE4E2504AC](https://user-images.githubusercontent.com/36473811/121148651-c6f20780-c863-11eb-80bc-a4771855c245.jpeg)

**Comment by muhitrhn** [comment]
Oh, okay.
