### ISSUE TITLE
[Feature Request]: use new discordjs/voice pacakge

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [Androz2091/discord-player#507]
**Describe the solution you'd like**
The `discordjs/voice` package should be implemented into `discord-player`

**Describe alternatives you've considered**
Implement the new voice package into discord-player.

**Additional context**
link to the new package: <https://github.com/discordjs/voice>

_ik this could be a lot of work, I appreciate the hard work that has been done already <3!_

**Comment by Snowflake107** [comment]
yes this is planned

**Comment by PuneetGopinath** [comment]
Is v5 released, you have moved it to done in v5?

**Comment by PuneetGopinath** [comment]
When will v5 be released?

**Comment by SidisLiveYT** [comment]
In v5 , i got this thumbnail url from youtube video - https://i3.ytimg.com/vi/bij0FI85AbA/maxresdefault.jpg and getting same url for every track its been played ! I have latest v5
