### ISSUE TITLE
[BUG] Thumbnail Bug on Spotify Song

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#513]
**Describe the bug**
No thumbnail is being given when bot plays solo songs of spotify , but when a playlist/album is played with same songs , thumbnail is received . may be a small bug ! It happens only with all solo spotify songs .

**To Reproduce**
1. Play a song like solo not a platlist/album
2. try to render thumbnail , a Unnatuaral behaviour will happen

**Expected behavior**
No thumbnail is present when songs are played using their song link not by playlist list

**Screenshots**
![leaving](https://user-images.githubusercontent.com/67759305/121561410-14be6980-ca36-11eb-86c6-48936bfc4270.PNG)

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [4.1.0]
 - Discord.js Version: [12.5.3]

**Additional context**
It was a bug earlier also but in playlists and albums , and also reported then , btw can you fix the autoplay bug of spotify , I know its `fixed on development` ,  but its been more 1 or 2 months may be , and Thanks for the attention for new discord.js/voice . Good work !!!

**Comment by Snowflake107** [comment]
I think thumbnail is not a big issue

**Comment by SidisLiveYT** [comment]
> I think thumbnail is not a big issue

Still I told you because it was there in playlist but not for single songs link !
