### ISSUE TITLE
[BUG] Error: input stream: Status code: 429

### ISSUE THREAD

**Issue by devPhytols** [Androz2091/discord-player#516]
When I try to play some songs, I get "Error: input stream: Status code: 429" I believe the problem is not in the music because in other bots it plays normally...
[Print Error](https://imgur.com/EcYrvr1)

**Comment by Snowflake107** [comment]
It's a ratelimit from youtube. You have to use Proxy to bypass this ban

**Comment by devPhytols** [comment]
> It's a ratelimit from youtube. You have to use Proxy to bypass this ban

how could i do this?

**Comment by Snowflake107** [comment]
https://discord-player.js.org/#/docs/main/master/youtube/proxy

**Comment by devPhytols** [comment]
> [https://discord-player.js.org/#/docs/main/master/youtube/proxy ](https://discord-player.js.org/#/docs/main/master/youtube/proxy)

I'll take a look, thanks a lot!
