### ISSUE TITLE
STATUS CODE 429

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#517]
**Question**
How to fix status code 429?
Or how to use proxy?

**Comment by zocker90** [comment]
https://github.com/Androz2091/discord-player/tree/master/docs/youtube

**Comment by Samiul30** [comment]
> https://github.com/Androz2091/discord-player/tree/master/docs/youtube

How to use proxy? Cause cookies is not working

**Comment by Snowflake107** [comment]
Using cookies after getting 429 won't help you

**Comment by Samiul30** [comment]
> Using cookies after getting 429 won't help you

But is proxy will help? If then would mind giving me any example?

**Comment by Snowflake107** [comment]
You need to find a public proxy and use it

**Comment by Samiul30** [comment]
> You need to find a public proxy and use it

Any way to help me out? I am not understanding where to find the public proxy for yt🤦

**Comment by Snowflake107** [comment]
Get it from proxy provider

**Comment by Snowflake107** [comment]
stale, feel free to re-open
