### ISSUE TITLE
[QUESTION] How to use proxies?

### ISSUE THREAD

**Issue by SathvikKS** [Androz2091/discord-player#520]
**Question**
I want to know how I can use proxies.

I have used [this](https://github.com/Androz2091/discord-player/blob/master/docs/youtube/proxy.md), with few proxies ip and ports that I found on google. I have manually ping'd those proxies to make sure they are working, but the player never plays any song and throws this 
`Error: input stream: connect ETIMEDOUT ip:port`

This is my setup: 

```
const HttpsProxyAgent = require("https-proxy-agent");

const proxy = "http://ip:port";
const agent = HttpsProxyAgent(proxy);

client.player = new DiscordPlayer.Player(client, {
    leaveOnEnd: true,
    leaveOnEndCooldown: 300000,
    leaveOnStop: false,
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 300000,
    enableLive: true,
    fetchBeforeQueued: true,
    ytdlDownloadOptions: {
        requestOptions: { agent }
    }
});
```

Am I doing any mistakes here? Also [this](https://gimmeproxy.com/api/getProxy) is the site that I am using ti fetch free proxy

**Comment by Positive2022** [comment]
you have to use ip and port of the hosting u use

**Comment by Snowflake107** [comment]
You might have to buy one instead

**Comment by Snowflake107** [comment]
stale, feel free to re-open
