### ISSUE TITLE
[BUG]WRITE EPIPE. 

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#536]
**Describe the bug**
Get this error 404 and write epie when I played https://www.youtube.com/watch?v=zGd7BBorCKA
https://www.youtube.com/watch?v=x3hhOW28fw8
yt url.
**To Reproduce**
1. Play 
https://www.youtube.com/watch?v=zGd7BBorCKA
Or https://www.youtube.com/watch?v=x3hhOW28fw8

**Expected behavior**
Should play.

**Screenshots**

**Please complete the following information:**
 - Node Version: [14.17.1]
 - Discord Player Version: [4.1.1]
 - Discord.js Version: [12.5.3]
 - 
**Additional context**
Rythm can play it. Means lava music bot can play it.

**Comment by Snowflake107** [comment]
#378
