### ISSUE TITLE
Playlist.title

### ISSUE THREAD

**Issue by taNtr1k** [Androz2091/discord-player#538]
Playlist.title does this exist if yes its not working when i am adding Spotify playlist

**Comment by Snowflake107** [comment]
There is not a defined playlist object in v4 so we cannot say what exactly is the playlist object. However, in the next version we have added a fixed playlist object to solve this issue.

**Comment by vkshantanukumar7** [comment]
Where can i find all the existing objects to develop my own code?

**Comment by Snowflake107** [comment]
you can console log playlist object
