### ISSUE TITLE
You need to handle playlists in similar way. Else you may get status code 404

### ISSUE THREAD

**Issue by DragonTahmid1** [Androz2091/discord-player#548]
You need to handle playlists in similar way. Else you may get status code 404

_Originally posted by @Snowflake107 in https://github.com/Androz2091/discord-player/issues/539#issuecomment-866137669_

WORKS thanks!!

**Comment by DragonTahmid1** [comment]
lol sorry

**Comment by DragonTahmid1** [comment]
i created issue, not commented

**Comment by SuperSweatyTejas** [comment]
Can you give an example @snowflake107 of how to handle playlists?
