### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by UndiedGamer** [Androz2091/discord-player#549]
**Question**
Will discord-player be updated to discord.js v13 when discordjs version 13 comes ? because the current version states error while using v13 but works perfectly fine with v12

**Comment by zocker90** [comment]
yes 😺

**Comment by Snowflake107** [comment]
You can test it with `npm i discord-player@dev`

**Comment by UndiedGamer** [comment]
> You can test it with `npm i discord-player@dev`

Oh thanks, I never knew this
