### ISSUE TITLE
Miniget

### ISSUE THREAD

**Issue by Sattishh** [Androz2091/discord-player#55]
Miniget Status Code : 416
I ran into that while using this and I believe it's a simple fix.
It happens because you're playing a video when all you need is the audio
You can fix this by making a filter 'options' in the play() function which gives you audio instead of video. So instead you'll do .play(ytdl(song.url, options))

```
const dispatcher = serverQueue.connection
options = {
  quality: 'highestaudio'
};
 .play(ytdl(song.url, options))

**Comment by Androz2091** [comment]
It should have been fixed in v3.1.0
