### ISSUE TITLE
Hey i am getting this error pls help

### ISSUE THREAD

**Issue by UndiedGamer** [Androz2091/discord-player#552]
const _meta = queueInitOptions.metadata;
                                       ^

TypeError: Cannot read property 'metadata' of undefined
    at Player.createQueue (/mnt/c/Users/heman/OneDrive/Documents/PublicBot/node_modules/discord-player/lib/Player.js:143:40)
    at callback (/mnt/c/Users/heman/OneDrive/Documents/PublicBot/commands/music/play.js:26:31)
      My code:

```js
    		const queue = client.player.createQueue(message.guild);
		const song = await client.player.search(args.join(" "));

		try {
			await queue.connect(message.member.voice.channel);
		}
		catch {
			message.reply("Could not join your voice channel");
		}

		queue.addTrack(song.tracks[0]);
		queue.play();
```

**Comment by Snowflake107** [comment]
Please use the discord server for v5 bug reports: https://androz2091.fr/discord

**Comment by UndiedGamer** [comment]
> Please use the discord server for v5 bug reports: https://androz2091.fr/discord

I am unable to join that server , only that i was able to join other servers at this time but not this one

**Comment by UndiedGamer** [comment]
Shows this screen for so much time, still does not load server
![image](https://user-images.githubusercontent.com/84702365/123203599-40c8f880-d4d4-11eb-93af-618467c3c6d7.png)

**Comment by UndiedGamer** [comment]
Took 6 minutes for the server to load nvm
