### ISSUE TITLE
EventEmitter Error

### ISSUE THREAD

**Issue by DragonTahmid1** [Androz2091/discord-player#553]
(node:445) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:445) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

how do i fix this and where do i put that emitter.setMaxListeners()?

**Comment by DragonTahmid1** [comment]
this occurs when i loop a song

**Comment by Snowflake107** [comment]
This isn't error, it's just a warning. Your code is adding multiple event listeners (for example: `player.on("something")` inside your command)

**Comment by Snowflake107** [comment]
> i'm using the temporary solution of the 404 error, so maybe the loop has to be different or something
🤔 I don't think that has anything to do with this but I will check

**Comment by DragonTahmid1** [comment]
> 
> 
> This isn't error, it's just a warning. Your code is adding multiple event listeners (for example: `player.on("something")` inside your command)

ok, i'll check

**Comment by DragonTahmid1** [comment]
oh, they are all events (11 events) so how do i fix it?

**Comment by Snowflake107** [comment]
You dont add multiple listeners for same event
