### ISSUE TITLE
Getting "Error: input stream: Status code: 404"

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-player#554]
**Describe the bug**
Every time I try to play a song (either from YouTube or Spotify), I get this error.

**Screenshots**
![Screen Shot 2021-06-24 at 18 17 33](https://user-images.githubusercontent.com/14950662/123350621-96bf8f80-d518-11eb-8024-bac8ee4bc47c.png)
![Screen Shot 2021-06-24 at 18 17 50](https://user-images.githubusercontent.com/14950662/123350618-958e6280-d518-11eb-885a-8e601c9b9cf6.png)

**Please complete the following information:**
 - Node Version: 14.16.0
 - Discord Player Version: 4.1.2
 - Discord.js Version: 12.5.3

**Comment by Snowflake107** [comment]
#539
