### ISSUE TITLE
Errors in discord-player@dev branch

### ISSUE THREAD

**Issue by Killerpac** [Androz2091/discord-player#557]
**Describe the bug**
- Error in the Queue.js where queue is not used properly
- trackstart is not working for the music in queue only for the first song in queue its working
-  `Error emitted from the queue: getaddrinfo ENOTFOUND manifest.googlevideo.com` Error while playing live videos(Though it might be a ytdl-core error)
- sometimes the bot stops and emits error for queue and connection

**To Reproduce**
 using the dev branch of discord-player and the example provided with it causes the errors

**Expected behavior**

**Screenshots**
```  node_modules\discord-player\lib\Structures\Queue.js:701
              ^
Error: Cannot use destroyed queue
    at Queue._Queue_watchDestroyed (node_modules\discord-player\lib\Structures\Queue.js:701:15)
    at Queue.setVolume (node_modules\discord-player\lib\Structures\Queue.js:277:84)
    at node_modules\discord-player\lib\Structures\Queue.js:627:22     
    at runMicrotasks (<anonymous>)  ```


**Please complete the following information:**
 - Node Version: [16]
 - Discord Player Version: [dev@latest]
 - Discord.js Version: [13-dev]

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by Snowflake107** [comment]
I think it is not a good idea to open issue for the version that hasn't been released for production. imo it'd be better if you comment on #515 instead of creating issues
