### ISSUE TITLE
Error Code 404 and 429

### ISSUE THREAD

**Issue by iShaddi** [Androz2091/discord-player#558]
Alright so after the 404 code was fixed I tried to update everything and deploy it to heroku however when I did so it ended up giving me the same 404 code as before and sometimes it ends up giving me error code 429

**Comment by Snowflake107** [comment]
429 - You are ratelimited (aka your ip is temporarily banned by youtube)
404 - It's not from our side. And the latest release uses the latest version of ytdl-core which claims to fix 404
