### ISSUE TITLE
support for callbacks in ytsr will be removed in the next release

### ISSUE THREAD

**Issue by PokemonLeader** [Androz2091/discord-player#56]
I keep getting this in the console and it annoys me.. is there anyways i can stop this?

![image](https://user-images.githubusercontent.com/30406817/88399888-37b93e00-cdd0-11ea-802b-772f5dfe1c02.png)

each tym the command is used this pops up!

**Comment by Androz2091** [comment]
Fixed, you can install v2.3.1 (ea3c27f3fc2f2688aaf4244b533a1b66d0ccdd3f).
