### ISSUE TITLE
Play song immediately if URL is provided

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-player#565]
**Describe the bug**
If I was to request a song using a YouTube URL directly, it will still give me a list of search results based on the link. If a URL is provided, wouldn't it make sense to play the song immediately and not show the search results?

**Expected behavior**
The song should immediately play and not show search results if a URL is provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/14950662/123654947-cd80f880-d7eb-11eb-970e-80f545c98cfe.png)

**Please complete the following information:**
 - Node Version: 7.18.1
 - Discord Player Version: 4.1.3
 - Discord.js Version: 12.5.3

**Comment by alima566** [comment]
I'm sorry, I don't understand. Am I supposed to uninstall `@discord-player/extractor`?

**Comment by Snowflake107** [comment]
You should use `npm install @discord-player/extractor@3.0.0` with discord player v4.x.x

**Comment by alima566** [comment]
I did that, but the issue still occurs.

**Comment by Snowflake107** [comment]
> I did that, but the issue still occurs.

are you on the latest version of discord-player? `npm install discord-player@latest`. Also I don't see how this bug became "error"

**Comment by alima566** [comment]
> > I did that, but the issue still occurs.
> 
> are you on the latest version of discord-player? `npm install discord-player@latest`. Also I don't see how this bug became "error"

I did  `npm install discord-player@latest` as well as `npm install @discord-player/extractor@3.0.0` and now it says it can't find any results.
![image](https://user-images.githubusercontent.com/14950662/123687735-822c1180-d80e-11eb-83a6-1f81b69f2010.png)

**Comment by Snowflake107** [comment]
seems to be the problem with **[youtube-sr](https://github.com/DevSnowflake/youtube-sr)**

**Comment by Snowflake107** [comment]
could you open a new issue there?

**Comment by alima566** [comment]
Sure, will do.
