### ISSUE TITLE
Issue with Spotify

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#569]
**Describe the bug**
I have encountered the following err:
1.> - Something went wrong ... Error : TypeError: Cannot read property 'requestedBy' of undefined
2. - Something went wrong ... Error : Error: input stream: write EPIPE

**To Reproduce**
1. Play spotify song with the url : https://open.spotify.com/playlist/4PRCXTSbE6mr5mdSeHXcsw?si=fSBaFQh-QoeJoySyZOk_kw&utm_source=copy-link&dl_branch=1
2. Use skipto command for jump at 5th track.

**Expected behavior**
It should play the song.

**Screenshots**

**Please complete the following information:**
 - Node Version: [14.17.1]
 - Discord Player Version: [4.8.3]
 - Discord.js Version: [12.5.3]

**Additional context**

**Comment by zocker90** [comment]
before making an issue look if it got reported before

**Comment by Samiul30** [comment]
> before making an issue look if it got reported before

If then refer it here.

**Comment by zocker90** [comment]
> > before making an issue look if it got reported before
> 
> 
> 
> If then refer it here.

ye 🗿

**Comment by Samiul30** [comment]
> > > before making an issue look if it got reported before
> > 
> > 
> > If then refer it here.
> 
> ye 🗿 it got reported 69+ times

then without writing this just refer I will close the bug with reffered one. hscs

**Comment by Snowflake107** [comment]
> Discord Player Version: [**4.8.3**]

woah you are in the future

**Comment by zocker90** [comment]
> > > > before making an issue look if it got reported before
> 
> > > 
> 
> > > 
> 
> > > If then refer it here.
> 
> > 
> 
> > ye 🗿 it got reported 69+ times
> 
> 
> 
> then without writing this just refer I will close the bug with reffered one. hscs
> 
> 

https://github.com/Androz2091/discord-player/issues/378

**Comment by Samiul30** [comment]
> > Discord Player Version: [**4.8.3**]
> 
> woah you are in the future

Mistake 😀
