### ISSUE TITLE
How can I set the volume of the bot?

### ISSUE THREAD

**Issue by BenjaminJForster** [Androz2091/discord-player#57]
Hey there, I was wondering how I could set the volume of the bot? It's really quiet still on full and I'd like to make it louder with the .setVolume function but it doesn't seem to work.

**Comment by Androz2091** [comment]
What do you mean by "it doesn't seem to work"?

**Comment by BenjaminJForster** [comment]
I mean, the .setVolume function throws me an error. But forget that, the music is quite quiet when it plays? Is there any way to make it louder?

**Comment by Androz2091** [comment]
You can increase the volume... What's the error?

**Comment by Androz2091** [comment]
Closed due to inactivity.

**Comment by MathInDOS** [comment]
Hello! I also have this issue, that volume is too low for listening, everytime I need to use commands to update volume, it would be great if I can set default volume in Player init.
