### ISSUE TITLE
Playing the song that i haven't searched

### ISSUE THREAD

**Issue by DevRohit06** [Androz2091/discord-player#572]
i'm using the discord-player v5 
and if i play any song it plays the wrong song (some random songs instead of the searched song 
![image](https://user-images.githubusercontent.com/66678395/124013188-a3a01f80-d9ff-11eb-8ffa-eca974176e79.png)
)
![image](https://user-images.githubusercontent.com/66678395/124013408-e19d4380-d9ff-11eb-8f79-ef64a30a0290.png)

**Comment by Snowflake107** [comment]
are you on the latest version?

**Comment by DevRohit06** [comment]
> are you on the latest version?

yeah 

discord-player v5

**Comment by Snowflake107** [comment]
v5 is not ready, please comment on #515 instead of creating issues
