### ISSUE TITLE
[BUG] Bot only responds to URLs, not a search query.

### ISSUE THREAD

**Issue by Thisisnotharry** [Androz2091/discord-player#575]
Not sure if I am stupid, however the bot only responds to YouTube URLs and doesn't bother to search YouTube for any song that applies to the search term.

index.js
`const player = new Player(client, {
    leaveOnEnd: true,
    leaveOnEndCooldown: 300000,
    leaveOnStop: true,
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 0,
    autoSelfDeaf: false,
    enableLive: true,
    ytdlDownloadOptions: {},
    useSafeSearch: false,
    disableAutoRegister: false,
    disableArtistSearch: false,
    fetchBeforeQueued: false
});`

play.js
`const Discord = require('discord.js')

module.exports = {
	name: 'play',
	description: `Join a voice channel and listen to some tunes.`,
  aliases: ['p'],
  usage: '',
	async run (client, message, args) {

client.player.play(message, args.join(" "));

  },
}`

This could be an issue on my end or just that the package doesn't support it. Please help asap.

**Comment by Snowflake107** [comment]
Looks like you are not using `firstResult` because of which, discord player emits searchResult event as a message collector.

You have to either handle searchResult event or use firstResult in `player.play()`
