### ISSUE TITLE
[QUESTION] How do I find a list of commands?

### ISSUE THREAD

**Issue by Thisisnotharry** [Androz2091/discord-player#576]
How do I find a command list, like the things this music package supports, and how to add them into my bot?

I don't see anything on the documentation website that is particularly helpful, 
I'd like to know how to create a queue, progress bar etc etc however I cannot find anything.

Please help me!

**Comment by u-sayuri** [comment]
for what this package offers for you, visit the docs [here](https://discord-player.js.org/)
as for how to commands then it's up to you to implement them into your code
hope that helps :)

**Comment by Snowflake107** [comment]
I don't think it's our problem to give you the list of every possible commands. You need to go through docs and use the available methods to make your commands
