### ISSUE TITLE
Support Stage channel

### ISSUE THREAD

**Issue by Jourdelune** [Androz2091/discord-player#578]
**Is your feature request related to a problem? Please describe.**
Discord player can't connect to a stage channel (No connected)

**Describe the solution you'd like**
Discord player accepts stage channel , version 13 of discord.js can already be used and it would be nice to be able to connect to these channel.

**Comment by Snowflake107** [comment]
Discord player v5 dev supports this #515 

You can test it with `npm i discord-player@dev`
