### ISSUE TITLE
Can't play Soundcloud tracks

### ISSUE THREAD

**Issue by JerryFunHouse** [Androz2091/discord-player#579]
So whenever I give my bot a soundcloud link it will take around 30 seconds for it to give me the following error:
![image](https://user-images.githubusercontent.com/71543051/124381408-61d9d800-dc90-11eb-98d1-4e91d4a7d9e6.png)
![image](https://user-images.githubusercontent.com/71543051/124381416-6ef6c700-dc90-11eb-9b19-a195bae29993.png)

I have not altered anything in the discord-player or soundcloud-scraper module, I tried updating them both but that didn't work either. I can't find any special exceptions for soundcloud in the docs either so am I doing something wrong? Everything else, normal queries, spotify and youtube are all working perfectly. 

Any ideas?

**Comment by Snowflake107** [comment]
You should open a new issue at https://github.com/DevSnowflake/soundcloud-scraper/issues because im unable to transfer this one

**Comment by JerryFunHouse** [comment]
Alright, thanks!
