### ISSUE TITLE
Video duration is incorrect when given a direct YouTube link

### ISSUE THREAD

**Issue by joshuayuen99** [Androz2091/discord-player#584]
**Describe the bug**
When playing a direct YouTube link (as opposed to entering a search phrase and then selecting a song), the internal duration for the song is incorrect. It seems to be 1000 times longer than expected.

**To Reproduce**
Call the play() function with a YouTube link.
Check the video's duration by checking the duration property of the track.

**Expected behavior**
The returned video duration matches up with the actual duration.

**Screenshots**
![image](https://user-images.githubusercontent.com/56708104/124517190-5df1a700-ddb1-11eb-9029-297dde5e0c6c.png)
![image](https://user-images.githubusercontent.com/56708104/124517222-719d0d80-ddb1-11eb-8a1b-b25c2d9808cc.png)

**Please complete the following information:**
 - Node Version: [14.17.3]
 - Discord Player Version: [4.1.4]
 - Discord.js Version: [12.5.3]

**Additional context**
This issue can be fixed by removing the "* 1000" when parsing the duration from the YouTube API data.

**Comment by Snowflake107** [comment]
This was a bug with `youtube-sr` and has been fixed in the recent update but discord-player is still using the older version of `youtube-sr`.

**Comment by Snowflake107** [comment]
reference https://github.com/DevSnowflake/youtube-sr/issues/27
