### ISSUE TITLE
queue.voiceConnection.dispatcher is null if used with ButtonCollector

### ISSUE THREAD

**Issue by Mr-Leonerrr** [Androz2091/discord-player#588]
**Describe the bug**
Using _ReactionCollector_ not give problems, the Message is sent and reactions work perfectly. 
Using _ButtonCollector_ the message is sent, the bot joins the voice channel and plays the track, but the buttons don't work and send the error in console _(without use **queue.voiceConnection.dispatcher** buttons works correctly)_

**To Reproduce**
1. Send message with buttons and create ButtonCollector on `trackStart` event
2. Show in console `queue.voiceConnection.dispatcher`
3. Use your `play` command
4. See your console/terminal

**Expected behavior**
Not get errors

**Screenshots**
_Console/Terminal_
![image](https://user-images.githubusercontent.com/56647065/124711398-a5685800-dec3-11eb-8cc1-3db0245b680e.png)

_Code_
![code](https://user-images.githubusercontent.com/56647065/124711819-258ebd80-dec4-11eb-83f6-44e434b3d982.png)

**Please complete the following information:**
 - Node Version: [16.4.2]
 - Discord Player Version: [4.1.3]
 - Discord.js Version: [12.5.3]

**Comment by Snowflake107** [comment]
why would you attach listener to `queue.voiceConnection` in first place instead of using the events provided by discord-player?

**Comment by Mr-Leonerrr** [comment]
What events can do the same function?
this is only for when the song is over
