### ISSUE TITLE
Slash Commands Support

### ISSUE THREAD

**Issue by LinusBotTips** [Androz2091/discord-player#595]
Hi, I'm trying to make a music bot with slash commands and when I try and run the slash command (/play) I get this error

```
(node:6228) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Player.<anonymous> (C:\Users\***\Documents\GitHub\dischord\node_modules\discord-player\lib\Player.js:436:65)
```
How I defined the guild:
  ```
 const message = interaction.guild_id
   client.player.play(message, song, { firstResult: true });
```

**Comment by u-sayuri** [comment]
it's not a bug 
you passed a possibly `string` value into a `message` parameter
`Player#play()`'s `message` parameter takes a [Message](https://discord.js.org/#/docs/main/master/class/Message) object

**Comment by DevAndromeda** [comment]
You should not use discord-player v4.x with discord.js v13. You can try discord-player v5 dev (`npm i discord-player@dev`) and there is also a **[Slash commands bot example](https://github.com/Androz2091/discord-player/tree/v5/example/music-bot)**
