### ISSUE TITLE
Facing error with new update

### ISSUE THREAD

**Issue by hydraindia** [Androz2091/discord-player#6]
`(node:153) UnhandledPromiseRejectionWarning: voiceChannel must be type of VoiceChannel. value=673975005075341373
(node:153) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:153) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

When I use the play command bot throws that error.

**Comment by Androz2091** [comment]
@hydraindia yes, a fix was deployed 4 minutes ago... Install the package again and it should work!

**Comment by hydraindia** [comment]
ok

**Comment by hydraindia** [comment]
`(node:2378) UnhandledPromiseRejectionWarning: voiceChannel must be type of VoiceChannel. value=null`

**Comment by Androz2091** [comment]
It means you didn't provide a valid voice channel. Are you sure that the member is in a voice channel?

**Comment by hydraindia** [comment]
Issue fixed update it on npm.
