### ISSUE TITLE
queue.voiceConnection.play is not a function

### ISSUE THREAD

**Issue by Nyfos** [Androz2091/discord-player#61]
`         bot.player.play(message.member.voiceChannel, message.content.substr(7, 2000))/*.queue.on('end', () => {
             message.channel.send(embeds[queueEmpty]);
         }).on('trackChanged', (oldTrack, newTrack, skipped, repeatMode) => {
             if(repeatMode){
                 message.channel.send(embeds[playingRepeat]);
             } else {
                 message.channel.send(embeds[playingNext]);
             }
         }).on('channelEmpty', () => {
             bot.player.stop(message.guild.id);
             message.channel.send(embeds[channelEmpty]);
         });*/`

`TypeError: queue.voiceConnection.play is not a function
    at Timeout._onTimeout (/home/nyfos/Secret/node_modules/discord-player/src/Player.js:841:39)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**Comment by Nyfos** [comment]
> **Try to use "connection.play" In Discord. Js 12, it's the only method to play. It's explained in documentation**

Source : [Reddit URL](https://www.reddit.com/r/Discord_Bots/comments/g3o1rz/discordjs_error_typeerror_connectionplaystream_is/)

This solve my problem :)

**Comment by Androz2091** [comment]
Hmm, Discord Player never uses playStream(). But glad to hear that your problem is solved.
