### ISSUE TITLE
Wrong duration format

### ISSUE THREAD

**Issue by MathInDOS** [Androz2091/discord-player#634]
I've just installed discord-player latest version and found out this bug while playing some of music. (Not all of them). It's duration sometimes goes like 2 days, even those music are less than 5 minutes. Here is a screenshot.

![Screenshot_20210726-210119_Discord](https://user-images.githubusercontent.com/71683721/127017051-452b5932-5863-4aae-9bf6-f139edd140b3.jpg)

It's not more than 5 minutes but some of music duration I found this format, it works fine on previous releases.

**Comment by joshuayuen99** [comment]
#584
