### ISSUE TITLE
Not sending trackStart event message (v5)

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#635]
**Describe the bug**

Not sending trackStart message
Only sending trackStart event once for the first song
(It's sending trackStart message if there is no more songs and autoplay is enabled)

**To Reproduce**

**Expected behavior**

It should send trackStart event message, every time there a new song start 
**Screenshots**

**Please complete the following information:**
 - Node Version: [14.x]
 - Discord Player Version: [v5]
 - Discord.js Version: [v13-dev]

**Additional context**

**Comment by DevAndromeda** [comment]
report v5 bugs at #515 instead of creating issues because v5 has not been officially released

**Comment by L0SER8228** [comment]
Ok
