### ISSUE TITLE
Resume function not working

### ISSUE THREAD

**Issue by RamonvanKeulen** [Androz2091/discord-player#639]
**Describe the bug**
The resume function doesnt start the music back up, if you enter the resume command for a second time it says that the music is already playing but it isnt. I waited for twice the duration of the song playing and it was still on the same song so it doesnt play without giving sound, just the function thats broken.

**To Reproduce**
1. Have music playing
2. use the pause function
3. try to resume it

**Expected behavior**
I expected that the music would resume.

**Screenshots**
Not applicable

**Please complete the following information:**
 - Node Version: [14.17.4]
 - Discord Player Version: [4.1.4]
 - Discord.js Version: [12.5.3]

**Comment by Killerpac** [comment]
Have you added the workaround for the discord js bug [Discord js #5300](https://github.com/discordjs/discord.js/issues/5300) 

If not try doing something like this 

```
- client.player.resume(message);

+ client.player.resume(message);
+ client.player.pause(message);
+ client.player.resume(message);
```

**Comment by DevAndromeda** [comment]
#342
