### ISSUE TITLE
Fetch Spotify equivalent song from youtube Error

### ISSUE THREAD

**Issue by Killerpac** [Androz2091/discord-player#657]
**Describe the bug**
fetches the Wrong song from youtube When given certain songs not available in YouTube from Spotify

**To Reproduce**
Use this link as the example 
Use to play the music

https://open.spotify.com/track/2U9Abi4ZwTuJXyyuru5aZJ?si=We-PuApYTPql8O772vVdVw

**Expected behavior**
Should throw an error that equivalent song are not found in YouTube and skip to the next song in queue

**Screenshots**

**Please complete the following information:**
 - Node Version: [na]
 - Discord Player Version: [4]
 - Discord.js Version: [12]

**Additional context**

**Comment by DevAndromeda** [comment]
see https://github.com/Androz2091/discord-player/issues/402#issuecomment-835811367
