### ISSUE TITLE
Voice Channel Connection Timeout Error

### ISSUE THREAD

**Issue by MinhCrafters** [Androz2091/discord-player#673]
**Describe the bug**

When I execute the play command (not using slash cmds), it connected successfully but 20 secs later it returns the timeout error
```
D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\@discordjs\voice\dist\util\entersState.js:17
        const timeout = setTimeout(() => reject(new Error(`Did not enter state ${status} within ${maxTime}ms`)), maxTime);
                                                ^

Error: Did not enter state ready within 20000ms
    at Timeout.<anonymous> (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\@discordjs\voice\dist\util\entersState.js:17:49)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**To Reproduce**
1. execute the play command
2. theres no step 2

**Expected behavior**

it should search and play the specified song

**Screenshots**

**Please complete the following information:**
 - Node Version: [16.5.0]
 - Discord Player Version: [5.0.1]
 - Discord.js Version: [13.0.1]
 - @discordjs/opus Version: [0.5.3]

**Additional context**

Code here:
```javascript
module.exports = {
    name: 'play',
    aliases: ['p'],
    category: 'Music',
    utilisation: '{prefix}play [Name/URL]',

    async execute(client, message, args) {
        if (!message.member.voice.channel) return message.channel.send(`${client.emotes.error} - You're not in a voice channel!`);

        if (message.guild.me.voice.channel && message.member.voice.channel.id !== message.guild.me.voice.channel.id) return message.channel.send(`${client.emotes.error} - You're not in the same voice channel!`);

        if (!args[0]) return message.channel.send(`${client.emotes.error} - Please provide the title/URL of the song!`);

        const queue = client.player.createQueue(message.guild);

        await queue.connect(message.member.voice.channel);

        const song = client.player.search(args.join(" "), {
            requestedBy: message.author
        }).then(x => x.tracks[1]);

        queue.play(song);
    },
};
```

**Comment by DevAndromeda** [comment]
Hello, do you have `GUILD_VOICE_STATES` intent enabled?

**Comment by MinhCrafters** [comment]
> Hello, do you have `GUILD_VOICE_STATES` intent enabled?

i just enabled that intent and it's now working but it returns another error:
```
TypeError: Cannot read property 'source' of undefined
    at Queue.<anonymous> (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:636:59)
    at Generator.next (<anonymous>)
    at D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:4:12)
    at Queue.play (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:620:16)
    at Object.execute (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\commands\music\play.js:22:15)
```

**Comment by MinhCrafters** [comment]
> > Hello, do you have `GUILD_VOICE_STATES` intent enabled?
> 
> i just enabled that intent and it's now working but it returns another error:
> 
> ```
> D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:636
>             if (["youtube", "spotify"].includes(track.raw.source)) {
> 
> TypeError: Cannot read property 'source' of undefined
>     at Queue.<anonymous> (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:636:59)
>     at Generator.next (<anonymous>)
>     at D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:4:12)
>     at Queue.play (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\node_modules\discord-player\dist\Structures\Queue.js:620:16)
>     at Object.execute (D:\8. Du lieu cua Minh\Lap trinh\Node.js\Discord.js\commands\music\play.js:22:15)
> ```

seconds later i realized i didn't `await` player.search() cuz im dumb
