### ISSUE TITLE
YouTube Links Still Broken

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-player#677]
**Describe the bug**
Copying and pasting a YouTube link gives me "I could not find track" error message. Bot joins the VC, but doesn't play anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/14950662/128730903-213f59ba-50bb-463d-b2b8-72b7f49750e2.png)

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: 5.0.1
 - Discord.js Version: 13.0.1

**Comment by DevAndromeda** [comment]
Hello @alima566, I am unable to reproduce your issue

![image](https://user-images.githubusercontent.com/46562212/128732145-407d217e-0684-44b9-ba0c-c71cdbea0a2f.png)

I did this test in example bot https://github.com/Androz2091/discord-player/tree/master/example/music-bot
