### ISSUE TITLE
Invalid Channel Error

### ISSUE THREAD

**Issue by SidisLiveYT** [Androz2091/discord-player#691]
**Describe the bug**
Error shows up when playing song , can't say when because its random , but crashes whole bot , btw i have a decent and working catching error event . These one is related to voice state I guess .

**To Reproduce**
Can't say , Because its so Random , happens sometimes , may be doing queue.connect(channel);

**Expected behavior**
Bot crashes with there error

**Screenshots**
![Capture](https://user-images.githubusercontent.com/67759305/129257488-606d04cd-2864-42a9-bb74-0cdb3649838f.JPG)

**Please complete the following information:**
 - Node Version: [15.14.0]
 - Discord Player Version: [5.0.2]
 - Discord.js Version: [0.5.6]

**Additional context**
Nope

**Comment by Mr-Leonerrr** [comment]
Try to get and validate the voice status first, then try to connect
```js
const voiceChannel = message.member.voice;
if(!voiceChannel.channel) return;
try {
    if(!queue.connection) await queue.connect(voiceChannel.channel);
} catch (err) {
    console.log(err);
}
```

**Comment by SidisLiveYT** [comment]
> Try to get and validate the voice status first, then try to connect
> 
> ```js
> const voiceChannel = message.member.voice;
> if(!voiceChannel.channel) return;
> try {
>     if(!queue.connection) await queue.connect(voiceChannel.channel);
> } catch (err) {
>     console.log(err);
> }
> ```

I did made that if statement , but happening

**Comment by DevAndromeda** [comment]
why dont you follow the example bot https://github.com/Androz2091/discord-player/blob/master/example/music-bot/index.js#L180
