### ISSUE TITLE
Bot disconnects while playing music

### ISSUE THREAD

**Issue by MinhCrafters** [Androz2091/discord-player#698]
**Describe the bug**
idk but sometimes when the bot is playing music it disconnects for no reason.
no errors though

**To Reproduce**
1. Let the bot play music
2. no step 2

**Expected behavior**
it should play till the end

**Screenshots**

**Please complete the following information:**
 - Node Version: [16.6.2]
 - Discord Player Version: [5.0.2]
 - Discord.js Version: [13.0.1]

**Additional context**

**Comment by DevAndromeda** [comment]
I haven't seen this type of issue with discord-player. But I think it's happening due to ytdl's abort error or something similar to that

**Comment by MinhCrafters** [comment]
> I haven't seen this type of issue with discord-player. But I think it's happening for you due to ytdl's abort error or something similar to that

but sometimes it happens when i pass soundcloud urls

spotify is fine though

**Comment by DevAndromeda** [comment]
> but sometimes it happens when i pass soundcloud urls
some soundcloud links do not contain full stream, they are rather a preview streams

**Comment by PiousGaming** [comment]
its happened with youtube too when i type play ok binz and 3,4 songs more bot still playing 2 or 3 song but some time if this song end bot will auto change to the new song in the queue but when bot starting play that song for 2,3 sec and bot leave with reason : queue ended

**Comment by BeastBoyADI** [comment]
> I haven't seen this type of issue with discord-player. But I think it's happening for you due to ytdl's abort error or something similar to that

No it happened to me also many times

**Comment by DaSussy** [comment]
same, doesn't log any error

**Comment by BeastBoyADI** [comment]
> same, doesn't log any error

Tho it logs for me. It throws connection error aborted

**Comment by DevAndromeda** [comment]
> It throws connection error aborted

yes the reason for this is related to ytdl-core as per my research

**Comment by DaSussy** [comment]
any fix?

**Comment by fadiatamny** [comment]
ive also encountered the issue and it seems that it causes the player instance to emit an error event. 
i only managed to reproduce it with long videos of youtube playing usually crashes around 7-9 minutes of playing.

**Comment by rdapshii** [comment]
Yep, I'm having the same problem, I was reading stuff and people says it will be a ytdl-core or @discordjs/voice error. As well, it is just an abort, when you play music, it just stops and disconnects.

**Comment by pauldb09** [comment]
> Yep, I'm having the same problem, I was reading stuff and people says it will be a ytdl-core or @discordjs/voice error. As well, it is just an abort, when you play music, it just stops and disconnects.

The error is from ytdl-core. Using play-dl will fix that

**Comment by rdapshii** [comment]
> 

Just replace the library? I mean, uninstall ytdl and install play-dl

**Comment by doiska** [comment]
> > The error is from ytdl-core. Using play-dl will fix that
> 
> Just replace the library? I mean, uninstall ytdl and install play-dl

Nope, use [onBeforeCreateStream ](https://github.com/Androz2091/discord-player/tree/develop#custom-stream-engine) with play-dl (or Youtube-ext)

**Comment by Klairm** [comment]
I have this problem, it will disconnect with some songs, and I don't fully understand how to change to play-dl, is there any real-use example?

**Comment by Klairm** [comment]
> I have this problem, it will disconnect with some songs, and I don't fully understand how to change to play-dl, is there any real-use example?

I Implemented the onBeforeCreateStream but it stills disconnecting when playing some music

**Comment by DevAndromeda** [comment]
- Try disabling `spotifyBridge` if its enabled (which is by default) else you will have problems playing spotify tracks with `onBeforeCreateStream`
- Make sure you are on the latest version
- make sure you are handling sources properly
- try debugging if your play-dl part is actually being called

Bot will show old behaviour if:
- you are not returning stream
- your code executed incorrectly which somehow returned void type
- or there could be something going wrong with play-dl

**Comment by DevAndromeda** [comment]
`onBeforeCreateStream` lets you have full control over what should be played. So in practical, you could just hook up any youtube dl library within it.

**Comment by milkbag19** [comment]
> > I have this problem, it will disconnect with some songs, and I don't fully understand how to change to play-dl, is there any real-use example?
> 
> I Implemented the onBeforeCreateStream but it stills disconnecting when playing some music

In my code where I have my /play command, and create a queue, I used this and it worked with play-dl.

const queue = await player.createQueue(interaction.guild, {
                        metadata: interaction.channel,
                        async onBeforeCreateStream(track, source, _queue) {
                            if (source === "youtube") {
                                // track here would be youtube track (Default ytdl is brokey)
                                return (await playdl.stream(track.url)).stream;
                            }
                        }
                    });


I had the same issue where I used onBeforeCreateStream and it didnt work, but I just put it in the wrong spot.

**Comment by Klairm** [comment]
```
	const queue = await interaction.client.player.createQueue(interaction.guild, {
			metadata: {
				channel: interaction.channel,
			},
			async OnBeforeCreateStream(track,source,_queue){
                if (source == "youtube") return (await playdl.stream(track.url)).stream;


			},
			spotifyBridge:false,
			

			

		});
```
this is my code and it won't work, I don't understand why it's the same as the example


> * Try disabling `spotifyBridge` if its enabled (which is by default) else you will have problems playing spotify tracks with `onBeforeCreateStream`
> 
>     * Make sure you are on the latest version
> 
>     * make sure you are handling sources properly
> 
>     * try debugging if your play-dl part is actually being called
> 
> 
> Bot will show old behaviour if:
> 
>     * you are not returning stream
> 
>     * your code executed incorrectly which somehow returned void type
> 
>     * or there could be something going wrong with play-dl

What would be the correct way for debugging play-dl?

**Comment by pauldb09** [comment]
Working play-dl integration:
```js
async onBeforeCreateStream(track, source, _queue) {
                    if (track.url.includes('youtube') || track.url.includes("youtu.be")) {
                        try {
                            return (await playdl.stream(track.url)).stream;
                        } catch (err) {
                            return _queue.metadata.m.errorMessage("This video is restricted. Try with another link.")
                        }
                    } else if (track.url.includes('spotify')) {
                        try {
                            let songs = await client.player.search(`${track.author} ${track.title} `, {
                                requestedBy: message.member,
                            }).catch().then(x => x.tracks[0]);
                            return (await playdl.stream(songs.url)).stream;
                        } catch (err) {
                            console.log(err)
                        }
                    } else if (track.url.includes('soundcloud')) {
                        try {
                            return (await playdl.stream(track.url)).stream;
                        } catch (err) {
                            console.log(err)
                        }
                    }
                }
                ```

**Comment by Klairm** [comment]
> 

tried this and I still getting the problem where the bot will disconnect after 1 song, idk what I'm doing wrong here

**Comment by pauldb09** [comment]
> tried this and I still getting the problem where the bot will disconnect after 1 song, idk what I'm doing wrong here
> 
> > Working play-dl integration:
> > ```js
> > async onBeforeCreateStream(track, source, _queue) {
> >                     if (track.url.includes('youtube') || track.url.includes("youtu.be")) {
> >                         try {
> >                             return (await playdl.stream(track.url)).stream;
> >                         } catch (err) {
> >                             return _queue.metadata.m.errorMessage("This video is restricted. Try with another link.")
> >                         }
> >                     } else if (track.url.includes('spotify')) {
> >                         try {
> >                             let songs = await client.player.search(`${track.author} ${track.title} `, {
> >                                 requestedBy: message.member,
> >                             }).catch().then(x => x.tracks[0]);
> >                             return (await playdl.stream(songs.url)).stream;
> >                         } catch (err) {
> >                             console.log(err)
> >                         }
> >                     } else if (track.url.includes('soundcloud')) {
> >                         try {
> >                             return (await playdl.stream(track.url)).stream;
> >                         } catch (err) {
> >                             console.log(err)
> >                         }
> >                     }
> >                 }
> >                 ```
> > ```

Can you send the code of your play command?

**Comment by Klairm** [comment]
> > tried this and I still getting the problem where the bot will disconnect after 1 song, idk what I'm doing wrong here
> > > Working play-dl integration:
> > > ```js
> > > async onBeforeCreateStream(track, source, _queue) {
> > >                     if (track.url.includes('youtube') || track.url.includes("youtu.be")) {
> > >                         try {
> > >                             return (await playdl.stream(track.url)).stream;
> > >                         } catch (err) {
> > >                             return _queue.metadata.m.errorMessage("This video is restricted. Try with another link.")
> > >                         }
> > >                     } else if (track.url.includes('spotify')) {
> > >                         try {
> > >                             let songs = await client.player.search(`${track.author} ${track.title} `, {
> > >                                 requestedBy: message.member,
> > >                             }).catch().then(x => x.tracks[0]);
> > >                             return (await playdl.stream(songs.url)).stream;
> > >                         } catch (err) {
> > >                             console.log(err)
> > >                         }
> > >                     } else if (track.url.includes('soundcloud')) {
> > >                         try {
> > >                             return (await playdl.stream(track.url)).stream;
> > >                         } catch (err) {
> > >                             console.log(err)
> > >                         }
> > >                     }
> > >                 }
> > >                 ```
> > > ```
> 
> Can you send the code of your play command?

```js
const playdl  = require('play-dl');
const { SlashCommandBuilder } = require('@discordjs/builders');
const { QueryType } = require('discord-player');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('play')
		.setDescription('Play music in your voice channel.')
		.addStringOption((option) => option.setName('song').setDescription('The song to play').setRequired(true)),

	async execute(interaction) {
		
		await interaction.deferReply();
		if (!interaction.member.voice.channelId) return await interaction.reply({ content: 'You are not in a voice channel!', empheral: true });
		if (interaction.guild.me.voice.channelId && interaction.member.voice.channelId !== interaction.guild.me.voice.channelId)
			return await interaction.reply({ content: 'You are not in my voice channel!', empheral: true });

		const query = interaction.options.get('song').value;
		const searchResult = await interaction.client.player
			.search(query, {
				requestedBy: interaction.author,
				searchEngine: QueryType.AUTO
			})
			.catch(()=>{
				console.log('he');
			});
		if (!searchResult || !searchResult.tracks.length) return await interaction.followUp({ content: `❌ | Track **${query}** not found!`, empheral: false });

        const queue = await interaction.client.player.createQueue(interaction.guild, {
			metadata: {
				channel: interaction.channel,
			},
			async OnBeforeCreateStream(track,source,_queue){
                if (track.url.includes('youtube') || track.url.includes("youtu.be")) {
					try {
						return (await playdl.stream(track.url)).stream;
					} catch (err) {
						return _queue.metadata.m.errorMessage("This video is restricted. Try with another link.")
					}
				} else if (track.url.includes('spotify')) {
					try {
						let songs = await client.player.search(`${track.author} ${track.title} `, {
							requestedBy: message.member,
						}).catch().then(x => x.tracks[0]);
						return (await playdl.stream(songs.url)).stream;
					} catch (err) {
						console.log(err)
					}
				} else if (track.url.includes('soundcloud')) {
					try {
						return (await playdl.stream(track.url)).stream;
					} catch (err) {
						console.log(err)
					}
				}


			},
			spotifyBridge:false,




		});

		// verify vc connection
		try {
			if (!queue.connection) await queue.connect(interaction.member.voice.channel);
		} catch {
			console.log("[ERROR] error trying to connect voice")
			queue.destroy();
			return await interaction.reply({ content: 'Could not join your voice channel!', empheral: true });
		}

		await interaction.followUp({ content: `⏱️ | Loading your ${searchResult.playlist ? 'playlist' : 'track'}...!` });
		searchResult.playlist ? queue.addTracks(searchResult.tracks) : queue.addTrack(searchResult.tracks[0]);	
		
		if(!queue.playing) await queue.play();

	},
};
```

**Comment by pauldb09** [comment]
Did you have the latest version of discord player? try `npm i discord-player@latest`

**Comment by Klairm** [comment]
> Did you have the latest version of discord player? try `npm i discord-player@latest`

I installed the dev branch

**Comment by Klairm** [comment]
I even tried running the bot in another machine and it will still happen the same error, I honestly don't know what else to do or is there's any better way to debug this

**Comment by DevAndromeda** [comment]
try v5.3.x, re-open if this still persists
