### ISSUE TITLE
Search song Issue

### ISSUE THREAD

**Issue by PiousGaming** [Androz2091/discord-player#703]
Hi, This is my first time create a bug report
I think the package have issue
This is my code in discord.js v12.5.3 and discord-player v4.1.4 its work well at that version
[source](https://sourceb.in/5q09cHNqLp)
But in the new version of discord.js and discord-player it has a few change i was read in the docs to change code
[new source](https://sourceb.in/AtyV59xPBT)
When i use play command it doesn't play the song I want even though I typed the title and the author's name. You can see in the screenshot below
**Screenshots**
![image](https://user-images.githubusercontent.com/87639535/129479514-ee712b38-4d05-4b98-a14d-a6c4c256e9f6.png)

**Version i'm using**
 - Node Version: [16.6.2]
 - Discord Player Version: [5.0.2]
 - Discord.js Version: [13.1.0]

**Comment by PiousGaming** [comment]
I think the issue from `.then(x => x.tracks[1])` I think its should be 0 not 1 if this is true pls change this in the docs

**Comment by DaSussy** [comment]
> I think the issue is from `.then(x => x.tracks[1])` I think its should be 0 not 1 if this is true pls change this in the docs

yes thats true

**Comment by PiousGaming** [comment]
Youtube link not found is start from that issue too, we should be change 1 to 0 its will help bot can find song with youtube link
