### ISSUE TITLE
<Queue>.jump not working properly

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#711]
**Describe the bug**

jump () is not working properly, it's just skiping to the next track instead of that specific positioned track.
**To Reproduce**

**Expected behavior**

It should jump to that specific positioned track
**Screenshots**

**Please complete the following information:**
 - Node Version: [16.x]
 - Discord Player Version: [dev]
 - Discord.js Version: [13.1.0]

**Additional context**

**Comment by joshuayuen99** [comment]
#683

**Comment by DevAndromeda** [comment]
The patch may not have been published yet, so you can try using dev version: `npm i discord-player@dev`

**Comment by L0SER8228** [comment]
I'm using dev version, still the same problem

**Comment by DevAndromeda** [comment]
> I'm using dev version, still the same problem

yes, this is a bug created due to @joshuayuen99's #684 which makes the found track to be added to the index 0 and then skips which makes player skip that specific track and move to another one. Reverting that fixes the issue.

**Comment by L0SER8228** [comment]
Ok

**Comment by L0SER8228** [comment]
Still not fixed,

**Comment by L0SER8228** [comment]
> > I'm using dev version, still the same problem
> 
> yes, this is a bug created due to @joshuayuen99's #684 which makes the found track to be added to the index 0 and then skips which makes player skip that specific track and move to another one. Reverting that fixes the issue.

I think, he actually did it correctly. Please recheck in a bot ,
