### ISSUE TITLE
Play reply bug when using queue.metadata

### ISSUE THREAD

**Issue by PiousGaming** [Androz2091/discord-player#716]
**Describe the bug**
Bug about the play command when i type play a song in channel x bot will send trackAdd message in that channel. But when i type that command in channel y while bot playing song i ordered in channel x bot still send trackAdd message in channel x
**Please complete the following information:**
 - Node Version: [16.6.2]
 - Discord Player Version: [5.0.2]
 - Discord.js Version: [13.1.0]

**Comment by BeastBoyADI** [comment]
Not a bug that is what it meant to do. As u send the track add message using queue.metadata.channel.send which contains the channel id of the channel where u created the queue not where u added tracks to the current queue
