### ISSUE TITLE
Bug when use the same way to resume and pause

### ISSUE THREAD

**Issue by PiousGaming** [Androz2091/discord-player#720]
**Describe the bug**
Bug about resume and pause
[Resume command](https://sourceb.in/k65GPqKK7d) and [Pause command](https://sourceb.in/8KOdlbtgpc) have bug
When i console.log the success in pause use pause command it is true and send the pause embed
But when i console.log the success in resume and use resume command it is false but still resume and not send the embed in resume so i changed the success in resume to `const success = client.player.getQueue(message.guild).setPaused() == false` the console log can be true and send the embed in resume

**Before Change**
![image](https://user-images.githubusercontent.com/87639535/130099235-d5be41cb-7b3b-4618-9742-5e35d0828fd7.png)
**After Changed**
![image](https://user-images.githubusercontent.com/87639535/130099333-1cce2b8d-a859-48b1-88b5-a14d4501fa71.png)

**Please complete the following information:**
 - Node Version: [16.6.2]
 - Discord Player Version: [5.0.2]
 - Discord.js Version: [13.1.0]

**Comment by aiko-chan-ai** [comment]
I made a merge request, so it will be fixed soon

**Comment by PiousGaming** [comment]
this is not a bug this is my bad when using if(...) to reply when song already paused or resumed
