### ISSUE TITLE
ERR:ABORTED

### ISSUE THREAD

**Issue by Samiul30** [Androz2091/discord-player#724]
**Describe the bug**
I got this error: aborted from the event 'connectionError'

**To Reproduce**
Play a song, use autoplay

**Expected behavior**
It should play 

**Screenshots**

**Please complete the following information:**
 - Node Version: [16.x]
 - Discord Player Version: [5.0.2dev]
 - Discord.js Version: [13.x]

**Additional context**

**Comment by DevAndromeda** [comment]
abort errors are most of the time related to ytdl-core and we cant really do anything about this. Even @discordjs/voice suggests us to use youtube-dl instead of ytdl-core because of this reason
