### ISSUE TITLE
Set the stream volume before playing 

### ISSUE THREAD

**Issue by TerreBleue** [Androz2091/discord-player#725]
**Is your feature request related to a problem? Please describe.**
Currently, every time a track is streamed, it is always played at default volume until the buffer stream is refreshed. This is often problematic when we play tracks at a different volume, because track starts can be too loud or inaudible compared to the overall stream.

**Describe the solution you'd like**
Set the stream volume between its creation and play.

**Additional context**
Actually I've managed to fix this issue by myself, though not nicely. The attachment shows where I tested out.

![test location](https://user-images.githubusercontent.com/82955208/130369416-cece23b7-40a6-41a2-a0b5-44da6f1eddc5.png)

**Comment by DevAndromeda** [comment]
are you sure this would work? because setting volume there would affect current stream not the future one
