### ISSUE TITLE
Phone soundcloud Links dose not work

### ISSUE THREAD

**Issue by abdusyr** [Androz2091/discord-player#742]
- Node Version: 16
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

The phone soundcloud links dose not work on discord-player

![image](https://user-images.githubusercontent.com/69731556/131227881-d193788f-815f-4546-aa0f-b752fb937660.png)

**Comment by modee0011** [comment]
me to i have this problem

**Comment by DevAndromeda** [comment]
Ok there could be many url formats for soundcloud, we can't verify each of them...

**Comment by DevAndromeda** [comment]
Let's merge this issue with #692
