### ISSUE TITLE
.jump() broke

### ISSUE THREAD

**Issue by BeastBoyADI** [Androz2091/discord-player#744]
**Describe the bug**

Before .jump() was working without any issues but don't know why today it's not working anymore. It's now just skipping to the next song instead of jumping to the song i specified.
**To Reproduce**

It is just skipping to the next song instead of jumping to the song specified
**Expected behavior**

I wanted it to jump to the song i specified
**Screenshots**

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: latest develop branch
 - Discord.js Version: latest version

**Additional context**

Please fix it and all other are working perfectlly Working

**Comment by DevAndromeda** [comment]
🤔 ok this is a bit confusing now. When we revert the `jump` back to original form, we get pull requests like #738 
and when we merge those pull requests, users open issue saying `jump` does not work...

**Comment by BeastBoyADI** [comment]
Yeah jump is not working now. It was working perfectly before when u haven't merged the pr

**Comment by BeastBoyADI** [comment]
I guess as per their pr the bot removes the song from the queue and add it at now playing. So that actually is skipping to the next song and due to it takes time to do that it is skipping to the next song instead of skipping to the song which we mentioned.

**Comment by BeastBoyADI** [comment]
> 🤔 ok this is a bit confusing now. When we revert the `jump` back to original form, we get pull requests like #738
> and when we merge those pull requests, users open issue saying `jump` does not work...

Hey what about reverting it back again and i will check it that it works or not?

**Comment by BeastBoyADI** [comment]
If it worked that means that pr is of no use

**Comment by DevAndromeda** [comment]
after some testing and discussions, `jump` method seems to be absolutely fine and works perfectly
