### ISSUE TITLE
ytdl_core_1.default is not a function

### ISSUE THREAD

**Issue by LinusBotTips** [Androz2091/discord-player#745]
Happens when I run /play

 TypeError: ytdl_core_1.default is not a function
    at Object.StreamDownloader [as default] (/root/dischord-main/node_modules/discord-ytdl-core/index.js:1:917)
    at Queue.<anonymous> (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:648:53)
    at Generator.next (<anonymous>)
    at /root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:4:12)
    at Queue.play (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:622:16)
    at Object.run (/root/dischord-main/SlashCommands/music/play.js:61:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 - Node Version: 16
 - Discord Player Version: 5.1.0

 - Discord.js Version: 13.1.0

**Comment by Samiul30** [comment]
> Happens when I run /play
> 
> TypeError: ytdl_core_1.default is not a function
> at Object.StreamDownloader [as default] (/root/dischord-main/node_modules/discord-ytdl-core/index.js:1:917)
> at Queue. (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:648:53)
> at Generator.next ()
> at /root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:8:71
> at new Promise ()
> at __awaiter (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:4:12)
> at Queue.play (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:622:16)
> at Object.run (/root/dischord-main/SlashCommands/music/play.js:61:41)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> * Node Version: 16
> * Discord Player Version: 5.1.0
> * Discord.js Version: 13.1.0

Can I get the package.json of your bot file???

**Comment by LinusBotTips** [comment]
> > Happens when I run /play
> > TypeError: ytdl_core_1.default is not a function
> > at Object.StreamDownloader [as default] (/root/dischord-main/node_modules/discord-ytdl-core/index.js:1:917)
> > at Queue. (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:648:53)
> > at Generator.next ()
> > at /root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:8:71
> > at new Promise ()
> > at __awaiter (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:4:12)
> > at Queue.play (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:622:16)
> > at Object.run (/root/dischord-main/SlashCommands/music/play.js:61:41)
> > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 
> > * Node Version: 16
> > * Discord Player Version: 5.1.0
> > * Discord.js Version: 13.1.0
> 
> Can I get the package.json of your bot file???

Yeah sure!

```
{
  "name": "dischord",
  "version": "1.0.0",
  "description": "dischord",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@discordjs/opus": "^0.5.3",
    "axios": "^0.21.1",
    "chalk": "^4.1.2",
    "colors": "^1.4.0",
    "discord-player": "^5.1.0",
    "discord-ytdl-core": "^5.0.4",
    "discord.js": "^13.1.0",
    "ffmpeg-static": "^4.4.0",
    "glob": "^7.1.7",
    "install": "^0.13.0",
    "luxon": "^2.0.1",
    "lyrics-finder": "^21.7.0",
    "mongoose": "^5.13.2",
    "node-os-utils": "^1.3.5",
    "npm": "^7.20.3",
    "opusscript": "^0.0.8",
    "os": "^0.1.2",
    "pretty-ms": "^7.0.1",
    "rnd-song": "^1.0.2",
    "voidbots": "^2.6.2",
    "ytdl-core": "^4.9.1"
  }
}
```

**Comment by Samiul30** [comment]
> > > Happens when I run /play
> > > TypeError: ytdl_core_1.default is not a function
> > > at Object.StreamDownloader [as default] (/root/dischord-main/node_modules/discord-ytdl-core/index.js:1:917)
> > > at Queue. (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:648:53)
> > > at Generator.next ()
> > > at /root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:8:71
> > > at new Promise ()
> > > at __awaiter (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:4:12)
> > > at Queue.play (/root/dischord-main/node_modules/discord-player/dist/Structures/Queue.js:622:16)
> > > at Object.run (/root/dischord-main/SlashCommands/music/play.js:61:41)
> > > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > > 
> > > * Node Version: 16
> > > * Discord Player Version: 5.1.0
> > > * Discord.js Version: 13.1.0
> > 
> > Can I get the package.json of your bot file???
> 
> Yeah sure!
> 
> ```
> {
>   "name": "dischord",
>   "version": "1.0.0",
>   "description": "dischord",
>   "main": "index.js",
>   "scripts": {
>     "start": "node index.js"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "@discordjs/opus": "^0.5.3",
>     "axios": "^0.21.1",
>     "chalk": "^4.1.2",
>     "colors": "^1.4.0",
>     "discord-player": "^5.1.0",
>     "discord-ytdl-core": "^5.0.4",
>     "discord.js": "^13.1.0",
>     "ffmpeg-static": "^4.4.0",
>     "glob": "^7.1.7",
>     "install": "^0.13.0",
>     "luxon": "^2.0.1",
>     "lyrics-finder": "^21.7.0",
>     "mongoose": "^5.13.2",
>     "node-os-utils": "^1.3.5",
>     "npm": "^7.20.3",
>     "opusscript": "^0.0.8",
>     "os": "^0.1.2",
>     "pretty-ms": "^7.0.1",
>     "rnd-song": "^1.0.2",
>     "voidbots": "^2.6.2",
>     "ytdl-core": "^4.9.1"
>   }
> }
> ```

This error originate because discord player needs ytdl-core to perform. Ytdl core is not define for discord player and the error is shown

**Comment by DevAndromeda** [comment]
you dont need to manually install `ytdl-core` and `discord-ytdl-core`

**Comment by Samiul30** [comment]
> you dont need to manually install `ytdl-core` and `discord-ytdl-core`

But in his case it was not installed.

**Comment by LinusBotTips** [comment]
I fixed it, thanks for the help
