### ISSUE TITLE
Don't know if it is a bug or not but wanted to know

### ISSUE THREAD

**Issue by BeastBoyADI** [Androz2091/discord-player#747]
**Describe the bug**

The thing is i was trying to make a search command which would send me first 5 latest tracks found. I used the following code to get the tracks.
```js
const query = args.join(' ');
const result = client.player.search(query, {
            requestedBy: message.author
        });
        if (!result) return message.channel.send({
            content: `${client.ename.error}** | Track ${query} not found!**`
        });
        const songs = result.tracks;
        const allsongs = songs.map(x => x.title).join(",\n");
         message.channel.send({content: `Tracks Found:\n${allsongs}.`});
```
As i know it should have worked but it returned an error that 
```txt
cannot read property 'map' of undefined.
``` 
and when i evaluated whole code but replaced songs.map with songs alone then it returned undefined don't know why it is returning undefined. Please help me only in this as i don't get what error i made.
Please help me by saying what mistake i have made.

**Expected behavior**

Should send all the tracks name

**Screenshots**

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Additional context**

No additional context.

**Comment by BeastBoyADI** [comment]
Also yeah i didn't sent my whole code as my whole code is of 160 lines. So just sent the main part that finds the tracks

**Comment by DevAndromeda** [comment]
Because `player.search` returns a promise, you must resolve it first. Adding `await` before `client.player.search` should fix your problem
![image](https://user-images.githubusercontent.com/46562212/131246909-6edf87e1-d832-41d5-a50e-a01f52451317.png)

**Comment by BeastBoyADI** [comment]
No wait my bad i already have added await in my main code but forgot to add here

**Comment by BeastBoyADI** [comment]
But yeah i think i will try again

**Comment by BeastBoyADI** [comment]
Oh shit i did added await but forgot to save it due to which it was not working

**Comment by BeastBoyADI** [comment]
My bad. But tysm for helping
