### ISSUE TITLE
Playing a song in a stage channel breaks the queue

### ISSUE THREAD

**Issue by BeastBoyADI** [Androz2091/discord-player#752]
**Describe the bug**

So basically i was trying to play a song in my stage channel. It did triggered the track add event but didn't triggerred the track start event. After that when i tried to skip or pause and as i have a limiter that says no song is playing when queue.playing returns false and yeah it was returning false even if my bot was playing song in a stage channel. I think it's a bug so maybe fix it.
**To Reproduce**

There was no error in the console
**Expected behavior**

It should return queue.playing as true as well as emit trackstart event but both didn't worked.
**Screenshots**

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Additional context**

**Comment by DevAndromeda** [comment]
in stage channel, discord player tries to set bot to speaker mode and if it fails, it pauses the playback and waits for stage mod/admin to set the bot to speaker mode.

**Comment by DevAndromeda** [comment]
You should be able to reproduce similar issue in a voice channel as well, by server muting the bot

**Comment by BeastBoyADI** [comment]
> You should be able to reproduce similar issue in a voice channel as well, by server muting the bot

Wait it didnt got paused it was playing the song smoothly but the thing is it is returning queue.playing as false as well as not emitting any player event except botdisconnect and trackadd. I think there is any issue with stage channels or something

**Comment by Samiul30** [comment]
> > You should be able to reproduce similar issue in a voice channel as well, by server muting the bot
> 
> Wait it didnt got paused it was playing the song smoothly but the thing is it is returning queue.playing as false as well as not emitting any player event except botdisconnect and trackadd. I think there is any issue with stage channels or something

There is no issue regarding this... I can reproduce your problem but its totally upto the bots permission whether it can play the song or not....as Andro told u.

**Comment by BeastBoyADI** [comment]
> > > You should be able to reproduce similar issue in a voice channel as well, by server muting the bot
> > 
> > 
> > Wait it didnt got paused it was playing the song smoothly but the thing is it is returning queue.playing as false as well as not emitting any player event except botdisconnect and trackadd. I think there is any issue with stage channels or something
> 
> There is no issue regarding this... I can reproduce your problem but its totally upto the bots permission whether it can play the song or not....as Andro told u.

Dude didn't i said the bot is playing the song and i am able to listen in the stage channel but it is not emitting events and returning queue.playing as false. Which is none related to perms as the bot can play music and also it have admin perms

**Comment by DevAndromeda** [comment]
@BeastBoyADI is this happening on voice channels too? could you try the same thing but by server muting/unmuting the bot?

**Comment by Samiul30** [comment]
> > > > You should be able to reproduce similar issue in a voice channel as well, by server muting the bot
> > > 
> > > 
> > > Wait it didnt got paused it was playing the song smoothly but the thing is it is returning queue.playing as false as well as not emitting any player event except botdisconnect and trackadd. I think there is any issue with stage channels or something
> > 
> > 
> > There is no issue regarding this... I can reproduce your problem but its totally upto the bots permission whether it can play the song or not....as Andro told u.
> 
> Dude didn't i said the bot is playing the song and i am able to listen in the stage channel but it is not emitting events and returning queue.playing as false. Which is none related to perms as the bot can play music and also it have admin perms

Then it is from your end

**Comment by BeastBoyADI** [comment]
> @BeastBoyADI is this happening on voice channels too? could you try the same thing but by server muting/unmuting the bot?

Let me

**Comment by BeastBoyADI** [comment]
No it works perfectly. Even after i server muted the bot it returning queue.playing as true and even all the events are getting emitted

**Comment by BeastBoyADI** [comment]
I don't know why but the problem is arising only in stage channel

**Comment by DevAndromeda** [comment]
> I don't know why but the problem is arising only in stage channel

seems to be a bug 👍

**Comment by BeastBoyADI** [comment]
> The trackStart event is not triggered and also if any new song is added, it automatically skip the current one after few seconds

Ye same for me

**Comment by BeastBoyADI** [comment]
Even the channel empty, queue end events are also not triggered

**Comment by Samiul30** [comment]
Any update?

**Comment by Newt74** [comment]
This bug comes from _handleVoiceState because it didn't handle voiceStateUpdate for stage channel correctly

**Comment by Newt74** [comment]
This bug comes from _handleVoiceState because it didn't handle voiceStateUpdate correctly. What would happen if I delete this in Player.ts ?
`if (!oldState.channelId && newState.channelId && newState.member.id === newState.guild.me.id) {
    if (newState.serverMute || !newState.serverMute) {
        queue.setPaused(newState.serverMute);
    } else if (newState.suppress || !newState.suppress) {
        if (newState.suppress) newState.guild.me.voice.setRequestToSpeak(true).catch(Util.noop);
        queue.setPaused(newState.suppress);
    }
}

if (oldState.channelId === newState.channelId && oldState.member.id === newState.guild.me.id) {
    if (oldState.serverMute !== newState.serverMute) {
        queue.setPaused(newState.serverMute);
    } else if (oldState.suppress !== newState.suppress) {
        if (newState.suppress) newState.guild.me.voice.setRequestToSpeak(true).catch(Util.noop);
        queue.setPaused(newState.suppress);
    }
}`
The bot still works fine and this bug has gone.

**Comment by Newt74** [comment]
This bug comes from _handleVoiceState because it didn't handle voiceStateUpdate correctly. What would happen if I delete this in Player.ts ?
```js
if (!oldState.channelId && newState.channelId && newState.member.id === newState.guild.me.id) {
    if (newState.serverMute || !newState.serverMute) {
        queue.setPaused(newState.serverMute);
    } else if (newState.suppress || !newState.suppress) {
        if (newState.suppress) newState.guild.me.voice.setRequestToSpeak(true).catch(Util.noop);
        queue.setPaused(newState.suppress);
    }
}

if (oldState.channelId === newState.channelId && oldState.member.id === newState.guild.me.id) {
    if (oldState.serverMute !== newState.serverMute) {
        queue.setPaused(newState.serverMute);
    } else if (oldState.suppress !== newState.suppress) {
        if (newState.suppress) newState.guild.me.voice.setRequestToSpeak(true).catch(Util.noop);
        queue.setPaused(newState.suppress);
    }
}
```
The bot still works fine and this bug has gone.

**Comment by thanhgaming5550** [comment]
> This bug comes from _handleVoiceState because it didn't handle voiceStateUpdate correctly for stage channel. What would happen if I delete this in Player.ts ?
> 
> ```js
> if (!oldState.channelId && newState.channelId && newState.member.id === newState.guild.me.id) {
>     if (newState.serverMute || !newState.serverMute) {
>         queue.setPaused(newState.serverMute);
>     } else if (newState.suppress || !newState.suppress) {
>         if (newState.suppress) newState.guild.me.voice.setRequestToSpeak(true).catch(Util.noop);
>         queue.setPaused(newState.suppress);
>     }
> }
> 
> if (oldState.channelId === newState.channelId && oldState.member.id === newState.guild.me.id) {
>     if (oldState.serverMute !== newState.serverMute) {
>         queue.setPaused(newState.serverMute);
>     } else if (oldState.suppress !== newState.suppress) {
>         if (newState.suppress) newState.guild.me.voice.setRequestToSpeak(true).catch(Util.noop);
>         queue.setPaused(newState.suppress);
>     }
> }
> ```
> 
> The bot still works fine and this bug has gone.

So should we make it a Pull Request to fix this error?

**Comment by DevAndromeda** [comment]
is it working in the latest update? (#852)

**Comment by EwoX07** [comment]
its fine for me with the latest update #986

**Comment by DevAndromeda** [comment]
try v5.3.x, re-open if this still persists
