### ISSUE TITLE
node_modules/discord-player/dist/index.d.ts:2:41 - error TS2724: '"discord.js"' has no exported member named 'StageChannel'. Did you mean 'StoreChannel'?      

### ISSUE THREAD

**Issue by S4qib** [Androz2091/discord-player#758]
**Describe the bug**
the StageChannel class that discord-player is importing does work.

**Please complete the following information:**
 - Node Version: latest
 - Discord Player Version: latest
 - Discord.js Version: latest

**The error**
node_modules/discord-player/dist/index.d.ts:2:41 - error TS2724: '"discord.js"' has no exported member named 'StageChannel'. Did you mean 'StoreChannel'?

**Comment by Samiul30** [comment]
Why this error was triggered? What was the command? Or work?

**Comment by DevAndromeda** [comment]
Something is not right with your discord.js, try re-installing
