### ISSUE TITLE
Jump Issue

### ISSUE THREAD

**Issue by abdusyr** [Androz2091/discord-player#759]
- Node Version: Latest
 - Discord Player Version: Latest
 - Discord.js Version: Latest

The issue is:
When I use "jump", the player move the jumped song to the first position on the queue, and skip the current track

![image](https://user-images.githubusercontent.com/69731556/132066621-1845cc39-fb3d-47af-9ea9-3dcfac430723.png)
![image](https://user-images.githubusercontent.com/69731556/132066539-7ad0d27d-a9e0-4bd5-9358-34f278441e6f.png)

**Comment by DevAndromeda** [comment]
This is exactly what `jump` is supposed to do, we could add a function to skip all the tracks and play from the specified track in the future
