### ISSUE TITLE
player.skipTo feature suggestion

### ISSUE THREAD

**Issue by abdusyr** [Androz2091/discord-player#760]
**Describe the feature you would like**
"Skip to" feature, skip to a certain position on the queue

**Expected behavior**
```player.skipTo(Track or Number)```

**Screenshots**
![image](https://user-images.githubusercontent.com/69731556/132117138-41eb20d1-a643-4c76-83b0-8ec4bd6686c2.png)
![image](https://user-images.githubusercontent.com/69731556/132117170-f4213218-6c14-440d-9c99-7aaae7a58ac8.png)
![image](https://user-images.githubusercontent.com/69731556/132117175-dd5c4ce3-e6c0-4f12-b890-c566ba521d35.png)

**Comment by PiousGaming** [comment]
its .jump() lmao

**Comment by abdusyr** [comment]
> its .jump() lmao

nope its not, jump is just get the song and put it on the first position on the queue DUMB

**Comment by Samiul30** [comment]
> > its .jump() lmao
> 
> nope its not, jump is just get the song and put it on the first position on the queue on v5

Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.

**Comment by abdusyr** [comment]
> > > its .jump() lmao
> > 
> > 
> > nope its not, jump is just get the song and put it on the first position on the queue on v5
> 
> Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.

I didn't ask for your opinion of my suggestion, please shut up

**Comment by LiterallyLink** [comment]
First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.

Just copy the .jump() function and modify the code to remove the songs with slice.

**Comment by LiterallyLink** [comment]
> > > > its .jump() lmao
> > > 
> > > 
> > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > 
> > 
> > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> 
> I didn't ask for your opinion of my suggestion, please shut up

First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.

Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.

**Comment by DevAndromeda** [comment]
I guess we can have this feature built into discord-player in the next update, since we already have a lot of utility methods baked in and this particular one seems to be missing. However, this feature is not so important as of right now, so I marked it as `minor` (will be done but slowly).

**Comment by Samiul30** [comment]
> > > > > its .jump() lmao
> > > > 
> > > > 
> > > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > > 
> > > 
> > > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> > 
> > 
> > I didn't ask for your opinion of my suggestion, please shut up
> 
> First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.
> 
> Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.

Please don't tell much otherwise he will say shutup

**Comment by abdusyr** [comment]
> > > > > its .jump() lmao
> > > > 
> > > > 
> > > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > > 
> > > 
> > > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> > 
> > 
> > I didn't ask for your opinion of my suggestion, please shut up
> 
> First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.
> 
> Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.

Here is the problem,
That the jump function does not play the song immediately
But rather moves it to the first position of the queue
Sorry for being a bit immature

> > > > > its .jump() lmao
> > > > 
> > > > 
> > > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > > 
> > > 
> > > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> > 
> > 
> > I didn't ask for your opinion of my suggestion, please shut up
> 
> First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.
> 
> Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.

Here is the problem,
That the jump function does not play the song immediately
But rather moves it to the first position of the queue
Sorry for being a bit immature

**Comment by abdusyr** [comment]
> > > > > > its .jump() lmao
> > > > > 
> > > > > 
> > > > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > > > 
> > > > 
> > > > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> > > 
> > > 
> > > I didn't ask for your opinion of my suggestion, please shut up
> > 
> > 
> > First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.
> > Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.
> 
> Please don't tell much otherwise he will say shutup

Sorry for the way I spoke, I hope you'll accept my apology

**Comment by abdusyr** [comment]
> I guess we can have this feature built into discord-player in the next update, since we already have a lot of utility methods baked in and this particular one seems to be missing. However, this feature is not so important as of right now, so I marked it as `minor` (will be done but slowly).

Thanks for your reply, I am waiting

**Comment by Samiul30** [comment]
> > > > > > its .jump() lmao
> > > > > 
> > > > > 
> > > > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > > > 
> > > > 
> > > > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> > > 
> > > 
> > > I didn't ask for your opinion of my suggestion, please shut up
> > 
> > 
> > First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.
> > Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.
> 
> Here is the problem,
> That the jump function does not play the song immediately
> But rather moves it to the first position of the queue
> Sorry for being a bit immature
> 
> > > > > > its .jump() lmao
> > > > > 
> > > > > 
> > > > > nope its not, jump is just get the song and put it on the first position on the queue on v5
> > > > 
> > > > 
> > > > Do you know what rythm do? What the code written for rythm to use skipto? If then make your own code..otherwise use the .jump method.
> > > 
> > > 
> > > I didn't ask for your opinion of my suggestion, please shut up
> > 
> > 
> > First of all, have some maturity. Second of all, that suggestion is so easy you might as well implement it yourself.
> > Just copy the .jump() function and modify the code to remove X songs until you’re at the track you specified.
> 
> Here is the problem,
> That the jump function does not play the song immediately
> But rather moves it to the first position of the queue
> Sorry for being a bit immature

.jump() has been made in that way so that it works like jumping to the song without touching the rest of the songs in the queue. And it's ok as Amdromeda told that it will be added. But for now if you want to make it a skipto command with the jump method you can make if any problem arises feel free to send it in https://discord.gg/D6Tw6kgt8V at #discord-player. I will try to help you or even others are also there.
