### ISSUE TITLE
Make a .move() function.

### ISSUE THREAD

**Issue by BeastBoyADI** [Androz2091/discord-player#763]
**Describe the feature you would like**

Basically what it does is move a specified song to a specified position in the queue
**Expected behavior**

`queue.move(3, 7)` would move the song at the position `3` to the position `7` in the queue.
**Screenshots**

**Additional context**

I don't know if it is already made or not as i never found it so made a suggestion for it.

**Comment by DevAndromeda** [comment]
This is very easy to implement, doing something like:

```js
const removedTrack = this.remove(3);
this.insert(removedTrack, 7);
```

**Comment by BeastBoyADI** [comment]
No i want the bot to insert the song in queue position 7 in the queue position 3. So basically it's like swapping two songs positions

**Comment by BeastBoyADI** [comment]
This function doesn't remove any song from the queue just swaps their positions

**Comment by DevAndromeda** [comment]
> No i want the bot to insert the song in queue position 7 in the queue position 3. So basically it's like swapping two songs positions

Just use the `queue.insert` again if you want to insert another one. And `queue.remove` is used to remove the track

**Comment by DevAndromeda** [comment]
```js
const removedTrack = queue.remove(3);
queue.insert(removedTrack, 7);
```

this code removes the song at index 3 and inserts it to the index 7
