### ISSUE TITLE
Unhandled Error on Specific Songs

### ISSUE THREAD

**Issue by cacacaio** [Androz2091/discord-player#764]
**Describe the bug**
Some songs give an unhadled error when you try and play them, you can add to the queue like normal, but whenever it's going to play it just crashed the entire bot. An example of a music that does this is below

**To Reproduce**
1 - Play some specific songs like this one https://www.youtube.com/watch?v=FRePSrWXLss

**Expected behavior**
Play the song like normal

**Please complete the following information:**
 - Node Version: 16.8.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (<ref *1> Queue {
  tracks: [],
  previousTracks: [
    Track {
      id: '884426175307448321',
      title: 'ELA TA COM SHORT COLADA NO FRANCISQUINHO - VAI TCHUCA - MC NAUAN (DJ K)',
      author: 'MANDELA FLUXOS',
      url: 'https://www.youtube.com/watch?v=FRePSrWXLss',
      thumbnail: 'https://i.ytimg.com/vi_webp/FRePSrWXLss/maxresdefault.webp',
      duration: '03:09',
      views: 9148,
      requestedBy: [User],
      playlist: undefined
    }
  ],
  playing: false,
  metadata: {
    channel: VoiceChannel {
      type: 'GUILD_VOICE',
      deleted: false,
      guild: [Guild],
      guildId: '**Omitted**',
      parentId: null,
      permissionOverwrites: [PermissionOverwriteManager],
      id: '**Omitted**',
      name: 'General',
      rawPosition: 0,
      rtcRegion: null,
      bitrate: 64000,
      userLimit: 0
    },
    textChannel: TextChannel {
      type: 'GUILD_TEXT',
      deleted: false,
      guild: [Guild],
      guildId: '**Omitted**',
      parentId: null,
      permissionOverwrites: [PermissionOverwriteManager],
      messages: [MessageManager],
      threads: [ThreadManager],
      nsfw: false,
      id: '**Omitted**',
      name: 'rogerin',
      rawPosition: 1,
      topic: null,
      lastMessageId: '884426197415628830',
      rateLimitPerUser: 0
    }
  },
  repeatMode: 0,
  id: '**Omitted**',
  _streamTime: 0,
  _cooldownsTimeout: Collection(0) [Map] {},
  _activeFilters: [],
  _filtersUpdate: undefined,
  player: default_1 {
    _events: [Object: null prototype] {
      trackStart: [AsyncFunction (anonymous)]
    },
    _eventsCount: 1,
    _maxListeners: undefined,
    options: {
      autoRegisterExtractor: true,
      ytdlOptions: [Object],
      connectionTimeout: 20000
    },
    queues: Collection(1) [Map] { '**Omitted**' => [Circular *1] },
    voiceUtils: VoiceUtils { cache: [Collection [Map]] },
    extractors: Collection(0) [Map] {},
    client: Client {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      options: [Object],
      rest: [RESTManager],
      _cleanups: [Set],
      _finalizers: FinalizationRegistry {},
      ws: [WebSocketManager],
      actions: [ActionsManager],
      voice: [ClientVoiceManager],
      shard: null,
      users: UserManager {},
      guilds: GuildManager {},
      channels: ChannelManager {},
      presence: [ClientPresence],
      user: [ClientUser],
      application: [ClientApplication],
      readyAt: 2021-09-06T13:13:45.393Z,
      [Symbol(kCapture)]: false
    },
    commands: Collection(5) [Map] {
      'clear' => [Object],
      'leave' => [Object],
      'nowplaying' => [Object],
      'play' => [Object],
      'skip' => [Object]
    },
    [Symbol(kCapture)]: false
  },
  guild: <ref *2> Guild {
    id: '**Omitted**',
    name: '**Omitted**,
    icon: null,
    features: [],
    commands: GuildApplicationCommandManager {
      permissions: [ApplicationCommandPermissionsManager],
      guild: [Circular *2]
    },
    members: GuildMemberManager { guild: [Circular *2] },
    channels: GuildChannelManager { guild: [Circular *2] },
    bans: GuildBanManager { guild: [Circular *2] },
    roles: RoleManager { guild: [Circular *2] },
    presences: PresenceManager {},
    voiceStates: VoiceStateManager { guild: [Circular *2] },
    stageInstances: StageInstanceManager { guild: [Circular *2] },
    invites: GuildInviteManager { guild: [Circular *2] },
    deleted: false,
    available: true,
    shardId: 0,
    splash: null,
    banner: null,
    description: null,
    verificationLevel: 'NONE',
    vanityURLCode: null,
    nsfwLevel: 'DEFAULT',
    discoverySplash: null,
    memberCount: 4,
    large: false,
    applicationId: null,
    afkTimeout: 300,
    afkChannelId: null,
    systemChannelId: null,
    premiumTier: 'NONE',
    premiumSubscriptionCount: 0,
    explicitContentFilter: 'DISABLED',
    mfaLevel: 'NONE',
    joinedTimestamp: 1630371507652,
    defaultMessageNotifications: 'ALL_MESSAGES',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    maximumMembers: 250000,
    maximumPresences: null,
    approximateMemberCount: null,
    approximatePresenceCount: null,
    vanityURLUses: null,
    rulesChannelId: null,
    publicUpdatesChannelId: null,
    preferredLocale: 'en-US',
    ownerId: '**Omitted**',
    emojis: GuildEmojiManager { guild: [Circular *2] },
    stickers: GuildStickerManager { guild: [Circular *2] }
  },
  options: {
    leaveOnEnd: true,
    leaveOnStop: true,
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 1000,
    autoSelfDeaf: true,
    ytdlOptions: { highWaterMark: 33554432 },
    initialVolume: 100,
    bufferingTimeout: 3000
  },
  connection: StreamDispatcher {
    _events: [Object: null prototype] {
      error: [Function (anonymous)],
      debug: [Function (anonymous)],
      start: [Function (anonymous)],
      finish: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    connectionTimeout: 20000,
    readyLock: false,
    voiceConnection: VoiceConnection {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      debug: null,
      rejoinAttempts: 0,
      receiver: [VoiceReceiver],
      onNetworkingClose: [Function: bound onNetworkingClose],
      onNetworkingStateChange: [Function: bound onNetworkingStateChange],
      onNetworkingError: [Function: bound onNetworkingError],
      onNetworkingDebug: [Function: bound onNetworkingDebug],
      _state: [Object],
      packets: [Object],
      joinConfig: [Object],
      [Symbol(kCapture)]: false
    },
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      subscribers: [Array],
      _state: [Object],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    channel: VoiceChannel {
      type: 'GUILD_VOICE',
      deleted: false,
      guild: [Guild],
      guildId: '**Omitted**',
      parentId: null,
      permissionOverwrites: [PermissionOverwriteManager],
      id: '**Omitted**',
      name: 'General',
      rawPosition: 0,
      rtcRegion: null,
      bitrate: 64000,
      userLimit: 0
    },
    paused: false,
    audioResource: null,
    [Symbol(kCapture)]: false
  }
})
    at new NodeError (node:internal/errors:371:5)
    at default_1.emit (node:events:383:17)
    at FFmpeg.<anonymous> (C:\Users\ADMREDE\RogerMusicBot\node_modules\discord-player\dist\Structures\Queue.js:651:103)
    at FFmpeg.emit (node:events:406:35)
    at Socket.processError (C:\Users\ADMREDE\RogerMusicBot\node_modules\prism-media\src\core\FFmpeg.js:65:40)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by DevAndromeda** [comment]
hello, are you listening to the `error` event emitted by `discord-player`? You can do that by adding the following code:

```js
player.on("error", (queue, error) => {
    console.log(`Error at ${queue.guild.id} | ${error.message}`);
});
```

**Comment by cacacaio** [comment]
Oh I didn't know that I could listen to errors, at least that way I can skip the song and not let the bot crash, but the error it's giving me is "Error at **GuildId** | write EPIPE"

**Comment by MobiliLavander** [comment]
I have this error too, with some songs the bot just doesn't work. I start the song he joins and then leave instantly getting the EPIPE error in console.

**Comment by Samiul30** [comment]
> I have this error too, with some songs the bot just doesn't work. I start the song he joins and then leave instantly getting the EPIPE error in console.

This err is related to the ytdl and if you have better stream downloading package you can use that to avoid the issue .

**Comment by MobiliLavander** [comment]
Tysm hope I can fix
