### ISSUE TITLE
[v3-rewrite] Will this version support Radio?

### ISSUE THREAD

**Issue by thomasthebro1** [Androz2091/discord-player#77]
The question is quite obvious because of the title. **Will v3 support the ability to play a live radio stream** will built-in functions? (e.g. `client.player.play(voiceChannel, { type: 'radio', name: 'someradioname' }, user)`) - if the 2nd argument isn't an object then it will just scrape YouTube as normal.

If you need help finding any streaming URLs for Radio services I have a few compiled that might be useful for you.

**Comment by Androz2091** [comment]
Hello,
In the end, I don't think it will be added. It's really a special use case that would change a lot of things in the code. But I keep this in mind for another package, maybe :grin:
