### ISSUE TITLE
client.player.lyrics is not a function. help

### ISSUE THREAD

**Issue by Liam6791** [Androz2091/discord-player#777]
**Describe the bug**
I'm not really sure if it's a bug, but I'll still make this issue anyways. I've got a lyrics command, and it doesn't work. Everytime I do .lyrics it shows in console: `UnhandledPromiseRejectionWarning: TypeError: client.player.lyrics is not a function`. What can I do to fix this?

**Expected behavior**
I expected the lyrics of the current song playing to be sent in chat by my bot.

**Screenshots**
https://prnt.sc/1s04thu

**Please complete the following information:**
 - Node Version: v14.17.6
 - Discord Player Version: v3.4.0
 - Discord.js Version: v12.5.3

**Additional context**
none

**Comment by DevAndromeda** [comment]
**\<Player\>.lyrics** was removed with the release of Discord Player v5.x, and instead you should use the extractor yourself to get the lyrics:

```js
const { Lyrics } = require("@discord-player/extractor");
const lyricsClient = Lyrics.init("api_key_or_leave_it_blank");

lyricsClient.search("alan walker faded")
    .then(x => console.log(x))
    .catch(console.error);
```

Link: https://github.com/DevSnowflake/discord-player-extractors
