### ISSUE TITLE
Bot doesn't leave the voice channel when empty even if leaveOnEmpty is true

### ISSUE THREAD

**Issue by mbackermann** [Androz2091/discord-player#784]
**Describe the bug**
when I create my queue and set the `leaveOnEmpty: true` and `leaveOnEmptyCooldown: 30`, the bot doesn't leave the channel even after waiting the cooldown. However, the `channelEmpty` event still gets fired.

**To Reproduce**
create a `player.createQueue` setting the `leaveOnEmpty: true` and play a track. Leave the channel.

**Expected behavior**
The bot should leave the channel

**Screenshots**

**Please complete the following information:**
 - Node Version: channelEmpty
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Additional context**
You can check my implementation here
https://github.com/mbackermann/dj-arthas/blob/master/commands/bot-commands/play.js

**Comment by Newt74** [comment]
If you want the bot to leaves, you must set `leaveOnStop: true` too. Otherwise, you can force the bot to leave in `channelEmpty` event:
```js
player.on('channelEmpty', (queue) => {
    if (queue.connection) {
        queue.connection.disconnect();
    }
});
```

**Comment by mbackermann** [comment]
I got it! Thanks, I will close the issue.
