### ISSUE TITLE
Audio quality issues.

### ISSUE THREAD

**Issue by SoulHarsh007** [Androz2091/discord-player#8]
Errors like these are noted in console while playing music
`Could not extract html5player key: https://www.youtube.com/s/player/9b926fb0/player_ias.vflset/en_US/base.js`
Audio plays distorted.

**Comment by thomasthebro1** [comment]
I am also experiencing this issue, but I don't really notice any audio quality issues.

**Comment by Androz2091** [comment]
Did you solve the problem @SoulHarsh007?
