### ISSUE TITLE
Youtube Music search

### ISSUE THREAD

**Issue by ttoino** [Androz2091/discord-player#804]
**Describe the feature you would like**
Ability to search for songs from Youtube Music.

**Expected behavior**
```typescript
player.search(query, {
    requestedBy: message.author,
    searchEngine: QueryType.YOUTUBE_MUSIC_SEARCH
})
```

**Additional context**
Playing songs from Youtube Music is already supported, so this would only require a new `QueryType`.
Using [youtube-music-api](https://github.com/emresenyuva/youtube-music-api) seems to be the best option, allowing you to search only songs (as videos are already covered by `QueryType.YOUTUBE_SEARCH`).
Additionally, this would provide a better way to handle Spotify tracks, as the current implementation usually plays music videos that have interludes, preludes or sound effects over top the music.

**Comment by ethhaqn** [comment]
Vouch.

**Comment by FreshImmuc** [comment]
+1
