### ISSUE TITLE
Remove Youtube from core and add as a plugin

### ISSUE THREAD

**Issue by UndiedGamer** [Androz2091/discord-player#805]
Hey i would like to suggest this, tho this suggestion would be a bit sour, maybe you should remove youtube from the core and add it as a plugin so that people who do not want to add youtube to their bot because of youtube's TOS wont run away from this package

**Comment by DevAndromeda** [comment]
In the dev version, we've added stream trap support that runs before actually downloading streams. You should use that to block YouTube streams downloader instead. We do not have plans on removing anything at the core level.

**Comment by KingCh1ll** [comment]
> In the dev version, we've added stream trap support that runs before actually downloading streams. You should use that to block YouTube streams downloader instead. We do not have plans on removing anything at the core level.

Can you elaborate on this? I no longer want to support YouTube as an option due to the recent events.
