### ISSUE TITLE
(node:18080) MaxListenersExceededWarning

### ISSUE THREAD

**Issue by SathvikKS** [Androz2091/discord-player#808]
**Describe the bug**
`(node:18080) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11  listeners added to [Player]. Use emitter.setMaxListeners() to increase limit`

**To Reproduce**
Added an event handler for Player that contains 11 files, each file for an event available for Player.

**Screenshots**
![image](https://user-images.githubusercontent.com/31741267/134809883-e065a3ee-b4fc-439f-a0cb-b1984c99b87b.png)

**Please complete the following information:**
 - Node Version: 16.10.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Comment by DevAndromeda** [comment]
you probably added a listener inside your command meaning:
- bot will add new listener every time the command is ran

**Comment by SathvikKS** [comment]
fixed the issue by changing event handler logic
