### ISSUE TITLE
SoundCloud Playlists Not Working

### ISSUE THREAD

**Issue by ethhaqn** [Androz2091/discord-player#810]
**Describe the bug**
When I play a SoundCloud playlist, it returns invalid. Although, SoundCloud songs, YouTube playlists, YouTube songs, Spotify songs and Spotify playlists work.

**To Reproduce**
1. Play a SoundCloud playlist (https://soundcloud.com/nocopyrightsounds/sets/ncs-top-100)
2. Observe

**Expected behavior**
Should add the songs from the playlist to the queue.

**Screenshots**
![image](https://user-images.githubusercontent.com/46451398/134810833-0d8610c9-fd04-4c0f-82c3-7647bdaf89ad.png)

**Please complete the following information:**
 - Node Version: v16.6.1
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Comment by DevAndromeda** [comment]
Hello, You can use extractors api to parse playlists with any soundcloud library out there. And if you are having problems with streams, you should try using  **[onBeforeCreateStream](https://github.com/Androz2091/discord-player#custom-stream-engine)**.
