### ISSUE TITLE
Error when playing music 

### ISSUE THREAD

**Issue by reachomk** [Androz2091/discord-player#813]
![image](https://user-images.githubusercontent.com/46237581/134821933-5e1e75a2-15ef-429a-b862-13176eb3e331.png)

Getting the following error whenever I try to play music. Joins vc and sends message that the song is queued, but does not play it. 

Node Version: v16.6.1
Discord Player Version: 5.1.0
Discord.js Version: 13.1.0

**Comment by reachomk** [comment]
I also tried reinstalling discord-player/downloader, but got this error. 

npm ERR! code 1
npm ERR! path O:\Om\Coding\Discord Bots\discord-music-bot\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run check && node scripts/postinstall.js
npm ERR! > youtube-dl-exec@1.2.11 check
npm ERR! > bin-version-check python '>=2'
npm ERR! Error: Invalid version range
npm ERR!     at binaryVersionCheck (file:///O:/Om/Coding/Discord%20Bots/discord-music-bot/node_modules/bin-version-check/index.js:11:9)
npm ERR!     at file:///O:/Om/Coding/Discord%20Bots/discord-music-bot/node_modules/bin-version-check-cli/cli.js:28:1
npm ERR!     at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
npm ERR!     at async Loader.import (node:internal/modules/esm/loader:178:24)
npm ERR!     at async Object.loadESM (node:internal/process/esm_loader:68:5)
npm ERR!     at async handleMainPromise (node:internal/modules/run_main:63:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\reach\AppData\Local\npm-cache\_logs\2021-09-26T19_43_23_246Z-debug.log

**Comment by ethhaqn** [comment]
Exact same issue over here.

**Comment by DevAndromeda** [comment]
same as #814
