### ISSUE TITLE
add all youtube mix song to the queue

### ISSUE THREAD

**Issue by agusjanardana** [Androz2091/discord-player#817]
Hello, recently i tried to playing song from youtube mix videos, its like this link that i use to: 

https://www.youtube.com/watch?v=8omSc01lpbI&list=RD8omSc01lpbI&start_radio=1&rv=8omSc01lpbI&t=0&ab_channel=TEGRA%2a39TEGRA%2a39

But, currently I'm using discord-player in a bot, when i type /play [_link mix video_] ( / or another prefix), its only return one song.
 
![image](https://user-images.githubusercontent.com/62202561/134928665-7f4e1b11-c357-4a43-a366-d6f277f6f6f8.png) 

So my suggestion is to add youtube mix to queue list... I hope this feature can be considered.. thanks you.

**Comment by DevAndromeda** [comment]
Please implement extractor for that, we have decided not to include it internally as it increases the complexity and module size.

**Comment by DevAndromeda** [comment]
stale
