### ISSUE TITLE
Error emitted from the queue: write EPIPE

### ISSUE THREAD

**Issue by SomeRandomOwl** [Androz2091/discord-player#818]
Now i am fairly confident this is an issue with youtube-dl-core specifically (possibly FFMPEG)

But with certain videos this error is emitted and doesn't play the video but it doesnt with every video

For example this video works https://www.youtube.com/watch?v=LGRo0XtbdyY
but this one does not https://www.youtube.com/watch?v=a91ETEev6-A

Now i know this likely is not an issue with discord-player itself

I am just trying to figure out if there is a workaround for this issue or a way to fix it 

running the script on: 
Debian GNU/Linux 10 (buster)
Node v16.6.2
discord-player 5.1.0
discord.js 13.1.0

**Comment by DaSussy** [comment]
its a linux issue, works completely fine on windows

**Comment by C-Lunn** [comment]
Also experiencing this; CentOS 7.

**Comment by samusaran** [comment]
Also experiencing this on CentOS 8

**Comment by wojciechjablonski96** [comment]
Also experiencing this on Ubuntu 20.04.3 LTS.

**Comment by TriggeredBoi** [comment]
I was having this issue as well - Somehow initializing the Player with `{ ytdlOptions: { quality: 'highestaudio' } }` (or `lowestaudio`, just not `lowest` or `highest` because those error with 404's instead) magically fixed it for me, so that's a workaround that could work too for anyone reading this.

**Comment by LinusBotTips** [comment]
Yeah I'm also experiencing this on Ubuntu 20.04.3

**Comment by samusaran** [comment]
> 
> 
> I was having this issue as well - Somehow initializing the Player with `{ ytdlOptions: { quality: 'highestaudio' } }` (or `lowestaudio`, just not `lowest` or `highest` because those error with 404's instead) magically fixed it for me, so that's a workaround that could work too for anyone reading this.

while I didn't had any EPIPE errors, I'm still getting `aborted` errors :(

**Comment by DaSussy** [comment]
EPIPE errors are caused by linux. Aborted errors are caused by ytdl-core.

**Comment by samusaran** [comment]
Currently I managed to fix most errors by using `lowestaudio` filter. It seems to fix both ytdl and EPIPE errors

**Comment by DevAndromeda** [comment]
Hello, you can use some stable stream sources/alternatives of `ytdl-core` with **[onBeforeCreateStream](https://github.com/Androz2091/discord-player#custom-stream-engine)** to fix this issue. If it does not fix the problem, you are free to open a new issue.
