### ISSUE TITLE
return more than only 100 tracks

### ISSUE THREAD

**Issue by choco-green** [Androz2091/discord-player#821]
**Having more tracks returned than 100 in any given playlist**

**Expected behavior**
```js
const searchResult = await player.search("https://open.spotify.com/playlist/4OSKpxBbXwUfxgoSdZJpVx?si=eb05c37af6894f11", 
    { requestedBy: message.member.user, searchEngine: QueryType.AUTO });

searchResult.tracks.length > 100 // true
```

**Comment by DevAndromeda** [comment]
I dont think this is possible without api. You could implement this yourself by adding custom extractor. By default, discord-player gets only 100 items max. due to the limitations from spotify

**Comment by choco-green** [comment]
There is an [offset available](https://developer.spotify.com/documentation/web-api/reference/#category-playlists), perhaps checking if there are enough tracks returned, if so, add 50 to the offset (due to a limit of 50), then send a second API request, and vice versa. However, if it returned less than 50 tracks, it stops sending requests of the same playlist with offset because the end of the playlist has reached, I haven't yet read through the code of where the logic can be implemented, but I'll get back as soon as I have.

It is of course possible for people to misuse this to attempt to break the code, but I think it should at least be added as an optional parameter somewhere, it is also possible for the API to run out of request due to multiple requests can be sent with simply just one line of code expected from the end-user.

**Comment by choco-green** [comment]
For anyone reading this issue in the future:

This line of [code](https://github.com/Androz2091/discord-player/blob/94ffd93cde2257034122c98e03ffdb9582e15233/src/Player.ts#L319) gets the "entire" playlist (first 100 songs) and it's achieving that using a [function ](https://github.com/microlinkhq/spotify-url-info/blob/33c9323db7f654a89620b6945d45b4e0d16c7093/index.js#L26)on "[spotify-url-info](https://github.com/microlinkhq/spotify-url-info)". This is because spotify-url-info is "[scraping the spotify embed widget and that only contains the first 100 tracks. I don't think there's anything we can do without adding another scraping method.](https://github.com/microlinkhq/spotify-url-info/issues/69#issuecomment-802364053)", and neither discord-player nor spotify-url-info are calling directly to the API, resulting in only the first 100 tracks in the playlist being returned. 

This means that unless there is a different way of getting track data from spotify, there can only be 100 songs returned by discord-player :(
