### ISSUE TITLE
Skip some song from youtube

### ISSUE THREAD

**Issue by Rosik93** [Androz2091/discord-player#826]
The bot works very well with 90% of the songs but sometimes it plays a song and immediately skip to the next. 
I tried with different song and channel from youtube. 
I dont have any error log or other

**Please complete the following information:**
    "node": "16.x"
    "dependencies": {
    "@discordjs/builders": "^0.6.0",
    "@discordjs/opus": "^0.5.3",
    "@discordjs/rest": "^0.1.0-canary.0",
    "discord-player": "^5.1.0",
    "discord.js": "^13.1.0",
    "fs": "^0.0.1-security",
    "nodemon": "^2.0.12"
  }

thank you

**Comment by milkbag19** [comment]
I am also having this issue.

**Comment by TheChilliPL** [comment]
Happened to me multiple times too

**Comment by milkbag19** [comment]
> Happened to me multiple times too

I found a quick fix with a few lines of code, I will link soon

**Comment by milkbag19** [comment]
> Happened to me multiple times too

https://github.com/Androz2091/discord-player/issues/794#issue-1000772967

**Comment by DevAndromeda** [comment]
Ok, we will allow you guys to handle streams on your own (by default discord-player will do that).

You can test it rn with `npm install discord-player@dev`

**Comment by DevAndromeda** [comment]
Hello, you can use some stable stream sources/alternatives of `ytdl-core` with **[onBeforeCreateStream](https://github.com/Androz2091/discord-player#custom-stream-engine)** to fix this issue.
