### ISSUE TITLE
Error 403, 410, Cannot play a resource that has already ended; Can't find music/video or write EPIPE when play by link

### ISSUE THREAD

**Issue by thanhgaming5550** [Androz2091/discord-player#841]
**Describe the bug**
[PlayerError] Cannot play a resource that has already ended (and return error code 403 or 410)
Return Can't find music/video or write EPIPE when play by link

**To Reproduce**
Command Bot play music
**Expected behavior**
Bot play music

**Screenshots**
![image](https://user-images.githubusercontent.com/62001770/136669373-733175bc-a514-4e4b-83a3-ac0625f99e67.png)
![image](https://user-images.githubusercontent.com/62001770/136669689-4d758d17-ffea-4fcb-b7e5-1b2d09230eac.png)
![image](https://user-images.githubusercontent.com/62001770/136669447-fd266a3f-61e9-42ae-afd8-11e8040ad5d7.png)
![image](https://user-images.githubusercontent.com/62001770/136669536-7518ba92-7060-44c9-847e-a140c266d443.png)
![image](https://user-images.githubusercontent.com/62001770/136669575-fe9c803b-0dbd-4254-b65a-8803596b9979.png)

**Please complete the following information:**
 - Node Version: 16.11.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.2.0
 - FFmpeg-static Version: 4.4.0

**Additional context**
**Code:** 

`main.js`:
```js
//{code}

client.player = new Player(client, {
    ytdlDownloadOptions: {
        filter: "audioonly"
    }
});

client.player.on("error", (queue, error) => {
    console.log(colors.red(`Lỗi trong hàng đợi: ${error.message}`));
    queue.metadata.send(`❌ | Lỗi trong hàng đợi: ` + "`" + `${error.message}` + "`" + `. Vui lòng thử lại sau`)
});
client.player.on("connectionError", (queue, error) => {
    console.log(colors.red(`Lỗi kết nối: ${error.message}`));
    queue.metadata.send(`❌ | Lỗi kết nối: ` + "`" + `${error.message}` + "`" + `. Vui lòng thử lại sau`)
});

client.player.on("trackStart", (queue, track) => {
    queue.metadata.send(`🎶 | Bắt đầu phát **${track.title}** trong **${queue.connection.channel.name}**!`);
});

client.player.on("trackAdd", (queue, track) => {
    queue.metadata.send(`🎶 | Bài **${track.title}** đã được thêm vào hàng đợi!`);
});

client.player.on("botDisconnect", (queue) => {
    queue.metadata.send("❌ | Xóa hàng đợi do bị ngắt kết nối khỏi kênh nói thủ công!");
});

client.player.on("channelEmpty", (queue) => {
    queue.metadata.send("❌ | Tự thoát do không có người nghe");
});

client.player.on("queueEnd", (queue) => {
    queue.metadata.send("**✅ | Đã phát xong!** *Nếu bài của bạn vẫn chưa được phát, vui lòng thử lại*");
});

//{some code}
```

`play.js`:
```js
const Discord = require('discord.js')
const { Player, QueryType, QueueRepeatMode } = require("discord-player");

module.exports = {
    name: "play",
    description: "play songs",

    async run (client, message, args) {
        const player = client.player;
        if (!message.member.voice.channel) return message.channel.send("❌ | **Bạn phải ở trong một kênh nói!**");
        if (message.guild.me.voice.channel && message.member.voice.channel.id !== message.guild.me.voice.channel.id) return message.channel.send(":x: | **Bạn phải ở cùng kênh nói với Bot!**"); 

        const queue = await player.createQueue(message.guild, {
            metadata: message.channel
        });
        try {
            if (!queue.connection) await queue.connect(message.member.voice.channel);
        } catch {
            queue.destroy();
            return message.channel.send("❌ | Đã xảy ra lỗi khi tham gia kênh nói!");
        }
        const searchResult = await player.search(args.join(" "), {
            requestedBy: message.user,
            searchEngine: QueryType.AUTO
        })
        if (!searchResult || !searchResult.tracks.length) return message.channel.send("❌ | Không tìm thấy nhạc/video hoặc đã xảy ra lỗi khi tìm kiếm");
        message.channel.send(`⏱ | Đang tải ${searchResult.playlist ? "danh sách phát" : "bài nhạc"}...` );
        if (searchResult.playlist) {queue.addTracks(searchResult.tracks)} else {queue.addTrack(searchResult.tracks[0])};
        if (!queue.playing) await queue.play();
    }
}
```

**Run Command : `node --max-old-space-size=4096 main.js`**

**Comment by PiousGaming** [comment]
That why u have EPIPE error, uninstall ffmpeg-static package cuz that package is not stable. Let download ffmpeg from https://www.ffmpeg.org/download.html
and about error 410, it will reduce if you use cookies
about error 403, i asked ytdl and they said "there is no way to fix yet, its probably caused on youtube's side"

**Comment by PiousGaming** [comment]
i asked them, and they said u can install ffmpeg by use dockerfile

**Comment by thanhgaming5550** [comment]
> i asked them, and they said u can install ffmpeg by use dockerfile

Is there any other way?

**Comment by willm132** [comment]
Has anyone found a stable fix for this?

**Comment by DevAndromeda** [comment]
This problem is with youtube itself, we cannot fix this from here. You can take a look at https://github.com/fent/node-ytdl-core and see if they can do something about this

**Comment by SuperSweatyTejas** [comment]
> i asked them, and they said u can install ffmpeg by use dockerfile

can you send the specific dockerfile for it?

**Comment by DevAndromeda** [comment]
this should be fixed by https://github.com/fent/node-ytdl-core/releases/tag/v4.9.2

**Comment by tomihbk** [comment]
Any new developments on this issue?

**Comment by skdhg** [comment]
> Any new developments on this issue?

https://github.com/Androz2091/discord-player/releases/tag/v6.0.0
