### ISSUE TITLE
[BUG] Leaves channel as soon as the bot starts to play any music - or will skip the song then leave.

### ISSUE THREAD

**Issue by Phoenix557** [Androz2091/discord-player#848]
**Describe the bug**

Leaves channel as soon as the bot starts to play any music - or will skip the song then leave.
**To Reproduce**

**Expected behavior**

Shouldn't do this
**Screenshots**

**Please complete the following information:**
 - Node Version: x.x.x
 - Discord Player Version: x.x.x
 - Discord.js Version: x.x.x
v 16.11 - Discord Player v MOST RECENT - DJS MOST RECENT
**Additional context**

**Comment by Amir-HSD** [comment]
I also have this problem, please help me

**Comment by lennox-lmao** [comment]
I still have the same problem...

**Comment by nizeic** [comment]
> ```js
> const playdl = require('play-dl');
> 
> const queue = await client.player.createQueue(guild, {
>     metadata: channel,
>     async onBeforeCreateStream(track, source, _queue) {
>         // console.log({track: track, source: source});
> 
>         if (isSpotify(track.url)) {
>             if (playdl.is_expired()) await playdl.refreshToken();
>             let spotify_data = await playdl.spotify(track.url);
>             
>             let yt_query = `${spotify_data.name} by `;
>             spotify_data.artists.forEach((key) => yt_query += key.name + ' ');
>             console.log(`[${guild.name}] Spotify -> YouTube: ${yt_query}`);
> 
>             let search_yt = await playdl.search(yt_query, { limit: 1 });
>             return (await playdl.stream(search_yt[0].url)).stream;
>         } else {
>             return (await playdl.stream(track.url)).stream;
>         }
>     }
> });
> ```
> ```js
> function isSpotify (url) {
>     let re = new RegExp('^(spotify:|https://[a-z]+\.spotify\.com/)');
>     return re.test(url);
> }
> ```

afaik play-dl can only play youtube links so you're probably gonna get an error if you try to play non-youtube/spotify links (e.g. soundcloud) with that
also is it really better to use regex? i simply used `.includes()` to check if it's a youtube track and it works perfectly fine for me

```js
const queue = await client.player.createQueue(message.guild,{ metadata: { channel: message.channel },
    async onBeforeCreateStream(track, source, _queue) {
        if (track.url.includes("youtube.com")) {
            // play directly if it's a youtube track
            return (await playdl.stream(track.url)).stream;
        }
        else {
            // search for the track on youtube with the track author & title using playdl.search()
            // i added "lyric" to the search query to avoid playing music video streams
            return (await playdl.stream(await playdl.search(`${track.author} ${track.title} lyric`, { limit : 1, source : { youtube : "video" } }).then(x => x[0].url))).stream;
        }
    }
});
```

**Comment by phxgg** [comment]
@nizeic My code currently is the following:

```javascript
async onBeforeCreateStream(track, source, _queue) {
  // console.log({track: track, source: source});
  
  try {
      if (isSpotify(track.url)) {
          // Spotify
          if (play_dl.is_expired()) await play_dl.refreshToken();
          let spotify_data = await play_dl.spotify(track.url);
          
          let yt_query = `${spotify_data.name} by `;
          spotify_data.artists.forEach((key) => yt_query += key.name + ' ');
          console.log(`[${guild.name}] Spotify -> YouTube: ${yt_query}`);
  
          let search_yt = await play_dl.search(yt_query, { limit: 1 });
          return (await play_dl.stream(search_yt[0].url)).stream;
      } else {
          // YouTube & SoundCloud
          return (await play_dl.stream(track.url)).stream;
      }
  } catch (err) {
      console.error(`[${guild.name}] Error: onBeforeCreateStream() -> ${err.message}`);
  }
}
```

I'm actually checking if the track comes from spotify, then it'll search for the track name and artists' names and play it via youtube. Otherwise, if the track comes from either youtube or soundcloud it'll just play the stream. This implementation currently works perfectly for me. The only thing that will not work is soundcloud private links, but I have not had the time yet to look into why this is happening.

**Comment by nizeic** [comment]
my bad. i thought play-dl could only play directly from youtube
thanks for sharing!

**Comment by DevAndromeda** [comment]
You can just check the source parameter

**Comment by SuperSweatyTejas** [comment]
here is a lil other fix that I have found

https://github.com/Androz2091/discord-music-bot/issues/24#issuecomment-922339568

**Comment by Yuichiro1019** [comment]
> I was facing this issue too but was able to get around it by adding these ytdl options to the player.
> 
> ```js
> ytdlOptions: {
>     quality: 'highestaudio',
>     highWaterMark: 1 << 25,
> },
> ```
> 
> Haven't tested this extensively, but it seems to stop the bot from stopping after playing for a few seconds.
> 
> [Edit]: Inspired by the config values in [MusicBot by ZerioDev](https://github.com/ZerioDev/Music-bot/blob/master/config.js)

thanks man saved my day

**Comment by DevAndromeda** [comment]
Hello, you can use some stable stream sources/alternatives of `ytdl-core` with **[onBeforeCreateStream](https://github.com/Androz2091/discord-player#custom-stream-engine)** to fix this issue.
