### ISSUE TITLE
url is not defined

### ISSUE THREAD

**Issue by DeathMario** [Androz2091/discord-player#85]
I have this error code: https://hasteb.in/ujoxalad.coffeescript

The code is: https://gyazo.com/e7aa2762c6bfb25ec903b358a87109c6

And The Line of the error code is: https://gyazo.com/037b2788314c765cf83c588c4624a241

Can Help me? :(

**Comment by Androz2091** [comment]
Can you test using v3.0.0-beta.3 please?

**Comment by DeathMario** [comment]
Srry for inactivity, I am going to try

**Comment by DeathMario** [comment]
This error was fixed a long time ago, sorry for not closing the issue ... The problem lately with discord-player is that when searching for songs it gives me an error like it can't find it or I don't know very well.

**Comment by DeathMario** [comment]
I have seen that there are other people with this same problem

**Comment by DeathMario** [comment]
Oh wait, it seems that things have changed in the npm, I will see them and try everything again! @Androz2091
