### ISSUE TITLE
Stop using inLineVolume

### ISSUE THREAD

**Issue by pauldb09** [Androz2091/discord-player#865]
**Describe the bug**
When you use inLineVolume , in the discord.js/voice package, it can creates important memory leaks.

**To Reproduce**
Create a music bot with discord-player and discord.js/voice and see the ram.
Create another with same structure and lavalink. And compare

**Screenshots**
With discord.js/voice: https://cdn.discordapp.com/attachments/893164961264717854/903546082104057876/unknown.png
Without: only 1gb

**Please complete the following information:**
 - Node Version: v16
 - Discord Player Version: dev
 - Discord.js Version: v13

**Additional context**
I asked in discord.js server and they answered that it's inLineVolume who creates important problems

**Comment by DevAndromeda** [comment]
After doing some research, I did not find anything that properly states the "alternative" to this. According to docs,

> By default, inline volume is disabled for performance reasons. Enabling it will allow you to modify the volume of your stream in realtime. This comes at a performance cost, even if you aren't actually modifying the volume of your stream.

which means volume controls is impossible without enabling `inlineVolume` and volume controls is also required for audio filters. Disabling `inlineVolume` would improve the performance but it also means we need to restart the stream with `inlineVolume` enabled if user wants to change volume which is actually worse imo. Therefore, as of right now we do not want to remove the `inlineVolume` from the library as it causes more problems.
