### ISSUE TITLE
ABORT_ERR

### ISSUE THREAD

**Issue by slowwdev** [Androz2091/discord-player#871]
**Describe the bug**
When I listen music, i have this error but it does not stop because i made an anticrash i think

**To Reproduce**
Just Listen Music

**Screenshots**
![image](https://user-images.githubusercontent.com/75091300/139946281-65c7c5b6-a6cf-497f-86f6-abc03f424524.png)

**Please complete the following information:**
 - Node Version: 16.10.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.3.1

**Comment by pauldb09** [comment]
Try to update your nodejs and discord.js/voice version.

**Comment by pauldb09** [comment]
And the problem is probably from your code. Can you send your play command?

**Comment by slowwdev** [comment]
elles sont deja update @pauldb09 je sais t fr mdr je suis sur greenbotdev

**Comment by slowwdev** [comment]
La commande play:

const { QueryType } = require('discord-player');
const { MessageEmbed } = require('discord.js');
const player = require('../../client/player');

module.exports = {
    name: 'play',
    description: 'play a song',
    options: [
        {
            name: 'songtitle',
            description: 'title of the song',
            type: 'STRING',
            required: true,
        },
    ],
    run: async (client, interaction) => {
        const songTitle = interaction.options.getString('songtitle');

        if (!interaction.member.voice.channel)
            {return interaction.followUp({
                content: 'Please join a voice channel first!',
            });}

        const searchResult = await player.search(songTitle, {
            requestedBy: interaction.user,
            searchEngine: QueryType.AUTO,
        });
        if (!searchResult || !searchResult.tracks.length) return void interaction.followUp({ content: 'No results were found!' });

        const queue = await player.createQueue(interaction.guild, {
            metadata: interaction.channel,
        });

        if (!queue.connection)
            {await queue.connect(interaction.member.voice.channel);}

        interaction.followUp({ embeds: [new MessageEmbed()
        .setTitle('🎶 | Music Player')
        .setDescription(`⏱ | Loading your ${searchResult.playlist ? 'playlist' : 'track'}...`)
        .setFooter(client.embed.footertext, client.embed.footericon)
        .setColor(client.embed.color)] });

        searchResult.playlist
            ? queue.addTracks(searchResult.tracks)
            : queue.addTrack(searchResult.tracks[0]);


        if (!queue.playing) await queue.play();
    },
};

**Comment by pauldb09** [comment]
@slowwdev Essaye npm i discord-player@dev

**Comment by slowwdev** [comment]
ok j essaie

**Comment by pauldb09** [comment]
Si c'est pas fix, ajoute ça à la queue que tu crées.
`   ytdlOptions: {
                    quality: 'highest',
                    filter: 'audioonly',
                    highWaterMark: 1 << 25,
                    dlChunkSize: 0
                },`

**Comment by slowwdev** [comment]
c deja ajouté

**Comment by pauldb09** [comment]
Avec version dev?

**Comment by slowwdev** [comment]
j ai fait les modifs j ai toujours l erreur

**Comment by pauldb09** [comment]
Remplace `const queue = await player.createQueue(interaction.guild, {
        metadata: interaction.channel,
    });` 
    par
    `const queue = await player.createQueue(interaction.guild, {
        metadata: interaction.channel,   
        ytdlOptions: {
                    quality: 'highest',
                    filter: 'audioonly',
                    highWaterMark: 1 << 25,
                    dlChunkSize: 0
                },
    });`
    ça le fait avec toutes les musiques?

**Comment by slowwdev** [comment]
oui toutes les musiques bon attends j essaie

**Comment by slowwdev** [comment]
toujours pas bon

**Comment by pauldb09** [comment]
L'erreur fait pas crash ?

**Comment by pauldb09** [comment]
Elle vient de discord.js/voice. Ils disent qu'elle sera fix bientot. Met juste un return dans ton anti crash et voilà

**Comment by slowwdev** [comment]
ah et si j essaie de desinstaller voice ?

**Comment by pauldb09** [comment]
ça va pas marcher.

**Comment by slowwdev** [comment]
ah bah j ai desinstallé voice et ça marche (j ai @discordjs/opus par contre)

**Comment by slowwdev** [comment]
enfin l erreur est tjrs là

**Comment by DevAndromeda** [comment]
Hello, you can use some stable stream sources/alternatives of `ytdl-core` with **[onBeforeCreateStream](https://github.com/Androz2091/discord-player#custom-stream-engine)** to fix this issue.
