### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by VedantNoob** [Androz2091/discord-player#886]
**Describe the bug**
Hey, Whenever I Play a song, the Bot has  a laggy Voice when it plays the music. Is there anything I can do?

**Expected behavior**
Whenever I play the songs using the bot, it lags.

**Screenshots**
I have none.

**Please complete the following information:**
 - Node Version: 16
 - Discord Player Version: Its the latest one since i installed it yesterday
 - Discord.js Version: v13

**Comment by DevAndromeda** [comment]
what do you mean by 
![image](https://user-images.githubusercontent.com/46562212/141990039-2f68fb4b-4307-443f-a10b-11e901f95783.png)

**Comment by VedantSharma7** [comment]
Nothing, It was automatically there.

**Comment by PinKiUwU** [comment]
I have the same issue actually, the bot's music is choppy for some goddamn reason. I have noticed it has to do something with multiple big intervals running at once for some reason.



> **Describe the bug** Hey, Whenever I Play a song, the Bot has a laggy Voice when it plays the music. Is there anything I can do?
> 
> **Expected behavior** Whenever I play the songs using the bot, it lags.
> 
> **Screenshots** I have none.
> 
> **Please complete the following information:**
> 
> * Node Version: 16
> * Discord Player Version: Its the latest one since i installed it yesterday
> * Discord.js Version: v13

**Comment by pauldb09** [comment]
Try to change the voice channel region and what are your vps performances

**Comment by VedantSharma7** [comment]
I dont have a vps and i use pc for hosting it

**Comment by Cengiouwe** [comment]
> I dont have a vps and i use pc for hosting it

what are the specs for your pc?

**Comment by VedantSharma7** [comment]
nvidia 940m, 16 gigs of ram, i5?

**Comment by ShashankAlt** [comment]
> nvidia 940m, 16 gigs of ram, i5?

And internet speed ??

**Comment by VedantSharma7** [comment]
300mbps

**Comment by VedantSharma7** [comment]
on my other pc, i have rtx3060 and i7

**Comment by rdapshii** [comment]
pc graphic card has nothing to be here, the important things are the processor, ram and internet speed

**Comment by PinKiUwU** [comment]
> pc graphic card has nothing to be here, the important things are the processor, ram and internet speed

I have a ryzen 3 3700x 8 cores 4005 mhz, 32gb ram ddr4 3600mhz (? i don't remember exactly) and 400 Mbps.

The issue seems to be happening for some reason consistently on every single play of anything that's not a file, also it throws the "resource has already ended" error way too much for some reason.

**Comment by VedantSharma7** [comment]
> > pc graphic card has nothing to be here, the important things are the processor, ram and internet speed
> 
> I have a ryzen 3 3700x 8 cores 4005 mhz, 32gb ram ddr4 3600mhz (? i don't remember exactly) and 400 Mbps.
> 
> The issue seems to be happening for some reason consistently on every single play of anything that's not a file, also it throws the "resource has already ended" error way too much for some reason.

Then all i would suggest is moving from this package to distube(search on npmjs.), And you can maybe wait(?) for them to clear the voice lag. Cause that is what im doing at the minute.

**Comment by VedantSharma7** [comment]
And also, yeah i get the same resource error

**Comment by PinKiUwU** [comment]
> And also, yeah i get the same resource error

The current version of this package is kind of really broken. I use a modified version of it and managed to temporarily solve the resource ended but for only like a week or so before it somehow came back.

**Comment by VedantSharma7** [comment]
> > And also, yeah i get the same resource error
> 
> The current version of this package is kind of really broken. I use a modified version of it and managed to temporarily solve the resource ended but for only like a week or so before it somehow came back.

Aah i see,

**Comment by Majoramari** [comment]
I think a video would be helpful
