### ISSUE TITLE
Use play-dl instead of ytdl-core

### ISSUE THREAD

**Issue by pauldb09** [Androz2091/discord-player#892]
**Describe the feature you would like**
Making play-dl as default stream engine because ytdl-core is very bugged

**Comment by rdapshii** [comment]
Yes please, ytdl-core aborts songs everytime and has lots of bugs/problems

**Comment by fobdev** [comment]
There is a way of doing this already with the dev branch. 

```npm i discord-player@dev```

In my project, I do this at the queue creation (typescript): 
```ts
import * as playdl from "play-dl"
...
const queue: Queue = player!.createQueue(guild!, {
            metadata: {
                channel: channel,
            },
            async onBeforeCreateStream(track, source, _queue) {
                return (await playdl.stream(track.url)).stream;
            },
        });
```

**Comment by DevAndromeda** [comment]
We don't have any plans on switching over to play-dl. As mentioned by @fobdev, you should instead utilize the `discord-player@dev` which lets you gain control over streaming api of discord-player.

**Comment by pauldb09** [comment]
I don't know if it's a good idea to leave a known bug on this package. Lots of users are asking help with errors related to ytdl-core on the discord server...

**Comment by skdhg** [comment]
The next stable release of discord-player will prefer play-dl over ytdl-core. You dont need `onBeforeCreateStream` hook or anything. If discord-player detects play-dl, it will use it automatically, otherwise falling back to ytdl-core.

There is no ETA yet but the PR for the next release is #1513
