### ISSUE TITLE
Update code in extractor

### ISSUE THREAD

**Issue by Lutra-Fs** [Androz2091/discord-player#895]
```Player.play()``` has been deprecated and should be replaced in 

https://github.com/Androz2091/discord-player/blob/94ffd93cde2257034122c98e03ffdb9582e15233/docs/extractors/extractor.md#L8

also

https://github.com/Androz2091/discord-player/blob/94ffd93cde2257034122c98e03ffdb9582e15233/src/Structures/ExtractorModel.ts#L30

**Comment by DevAndromeda** [comment]
https://github.com/Androz2091/discord-player/commit/bf22b25342f83636992827ca4f0b17d7448735ed
