### ISSUE TITLE
Bug from event "channelEmpty"

### ISSUE THREAD

**Issue by CurPlayzz2k6** [Androz2091/discord-player#896]
**Describe the bug**

When a user connect to a voice channel same with bot, next that user connect to another voice channel have only that user and disconnect, bot will auto disconnect and return error "Error emitted from the queue"

**To Reproduce**

**Expected behavior**

Will create `sameBotVoiceChannel` to check user is in a same voice channel with bot.
I hope author will fix this bug

**Screenshots**

**Please complete the following information:**
 - Node Version: 16.12.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Additional context**

**Comment by DevAndromeda** [comment]
This should be fixed on the latest update by #852
