### ISSUE TITLE
leaveOnEmpty not working 

### ISSUE THREAD

**Issue by Grayson-code** [Androz2091/discord-player#908]
**Describe the bug**
The bug basically is that even though i pass in option for leaveOnEmpty to false it keeps leaving the channel

**To Reproduce**
`discordPlayer: {
            leaveOnEmpty: false,
            ytdlOptions: {
                quality: 'highestaudio',
                highWaterMark: 1 << 25
            }
        }`
       This is my player options 
       `global.player = new Player(client, client.config.opt.discordPlayer);` this is how i define player

**Expected behavior**
It should not leave the channel when no one is in the channel

**Please complete the following information:**
 - Node Version: 16.10.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.3.1

**Comment by DevAndromeda** [comment]
This option should be passed to createQueue method, not Player

**Comment by Grayson-code** [comment]
> This option should be passed to createQueue method, not Player

OHHHH Sorry thanks tho
