### ISSUE TITLE
Skipping add the current track to previousTracks twice

### ISSUE THREAD

**Issue by th13n-h4ck3r** [Androz2091/discord-player#910]
**Describe the bug**
When skipping a track, 2 instance of that track is added to <Queue>.previousTracks

**To Reproduce**
1. `await <Queue>.play();` any song
2. `await <Queue>.skip();`
3. `console.log(<Queue>.previousTracks);` will shows 2 copy of that song, even though it has only been played once.
`// [Track1, Track1]`
4. This will also happens when you skip multiple songs `//[Track1, Track1, Track2, Track2, Track3]`

Because of this bug. Using `<Queue>.back()` and `<Queue>.skip();` after one another will not play certain song in the queue.

**Expected behavior**
previousTrack should only contain the previousTrack, not including nowPlaying track.

**Screenshots**
This is when `<Queue>.skip();` is called twice after `<Queue>.play();` 
![image](https://user-images.githubusercontent.com/45925109/144183140-f6831f1b-2d06-4081-abb7-4a37bf2e918c.png)

**Please complete the following information:**
 - Node Version: 16.13.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.3.1

**Additional context**
I think the issue is when using `<Queue>.play();`, it adds the now playing song to the `previousTracks` already, So when `<Queue>.skip();` is used, it will move the current song to `previousTracks` again. Then the skip() move the now playing song to `previousTracks`  again because it's playing the next song.

**Comment by xSqne** [comment]
bump, I have the same issue

**Comment by DevAndromeda** [comment]
re-open if it still persists
