### ISSUE TITLE
Switching voice channels while there's an active voice connection

### ISSUE THREAD

**Issue by kawaiiseiba** [Androz2091/discord-player#911]
I have a feature in my discord server that automatically moves users in voice channels to appropriate game voice channels.
Now I want my music bot to follow the users who've requested the current song to the voice channels he got moved into.

I've tried something like this.

```javascript
client.on('voiceStateUpdate', async (oldState, newState) => {
  const guild= client.guilds.cache.get(GUILD_ID)
  const member = guild.members.cache.get(newState.id)
  const voiceState = member.voice
  const presence = member.presence
  const user = member.user

  if(user.bot) return 

  if(!voiceState) return
  if(!voiceState?.channelId) return 
  
  const queue = player.getQueue(guild.id)
  if(!queue) return
  const current = queue.current

  const vcToJoin = guild.channels.cache.get(voiceState?.channelId)
  return (await queue.connect(vcToJoin)).play() // <= I don't know what to do here!
})
```
But the problem here is when the bot switch over voice channels, it doesn't continue playing. 
I had to use `queue.play` in order for it to play a song but it only skips the current playing song after it connects.

The expected behavior I want is to continue playing the song even when switched to different voice channels. 
It's like moving the bot manually without interrupting the current playing song.

I'm using Discord.js `v13`  and I have every packages updated to the latest versions.

Edit: Might be a bug or needed some enhancements. I'm not sure...

**Comment by pauldb09** [comment]
@kawaiiseiba With the latest version of discord-player, you can use the discord.js function `guild.me.voice.setChannel` and the bot must continue playing.
`guild.me.voice.setChannel(vcToJoin, `Move command`)`

**Comment by kawaiiseiba** [comment]
> @kawaiiseiba With the latest version of discord-player, you can use the discord.js function `guild.me.voice.setChannel` and the bot must continue playing. `guild.me.voice.setChannel(vcToJoin,'Move command')`

got it~ Thanks!
