### ISSUE TITLE
"leaveOnEmpty" and "channelEmpty" not working

### ISSUE THREAD

**Issue by StarJules** [Androz2091/discord-player#912]
**Describe the bug**
When creating the queue with the option "leaveOnEmpty", nothing happens when everyone leaves the channel. Also the "channelEmpty" event is never emitted.

**To Reproduce**
When creating the queue add the option "leaveOnEmpty" to "true". Exit the channel and the bot will keep playing.
In the events, add the event "channelEmpty". When everyone leaves the channel, nothing will be emitted.

**Expected behavior**
In the "leaveOnEmpty", the bot should disconnect when everyone leaves.
In the "channelEmpty" event, when everyone leaves the channel, the event should be emitted.

**Screenshots/Codes**
`const queue = await player.createQueue(message.guild, {
      metadata: message.channel,
      autoSelfDeaf: true,
      leaveOnEnd: false,
      leaveOnStop: true,
      leaveOnEmpty: true,
      ytdlOptions: {
        quality: "highest",
        filter: "audioonly",
        highWaterMark: 1 << 25,
        dlChunkSize: 0,
      },
    });`

`player.on("channelEmpty", async (queue) => {console.log("Example")}`

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.3.1

**Additional context**

**Comment by AQRRastiq** [comment]
I have the same problem.

**Comment by Loadren** [comment]
Same problem here.

Passing parameter to the queue, not the player. Also, did leaveOnEndCooldown just stopped working?

**Comment by LePtitMetalleux** [comment]
> **Describe the bug** When creating the queue with the option "leaveOnEmpty", nothing happens when everyone leaves the channel. Also the "channelEmpty" event is never emitted.
> 
> **To Reproduce** When creating the queue add the option "leaveOnEmpty" to "true". Exit the channel and the bot will keep playing. In the events, add the event "channelEmpty". When everyone leaves the channel, nothing will be emitted.
> 
> **Expected behavior** In the "leaveOnEmpty", the bot should disconnect when everyone leaves. In the "channelEmpty" event, when everyone leaves the channel, the event should be emitted.
> 
> **Screenshots/Codes** `const queue = await player.createQueue(message.guild, { metadata: message.channel, autoSelfDeaf: true, leaveOnEnd: false, leaveOnStop: true, leaveOnEmpty: true, ytdlOptions: { quality: "highest", filter: "audioonly", highWaterMark: 1 << 25, dlChunkSize: 0, }, });`
> 
> `player.on("channelEmpty", async (queue) => {console.log("Example")}`
> 
> **Please complete the following information:**
> 
> * Node Version: 16.6.1
> * Discord Player Version: 5.2.0
> * Discord.js Version: 13.3.1
> 
> **Additional context**

These options must be passed in the crequeQueue() method (refers to https://discord-player.js.org/docs/main/master/class/Player?scrollTo=createQueue)
![image](https://user-images.githubusercontent.com/59097429/147679598-62e37fda-4d96-4bf4-80a2-f7f2b56be3ac.png)



> Same problem here.
> 
> Passing parameter to the queue, not the player. Also, did leaveOnEndCooldown just stopped working?

The option is leaveOn**Empty**Cooldown not leaveOn**End**Cooldown, but it doesn't work for me as well

**Comment by MrTheBank** [comment]
You need to create leaveOnEndCooldown handler by yourself, Maybe take a look of this code.

**endTimeout.js**
```js
module.exports = class EndTimeout {
    constructor() {
        this.timeouts = new Map();
    }

    setTimeout(queue) {
        let timeout = setTimeout(async () => {
            queue.connection.disconnect();
            queue.destroy(true);
            await queue.metadata.send({embeds: [new MessageEmbed()
                    .setColor('#ffff66')
                    .setDescription('เนื่องจากไม่มีความเคลื่อนไหว บอทจึงออกจากห้อง')]
            });
        }, leave_on_end * 1000);
        this.timeouts.set(queue.guild.id, timeout);
    }

    clearTimeout(queue) {
        let timeout = this.timeouts.get(queue.guild.id);
        if (timeout) {
            clearTimeout(timeout);
            this.timeouts.delete(queue.guild.id);
        }
    }
}
```

**player-handler.js**
```js
player
    .on('trackAdd', (queue, track) => {
        endTimeout.clearTimeout(queue);
    })
    .on('tracksAdd', (queue, track) => {
        endTimeout.clearTimeout(queue);
    })
    .on('channelEmpty', (queue => {
        endTimeout.clearTimeout(queue);
    }))
    .on('queueEnd', (queue => {
        endTimeout.setTimeout(queue);
    }))
    .on('botDisconnect', (queue => {
        endTimeout.clearTimeout(queue);
    }))
    ;
```
Hope this will work for you.

**Comment by EwoX07** [comment]
# # #986
