### ISSUE TITLE
Bot continues playing when manually disconnected from the vocal channel

### ISSUE THREAD

**Issue by Rokhnir** [Androz2091/discord-player#913]
**Describe the bug**
When I manually disconnect the bot from the vocal channel, It continues to play the queue.
When I move it to another vocal channel, it doesn't stop either but the `trackStart` event is triggered.

**To Reproduce**
1. Make your bot play music.
2. Disconnect the bot from its current vocal channel.
3. If you have any !queue command, do it, you will see that the queue isn't cleared.

**Expected behavior**
It should send the leave message that I set to the metadata channel and destroy the queue.

**Please complete the following information:**
 - Node Version: 16.11.11
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.3.1

**Comment by DevAndromeda** [comment]
re-open if this still persists
