### ISSUE TITLE
Autoplay not working

### ISSUE THREAD

**Issue by cattaneod** [Androz2091/discord-player#914]
**Describe the bug**
The autoplay function is not working: when the queue ends, or when I skip the last track of the queue, the function (e.g., ```queue.skip()```)  returns true, but no song is added to the queue and played.

**To Reproduce**
1. add a son to the queue
2. set repeatMode to AUTOPLAY
3. skip the current song

**Expected behavior**
A new song should be added to the queue and played.

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.3.1

**Comment by pauldb09** [comment]
Yeah, having same issue

**Comment by colinkehoe** [comment]
This is still an issue. `QueueRepeatMode.TRACK` works, but not `QueueRepeatMode.AUTOPLAY`.

**Comment by DevAndromeda** [comment]
Since discord-player v5.3.x, there's a fallback autoplay resolver. Re-open if it still persists
