### ISSUE TITLE
Getting unknown error from player

### ISSUE THREAD

**Issue by Zaid-maker** [Androz2091/discord-player#915]
**Describe the bug**

**Screenshots**
[screenshot](https://devmirza.2b2t.gold/YCmllNCQdHuAYA)

**Please complete the following information:**
 - Node Version: 16
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.3.1

**Comment by LePtitMetalleux** [comment]
Show how you creates your player

**Comment by DevAndromeda** [comment]
Looks like the `client` is malformed. You should pass discord.js client

**Comment by Zaid-maker** [comment]
> Show how you creates your player

const { Player } = require('discord-player');
const client = require('../index.js');

const player = new Player(client, {
    ytdlOptions: {
        quality: 'highestaudio',
        highWaterMark: 1 << 25
    },
});

module.exports = player;

**Comment by Zaid-maker** [comment]
@LePtitMetalleux 
@DevAndromeda

**Comment by LePtitMetalleux** [comment]
Oh I think that you didn't give the intents when creating your bot's Discord client as the error you get occurs when the module checks if your bot have the GUILD_VOICE_STATES intent (Refering to https://discord.js.org/#/docs/main/stable/class/Intents?scrollTo=s-FLAGS)

Something like that (check https://discord.js.org/#/docs/main/stable/typedef/ClientOptions) : 
![image](https://user-images.githubusercontent.com/59097429/150304643-dcbf9978-7b74-410f-b1ae-6374004f8233.png)

**Comment by Zaid-maker** [comment]
Thanks for the reply I have fix the problem there's actually not a problem
with player I have misspelled the string name with actual constant so I
have fixed the issue thank you so much for your help.
