### ISSUE TITLE
Memory leak on Queue.js

### ISSUE THREAD

**Issue by pauldb09** [Androz2091/discord-player#917]
**Describe the bug**
There's a memory leak in queue.js. It's because the events are emitting to infinity

**To Reproduce**
Just play music and you will get this error after 10-20m
https://cdn.discordapp.com/attachments/795044922800734221/916419058075844648/unknown.png
I think it's only when your bot is user by lots of persons

**Expected behavior**

**Screenshots**
[](https://cdn.discordapp.com/attachments/795044922800734221/916419058075844648/unknown.png)

**Please complete the following information:**
 - Node Version: v16
 - Discord Player Version: dev
 - Discord.js Version: v 13.2

**Additional context**
I think we can fix it adding a `_this` on the listenners of `connection`

**Comment by DevAndromeda** [comment]
re-open if this still persists
