### ISSUE TITLE
After the bot disconnects a vc, it won't reconnect a second time

### ISSUE THREAD

**Issue by Zaimoo** [Androz2091/discord-player#918]
**Describe the bug**

whenever the bot disconnects, it won't enter a vc again and it gets an error `error emitted from the connection: the operation was aborted`

**To Reproduce**

It should be able to connect to the vc again and play like normal

**Screenshots**

**Please complete the following information:**
 - Node Version: 17.2.0
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.3.1

**Additional context**

**Comment by DevAndromeda** [comment]
This issue usually occurs with ytdl-core. You can try play-dl as mentioned in https://github.com/Androz2091/discord-player#custom-stream-engine
