### ISSUE TITLE
Cannot read properties of undefined (reading 'previousTracks')

### ISSUE THREAD

**Issue by Sys-h-sudo** [Androz2091/discord-player#929]
/home/runner/Music-bot/commands/music/back.js:26
    if (!queue.previousTracks[1])
               ^

TypeError: Cannot read properties of undefined (reading 'previousTracks')

Here's the full block:

### Here's the full block:

`const discord = require('discord.js');
const { track, queue } = ('discord-player')
const { MessageEmbed } = require('discord.js');

module.exports = {
  name: 'back', 
  aliases: ['previous'],
  utilisation: '{prefix}back',
  voiceChannel: true,

  async execute(client, message) {
    
    const queue = player.getQueue(message.guild.id);

    const backembed2 = new MessageEmbed();

    if (!queue || !queue.playing)
    
    backembed2.setDescription(`No music currently playing ${message.author}... Try again! `);
    backembed2.setColor('LUMINOUS_VIVID_PINK')

    message.channel.send({ embeds: [backembed2] });

    const backembed3 = new MessageEmbed();

    if (!queue.previousTracks[1])

    backembed3.setDescription(`There was no music played before ${message.author}... Try again!`);
    backembed3.setColor('LUMINOUS_VIVID_PINK')

    message.channel.send({ embeds: [backembed3] });

    const backembed = new MessageEmbed();

    await queue.back();

    backembed.setDescription('``Playing latest song from queue.');
    backembed.setColor('LUMINOUS_VIVID_PINK')

    message.channel.send({ embeds: [backembed] });
  },
};
`

**Comment by Sys-h-sudo** [comment]
Sorry for the bad formatting, I don't know what happened.

**Comment by DevAndromeda** [comment]
add a simple check, like `if (!queue.previousTracks?.[1])`
