### ISSUE TITLE
Unhandled connection error

### ISSUE THREAD

**Issue by PhantomImad** [Androz2091/discord-player#938]
unhandled connection error, connectionError must have event listners.
wtf is this error

**Comment by pauldb09** [comment]
That's not a bug. You have to listen to the `connectionError` event (ex: player.on('connectionError',err=>{}) )

**Comment by DevAndromeda** [comment]
> unhandled connection error, connectionError must have event listners.

this is a warning message (not error actually) for error events emitted by discord-player
