### ISSUE TITLE
Unable to join a voice channel

### ISSUE THREAD

**Issue by JohannC-dev** [Androz2091/discord-player#939]
Hello, I'm currently using these settings: 
`

exports.play = async(url, serverId, ChannelId) => {

    let Guild = client.guilds.cache.get(serverId);
    let testChannel = client.channels.cache.get(ChannelId);
    let Channel = Guild.channels.cache.get(ChannelId)

    const queue = await player.createQueue(Guild);

    try {
        if (!queue.connection) await queue.connect(testChannel); //I've also tried with Channel
    } catch {
        await player.deleteQueue(Guild.id);
        return console.log(`I can't join the voice channel ... try again ? ❌`);
    }
    const res = await player.search(url, {
        searchEngine: QueryType.AUTO
    });

    await console.log(`Loading your ${res.playlist ? 'playlist' : 'track'}... 🎧`);

    res.playlist ? queue.addTracks(res.tracks) : queue.addTrack(res.tracks[0]);

    if (!queue.playing) await queue.play();
}

` 

and when i call play. I get 'I can't join the voice channel' over and over.
If you have any idea of how to fix it ?

**Comment by D3ord3NidAm** [comment]
You're not connecting to a voice channel. `if (!queue.connection) await queue.connect(member.voice.channel);`

**Comment by JohannC-dev** [comment]
I were connected to the room is question...

**Comment by D3ord3NidAm** [comment]
No the bot wasn't connecting, it was trying to connect to a text-type channel.

**Comment by JohannC-dev** [comment]
Still not the channel was a voice channel, I've tried with ytdl-core without using discord-player and it work..

**Comment by JohannC-dev** [comment]
And I've also tried to instead of queue.connect use Channel.join.
With channel.join it work (incredible...)
But after it can't play music.

**Comment by D3ord3NidAm** [comment]
you aren't objecting into the metadata as required.

const queue = await player.createQueue(Guild, {metadata: Channel} );

**Comment by D3ord3NidAm** [comment]
Also, did you at least define player?

**Comment by JohannC-dev** [comment]
I don't need metadata since I don't use them

**Comment by JohannC-dev** [comment]
> Also, did you at least define player?
> 

Of course not..

**Comment by Natemo6348** [comment]
I also have this problem, can't seem to figure out why either. Could it be related to another package? Because I didn't change code and it worked before.

**Comment by SiniMini876** [comment]
Try to log `testChannel` variable. Maybe it's undefined.

**Comment by SiniMini876** [comment]
Try to log `testChannel` variable. Maybe it's undefined.

**Comment by SiniMini876** [comment]
You shouldn't try creating queues every time, You can try to find an already existing one and if it's not found create another one.

**Comment by DevAndromeda** [comment]
re-open if this still persists
