### ISSUE TITLE
Unable to find RequestedBy username

### ISSUE THREAD

**Issue by D3ord3NidAm** [Androz2091/discord-player#942]
track.requestedBy returns null since slash-commands were introduced. Maybe can't find the User of the interaction?

**Comment by pauldb09** [comment]
Please send your code when you search a track

**Comment by D3ord3NidAm** [comment]
`const guild = client.guilds.cache.get(ctx.guildID);
    const channel = guild.channels.cache.get(ctx.channelID);
    const query = ctx.options.query;
    const member = guild.members.cache.get(ctx.user.id) ?? await guild.members.fetch(ctx.user.id);
    const searchResult = await client.player
      .search(query, {
        requestedBy: member.username,
        searchEngine: QueryType.AUTO
      })`
      
 this requestedBy works but only in the play/search file. But I would like for it to be saved to the track json.

**Comment by DevAndromeda** [comment]
[You need to supply who actually requested the track while calling search method of `Player`.](https://github.com/Androz2091/discord-player/blob/master/example/music-bot/index.js#L202)

**Comment by D3ord3NidAm** [comment]
I thought i was here `requestedBy: member.username,`

**Comment by DevAndromeda** [comment]
`member`s don't have `username`. Try `member.user.username` instead

**Comment by D3ord3NidAm** [comment]
I've tried 'ctx.user' 'ctx.user.id' 'ctx.user.user.username' 'ctx.user.username' 'member.username' 'member.user.username' and a lot more ways with different variables. I can console log all these ways and get my username to show up more than one way but it won't push into the search function to be used in other files.

**Comment by DevAndromeda** [comment]
try passing user id instead

**Comment by D3ord3NidAm** [comment]
That returns the entire user which is more that i've gotten before. I passed in `ctx.user.id` and it returned the following. 
`Track {
  id: '922962342180945920',
  title: 'Hoodie by Hey Violet [ Lyrics ]',
  author: 'Rizza Vidal',
  url: 'https://www.youtube.com/watch?v=PmlcfOc3YLg',
  thumbnail: 'https://i3.ytimg.com/vi/PmlcfOc3YLg/maxresdefault.jpg',
  duration: '3:41',
  views: 8377535,
  requestedBy: User {
    id: '371759410009341952',
    bot: false,
    system: false,
    flags: UserFlags { bitfield: 64 },
    username: 'marve1icious',
    discriminator: '4986',
    avatar: '7b0b007d3ecfafc966b10368e57187b0',
    banner: undefined,
    accentColor: undefined
  },
  playlist: undefined
}`

**Comment by DevAndromeda** [comment]
Thats discord.js user object. You can use `track.requestedBy.tag` or something like that if you want

**Comment by D3ord3NidAm** [comment]
I understand what I'm requesting is from discord.js user object. You told me to get it from user.id so I did. It's impossible to get the requestedBy to equal 'track.requestedBy.tag' when you are trying to get the user who created the interaction in discord. It returns null when I attempt it.
