### ISSUE TITLE
Refactor: VoiceUtils

### ISSUE THREAD

**Issue by pauldb09** [Androz2091/discord-player#947]
**Describe the feature you would like**
I think you need to rewrite the discord.js/voice part because you created an important memory leak
![image](https://user-images.githubusercontent.com/70904183/146995990-17667b03-fcb0-4ee8-9270-496a31b96a99.png)

**Comment by DevAndromeda** [comment]
Your screenshot does not show the origin

**Comment by pauldb09** [comment]
The [K] variable is in discord.js/voice

**Comment by pauldb09** [comment]
And I talker with others owners that are using discord.js/voice and they never had this error. So the problem must be from voiceUtils.js / StreamDispatcher.js

**Comment by DevAndromeda** [comment]
@pauldb09 can you trace the warning and show the result?

**Comment by pauldb09** [comment]
yes sure

**Comment by DevAndromeda** [comment]
re-open if this still persists
