### ISSUE TITLE
Spotify playlists' only takes the 100 first songs

### ISSUE THREAD

**Issue by LePtitMetalleux** [Androz2091/discord-player#959]
**Describe the bug**
When you want to play a spotify playlist/album with more than 100 songs, the module will oly add the 100 first in the queue

**To Reproduce**
1. Connect to a voice channel
2. Use the play command with the spotify playlist with more than 100 songs to play (Here, I'm using [Adrenaline Workout](https://open.spotify.com/playlist/37i9dQZF1DXe6bgV3TmZOL?si=2439b797267d4528))

**Expected behavior**
I'm expectig the bot to add the whole playlist in queue, the 120 songs.

**Screenshots**
![image](https://user-images.githubusercontent.com/59097429/147698548-14f92300-9547-44e7-a3c4-46cd2a21502c.png)
![image](https://user-images.githubusercontent.com/59097429/147698487-bdf5cb0a-fa37-40c0-b14b-1c14043d8084.png)

**Please complete the following information:**
 - Node Version: 16.16.1
- Discord Player Version: 5.2.0
 - Discord.js Version: 13.5.0

**Additional context**
I know that the spotify's API has a limit (50 songs as far as I can remember)
Youtube's playlist with more than 100 songs are well managed by the module. I only have the problem with spotify.
I also tried with the Spotify's [Rock Hard](https://open.spotify.com/playlist/37i9dQZF1DWWJOmJ7nRx0C?si=552deae46309462f) playlist to be sure the problem wasn't coming from this specific playlist.

**Comment by DevAndromeda** [comment]
Spotify playlists are parsed from the widget and there is no way of getting over 100 items from widget. The library we use to parse spotify playlists is https://npm.im/spotify-url-info
