### ISSUE TITLE
DestroyedQueue: [DestroyedQueue] Cannot use destroyed queue

### ISSUE THREAD

**Issue by LePtitMetalleux** [Androz2091/discord-player#960]
**Describe the bug**
I got an error when I stop the bot while playing a Spotify playlist or album

**To Reproduce**
1. Connect to a voice channel
2. Use the play command with a Spotify playlist or album
3. Wait for the bot to start playing the first song
4. Stop the bot with the stop command

**Expected behavior**
I'm expecting the bot to disconnect without any error

**Screenshots**
When playing a playlist :
![image](https://user-images.githubusercontent.com/59097429/147701022-5ec9ccbd-a29c-4045-82b8-01e48c82b326.png)
When playing an album :
![image](https://user-images.githubusercontent.com/59097429/147701248-baeb7e88-f0bc-4c74-a231-b5e064a390e6.png)
The error is always the same : 
![image](https://user-images.githubusercontent.com/59097429/147701061-588a6b4e-7405-49ae-9d4f-ffe51d40182b.png)

**Please complete the following information:**
 - Node Version: 16.13.1
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.5.0

**Additional context**
To stop the bot I'm using `this.client.player.getQueue(message.guild).destroy()` but I got the same error when I use `this.client.player.getQueue(message.guild).stop()`.
I don't have any error when doing this with a single spotify song
![image](https://user-images.githubusercontent.com/59097429/147701230-3ebc1ae5-ab63-4824-9cd2-55ec3f11295d.png)
My play command : [play.txt](https://github.com/Androz2091/discord-player/files/7790525/play.txt)

**Comment by SuperSweatyTejas** [comment]
#734

**Comment by LePtitMetalleux** [comment]
> #734 

I know but the answer don't fix my problem

**Comment by pauldb09** [comment]
I don't think there's any stable fix yet

**Comment by SuperSweatyTejas** [comment]
double check the code you are using
and see if the .stop() function is used else where

**Comment by LePtitMetalleux** [comment]
> double check the code you are using and see if the .stop() function is used else where

As you can see I olny use the queue.destroy() once
![image](https://user-images.githubusercontent.com/59097429/148175604-f280d5f4-59de-4a61-ae77-a950988bac3f.png)

And I don't use queue.stop() but when replacing destroy() by stop() I got the same error 
![image](https://user-images.githubusercontent.com/59097429/148175681-6a74e919-7b2c-4ac6-a2ff-0897f05bd8b6.png)

**Comment by MeridianGH** [comment]
I was encountering the same problem, but I have found a very simple fix.
Simply clear the queue before destroying it:
```
queue.clear()
queue.destroy()
```

**Comment by DevAndromeda** [comment]
> I was encountering the same problem, but I have found a very simple fix. Simply clear the queue before destroying it:
> 
> ```
> queue.clear()
> queue.destroy()
> ```

re-open if it does not work/still persists
