### ISSUE TITLE
cant play a playlist

### ISSUE THREAD

**Issue by blate-coder** [Androz2091/discord-player#97]
Well before when i want to play a playlist thru discord-player just type <prefix>play <url>,but when today,i want to make it play a playlist thru this
``const result = await client.player.addToQueue(message.guild.id, args.join(" ")).catch(() => {});``
it cant find one and it pops up "This Song provider is not supported" thru this 
`if(!result) {
                message.member.voice.channel.leave()
                return message.channel.send(`This song provider is not supported...`)
            };`
how should I make it play playlist?

**Comment by TheMonDon** [comment]
I'm having this same issue, playlists have stopped working and I don't have any idea why

**Comment by OxyTomato** [comment]
I am having this same issue, it doesnt work...

**Comment by Androz2091** [comment]
Duplicate of #122 I guess
