### ISSUE TITLE
The "botDisconnect" event is not emitted

### ISSUE THREAD

**Issue by loloToster** [Androz2091/discord-player#972]
**Describe the bug**
The "botDisconnect" event is not emitted

**Info:**
 - Node Version: v17.3.0
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.4.0

**Additional context**
I think I know why it is happening. The "botDisconnect" event is emitted in `_handleVoiceState` method of `Player` Class after
```ts
if (oldState.member.id === this.client.user.id && !newState.channelId)
```
statement that checks if the client has disconnected. For "botDisconnect" to get emitted the `newState.channelId` has to be `false`. But at the beggining of the method we can see this statement
```ts
if (oldState.channelId && newState.channelId && oldState.channelId !== newState.channelId)
```
that checks if `newState.channelId` is `true`. So the "botDisconnect" event cannot be emitted because `newState.channelId` cannot be both `true` and `false`.
That's what I think is happening. Maybe I'm missing something?

**Comment by zechaos031** [comment]
I have the same issue
![description](https://user-images.githubusercontent.com/36123003/147915785-6a7cf7a9-1627-40b4-af8c-b25252bef214.gif)

**Comment by zechaos031** [comment]
![image](https://user-images.githubusercontent.com/36123003/147917526-72ed1c4c-0fbb-4f46-9a3a-e8d19172d93f.png)
 Additionnal thing made two console.log before and after the if statement and there are never pass
 
 1 : When the bot arrive
 2: when the bot is disconnected manually

**Comment by zechaos031** [comment]
I managed to make a hotfix but there are still some adjustments

**Comment by pauldb09** [comment]
Known issue

**Comment by Alvin-Yu628** [comment]
It works now

**Comment by zechaos031** [comment]
With the hot fix yes but also no

**Comment by Alvin-Yu628** [comment]
Yep, just found that out now lmao

**Comment by EwoX07** [comment]
#986
