### ISSUE TITLE
Player.search method doesn't work

### ISSUE THREAD

**Issue by SiniMini876** [Androz2091/discord-player#978]
When I use the Player.search method I don't get any tracks. No matter what I am searching.

**Expected behavior**
get an object with an array with tracks in it.

**Screenshots**
![image](https://user-images.githubusercontent.com/67224094/148645639-c904b288-ba01-4f98-8248-c8bbcecc8385.png)

**Please complete the following information:**
 - Node Version: v17.2.0
 - Discord Player Version: ^5.2.0
 - Discord.js Version: ^13.5.1

**Additional context**
I wrote my code in typescript. Maybe it relates to it? But it won't make sense because the module itself is written in typescript

Thanks

**Comment by EvertonCosmo** [comment]
Same. It only works with the youtube link

**Comment by SiniMini876** [comment]
> 

Yeah, I've found a solution but it isn't perfect. You will need to download yt-search and parse the query. Once you do that you get an array of videos. Choose the first one by [0] and then .URL. After that parse the URL into the player.

But again. this shouldn't happen in the first place. I don't know what but typescript somehow messed something with the package.

**Comment by DevAndromeda** [comment]
After some research, this issue occurs when you don't have `node-fetch` or `undici` installed. You can fix this issue by running any command:

* `npm install node-fetch@2.6.6`
* `npm install undici`

**Comment by HerrEurobeat** [comment]
It didn't matter for me if `node-fetch` was installed or not but `undici` did the trick. Thanks!
