### ISSUE TITLE
(node:4) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!

### ISSUE THREAD

**Issue by fauzysan** [Androz2091/discord-player#979]
**Describe the bug**
(node:4) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!

**To Reproduce**
command bot play music

**Expected behavior**
bot play music

**Screenshots**
![image](https://user-images.githubusercontent.com/46274883/148690651-7b5709c8-470b-412a-9854-9d227b136385.png)

**Please complete the following information:**
 - Node Version: 16.x
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.5.0

**Additional context**

**Comment by LePtitMetalleux** [comment]
See https://discord-player.js.org/docs/main/master/class/Player?scrollTo=error and https://discord-player.js.org/docs/main/master/class/Player?scrollTo=connectionError
You must handle these events in your player

**Comment by fauzysan** [comment]
solved thanks

**Comment by SiniMini876** [comment]
> solved thanks

what did you do to stop the error?

**Comment by pauldb09** [comment]
> > solved thanks
> 
> what did you do to stop the error?

Just listen to the connectionError event

**Comment by SiniMini876** [comment]
> > > solved thanks
> > 
> > 
> > what did you do to stop the error?
> 
> Just listen to the connectionError event

ok I will do that

**Comment by fauzysan** [comment]
add this
```js
        try {
            if(!queue.connection){
                await queue.connect(interaction.member.voice.channel)
            }
            interaction.followUp({ content: `Playing ${songTitle}` });
        } catch (error) {
            queue.destroy()
            console.log(error)
            return await interaction.followUp({content: `Tidak bisa masuk ke voice channel anda karna ${error.message}`, ephemeral: true})
        }```

**Comment by SiniMini876** [comment]
> add this
> 
> ```js
>         try {
>             if(!queue.connection){
>                 await queue.connect(interaction.member.voice.channel)
>             }
>             interaction.followUp({ content: `Playing ${songTitle}` });
>         } catch (error) {
>             queue.destroy()
>             console.log(error)
>        
>         }
> ```

thanks I will add that
