### ISSUE TITLE
The operation was aborted 

### ISSUE THREAD

**Issue by LoneWolfSteam** [Androz2091/discord-player#991]
**Describe the bug**
I have a random bug, when someone executes the play command, there is a chance that node will return 'The operation was aborted' 

**To Reproduce**
Begin a play a music but it's a random bug (happens only a few times but when it happens the bot can't play for a while until I restart it and it's not sure if it works properly again)

**Expected behavior**
Go to the living room and play music
**Screenshots**
![image](https://user-images.githubusercontent.com/36123003/149180748-4c8b65c3-d875-469c-98e3-a0948aef45fc.png)

**Please complete the following information:**
 - Node Version:  16.13.1
 - Discord Player Version: ^5.2.0
 - Discord.js Version: ^13.5.1

**Comment by pauldb09** [comment]
Problem is from discord.js and can be caused by connection problems

**Comment by thathappynoodle** [comment]
> Problem is from discord.js and can be caused by connection problems

Do not think this is the issue. I asked there support as I am experiencing the same issue but it is something thats not on there end. I am pretty sure this is with the discord-player package. This error also started randomly

**Comment by PinKiUwU** [comment]
I'm having the same problem. At random, random songs just quit with the 'aborted' error. It's not reproducible and happens when the bot has basically perfect circumstances to work, great internet, no discord server connection issues, and no workload on the machine running it. I am fairly sure this error is related only to this package because when doing everything manually with some basic discord-voice and ytdl this error never happens.

**Comment by retrouser955** [comment]
### Hey mate!
Thanks for reaching out. May I know what extractor are you using with discord-player?

**Comment by Matt-PinKi** [comment]
> ### Hey mate!
> Thanks for reaching out. May I know what extractor you are using with discord-player?

I'm guessing the default one provided in the package, never changed any settings regarding that, although I did add the discord attachment section myself cause it didn't work for some reason.

**Comment by retrouser955** [comment]
> > ### Hey mate!
> > Thanks for reaching out. May I know what extractor you are using with discord-player?
> 
> I'm guessing the default one provided in the package, never changed any settings regarding that, although I did add the discord attachment section myself cause it didn't work for some reason.

Ah then try using `play-dl` package instead of the default one. You can look at the [docs](https://discord-player.js.org/) > welcome > scroll down > using a custom extractor

**Comment by Matt-PinKi** [comment]
> > > ### Hey mate!
> > > Thanks for reaching out. May I know what extractor you are using with discord-player?
> > 
> > 
> > I'm guessing the default one provided in the package, never changed any settings regarding that, although I did add the discord attachment section myself cause it didn't work for some reason.
> 
> Ah then try using `play-dl` package instead of the default one. You can look at the [docs](https://discord-player.js.org/) > welcome > scroll down > using a custom extractor

I'll run the bot with some new ones, but as there's no way to reproduce the bug it'll be up to random chance whether it happens or not :P
Thought this issue was due to me modifying the package for my own use but other people have it as well, so I guess it's just cursed.

**Comment by Matt-PinKi** [comment]
For the record, last time I got this error it said it occured in a file called "opusscript_native_wasm.js"

**Comment by DevAndromeda** [comment]
this usually occurs with ytdl-core, try play-dl as mentioned in https://github.com/Androz2091/discord-player#custom-stream-engine

**Comment by lmf-git** [comment]
Is this often caused by lacking the required libs on the system (often missing buildpack)?
